libopencm3: Generic USB Standard Request Interface
Generic USB Standard Request Interface
Generic USB
Generic USB Standard Request Interface
Functions
int usbd_register_set_config_callback (usbd_device *usbd_dev, usbd_set_config_callback callback)
Registers a "Set Config" callback.
void usbd_register_set_altsetting_callback (usbd_device *usbd_dev, usbd_set_altsetting_callback callback)
Registers a "Set Interface" (alternate setting) callback.
static uint16_t build_config_descriptor (usbd_device *usbd_dev, uint8_t index, uint8_t *buf, uint16_t len)
static int usb_descriptor_type (uint16_t wValue)
static int usb_descriptor_index (uint16_t wValue)
static int usb_standard_get_descriptor (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
static int usb_standard_set_address (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
static int usb_standard_set_configuration (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
static int usb_standard_get_configuration (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
static int usb_standard_set_interface (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
static int usb_standard_get_interface (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
static int usb_standard_device_get_status (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
static int usb_standard_interface_get_status (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
static int usb_standard_endpoint_get_status (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
static int usb_standard_endpoint_stall (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
static int usb_standard_endpoint_unstall (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
Detailed Description
Generic USB Standard Request Interface
Version
1.0.0
Author
© 2010 Gareth McMullin garet.nosp@m.h@bl.nosp@m.acksp.nosp@m.here.nosp@m..co.n.nosp@m.z
Date
10 March 2013
LGPL License Terms libopencm3 License
Function Documentation
static uint16_t build_config_descriptor (usbd_device * usbd_dev, uint8_t index, uint8_t * buf, uint16_t len) static
Definition at line 65 of file usb_standard.c.
References usb_config_descriptor::usb_interface::altsetting, usb_config_descriptor::bLength, usb_interface_descriptor::bLength, usb_endpoint_descriptor::bLength, usb_iface_assoc_descriptor::bLength, usb_interface_descriptor::bNumEndpoints, usb_config_descriptor::bNumInterfaces, _usbd_device::config, usb_interface_descriptor::endpoint, usb_interface_descriptor::extra, usb_endpoint_descriptor::extra, usb_interface_descriptor::extralen, usb_endpoint_descriptor::extralen, usb_config_descriptor::usb_interface::iface_assoc, usb_config_descriptor::interface, and usb_config_descriptor::usb_interface::num_altsetting.
Referenced by usb_standard_get_descriptor().
static int usb_descriptor_index (uint16_t wValue) static
Definition at line 143 of file usb_standard.c.
Referenced by usb_standard_get_descriptor().
static int usb_descriptor_type (uint16_t wValue) static
Definition at line 138 of file usb_standard.c.
Referenced by usb_standard_get_descriptor().
static int usb_standard_device_get_status (usbd_device * usbd_dev, struct usb_setup_data * req, uint8_t ** buf, uint16_t * len) static
Definition at line 382 of file usb_standard.c.
Referenced by _usbd_standard_request_device().
static int usb_standard_endpoint_get_status (usbd_device * usbd_dev, struct usb_setup_data * req, uint8_t ** buf, uint16_t * len) static
Definition at line 417 of file usb_standard.c.
References usbd_ep_stall_get(), and usb_setup_data::wIndex.
Referenced by _usbd_standard_request_endpoint().
static int usb_standard_endpoint_stall (usbd_device * usbd_dev, struct usb_setup_data * req, uint8_t ** buf, uint16_t * len) static
Definition at line 432 of file usb_standard.c.
References usbd_ep_stall_set(), and usb_setup_data::wIndex.
Referenced by _usbd_standard_request_endpoint().
static int usb_standard_endpoint_unstall (usbd_device * usbd_dev, struct usb_setup_data * req, uint8_t ** buf, uint16_t * len) static
Definition at line 444 of file usb_standard.c.
References usbd_ep_stall_set(), and usb_setup_data::wIndex.
Referenced by _usbd_standard_request_endpoint().
static int usb_standard_get_configuration (usbd_device * usbd_dev, struct usb_setup_data * req, uint8_t ** buf, uint16_t * len) static
Definition at line 306 of file usb_standard.c.
References usb_config_descriptor::bConfigurationValue, _usbd_device::config, and _usbd_device::current_config.
Referenced by _usbd_standard_request_device().
static int usb_standard_get_descriptor (usbd_device * usbd_dev, struct usb_setup_data * req, uint8_t ** buf, uint16_t * len) static
Definition at line 148 of file usb_standard.c.
References usb_string_descriptor::bDescriptorType, usb_device_descriptor::bLength, usb_string_descriptor::bLength, build_config_descriptor(), _usbd_device::ctrl_buf, _usbd_device::desc, _usbd_device::num_strings, _usbd_device::strings, usb_descriptor_index(), usb_descriptor_type(), USB_LANGID_ENGLISH_US, USBD_REQ_HANDLED, USBD_REQ_NOTSUPP, usb_string_descriptor::wData, usb_setup_data::wIndex, and usb_setup_data::wValue.
Referenced by _usbd_standard_request_device().
static int usb_standard_get_interface (usbd_device * usbd_dev, struct usb_setup_data * req, uint8_t ** buf, uint16_t * len) static
Definition at line 363 of file usb_standard.c.
References usb_config_descriptor::bNumInterfaces, _usbd_device::config, usb_config_descriptor::usb_interface::cur_altsetting, usb_interface::cur_altsetting, _usbd_device::current_config, usb_config_descriptor::interface, USBD_REQ_HANDLED, USBD_REQ_NOTSUPP, and usb_setup_data::wIndex.
Referenced by _usbd_standard_request_interface().
static int usb_standard_interface_get_status (usbd_device * usbd_dev, struct usb_setup_data * req, uint8_t ** buf, uint16_t * len) static
Definition at line 400 of file usb_standard.c.
Referenced by _usbd_standard_request_interface().
static int usb_standard_set_address (usbd_device * usbd_dev, struct usb_setup_data * req, uint8_t ** buf, uint16_t * len) static
Definition at line 219 of file usb_standard.c.
References usb_setup_data::bmRequestType, _usbd_device::current_address, _usbd_device::driver, _usbd_driver::set_address, _usbd_driver::set_address_before_status, and usb_setup_data::wValue.
Referenced by _usbd_standard_request_device().
static int usb_standard_set_configuration (usbd_device * usbd_dev, struct usb_setup_data * req, uint8_t ** buf, uint16_t * len) static
Definition at line 245 of file usb_standard.c.
References usb_config_descriptor::bConfigurationValue, usb_device_descriptor::bNumConfigurations, usb_config_descriptor::bNumInterfaces, _usbd_device::user_control_callback::cb, _usbd_device::config, usb_config_descriptor::usb_interface::cur_altsetting, _usbd_device::current_config, _usbd_device::desc, _usbd_device::driver, _usbd_driver::ep_reset, usb_config_descriptor::interface, usbd_dev, USBD_REQ_NOTSUPP, _usbd_device::user_callback_set_config, _usbd_device::user_control_callback, and usb_setup_data::wValue.
Referenced by _usbd_standard_request_device().
static int usb_standard_set_interface (usbd_device * usbd_dev, struct usb_setup_data * req, uint8_t ** buf, uint16_t * len) static
Definition at line 326 of file usb_standard.c.
References usb_config_descriptor::bNumInterfaces, _usbd_device::config, usb_interface::cur_altsetting, _usbd_device::current_config, usb_config_descriptor::interface, usb_interface::num_altsetting, USBD_REQ_HANDLED, USBD_REQ_NOTSUPP, _usbd_device::user_callback_set_altsetting, usb_setup_data::wIndex, and usb_setup_data::wValue.
Referenced by _usbd_standard_request_interface().
void usbd_register_set_altsetting_callback (usbd_device * usbd_dev, usbd_set_altsetting_callback callback)
Registers a "Set Interface" (alternate setting) callback.
Definition at line 59 of file usb_standard.c.
References _usbd_device::user_callback_set_altsetting.
int usbd_register_set_config_callback (usbd_device * usbd_dev, usbd_set_config_callback callback)
Registers a "Set Config" callback.
Returns
0 if successful
Definition at line 42 of file usb_standard.c.
References _usbd_device::user_callback_set_config.
Referenced by usb_msc_init().