libopencm3: Generic USB Control Requests
Generic USB Control Requests
Generic USB
Generic USB Control Requests
Functions
static void stall_transaction (usbd_device *usbd_dev)
static bool needs_zlp (uint16_t len, uint16_t wLength, uint8_t ep_size)
If we're replying with some data, but less than the host is expecting, then we normally just do a short transfer.
int usbd_register_control_callback (usbd_device *usbd_dev, uint8_t type, uint8_t type_mask, usbd_control_callback callback)
Registers a control callback.
static void usb_control_send_chunk (usbd_device *usbd_dev)
static int usb_control_recv_chunk (usbd_device *usbd_dev)
static int usb_control_request_dispatch (usbd_device *usbd_dev, struct usb_setup_data *req)
static void usb_control_setup_read (usbd_device *usbd_dev, struct usb_setup_data *req)
static void usb_control_setup_write (usbd_device *usbd_dev, struct usb_setup_data *req)
Detailed Description
Generic USB Control Requests
Version
1.0.0
Author
© 2010 Gareth McMullin garet.nosp@m.h@bl.nosp@m.acksp.nosp@m.here.nosp@m..co.n.nosp@m.z
Date
10 March 2013
LGPL License Terms libopencm3 License
Function Documentation
static bool needs_zlp (uint16_t len, uint16_t wLength, uint8_t ep_size) static
If we're replying with some data, but less than the host is expecting, then we normally just do a short transfer.
But if it's short, but a multiple of the endpoint max packet size, we need an explicit ZLP.
Parameters
len how much data we want to transfer
wLength how much the host asked for
ep_size
Returns
Definition at line 62 of file usb_control.c.
Referenced by usb_control_setup_read().
static void stall_transaction (usbd_device * usbd_dev) static
Definition at line 47 of file usb_control.c.
References _usbd_device::control_state, _usbd_device::usb_control_state::state, and usbd_ep_stall_set().
Referenced by _usbd_control_in(), _usbd_control_out(), _usbd_control_setup(), usb_control_recv_chunk(), usb_control_setup_read(), and usb_control_setup_write().
static int usb_control_recv_chunk (usbd_device * usbd_dev) static
Definition at line 121 of file usb_control.c.
References usb_device_descriptor::bMaxPacketSize0, _usbd_device::control_state, _usbd_device::usb_control_state::ctrl_buf, _usbd_device::usb_control_state::ctrl_len, _usbd_device::desc, stall_transaction(), and usbd_ep_read_packet().
Referenced by _usbd_control_out().
static int usb_control_request_dispatch (usbd_device * usbd_dev, struct usb_setup_data * req) static
Definition at line 141 of file usb_control.c.
References _usbd_standard_request(), usb_setup_data::bmRequestType, _usbd_device::user_control_callback::cb, _usbd_device::usb_control_state::complete, _usbd_device::control_state, _usbd_device::usb_control_state::ctrl_buf, _usbd_device::usb_control_state::ctrl_len, USBD_REQ_HANDLED, USBD_REQ_NOTSUPP, and _usbd_device::user_control_callback.
Referenced by _usbd_control_out(), and usb_control_setup_read().
static void usb_control_send_chunk (usbd_device * usbd_dev) static
Definition at line 93 of file usb_control.c.
References usb_device_descriptor::bMaxPacketSize0, _usbd_device::control_state, _usbd_device::usb_control_state::ctrl_buf, _usbd_device::usb_control_state::ctrl_len, _usbd_device::desc, _usbd_device::usb_control_state::needs_zlp, _usbd_device::usb_control_state::state, and usbd_ep_write_packet().
Referenced by _usbd_control_in(), and usb_control_setup_read().
static void usb_control_setup_read (usbd_device * usbd_dev, struct usb_setup_data * req) static
Definition at line 172 of file usb_control.c.
References usb_device_descriptor::bMaxPacketSize0, _usbd_device::control_state, _usbd_device::ctrl_buf, _usbd_device::usb_control_state::ctrl_buf, _usbd_device::usb_control_state::ctrl_len, _usbd_device::desc, needs_zlp(), _usbd_device::usb_control_state::needs_zlp, stall_transaction(), _usbd_device::usb_control_state::state, usb_control_request_dispatch(), usb_control_send_chunk(), usbd_ep_write_packet(), and usb_setup_data::wLength.
Referenced by _usbd_control_setup().
static void usb_control_setup_write (usbd_device * usbd_dev, struct usb_setup_data * req) static
Definition at line 197 of file usb_control.c.
References usb_device_descriptor::bMaxPacketSize0, _usbd_device::control_state, _usbd_device::ctrl_buf, _usbd_device::usb_control_state::ctrl_buf, _usbd_device::ctrl_buf_len, _usbd_device::usb_control_state::ctrl_len, _usbd_device::desc, stall_transaction(), _usbd_device::usb_control_state::state, and usb_setup_data::wLength.
Referenced by _usbd_control_setup().
int usbd_register_control_callback (usbd_device * usbd_dev, uint8_t type, uint8_t type_mask, usbd_control_callback callback)
Registers a control callback.
The specified callback will be called if (type == (bmRequestType & type_mask))
Parameters
type Handled request type
type_mask Mask to apply before matching request type
Returns
0 if successful
Definition at line 73 of file usb_control.c.
References _usbd_device::user_control_callback::cb, _usbd_device::user_control_callback::type, _usbd_device::user_control_callback::type_mask, and _usbd_device::user_control_callback.
Referenced by msc_set_config().