libopencm3: _usbd_driver Struct Reference
_usbd_driver Struct Reference
#include <usb_private.h>
Data Fields
usbd_device *(* init)(void)
void(* set_address)(usbd_device *usbd_dev, uint8_t addr)
void(* ep_setup)(usbd_device *usbd_dev, uint8_t addr, uint8_t type, uint16_t max_size, void(*cb)(usbd_device *usbd_dev, uint8_t ep))
void(* ep_reset)(usbd_device *usbd_dev)
void(* ep_stall_set)(usbd_device *usbd_dev, uint8_t addr, uint8_t stall)
void(* ep_nak_set)(usbd_device *usbd_dev, uint8_t addr, uint8_t nak)
uint8_t(* ep_stall_get)(usbd_device *usbd_dev, uint8_t addr)
uint16_t(* ep_write_packet)(usbd_device *usbd_dev, uint8_t addr, const void *buf, uint16_t len)
uint16_t(* ep_read_packet)(usbd_device *usbd_dev, uint8_t addr, void *buf, uint16_t len)
void(* poll)(usbd_device *usbd_dev)
void(* disconnect)(usbd_device *usbd_dev, bool disconnected)
uint32_t base_address
bool set_address_before_status
uint16_t rx_fifo_size
Detailed Description
Definition at line 140 of file usb_private.h.
Field Documentation
uint32_t _usbd_driver::base_address
Definition at line 157 of file usb_private.h.
void(* _usbd_driver::disconnect)(usbd_device *usbd_dev, bool disconnected)
Definition at line 156 of file usb_private.h.
Referenced by usbd_disconnect().
void(* _usbd_driver::ep_nak_set)(usbd_device *usbd_dev, uint8_t addr, uint8_t nak)
Definition at line 149 of file usb_private.h.
Referenced by usbd_ep_nak_set().
uint16_t(* _usbd_driver::ep_read_packet)(usbd_device *usbd_dev, uint8_t addr, void *buf, uint16_t len)
Definition at line 153 of file usb_private.h.
Referenced by usbd_ep_read_packet().
void(* _usbd_driver::ep_reset)(usbd_device *usbd_dev)
Definition at line 146 of file usb_private.h.
Referenced by usb_standard_set_configuration().
void(* _usbd_driver::ep_setup)(usbd_device *usbd_dev, uint8_t addr, uint8_t type, uint16_t max_size, void(*cb)(usbd_device *usbd_dev, uint8_t ep))
Definition at line 143 of file usb_private.h.
Referenced by usbd_ep_setup().
uint8_t(* _usbd_driver::ep_stall_get)(usbd_device *usbd_dev, uint8_t addr)
Definition at line 150 of file usb_private.h.
Referenced by usbd_ep_stall_get().
void(* _usbd_driver::ep_stall_set)(usbd_device *usbd_dev, uint8_t addr, uint8_t stall)
Definition at line 147 of file usb_private.h.
Referenced by usbd_ep_stall_set().
uint16_t(* _usbd_driver::ep_write_packet)(usbd_device *usbd_dev, uint8_t addr, const void *buf, uint16_t len)
Definition at line 151 of file usb_private.h.
Referenced by usbd_ep_write_packet().
usbd_device*(* _usbd_driver::init)(void)
Definition at line 141 of file usb_private.h.
Referenced by usbd_init().
void(* _usbd_driver::poll)(usbd_device *usbd_dev)
Definition at line 155 of file usb_private.h.
Referenced by usbd_poll().
uint16_t _usbd_driver::rx_fifo_size
Definition at line 159 of file usb_private.h.
Referenced by stm32f107_usbd_init(), stm32f207_usbd_init(), stm32fx07_ep_setup(), and stm32fx07_poll().
void(* _usbd_driver::set_address)(usbd_device *usbd_dev, uint8_t addr)
Definition at line 142 of file usb_private.h.
Referenced by _usbd_control_in(), _usbd_reset(), and usb_standard_set_address().
bool _usbd_driver::set_address_before_status
Definition at line 158 of file usb_private.h.
Referenced by usb_standard_set_address().
The documentation for this struct was generated from the following file:
usb_private.h