libopencm3: usb_standard.c File Reference
usb_standard.c File Reference
Functions
int usbd_register_set_config_callback (usbd_device *usbd_dev, usbd_set_config_callback callback)
void usbd_register_set_altsetting_callback (usbd_device *usbd_dev, usbd_set_altsetting_callback callback)
static uint16_t build_config_descriptor (usbd_device *usbd_dev, uint8_t index, uint8_t *buf, uint16_t len)
static int usb_descriptor_type (uint16_t wValue)
static int usb_descriptor_index (uint16_t wValue)
static int usb_standard_get_descriptor (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
static int usb_standard_set_address (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
static int usb_standard_set_configuration (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
static int usb_standard_get_configuration (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
static int usb_standard_set_interface (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
static int usb_standard_get_interface (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
static int usb_standard_device_get_status (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
static int usb_standard_interface_get_status (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
static int usb_standard_endpoint_get_status (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
static int usb_standard_endpoint_stall (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
static int usb_standard_endpoint_unstall (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
int _usbd_standard_request_device (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
int _usbd_standard_request_interface (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
int _usbd_standard_request_endpoint (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
int _usbd_standard_request (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
Function Documentation
int _usbd_standard_request (usbd_device * usbd_dev, struct usb_setup_data * req, uint8_t ** buf, uint16_t * len)
Definition at line 549 of file usb_standard.c.
References _usbd_standard_request_device(), _usbd_standard_request_endpoint(), _usbd_standard_request_interface(), and usb_setup_data::bmRequestType.
Referenced by usb_control_request_dispatch().
int _usbd_standard_request_device (usbd_device * usbd_dev, struct usb_setup_data * req, uint8_t ** buf, uint16_t * len)
Definition at line 428 of file usb_standard.c.
References usb_setup_data::bRequest, usb_standard_device_get_status(), usb_standard_get_configuration(), usb_standard_get_descriptor(), usb_standard_set_address(), usb_standard_set_configuration(), usbd_dev, and usb_setup_data::wValue.
Referenced by _usbd_standard_request().
int _usbd_standard_request_endpoint (usbd_device * usbd_dev, struct usb_setup_data * req, uint8_t ** buf, uint16_t * len)
Definition at line 512 of file usb_standard.c.
References usb_setup_data::bRequest, usb_standard_endpoint_get_status(), usb_standard_endpoint_stall(), usb_standard_endpoint_unstall(), usbd_dev, and usb_setup_data::wValue.
Referenced by _usbd_standard_request().
int _usbd_standard_request_interface (usbd_device * usbd_dev, struct usb_setup_data * req, uint8_t ** buf, uint16_t * len)
Definition at line 482 of file usb_standard.c.
References usb_setup_data::bRequest, usb_standard_get_interface(), usb_standard_interface_get_status(), usb_standard_set_interface(), and usbd_dev.
Referenced by _usbd_standard_request().