libopencm3: usb_f103.c File Reference
usb_f103.c File Reference
Functions
static usbd_device * stm32f103_usbd_init (void)
Initialize the USB device controller hardware of the STM32.
static void stm32f103_set_address (usbd_device *usbd_dev, uint8_t addr)
static void stm32f103_ep_setup (usbd_device *usbd_dev, uint8_t addr, uint8_t type, uint16_t max_size, void(*callback)(usbd_device *usbd_dev, uint8_t ep))
static void stm32f103_endpoints_reset (usbd_device *usbd_dev)
static void stm32f103_ep_stall_set (usbd_device *usbd_dev, uint8_t addr, uint8_t stall)
static uint8_t stm32f103_ep_stall_get (usbd_device *usbd_dev, uint8_t addr)
static void stm32f103_ep_nak_set (usbd_device *usbd_dev, uint8_t addr, uint8_t nak)
static uint16_t stm32f103_ep_write_packet (usbd_device *usbd_dev, uint8_t addr, const void *buf, uint16_t len)
static uint16_t stm32f103_ep_read_packet (usbd_device *usbd_dev, uint8_t addr, void *buf, uint16_t len)
static void stm32f103_poll (usbd_device *usbd_dev)
static void usb_set_ep_rx_bufsize (usbd_device *dev, uint8_t ep, uint32_t size)
Set the receive buffer size for a given USB endpoint.
static void usb_copy_to_pm (volatile void *vPM, const void *buf, uint16_t len)
Copy a data buffer to packet memory.
static void usb_copy_from_pm (void *buf, const volatile void *vPM, uint16_t len)
Copy a data buffer from packet memory.
Variables
static uint8_t force_nak [8]
static struct _usbd_device usbd_dev
const struct _usbd_driver stm32f103_usb_driver
Function Documentation
static void stm32f103_endpoints_reset (usbd_device * usbd_dev) static
Definition at line 147 of file usb_f103.c.
References usb_device_descriptor::bMaxPacketSize0, _usbd_device::desc, and _usbd_device::pm_top.
static void stm32f103_ep_nak_set (usbd_device * usbd_dev, uint8_t addr, uint8_t nak) static
Definition at line 206 of file usb_f103.c.
static uint16_t stm32f103_ep_read_packet (usbd_device * usbd_dev, uint8_t addr, void * buf, uint16_t len) static
Definition at line 279 of file usb_f103.c.
References usb_copy_from_pm().
static void stm32f103_ep_setup (usbd_device * usbd_dev, uint8_t addr, uint8_t type, uint16_t max_size, void(*)(usbd_device *usbd_dev, uint8_t ep) callback) static
Definition at line 104 of file usb_f103.c.
References _usbd_device::pm_top, usb_set_ep_rx_bufsize(), USB_TRANSACTION_IN, USB_TRANSACTION_OUT, and _usbd_device::user_callback_ctr.
static uint8_t stm32f103_ep_stall_get (usbd_device * usbd_dev, uint8_t addr) static
Definition at line 189 of file usb_f103.c.
static void stm32f103_ep_stall_set (usbd_device * usbd_dev, uint8_t addr, uint8_t stall) static
Definition at line 159 of file usb_f103.c.
static uint16_t stm32f103_ep_write_packet (usbd_device * usbd_dev, uint8_t addr, const void * buf, uint16_t len) static
Definition at line 240 of file usb_f103.c.
References usb_copy_to_pm().
static void stm32f103_poll (usbd_device * usbd_dev) static
Definition at line 298 of file usb_f103.c.
References _usbd_reset(), _usbd_device::pm_top, _usbd_device::user_callback_ctr, _usbd_device::user_callback_resume, _usbd_device::user_callback_sof, and _usbd_device::user_callback_suspend.
static void stm32f103_set_address (usbd_device * usbd_dev, uint8_t addr) static
Definition at line 75 of file usb_f103.c.
static usbd_device * stm32f103_usbd_init (void) static
Initialize the USB device controller hardware of the STM32.
Definition at line 62 of file usb_f103.c.
References usbd_dev.
static void usb_copy_from_pm (void * buf, const volatile void * vPM, uint16_t len) static
Copy a data buffer from packet memory.
Parameters
buf Source pointer to data buffer.
vPM Destination pointer into packet memory.
len Number of bytes to copy.
Definition at line 264 of file usb_f103.c.
Referenced by stm32f103_ep_read_packet().
static void usb_copy_to_pm (volatile void * vPM, const void * buf, uint16_t len) static
Copy a data buffer to packet memory.
Parameters
vPM Destination pointer into packet memory.
buf Source pointer to data buffer.
len Number of bytes to copy.
Definition at line 230 of file usb_f103.c.
Referenced by stm32f103_ep_write_packet().
static void usb_set_ep_rx_bufsize (usbd_device * dev, uint8_t ep, uint32_t size) static
Set the receive buffer size for a given USB endpoint.
Parameters
ep Index of endpoint to configure.
size Size in bytes of the RX buffer.
Definition at line 88 of file usb_f103.c.
Referenced by stm32f103_ep_setup().
Variable Documentation
uint8_t force_nak[8] static
Definition at line 45 of file usb_f103.c.
struct _usbd_device usbd_dev static
Definition at line 46 of file usb_f103.c.
Referenced by _usbd_standard_request_device(), _usbd_standard_request_endpoint(), _usbd_standard_request_interface(), stm32f103_usbd_init(), stm32fx07_poll(), usb_msc_init(), usb_standard_set_configuration(), and usbd_init().