libopencm3: usb_msc.c File Reference
usb_msc.c File Reference
Data Structures
struct usb_msc_cbw
struct usb_msc_csw
struct sbc_sense_info
struct usb_msc_trans
struct _usbd_mass_storage
Enumerations
enum sbc_sense_key {
SBC_SENSE_KEY_NO_SENSE = 0x00, SBC_SENSE_KEY_RECOVERED_ERROR = 0x01, SBC_SENSE_KEY_NOT_READY = 0x02, SBC_SENSE_KEY_MEDIUM_ERROR = 0x03,
SBC_SENSE_KEY_HARDWARE_ERROR = 0x04, SBC_SENSE_KEY_ILLEGAL_REQUEST = 0x05, SBC_SENSE_KEY_UNIT_ATTENTION = 0x06, SBC_SENSE_KEY_DATA_PROTECT = 0x07,
SBC_SENSE_KEY_BLANK_CHECK = 0x08, SBC_SENSE_KEY_VENDOR_SPECIFIC = 0x09, SBC_SENSE_KEY_COPY_ABORTED = 0x0A, SBC_SENSE_KEY_ABORTED_COMMAND = 0x0B,
SBC_SENSE_KEY_VOLUME_OVERFLOW = 0x0D, SBC_SENSE_KEY_MISCOMPARE = 0x0E
}
enum sbc_asc {
SBC_ASC_NO_ADDITIONAL_SENSE_INFORMATION = 0x00, SBC_ASC_PERIPHERAL_DEVICE_WRITE_FAULT = 0x03, SBC_ASC_LOGICAL_UNIT_NOT_READY = 0x04, SBC_ASC_UNRECOVERED_READ_ERROR = 0x11,
SBC_ASC_INVALID_COMMAND_OPERATION_CODE = 0x20, SBC_ASC_LBA_OUT_OF_RANGE = 0x21, SBC_ASC_INVALID_FIELD_IN_CDB = 0x24, SBC_ASC_WRITE_PROTECTED = 0x27,
SBC_ASC_NOT_READY_TO_READY_CHANGE = 0x28, SBC_ASC_FORMAT_ERROR = 0x31, SBC_ASC_MEDIUM_NOT_PRESENT = 0x3A
}
enum sbc_ascq { SBC_ASCQ_NA = 0x00, SBC_ASCQ_FORMAT_COMMAND_FAILED = 0x01, SBC_ASCQ_INITIALIZING_COMMAND_REQUIRED = 0x02, SBC_ASCQ_OPERATION_IN_PROGRESS = 0x07 }
enum trans_event { EVENT_CBW_VALID, EVENT_NEED_STATUS }
Functions
struct usb_msc_cbw __attribute__ ((packed))
static void set_sbc_status (usbd_mass_storage *ms, enum sbc_sense_key key, enum sbc_asc asc, enum sbc_ascq ascq)
static void set_sbc_status_good (usbd_mass_storage *ms)
static uint8_t * get_cbw_buf (struct usb_msc_trans *trans)
static void scsi_read_6 (usbd_mass_storage *ms, struct usb_msc_trans *trans, enum trans_event event)
static void scsi_write_6 (usbd_mass_storage *ms, struct usb_msc_trans *trans, enum trans_event event)
static void scsi_write_10 (usbd_mass_storage *ms, struct usb_msc_trans *trans, enum trans_event event)
static void scsi_read_10 (usbd_mass_storage *ms, struct usb_msc_trans *trans, enum trans_event event)
static void scsi_read_capacity (usbd_mass_storage *ms, struct usb_msc_trans *trans, enum trans_event event)
static void scsi_format_unit (usbd_mass_storage *ms, struct usb_msc_trans *trans, enum trans_event event)
static void scsi_request_sense (usbd_mass_storage *ms, struct usb_msc_trans *trans, enum trans_event event)
static void scsi_mode_sense_6 (usbd_mass_storage *ms, struct usb_msc_trans *trans, enum trans_event event)
static void scsi_inquiry (usbd_mass_storage *ms, struct usb_msc_trans *trans, enum trans_event event)
static void scsi_command (usbd_mass_storage *ms, struct usb_msc_trans *trans, enum trans_event event)
static void msc_data_rx_cb (usbd_device *usbd_dev, uint8_t ep)
Handle the USB 'OUT' requests.
static void msc_data_tx_cb (usbd_device *usbd_dev, uint8_t ep)
Handle the USB 'IN' requests.
static int msc_control_request (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len, void(**complete)(usbd_device *usbd_dev, struct usb_setup_data *req))
Handle various control requests related to the msc storage interface.
static void msc_set_config (usbd_device *usbd_dev, uint16_t wValue)
Setup the endpoints to be bulk & register the callbacks.
usbd_mass_storage * usb_msc_init (usbd_device *usbd_dev, uint8_t ep_in, uint8_t ep_in_size, uint8_t ep_out, uint8_t ep_out_size, const char *vendor_id, const char *product_id, const char *product_revision_level, const uint32_t block_count, int(*read_block)(uint32_t lba, uint8_t *copy_to), int(*write_block)(uint32_t lba, const uint8_t *copy_from))
Initializes the USB Mass Storage subsystem.
Variables
uint32_t dCBWSignature
uint32_t dCBWTag
uint32_t dCBWDataTransferLength
uint8_t bmCBWFlags
uint8_t bCBWLUN
uint8_t bCBWCBLength
uint8_t CBWCB [16]
uint32_t dCSWSignature
uint32_t dCSWTag
uint32_t dCSWDataResidue
uint8_t bCSWStatus
struct sbc_sense_info __attribute__
static usbd_mass_storage _mass_storage
static const uint8_t _spc3_inquiry_response [36]
static const uint8_t _spc3_request_sense [18]
Enumeration Type Documentation
enum sbc_asc
Enumerator
SBC_ASC_NO_ADDITIONAL_SENSE_INFORMATION
SBC_ASC_PERIPHERAL_DEVICE_WRITE_FAULT
SBC_ASC_LOGICAL_UNIT_NOT_READY
SBC_ASC_UNRECOVERED_READ_ERROR
SBC_ASC_INVALID_COMMAND_OPERATION_CODE
SBC_ASC_LBA_OUT_OF_RANGE
SBC_ASC_INVALID_FIELD_IN_CDB
SBC_ASC_WRITE_PROTECTED
SBC_ASC_NOT_READY_TO_READY_CHANGE
SBC_ASC_FORMAT_ERROR
SBC_ASC_MEDIUM_NOT_PRESENT
Definition at line 98 of file usb_msc.c.
enum sbc_ascq
Enumerator
SBC_ASCQ_NA
SBC_ASCQ_FORMAT_COMMAND_FAILED
SBC_ASCQ_INITIALIZING_COMMAND_REQUIRED
SBC_ASCQ_OPERATION_IN_PROGRESS
Definition at line 112 of file usb_msc.c.
enum sbc_sense_key
Enumerator
SBC_SENSE_KEY_NO_SENSE
SBC_SENSE_KEY_RECOVERED_ERROR
SBC_SENSE_KEY_NOT_READY
SBC_SENSE_KEY_MEDIUM_ERROR
SBC_SENSE_KEY_HARDWARE_ERROR
SBC_SENSE_KEY_ILLEGAL_REQUEST
SBC_SENSE_KEY_UNIT_ATTENTION
SBC_SENSE_KEY_DATA_PROTECT
SBC_SENSE_KEY_BLANK_CHECK
SBC_SENSE_KEY_VENDOR_SPECIFIC
SBC_SENSE_KEY_COPY_ABORTED
SBC_SENSE_KEY_ABORTED_COMMAND
SBC_SENSE_KEY_VOLUME_OVERFLOW
SBC_SENSE_KEY_MISCOMPARE
Definition at line 81 of file usb_msc.c.
enum trans_event
Enumerator
EVENT_CBW_VALID
EVENT_NEED_STATUS
Definition at line 119 of file usb_msc.c.
Function Documentation
struct usb_msc_cbw __attribute__ ((packed))
static uint8_t* get_cbw_buf (struct usb_msc_trans * trans) static
Definition at line 253 of file usb_msc.c.
References usb_msc_trans::cbw, and usb_msc_cbw::CBWCB.
Referenced by scsi_inquiry(), scsi_read_10(), scsi_read_6(), scsi_write_10(), and scsi_write_6().
static int msc_control_request (usbd_device * usbd_dev, struct usb_setup_data * req, uint8_t ** buf, uint16_t * len, void(**)(usbd_device *usbd_dev, struct usb_setup_data *req) complete) static
Handle various control requests related to the msc storage interface.
Definition at line 709 of file usb_msc.c.
References usb_setup_data::bRequest, USBD_REQ_HANDLED, and USBD_REQ_NOTSUPP.
Referenced by msc_set_config().
static void msc_data_rx_cb (usbd_device * usbd_dev, uint8_t ep) static
Handle the USB 'OUT' requests.
Definition at line 537 of file usb_msc.c.
References _mass_storage, _usbd_mass_storage::ep_in, _usbd_mass_storage::ep_out_size, EVENT_CBW_VALID, EVENT_NEED_STATUS, _usbd_mass_storage::lock, _usbd_mass_storage::read_block, scsi_command(), _usbd_mass_storage::trans, _usbd_mass_storage::unlock, usbd_ep_read_packet(), usbd_ep_write_packet(), and _usbd_mass_storage::write_block.
Referenced by msc_set_config().
static void msc_data_tx_cb (usbd_device * usbd_dev, uint8_t ep) static
Handle the USB 'IN' requests.
Definition at line 643 of file usb_msc.c.
References _mass_storage, usb_msc_trans::block_count, usb_msc_trans::byte_count, usb_msc_trans::bytes_to_write, usb_msc_trans::csw_valid, usb_msc_trans::current_block, _usbd_mass_storage::ep_out_size, EVENT_NEED_STATUS, usb_msc_trans::lba_start, usb_msc_trans::msd_buf, _usbd_mass_storage::read_block, scsi_command(), _usbd_mass_storage::trans, _usbd_mass_storage::unlock, and usbd_ep_write_packet().
Referenced by msc_set_config().
static void msc_set_config (usbd_device * usbd_dev, uint16_t wValue) static
Setup the endpoints to be bulk & register the callbacks.
Definition at line 731 of file usb_msc.c.
References _mass_storage, _usbd_mass_storage::ep_in, _usbd_mass_storage::ep_in_size, _usbd_mass_storage::ep_out, _usbd_mass_storage::ep_out_size, msc_control_request(), msc_data_rx_cb(), msc_data_tx_cb(), usbd_ep_setup(), and usbd_register_control_callback().
Referenced by usb_msc_init().
static void scsi_command (usbd_mass_storage * ms, struct usb_msc_trans * trans, enum trans_event event) static
Definition at line 472 of file usb_msc.c.
References usb_msc_csw::bCSWStatus, usb_msc_trans::byte_count, usb_msc_trans::bytes_to_read, usb_msc_trans::bytes_to_write, usb_msc_trans::cbw, usb_msc_cbw::CBWCB, usb_msc_trans::csw, usb_msc_trans::csw_sent, usb_msc_cbw::dCBWTag, usb_msc_csw::dCSWDataResidue, usb_msc_csw::dCSWSignature, usb_msc_csw::dCSWTag, EVENT_CBW_VALID, SBC_ASC_INVALID_COMMAND_OPERATION_CODE, SBC_ASCQ_NA, SBC_SENSE_KEY_ILLEGAL_REQUEST, scsi_format_unit(), scsi_inquiry(), scsi_mode_sense_6(), scsi_read_10(), scsi_read_6(), scsi_read_capacity(), scsi_request_sense(), scsi_write_10(), scsi_write_6(), set_sbc_status(), and set_sbc_status_good().
Referenced by msc_data_rx_cb(), and msc_data_tx_cb().
static void scsi_format_unit (usbd_mass_storage * ms, struct usb_msc_trans * trans, enum trans_event event) static
Definition at line 360 of file usb_msc.c.
References _usbd_mass_storage::block_count, EVENT_CBW_VALID, usb_msc_trans::msd_buf, set_sbc_status_good(), and _usbd_mass_storage::write_block.
Referenced by scsi_command().
static void scsi_inquiry (usbd_mass_storage * ms, struct usb_msc_trans * trans, enum trans_event event) static
Definition at line 434 of file usb_msc.c.
References _spc3_inquiry_response, usb_msc_trans::bytes_to_write, usb_msc_trans::csw, usb_msc_csw::dCSWDataResidue, EVENT_CBW_VALID, get_cbw_buf(), usb_msc_trans::msd_buf, _usbd_mass_storage::product_id, _usbd_mass_storage::product_revision_level, set_sbc_status_good(), and _usbd_mass_storage::vendor_id.
Referenced by scsi_command().
static void scsi_mode_sense_6 (usbd_mass_storage * ms, struct usb_msc_trans * trans, enum trans_event event) static
Definition at line 395 of file usb_msc.c.
References usb_msc_csw::bCSWStatus, usb_msc_trans::bytes_to_write, usb_msc_trans::cbw, usb_msc_cbw::CBWCB, usb_msc_trans::csw, usb_msc_csw::dCSWDataResidue, EVENT_CBW_VALID, usb_msc_trans::msd_buf, SBC_ASC_INVALID_FIELD_IN_CDB, SBC_ASCQ_NA, SBC_SENSE_KEY_ILLEGAL_REQUEST, and set_sbc_status().
Referenced by scsi_command().
static void scsi_read_10 (usbd_mass_storage * ms, struct usb_msc_trans * trans, enum trans_event event) static
Definition at line 319 of file usb_msc.c.
References usb_msc_trans::block_count, usb_msc_trans::bytes_to_write, EVENT_CBW_VALID, get_cbw_buf(), usb_msc_trans::lba_start, and set_sbc_status_good().
Referenced by scsi_command().
static void scsi_read_6 (usbd_mass_storage * ms, struct usb_msc_trans * trans, enum trans_event event) static
Definition at line 258 of file usb_msc.c.
References usb_msc_trans::block_count, usb_msc_trans::bytes_to_write, usb_msc_trans::current_block, EVENT_CBW_VALID, get_cbw_buf(), usb_msc_trans::lba_start, and set_sbc_status_good().
Referenced by scsi_command().
static void scsi_read_capacity (usbd_mass_storage * ms, struct usb_msc_trans * trans, enum trans_event event) static
Definition at line 340 of file usb_msc.c.
References _usbd_mass_storage::block_count, usb_msc_trans::bytes_to_write, EVENT_CBW_VALID, usb_msc_trans::msd_buf, and set_sbc_status_good().
Referenced by scsi_command().
static void scsi_request_sense (usbd_mass_storage * ms, struct usb_msc_trans * trans, enum trans_event event) static
Definition at line 377 of file usb_msc.c.
References sbc_sense_info::asc, sbc_sense_info::ascq, usb_msc_trans::bytes_to_write, usb_msc_trans::cbw, usb_msc_cbw::CBWCB, EVENT_CBW_VALID, sbc_sense_info::key, usb_msc_trans::msd_buf, and _usbd_mass_storage::sense.
Referenced by scsi_command().
static void scsi_write_10 (usbd_mass_storage * ms, struct usb_msc_trans * trans, enum trans_event event) static
Definition at line 299 of file usb_msc.c.
References usb_msc_trans::block_count, usb_msc_trans::bytes_to_read, usb_msc_trans::current_block, EVENT_CBW_VALID, get_cbw_buf(), and usb_msc_trans::lba_start.
Referenced by scsi_command().
static void scsi_write_6 (usbd_mass_storage * ms, struct usb_msc_trans * trans, enum trans_event event) static
Definition at line 280 of file usb_msc.c.
References usb_msc_trans::block_count, usb_msc_trans::bytes_to_read, usb_msc_trans::current_block, EVENT_CBW_VALID, get_cbw_buf(), and usb_msc_trans::lba_start.
Referenced by scsi_command().
static void set_sbc_status (usbd_mass_storage * ms, enum sbc_sense_key key, enum sbc_asc asc, enum sbc_ascq ascq) static
Definition at line 235 of file usb_msc.c.
References sbc_sense_info::asc, sbc_sense_info::ascq, sbc_sense_info::key, and _usbd_mass_storage::sense.
Referenced by scsi_command(), scsi_mode_sense_6(), and set_sbc_status_good().
static void set_sbc_status_good (usbd_mass_storage * ms) static
Definition at line 245 of file usb_msc.c.
References SBC_ASC_NO_ADDITIONAL_SENSE_INFORMATION, SBC_ASCQ_NA, SBC_SENSE_KEY_NO_SENSE, and set_sbc_status().
Referenced by scsi_command(), scsi_format_unit(), scsi_inquiry(), scsi_read_10(), scsi_read_6(), scsi_read_capacity(), and usb_msc_init().
Variable Documentation
struct sbc_sense_info __attribute__
usbd_mass_storage _mass_storage static
Definition at line 194 of file usb_msc.c.
Referenced by msc_data_rx_cb(), msc_data_tx_cb(), msc_set_config(), and usb_msc_init().
const uint8_t _spc3_inquiry_response[36] static
Initial value:
= {
        0x00,
        0x80,
        0x04,
        0x02,
        0x20,
        0x00,
        0x00,
        0x00,
        0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20,
        0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20,
        0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20, 0x20,
        0x20, 0x20, 0x20, 0x20
}
Definition at line 198 of file usb_msc.c.
Referenced by scsi_inquiry().
const uint8_t _spc3_request_sense[18] static
Initial value:
= {
        0x70,
        0x00,
        0x00,
        0, 0, 0, 0,
        0x0a,
        0, 0, 0, 0,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00,
        0x00
}
Definition at line 216 of file usb_msc.c.
uint8_t bCBWCBLength
Definition at line 42 of file usb_msc.c.
uint8_t bCBWLUN
Definition at line 41 of file usb_msc.c.
uint8_t bCSWStatus
Definition at line 40 of file usb_msc.c.
uint8_t bmCBWFlags
Definition at line 40 of file usb_msc.c.
uint8_t CBWCB[16]
Definition at line 43 of file usb_msc.c.
uint32_t dCBWDataTransferLength
Definition at line 39 of file usb_msc.c.
uint32_t dCBWSignature
Definition at line 37 of file usb_msc.c.
uint32_t dCBWTag
Definition at line 38 of file usb_msc.c.
uint32_t dCSWDataResidue
Definition at line 39 of file usb_msc.c.
uint32_t dCSWSignature
Definition at line 37 of file usb_msc.c.
uint32_t dCSWTag
Definition at line 38 of file usb_msc.c.