libopencm3: flash_common_f234.h File Reference
flash_common_f234.h File Reference
#include <libopencm3/cm3/common.h>
Macros
#define FLASH_ACR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x00)
#define FLASH_KEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x04)
#define FLASH_OPTKEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x08)
#define FLASH_SR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x0C)
#define FLASH_CR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x10)
#define FLASH_ACR_LATENCY_0WS 0x00
#define FLASH_ACR_LATENCY_1WS 0x01
#define FLASH_ACR_LATENCY_2WS 0x02
#define FLASH_ACR_LATENCY_3WS 0x03
#define FLASH_ACR_LATENCY_4WS 0x04
#define FLASH_ACR_LATENCY_5WS 0x05
#define FLASH_ACR_LATENCY_6WS 0x06
#define FLASH_ACR_LATENCY_7WS 0x07
#define FLASH_KEYR_KEY1 ((uint32_t)0x45670123)
#define FLASH_KEYR_KEY2 ((uint32_t)0xcdef89ab)
Functions
void flash_set_ws (uint32_t ws)
void flash_unlock (void)
void flash_lock (void)
void flash_clear_pgperr_flag (void)
void flash_clear_eop_flag (void)
void flash_clear_bsy_flag (void)
void flash_clear_status_flags (void)
void flash_wait_for_last_operation (void)
Macro Definition Documentation
#define FLASH_ACR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x00)
Definition at line 38 of file flash_common_f234.h.
#define FLASH_ACR_LATENCY_0WS 0x00
Definition at line 46 of file flash_common_f234.h.
#define FLASH_ACR_LATENCY_1WS 0x01
Definition at line 47 of file flash_common_f234.h.
#define FLASH_ACR_LATENCY_2WS 0x02
Definition at line 48 of file flash_common_f234.h.
#define FLASH_ACR_LATENCY_3WS 0x03
Definition at line 49 of file flash_common_f234.h.
#define FLASH_ACR_LATENCY_4WS 0x04
Definition at line 50 of file flash_common_f234.h.
#define FLASH_ACR_LATENCY_5WS 0x05
Definition at line 51 of file flash_common_f234.h.
#define FLASH_ACR_LATENCY_6WS 0x06
Definition at line 52 of file flash_common_f234.h.
#define FLASH_ACR_LATENCY_7WS 0x07
Definition at line 53 of file flash_common_f234.h.
#define FLASH_CR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x10)
Definition at line 42 of file flash_common_f234.h.
#define FLASH_KEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x04)
Definition at line 39 of file flash_common_f234.h.
#define FLASH_KEYR_KEY1 ((uint32_t)0x45670123)
Definition at line 61 of file flash_common_f234.h.
#define FLASH_KEYR_KEY2 ((uint32_t)0xcdef89ab)
Definition at line 62 of file flash_common_f234.h.
#define FLASH_OPTKEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x08)
Definition at line 40 of file flash_common_f234.h.
#define FLASH_SR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x0C)
Definition at line 41 of file flash_common_f234.h.
Function Documentation
void flash_clear_bsy_flag (void)
Definition at line 83 of file flash.c.
References FLASH_SR, and FLASH_SR_BSY.
void flash_clear_eop_flag (void)
Definition at line 73 of file flash.c.
References FLASH_SR, and FLASH_SR_EOP.
void flash_clear_pgperr_flag (void)
Definition at line 48 of file flash_common_f234.c.
References FLASH_SR.
void flash_clear_status_flags (void)
Definition at line 88 of file flash.c.
References flash_clear_bsy_flag(), flash_clear_eop_flag(), flash_clear_pgerr_flag(), and flash_clear_wrprterr_flag().
void flash_lock (void)
Definition at line 63 of file flash.c.
References FLASH_CR, and FLASH_CR_LOCK.
void flash_set_ws (uint32_t ws)
Definition at line 43 of file flash.c.
References FLASH_ACR.
void flash_unlock (void)
Definition at line 53 of file flash.c.
References FLASH_CR, FLASH_CR_LOCK, FLASH_KEYR, FLASH_KEYR_KEY1, and FLASH_KEYR_KEY2.
void flash_wait_for_last_operation (void)
Definition at line 111 of file flash.c.
References FLASH_SR, and FLASH_SR_BSY.