libopencm3: flash.c File Reference
flash.c File Reference
Functions
void flash_prefetch_buffer_enable (void)
void flash_prefetch_buffer_disable (void)
void flash_halfcycle_enable (void)
void flash_halfcycle_disable (void)
void flash_set_ws (u32 ws)
void flash_unlock (void)
void flash_lock (void)
void flash_clear_pgerr_flag (void)
void flash_clear_eop_flag (void)
void flash_clear_wrprterr_flag (void)
void flash_clear_bsy_flag (void)
void flash_clear_status_flags (void)
void flash_unlock_option_bytes (void)
void flash_wait_for_last_operation (void)
void flash_program_word (u32 address, u32 data)
void flash_program_half_word (u32 address, u16 data)
void flash_erase_page (u32 page_address)
void flash_erase_all_pages (void)
void flash_erase_option_bytes (void)
void flash_program_option_bytes (u32 address, u16 data)
Function Documentation
void flash_clear_bsy_flag (void)
Definition at line 83 of file flash.c.
Referenced by flash_clear_status_flags().
void flash_clear_eop_flag (void)
Definition at line 73 of file flash.c.
Referenced by flash_clear_status_flags().
void flash_clear_pgerr_flag (void)
Definition at line 68 of file flash.c.
Referenced by flash_clear_status_flags().
void flash_clear_status_flags (void)
Definition at line 88 of file flash.c.
References flash_clear_bsy_flag(), flash_clear_eop_flag(), flash_clear_pgerr_flag(), and flash_clear_wrprterr_flag().
void flash_clear_wrprterr_flag (void)
Definition at line 78 of file flash.c.
Referenced by flash_clear_status_flags().
void flash_erase_all_pages (void)
Definition at line 158 of file flash.c.
References flash_wait_for_last_operation().
void flash_erase_option_bytes (void)
Definition at line 169 of file flash.c.
References flash_unlock_option_bytes(), and flash_wait_for_last_operation().
void flash_erase_page (u32 page_address)
Definition at line 146 of file flash.c.
References flash_wait_for_last_operation().
void flash_halfcycle_disable (void)
Definition at line 38 of file flash.c.
void flash_halfcycle_enable (void)
Definition at line 33 of file flash.c.
void flash_lock (void)
Definition at line 63 of file flash.c.
void flash_prefetch_buffer_disable (void)
Definition at line 28 of file flash.c.
void flash_prefetch_buffer_enable (void)
Definition at line 23 of file flash.c.
void flash_program_half_word (u32 address, u16 data)
Definition at line 133 of file flash.c.
References flash_wait_for_last_operation().
void flash_program_option_bytes (u32 address, u16 data)
Definition at line 182 of file flash.c.
References flash_unlock_option_bytes(), and flash_wait_for_last_operation().
void flash_program_word (u32 address, u32 data)
Definition at line 109 of file flash.c.
References flash_wait_for_last_operation().
void flash_set_ws (u32 ws)
Definition at line 43 of file flash.c.
Referenced by rcc_clock_setup_in_hse_12mhz_out_72mhz(), rcc_clock_setup_in_hse_16mhz_out_72mhz(), rcc_clock_setup_in_hse_25mhz_out_72mhz(), rcc_clock_setup_in_hse_8mhz_out_24mhz(), rcc_clock_setup_in_hse_8mhz_out_72mhz(), rcc_clock_setup_in_hsi_out_24mhz(), rcc_clock_setup_in_hsi_out_48mhz(), and rcc_clock_setup_in_hsi_out_64mhz().
void flash_unlock (void)
Definition at line 53 of file flash.c.
void flash_unlock_option_bytes (void)
Definition at line 96 of file flash.c.
Referenced by flash_erase_option_bytes(), and flash_program_option_bytes().
void flash_wait_for_last_operation (void)
Definition at line 103 of file flash.c.
Referenced by flash_erase_all_pages(), flash_erase_option_bytes(), flash_erase_page(), flash_program_half_word(), flash_program_option_bytes(), and flash_program_word().