libopencm3: RCC
RCC
STM32F1xx
libopencm3 STM32F1xx Reset and Clock Control
Functions
void rcc_osc_ready_int_clear (osc_t osc)
RCC Clear the Oscillator Ready Interrupt Flag.
void rcc_osc_ready_int_enable (osc_t osc)
RCC Enable the Oscillator Ready Interrupt.
void rcc_osc_ready_int_disable (osc_t osc)
RCC Disable the Oscillator Ready Interrupt.
int rcc_osc_ready_int_flag (osc_t osc)
RCC Read the Oscillator Ready Interrupt Flag.
void rcc_css_int_clear (void)
RCC Clear the Clock Security System Interrupt Flag.
int rcc_css_int_flag (void)
RCC Read the Clock Security System Interrupt Flag.
void rcc_wait_for_osc_ready (osc_t osc)
RCC Wait for Oscillator Ready.
void rcc_osc_on (osc_t osc)
RCC Turn on an Oscillator.
void rcc_osc_off (osc_t osc)
RCC Turn off an Oscillator.
void rcc_css_enable (void)
RCC Enable the Clock Security System.
void rcc_css_disable (void)
RCC Disable the Clock Security System.
void rcc_osc_bypass_enable (osc_t osc)
RCC Enable Bypass.
void rcc_osc_bypass_disable (osc_t osc)
RCC Disable Bypass.
void rcc_peripheral_enable_clock (volatile uint32_t *reg, uint32_t en)
RCC Enable Peripheral Clocks.
void rcc_peripheral_disable_clock (volatile uint32_t *reg, uint32_t en)
RCC Disable Peripheral Clocks.
void rcc_peripheral_reset (volatile uint32_t *reg, uint32_t reset)
RCC Reset Peripherals.
void rcc_peripheral_clear_reset (volatile uint32_t *reg, uint32_t clear_reset)
RCC Remove Reset on Peripherals.
void rcc_set_sysclk_source (uint32_t clk)
RCC Set the Source for the System Clock.
void rcc_set_pll_multiplication_factor (uint32_t mul)
RCC Set the PLL Multiplication Factor.
void rcc_set_pll2_multiplication_factor (uint32_t mul)
RCC Set the PLL2 Multiplication Factor.
void rcc_set_pll3_multiplication_factor (uint32_t mul)
RCC Set the PLL3 Multiplication Factor.
void rcc_set_pll_source (uint32_t pllsrc)
RCC Set the PLL Clock Source.
void rcc_set_pllxtpre (uint32_t pllxtpre)
RCC Set the HSE Frequency Divider used as PLL Clock Source.
void rcc_set_adcpre (uint32_t adcpre)
ADC Setup the A/D Clock.
void rcc_set_ppre2 (uint32_t ppre2)
RCC Set the APB2 Prescale Factor.
void rcc_set_ppre1 (uint32_t ppre1)
RCC Set the APB1 Prescale Factor.
void rcc_set_hpre (uint32_t hpre)
RCC Set the AHB Prescale Factor.
void rcc_set_usbpre (uint32_t usbpre)
RCC Set the USB Prescale Factor.
void rcc_set_prediv1 (uint32_t prediv)
void rcc_set_prediv2 (uint32_t prediv)
void rcc_set_prediv1_source (uint32_t rccsrc)
void rcc_set_mco (uint32_t mcosrc)
uint32_t rcc_system_clock_source (void)
RCC Get the System Clock Source.
void rcc_clock_setup_in_hsi_out_64mhz (void)
RCC Set System Clock PLL at 64MHz from HSI.
void rcc_clock_setup_in_hsi_out_48mhz (void)
RCC Set System Clock PLL at 48MHz from HSI.
void rcc_clock_setup_in_hsi_out_24mhz (void)
RCC Set System Clock PLL at 24MHz from HSI.
void rcc_clock_setup_in_hse_8mhz_out_24mhz (void)
RCC Set System Clock PLL at 24MHz from HSE at 8MHz.
void rcc_clock_setup_in_hse_8mhz_out_72mhz (void)
RCC Set System Clock PLL at 72MHz from HSE at 8MHz.
void rcc_clock_setup_in_hse_12mhz_out_72mhz (void)
RCC Set System Clock PLL at 24MHz from HSE at 12MHz.
void rcc_clock_setup_in_hse_16mhz_out_72mhz (void)
RCC Set System Clock PLL at 24MHz from HSE at 16MHz.
void rcc_clock_setup_in_hse_25mhz_out_72mhz (void)
RCC Set System Clock PLL at 72MHz from HSE at 25MHz.
void rcc_backupdomain_reset (void)
RCC Reset the backup domain.
Variables
uint32_t rcc_ppre1_frequency = 8000000
Default ppre1 peripheral clock frequency after reset.
uint32_t rcc_ppre2_frequency = 8000000
Default ppre2 peripheral clock frequency after reset.
Detailed Description
libopencm3 STM32F1xx Reset and Clock Control
Version
1.0.0
Author
© 2009 Federico Ruiz-Ugalde <memeruiz at gmail dot com>
© 2009 Uwe Hermann uwe@h.nosp@m.erma.nosp@m.nn-uw.nosp@m.e.de
© 2010 Thomas Otto tommi.nosp@m.@via.nosp@m.dmin..nosp@m.org
Date
18 August 2012
This library supports the Reset and Clock Control System in the STM32F1xx series of ARM Cortex Microcontrollers by ST Microelectronics.
Note
Full support for connection line devices is not yet provided.
Clock settings and resets for many peripherals are given here rather than in the corresponding peripheral library.
The library also provides a number of common configurations for the processor system clock. Not all possible configurations are included.
LGPL License Terms libopencm3 License
Function Documentation
void rcc_backupdomain_reset (void)
RCC Reset the backup domain.
The backup domain register is reset to disable all controls.
Definition at line 1213 of file rcc.c.
References RCC_BDCR, and RCC_BDCR_BDRST.
Referenced by rtc_awake_from_off().
void rcc_clock_setup_in_hse_12mhz_out_72mhz (void)
RCC Set System Clock PLL at 24MHz from HSE at 12MHz.
Definition at line 1029 of file rcc.c.
References FLASH_ACR_LATENCY_2WS, flash_set_ws(), HSE, HSI, PLL, RCC_CFGR_ADCPRE_PCLK2_DIV6, RCC_CFGR_HPRE_SYSCLK_NODIV, RCC_CFGR_PLLMUL_PLL_CLK_MUL6, RCC_CFGR_PLLSRC_HSE_CLK, RCC_CFGR_PLLXTPRE_HSE_CLK, RCC_CFGR_PPRE1_HCLK_DIV2, RCC_CFGR_PPRE2_HCLK_NODIV, RCC_CFGR_SW_SYSCLKSEL_HSECLK, RCC_CFGR_SW_SYSCLKSEL_HSICLK, RCC_CFGR_SW_SYSCLKSEL_PLLCLK, rcc_osc_on(), rcc_ppre1_frequency, rcc_ppre2_frequency, rcc_set_adcpre(), rcc_set_hpre(), rcc_set_pll_multiplication_factor(), rcc_set_pll_source(), rcc_set_pllxtpre(), rcc_set_ppre1(), rcc_set_ppre2(), rcc_set_sysclk_source(), and rcc_wait_for_osc_ready().
void rcc_clock_setup_in_hse_16mhz_out_72mhz (void)
RCC Set System Clock PLL at 24MHz from HSE at 16MHz.
Definition at line 1092 of file rcc.c.
References FLASH_ACR_LATENCY_2WS, flash_set_ws(), HSE, HSI, PLL, RCC_CFGR_ADCPRE_PCLK2_DIV6, RCC_CFGR_HPRE_SYSCLK_NODIV, RCC_CFGR_PLLMUL_PLL_CLK_MUL9, RCC_CFGR_PLLSRC_HSE_CLK, RCC_CFGR_PLLXTPRE_HSE_CLK_DIV2, RCC_CFGR_PPRE1_HCLK_DIV2, RCC_CFGR_PPRE2_HCLK_NODIV, RCC_CFGR_SW_SYSCLKSEL_HSECLK, RCC_CFGR_SW_SYSCLKSEL_HSICLK, RCC_CFGR_SW_SYSCLKSEL_PLLCLK, rcc_osc_on(), rcc_ppre1_frequency, rcc_ppre2_frequency, rcc_set_adcpre(), rcc_set_hpre(), rcc_set_pll_multiplication_factor(), rcc_set_pll_source(), rcc_set_pllxtpre(), rcc_set_ppre1(), rcc_set_ppre2(), rcc_set_sysclk_source(), and rcc_wait_for_osc_ready().
void rcc_clock_setup_in_hse_25mhz_out_72mhz (void)
RCC Set System Clock PLL at 72MHz from HSE at 25MHz.
Definition at line 1155 of file rcc.c.
References FLASH_ACR_LATENCY_2WS, flash_set_ws(), HSE, PLL, PLL2, RCC_CFGR2_PLL2MUL_PLL2_CLK_MUL8, RCC_CFGR2_PREDIV1SRC_PLL2_CLK, RCC_CFGR2_PREDIV2_DIV5, RCC_CFGR2_PREDIV_DIV5, RCC_CFGR_ADCPRE_PCLK2_DIV6, RCC_CFGR_HPRE_SYSCLK_NODIV, RCC_CFGR_PLLMUL_PLL_CLK_MUL9, RCC_CFGR_PLLSRC_PREDIV1_CLK, RCC_CFGR_PLLXTPRE_HSE_CLK, RCC_CFGR_PPRE1_HCLK_DIV2, RCC_CFGR_PPRE2_HCLK_NODIV, RCC_CFGR_SW_SYSCLKSEL_HSECLK, RCC_CFGR_SW_SYSCLKSEL_PLLCLK, RCC_CFGR_USBPRE_PLL_VCO_CLK_DIV3, rcc_osc_on(), rcc_ppre1_frequency, rcc_ppre2_frequency, rcc_set_adcpre(), rcc_set_hpre(), rcc_set_pll2_multiplication_factor(), rcc_set_pll_multiplication_factor(), rcc_set_pll_source(), rcc_set_pllxtpre(), rcc_set_ppre1(), rcc_set_ppre2(), rcc_set_prediv1(), rcc_set_prediv1_source(), rcc_set_prediv2(), rcc_set_sysclk_source(), rcc_set_usbpre(), and rcc_wait_for_osc_ready().
void rcc_clock_setup_in_hse_8mhz_out_24mhz (void)
RCC Set System Clock PLL at 24MHz from HSE at 8MHz.
Definition at line 903 of file rcc.c.
References FLASH_ACR_LATENCY_0WS, flash_set_ws(), HSE, HSI, PLL, RCC_CFGR_ADCPRE_PCLK2_DIV2, RCC_CFGR_HPRE_SYSCLK_NODIV, RCC_CFGR_PLLMUL_PLL_CLK_MUL3, RCC_CFGR_PLLSRC_HSE_CLK, RCC_CFGR_PLLXTPRE_HSE_CLK, RCC_CFGR_PPRE1_HCLK_NODIV, RCC_CFGR_PPRE2_HCLK_NODIV, RCC_CFGR_SW_SYSCLKSEL_HSECLK, RCC_CFGR_SW_SYSCLKSEL_HSICLK, RCC_CFGR_SW_SYSCLKSEL_PLLCLK, rcc_osc_on(), rcc_ppre1_frequency, rcc_ppre2_frequency, rcc_set_adcpre(), rcc_set_hpre(), rcc_set_pll_multiplication_factor(), rcc_set_pll_source(), rcc_set_pllxtpre(), rcc_set_ppre1(), rcc_set_ppre2(), rcc_set_sysclk_source(), and rcc_wait_for_osc_ready().
void rcc_clock_setup_in_hse_8mhz_out_72mhz (void)
RCC Set System Clock PLL at 72MHz from HSE at 8MHz.
Definition at line 966 of file rcc.c.
References FLASH_ACR_LATENCY_2WS, flash_set_ws(), HSE, HSI, PLL, RCC_CFGR_ADCPRE_PCLK2_DIV8, RCC_CFGR_HPRE_SYSCLK_NODIV, RCC_CFGR_PLLMUL_PLL_CLK_MUL9, RCC_CFGR_PLLSRC_HSE_CLK, RCC_CFGR_PLLXTPRE_HSE_CLK, RCC_CFGR_PPRE1_HCLK_DIV2, RCC_CFGR_PPRE2_HCLK_NODIV, RCC_CFGR_SW_SYSCLKSEL_HSECLK, RCC_CFGR_SW_SYSCLKSEL_HSICLK, RCC_CFGR_SW_SYSCLKSEL_PLLCLK, rcc_osc_on(), rcc_ppre1_frequency, rcc_ppre2_frequency, rcc_set_adcpre(), rcc_set_hpre(), rcc_set_pll_multiplication_factor(), rcc_set_pll_source(), rcc_set_pllxtpre(), rcc_set_ppre1(), rcc_set_ppre2(), rcc_set_sysclk_source(), and rcc_wait_for_osc_ready().
void rcc_clock_setup_in_hsi_out_24mhz (void)
RCC Set System Clock PLL at 24MHz from HSI.
Definition at line 851 of file rcc.c.
References FLASH_ACR_LATENCY_0WS, flash_set_ws(), HSI, PLL, RCC_CFGR_ADCPRE_PCLK2_DIV2, RCC_CFGR_HPRE_SYSCLK_NODIV, RCC_CFGR_PLLMUL_PLL_CLK_MUL6, RCC_CFGR_PLLSRC_HSI_CLK_DIV2, RCC_CFGR_PPRE1_HCLK_NODIV, RCC_CFGR_PPRE2_HCLK_NODIV, RCC_CFGR_SW_SYSCLKSEL_HSICLK, RCC_CFGR_SW_SYSCLKSEL_PLLCLK, rcc_osc_on(), rcc_ppre1_frequency, rcc_ppre2_frequency, rcc_set_adcpre(), rcc_set_hpre(), rcc_set_pll_multiplication_factor(), rcc_set_pll_source(), rcc_set_ppre1(), rcc_set_ppre2(), rcc_set_sysclk_source(), and rcc_wait_for_osc_ready().
void rcc_clock_setup_in_hsi_out_48mhz (void)
RCC Set System Clock PLL at 48MHz from HSI.
Definition at line 798 of file rcc.c.
References FLASH_ACR_LATENCY_1WS, flash_set_ws(), HSI, PLL, RCC_CFGR_ADCPRE_PCLK2_DIV8, RCC_CFGR_HPRE_SYSCLK_NODIV, RCC_CFGR_PLLMUL_PLL_CLK_MUL12, RCC_CFGR_PLLSRC_HSI_CLK_DIV2, RCC_CFGR_PPRE1_HCLK_DIV2, RCC_CFGR_PPRE2_HCLK_NODIV, RCC_CFGR_SW_SYSCLKSEL_HSICLK, RCC_CFGR_SW_SYSCLKSEL_PLLCLK, RCC_CFGR_USBPRE_PLL_CLK_NODIV, rcc_osc_on(), rcc_ppre1_frequency, rcc_ppre2_frequency, rcc_set_adcpre(), rcc_set_hpre(), rcc_set_pll_multiplication_factor(), rcc_set_pll_source(), rcc_set_ppre1(), rcc_set_ppre2(), rcc_set_sysclk_source(), rcc_set_usbpre(), and rcc_wait_for_osc_ready().
void rcc_clock_setup_in_hsi_out_64mhz (void)
RCC Set System Clock PLL at 64MHz from HSI.
Definition at line 746 of file rcc.c.
References FLASH_ACR_LATENCY_2WS, flash_set_ws(), HSI, PLL, RCC_CFGR_ADCPRE_PCLK2_DIV8, RCC_CFGR_HPRE_SYSCLK_NODIV, RCC_CFGR_PLLMUL_PLL_CLK_MUL16, RCC_CFGR_PLLSRC_HSI_CLK_DIV2, RCC_CFGR_PPRE1_HCLK_DIV2, RCC_CFGR_PPRE2_HCLK_NODIV, RCC_CFGR_SW_SYSCLKSEL_HSICLK, RCC_CFGR_SW_SYSCLKSEL_PLLCLK, rcc_osc_on(), rcc_ppre1_frequency, rcc_ppre2_frequency, rcc_set_adcpre(), rcc_set_hpre(), rcc_set_pll_multiplication_factor(), rcc_set_pll_source(), rcc_set_ppre1(), rcc_set_ppre2(), rcc_set_sysclk_source(), and rcc_wait_for_osc_ready().
void rcc_css_disable (void)
RCC Disable the Clock Security System.
Definition at line 351 of file rcc.c.
References RCC_CR, and RCC_CR_CSSON.
void rcc_css_enable (void)
RCC Enable the Clock Security System.
Definition at line 341 of file rcc.c.
References RCC_CR, and RCC_CR_CSSON.
void rcc_css_int_clear (void)
RCC Clear the Clock Security System Interrupt Flag.
Definition at line 204 of file rcc.c.
References RCC_CIR, and RCC_CIR_CSSC.
int rcc_css_int_flag (void)
RCC Read the Clock Security System Interrupt Flag.
Returns
int. Boolean value for flag set.
Definition at line 215 of file rcc.c.
References RCC_CIR, and RCC_CIR_CSSF.
void rcc_osc_bypass_disable (osc_t osc)
RCC Disable Bypass.
Re-enable the internal clock (high speed and low speed clocks only). The internal clock must be disabled (see rcc_osc_off) for this to have effect.
Note
The LSE clock is in the backup domain and cannot have bypass removed until the backup domain write protection has been removed (see pwr_disable_backup_domain_write_protect) or the backup domain has been reset (see rcc_backupdomain_reset).
Parameters
[in] osc enum osc_t. Oscillator ID. Only HSE and LSE have effect.
Definition at line 403 of file rcc.c.
References HSE, HSI, LSE, LSI, PLL, PLL2, PLL3, RCC_BDCR, RCC_BDCR_LSEBYP, RCC_CR, and RCC_CR_HSEBYP.
void rcc_osc_bypass_enable (osc_t osc)
RCC Enable Bypass.
Enable an external clock to bypass the internal clock (high speed and low speed clocks only). The external clock must be enabled (see rcc_osc_on) and the internal clock must be disabled (see rcc_osc_off) for this to have effect.
Note
The LSE clock is in the backup domain and cannot be bypassed until the backup domain write protection has been removed (see pwr_disable_backup_domain_write_protect).
Parameters
[in] osc enum osc_t. Oscillator ID. Only HSE and LSE have effect.
Definition at line 370 of file rcc.c.
References HSE, HSI, LSE, LSI, PLL, PLL2, PLL3, RCC_BDCR, RCC_BDCR_LSEBYP, RCC_CR, and RCC_CR_HSEBYP.
void rcc_osc_off (osc_t osc)
RCC Turn off an Oscillator.
Disable an oscillator and power off.
Note
An oscillator cannot be turned off if it is selected as the system clock.
The LSE clock is in the backup domain and cannot be disabled until the backup domain write protection has been removed (see pwr_disable_backup_domain_write_protect) or the backup domain has been (see reset rcc_backupdomain_reset).
Parameters
[in] osc enum osc_t. Oscillator ID
Definition at line 309 of file rcc.c.
References HSE, HSI, LSE, LSI, PLL, PLL2, PLL3, RCC_BDCR, RCC_BDCR_LSEON, RCC_CR, RCC_CR_HSEON, RCC_CR_HSION, RCC_CR_PLL2ON, RCC_CR_PLL3ON, RCC_CR_PLLON, RCC_CSR, and RCC_CSR_LSION.
void rcc_osc_on (osc_t osc)
RCC Turn on an Oscillator.
Enable an oscillator and power on. Each oscillator requires an amount of time to settle to a usable state. Refer to datasheets for time delay information. A status flag is available to indicate when the oscillator becomes ready (see rcc_osc_ready_int_flag and rcc_wait_for_osc_ready).
Note
The LSE clock is in the backup domain and cannot be enabled until the backup domain write protection has been removed (see pwr_disable_backup_domain_write_protect).
Parameters
[in] osc enum osc_t. Oscillator ID
Definition at line 268 of file rcc.c.
References HSE, HSI, LSE, LSI, PLL, PLL2, PLL3, RCC_BDCR, RCC_BDCR_LSEON, RCC_CR, RCC_CR_HSEON, RCC_CR_HSION, RCC_CR_PLL2ON, RCC_CR_PLL3ON, RCC_CR_PLLON, RCC_CSR, and RCC_CSR_LSION.
Referenced by rcc_clock_setup_in_hse_12mhz_out_72mhz(), rcc_clock_setup_in_hse_16mhz_out_72mhz(), rcc_clock_setup_in_hse_25mhz_out_72mhz(), rcc_clock_setup_in_hse_8mhz_out_24mhz(), rcc_clock_setup_in_hse_8mhz_out_72mhz(), rcc_clock_setup_in_hsi_out_24mhz(), rcc_clock_setup_in_hsi_out_48mhz(), and rcc_clock_setup_in_hsi_out_64mhz().
void rcc_osc_ready_int_clear (osc_t osc)
RCC Clear the Oscillator Ready Interrupt Flag.
Clear the interrupt flag that was set when a clock oscillator became ready to use.
Parameters
[in] osc enum osc_t. Oscillator ID
Definition at line 70 of file rcc.c.
References HSE, HSI, LSE, LSI, PLL, PLL2, PLL3, RCC_CIR, RCC_CIR_HSERDYC, RCC_CIR_HSIRDYC, RCC_CIR_LSERDYC, RCC_CIR_LSIRDYC, RCC_CIR_PLL2RDYC, RCC_CIR_PLL3RDYC, and RCC_CIR_PLLRDYC.
void rcc_osc_ready_int_disable (osc_t osc)
RCC Disable the Oscillator Ready Interrupt.
Parameters
[in] osc enum osc_t. Oscillator ID
Definition at line 136 of file rcc.c.
References HSE, HSI, LSE, LSI, PLL, PLL2, PLL3, RCC_CIR, RCC_CIR_HSERDYIE, RCC_CIR_HSIRDYIE, RCC_CIR_LSERDYIE, RCC_CIR_LSIRDYIE, RCC_CIR_PLL2RDYIE, RCC_CIR_PLL3RDYIE, and RCC_CIR_PLLRDYIE.
void rcc_osc_ready_int_enable (osc_t osc)
RCC Enable the Oscillator Ready Interrupt.
Parameters
[in] osc enum osc_t. Oscillator ID
Definition at line 103 of file rcc.c.
References HSE, HSI, LSE, LSI, PLL, PLL2, PLL3, RCC_CIR, RCC_CIR_HSERDYIE, RCC_CIR_HSIRDYIE, RCC_CIR_LSERDYIE, RCC_CIR_LSIRDYIE, RCC_CIR_PLL2RDYIE, RCC_CIR_PLL3RDYIE, and RCC_CIR_PLLRDYIE.
int rcc_osc_ready_int_flag (osc_t osc)
RCC Read the Oscillator Ready Interrupt Flag.
Parameters
[in] osc enum osc_t. Oscillator ID
Returns
int. Boolean value for flag set.
Definition at line 170 of file rcc.c.
References cm3_assert_not_reached, HSE, HSI, LSE, LSI, PLL, PLL2, PLL3, RCC_CIR, RCC_CIR_HSERDYF, RCC_CIR_HSIRDYF, RCC_CIR_LSERDYF, RCC_CIR_LSIRDYF, RCC_CIR_PLL2RDYF, RCC_CIR_PLL3RDYF, and RCC_CIR_PLLRDYF.
void rcc_peripheral_clear_reset (volatile uint32_t * reg, uint32_t clear_reset)
RCC Remove Reset on Peripherals.
Remove the reset on particular peripherals. There are three registers involved, each one controlling reset of peripherals associated with the AHB, APB1 and APB2 respectively. Several peripherals could have the reset removed simultaneously only if they are controlled by the same register.
Parameters
[in] *reg Unsigned int32. Pointer to a Reset Register (either RCC_AHBENR, RCC_APB1ENR or RCC_APB2ENR)
[in] clear_reset Unsigned int32. Logical OR of all resets to be removed:
If register is RCC_AHBRSTR, from RCC_AHBRSTR reset values
If register is RCC_APB1RSTR, from RCC_APB1RSTR reset values
If register is RCC_APB2RSTR, from RCC_APB2RSTR reset values
Definition at line 502 of file rcc.c.
Referenced by i2c_reset(), spi_reset(), and timer_reset().
void rcc_peripheral_disable_clock (volatile uint32_t * reg, uint32_t en)
RCC Disable Peripheral Clocks.
Enable the clock on particular peripherals. There are three registers involved, each one controlling the enabling of clocks associated with the AHB, APB1 and APB2 respectively. Several peripherals could be disabled simultaneously only if they are controlled by the same register.
Parameters
[in] *reg Unsigned int32. Pointer to a Clock Enable Register (either RCC_AHBENR, RCC_APB1ENR or RCC_APB2ENR)
[in] en Unsigned int32. Logical OR of all enables to be used for disabling.
If register is RCC_AHBER, from RCC_AHBENR enable values
If register is RCC_APB1ENR, from RCC_APB1ENR enable values
If register is RCC_APB2ENR, from RCC_APB2ENR enable values
Definition at line 460 of file rcc.c.
void rcc_peripheral_enable_clock (volatile uint32_t * reg, uint32_t en)
RCC Enable Peripheral Clocks.
Enable the clock on particular peripherals. There are three registers involved, each one controlling the enabling of clocks associated with the AHB, APB1 and APB2 respectively. Several peripherals could be enabled simultaneously only if they are controlled by the same register.
Parameters
[in] *reg Unsigned int32. Pointer to a Clock Enable Register (either RCC_AHBENR, RCC_APB1ENR or RCC_APB2ENR)
[in] en Unsigned int32. Logical OR of all enables to be set
If register is RCC_AHBER, from RCC_AHBENR enable values
If register is RCC_APB1ENR, from RCC_APB1ENR enable values
If register is RCC_APB2ENR, from RCC_APB2ENR enable values
Definition at line 438 of file rcc.c.
void rcc_peripheral_reset (volatile uint32_t * reg, uint32_t reset)
RCC Reset Peripherals.
Reset particular peripherals. There are three registers involved, each one controlling reset of peripherals associated with the AHB, APB1 and APB2 respectively. Several peripherals could be reset simultaneously only if they are controlled by the same register.
Parameters
[in] *reg Unsigned int32. Pointer to a Reset Register (either RCC_AHBENR, RCC_APB1ENR or RCC_APB2ENR)
[in] reset Unsigned int32. Logical OR of all resets.
If register is RCC_AHBRSTR, from RCC_AHBRSTR reset values
If register is RCC_APB1RSTR, from RCC_APB1RSTR reset values
If register is RCC_APB2RSTR, from RCC_APB2RSTR reset values
Definition at line 481 of file rcc.c.
Referenced by i2c_reset(), spi_reset(), and timer_reset().
void rcc_set_adcpre (uint32_t adcpre)
ADC Setup the A/D Clock.
The ADC's have a common clock prescale setting.
Parameters
[in] adcpre uint32_t. Prescale divider taken from RCC ADC clock prescaler enable values
Definition at line 615 of file rcc.c.
References RCC_CFGR.
Referenced by rcc_clock_setup_in_hse_12mhz_out_72mhz(), rcc_clock_setup_in_hse_16mhz_out_72mhz(), rcc_clock_setup_in_hse_25mhz_out_72mhz(), rcc_clock_setup_in_hse_8mhz_out_24mhz(), rcc_clock_setup_in_hse_8mhz_out_72mhz(), rcc_clock_setup_in_hsi_out_24mhz(), rcc_clock_setup_in_hsi_out_48mhz(), and rcc_clock_setup_in_hsi_out_64mhz().
void rcc_set_hpre (uint32_t hpre)
RCC Set the AHB Prescale Factor.
Parameters
[in] hpre Unsigned int32. AHB prescale factor RCC_CFGR AHB prescale Factors
Definition at line 662 of file rcc.c.
References RCC_CFGR.
Referenced by rcc_clock_setup_in_hse_12mhz_out_72mhz(), rcc_clock_setup_in_hse_16mhz_out_72mhz(), rcc_clock_setup_in_hse_25mhz_out_72mhz(), rcc_clock_setup_in_hse_8mhz_out_24mhz(), rcc_clock_setup_in_hse_8mhz_out_72mhz(), rcc_clock_setup_in_hsi_out_24mhz(), rcc_clock_setup_in_hsi_out_48mhz(), and rcc_clock_setup_in_hsi_out_64mhz().
void rcc_set_mco (uint32_t mcosrc)
Definition at line 713 of file rcc.c.
References RCC_CFGR.
void rcc_set_pll2_multiplication_factor (uint32_t mul)
RCC Set the PLL2 Multiplication Factor.
Note
This only has effect when the PLL is disabled.
Parameters
[in] mul Unsigned int32. PLL multiplication factor RCC_CFGR PLL Multiplication Factor
Definition at line 547 of file rcc.c.
References RCC_CFGR2.
Referenced by rcc_clock_setup_in_hse_25mhz_out_72mhz().
void rcc_set_pll3_multiplication_factor (uint32_t mul)
RCC Set the PLL3 Multiplication Factor.
Note
This only has effect when the PLL is disabled.
Parameters
[in] mul Unsigned int32. PLL multiplication factor RCC_CFGR PLL Multiplication Factor
Definition at line 564 of file rcc.c.
References RCC_CFGR2.
void rcc_set_pll_multiplication_factor (uint32_t mul)
RCC Set the PLL Multiplication Factor.
Note
This only has effect when the PLL is disabled.
Parameters
[in] mul Unsigned int32. PLL multiplication factor RCC_CFGR PLL Multiplication Factor
Definition at line 530 of file rcc.c.
References RCC_CFGR.
Referenced by rcc_clock_setup_in_hse_12mhz_out_72mhz(), rcc_clock_setup_in_hse_16mhz_out_72mhz(), rcc_clock_setup_in_hse_25mhz_out_72mhz(), rcc_clock_setup_in_hse_8mhz_out_24mhz(), rcc_clock_setup_in_hse_8mhz_out_72mhz(), rcc_clock_setup_in_hsi_out_24mhz(), rcc_clock_setup_in_hsi_out_48mhz(), and rcc_clock_setup_in_hsi_out_64mhz().
void rcc_set_pll_source (uint32_t pllsrc)
RCC Set the PLL Clock Source.
Note
This only has effect when the PLL is disabled.
Parameters
[in] pllsrc Unsigned int32. PLL clock source RCC_CFGR PLL Clock Source
Definition at line 581 of file rcc.c.
References RCC_CFGR.
Referenced by rcc_clock_setup_in_hse_12mhz_out_72mhz(), rcc_clock_setup_in_hse_16mhz_out_72mhz(), rcc_clock_setup_in_hse_25mhz_out_72mhz(), rcc_clock_setup_in_hse_8mhz_out_24mhz(), rcc_clock_setup_in_hse_8mhz_out_72mhz(), rcc_clock_setup_in_hsi_out_24mhz(), rcc_clock_setup_in_hsi_out_48mhz(), and rcc_clock_setup_in_hsi_out_64mhz().
void rcc_set_pllxtpre (uint32_t pllxtpre)
RCC Set the HSE Frequency Divider used as PLL Clock Source.
Note
This only has effect when the PLL is disabled.
Parameters
[in] pllxtpre Unsigned int32. HSE division factor RCC_CFGR HSE Divider for PLL
Definition at line 598 of file rcc.c.
References RCC_CFGR.
Referenced by rcc_clock_setup_in_hse_12mhz_out_72mhz(), rcc_clock_setup_in_hse_16mhz_out_72mhz(), rcc_clock_setup_in_hse_25mhz_out_72mhz(), rcc_clock_setup_in_hse_8mhz_out_24mhz(), and rcc_clock_setup_in_hse_8mhz_out_72mhz().
void rcc_set_ppre1 (uint32_t ppre1)
RCC Set the APB1 Prescale Factor.
Note
The APB1 clock frequency must not exceed 36MHz.
Parameters
[in] ppre1 Unsigned int32. APB1 prescale factor RCC_CFGR APB1 prescale Factors
Definition at line 647 of file rcc.c.
References RCC_CFGR.
Referenced by rcc_clock_setup_in_hse_12mhz_out_72mhz(), rcc_clock_setup_in_hse_16mhz_out_72mhz(), rcc_clock_setup_in_hse_25mhz_out_72mhz(), rcc_clock_setup_in_hse_8mhz_out_24mhz(), rcc_clock_setup_in_hse_8mhz_out_72mhz(), rcc_clock_setup_in_hsi_out_24mhz(), rcc_clock_setup_in_hsi_out_48mhz(), and rcc_clock_setup_in_hsi_out_64mhz().
void rcc_set_ppre2 (uint32_t ppre2)
RCC Set the APB2 Prescale Factor.
Parameters
[in] ppre2 Unsigned int32. APB2 prescale factor RCC_CFGR APB2 prescale Factors
Definition at line 630 of file rcc.c.
References RCC_CFGR.
Referenced by rcc_clock_setup_in_hse_12mhz_out_72mhz(), rcc_clock_setup_in_hse_16mhz_out_72mhz(), rcc_clock_setup_in_hse_25mhz_out_72mhz(), rcc_clock_setup_in_hse_8mhz_out_24mhz(), rcc_clock_setup_in_hse_8mhz_out_72mhz(), rcc_clock_setup_in_hsi_out_24mhz(), rcc_clock_setup_in_hsi_out_48mhz(), and rcc_clock_setup_in_hsi_out_64mhz().
void rcc_set_prediv1 (uint32_t prediv)
Definition at line 691 of file rcc.c.
References RCC_CFGR2.
Referenced by rcc_clock_setup_in_hse_25mhz_out_72mhz().
void rcc_set_prediv1_source (uint32_t rccsrc)
Definition at line 707 of file rcc.c.
References RCC_CFGR2.
Referenced by rcc_clock_setup_in_hse_25mhz_out_72mhz().
void rcc_set_prediv2 (uint32_t prediv)
Definition at line 699 of file rcc.c.
References RCC_CFGR2.
Referenced by rcc_clock_setup_in_hse_25mhz_out_72mhz().
void rcc_set_sysclk_source (uint32_t clk)
RCC Set the Source for the System Clock.
Parameters
[in] clk Unsigned int32. System Clock Selection RCC_CFGR System Clock Selection
Definition at line 513 of file rcc.c.
References RCC_CFGR.
Referenced by rcc_clock_setup_in_hse_12mhz_out_72mhz(), rcc_clock_setup_in_hse_16mhz_out_72mhz(), rcc_clock_setup_in_hse_25mhz_out_72mhz(), rcc_clock_setup_in_hse_8mhz_out_24mhz(), rcc_clock_setup_in_hse_8mhz_out_72mhz(), rcc_clock_setup_in_hsi_out_24mhz(), rcc_clock_setup_in_hsi_out_48mhz(), and rcc_clock_setup_in_hsi_out_64mhz().
void rcc_set_usbpre (uint32_t usbpre)
RCC Set the USB Prescale Factor.
The prescale factor can be set to 1 (no prescale) for use when the PLL clock is 48MHz, or 1.5 to generate the 48MHz USB clock from a 64MHz PLL clock.
Note
This bit cannot be reset while the USB clock is enabled.
Parameters
[in] usbpre Unsigned int32. USB prescale factor RCC_CFGR USB prescale Factors
Definition at line 682 of file rcc.c.
References RCC_CFGR.
Referenced by rcc_clock_setup_in_hse_25mhz_out_72mhz(), and rcc_clock_setup_in_hsi_out_48mhz().
uint32_t rcc_system_clock_source (void)
RCC Get the System Clock Source.
Returns
Unsigned int32. System clock source:
00 indicates HSE
01 indicates LSE
02 indicates PLL
Definition at line 730 of file rcc.c.
References RCC_CFGR.
void rcc_wait_for_osc_ready (osc_t osc)
RCC Wait for Oscillator Ready.
Parameters
[in] osc enum osc_t. Oscillator ID
Definition at line 226 of file rcc.c.
References HSE, HSI, LSE, LSI, PLL, PLL2, PLL3, RCC_BDCR, RCC_BDCR_LSERDY, RCC_CR, RCC_CR_HSERDY, RCC_CR_HSIRDY, RCC_CR_PLL2RDY, RCC_CR_PLL3RDY, RCC_CR_PLLRDY, RCC_CSR, and RCC_CSR_LSIRDY.
Referenced by rcc_clock_setup_in_hse_12mhz_out_72mhz(), rcc_clock_setup_in_hse_16mhz_out_72mhz(), rcc_clock_setup_in_hse_25mhz_out_72mhz(), rcc_clock_setup_in_hse_8mhz_out_24mhz(), rcc_clock_setup_in_hse_8mhz_out_72mhz(), rcc_clock_setup_in_hsi_out_24mhz(), rcc_clock_setup_in_hsi_out_48mhz(), and rcc_clock_setup_in_hsi_out_64mhz().
Variable Documentation
uint32_t rcc_ppre1_frequency = 8000000
Default ppre1 peripheral clock frequency after reset.
Definition at line 57 of file rcc.c.
Referenced by rcc_clock_setup_in_hse_12mhz_out_72mhz(), rcc_clock_setup_in_hse_16mhz_out_72mhz(), rcc_clock_setup_in_hse_25mhz_out_72mhz(), rcc_clock_setup_in_hse_8mhz_out_24mhz(), rcc_clock_setup_in_hse_8mhz_out_72mhz(), rcc_clock_setup_in_hsi_out_24mhz(), rcc_clock_setup_in_hsi_out_48mhz(), rcc_clock_setup_in_hsi_out_64mhz(), and usart_set_baudrate().
uint32_t rcc_ppre2_frequency = 8000000
Default ppre2 peripheral clock frequency after reset.
Definition at line 59 of file rcc.c.
Referenced by rcc_clock_setup_in_hse_12mhz_out_72mhz(), rcc_clock_setup_in_hse_16mhz_out_72mhz(), rcc_clock_setup_in_hse_25mhz_out_72mhz(), rcc_clock_setup_in_hse_8mhz_out_24mhz(), rcc_clock_setup_in_hse_8mhz_out_72mhz(), rcc_clock_setup_in_hsi_out_24mhz(), rcc_clock_setup_in_hsi_out_48mhz(), rcc_clock_setup_in_hsi_out_64mhz(), and usart_set_baudrate().