libopencm3: RCC Defines
RCC Defines
STM32F1xx Defines
libopencm3 STM32F1xx Reset and Clock Control
Modules
RCC_CFGR Microcontroller Clock Output Source
RCC_CFGR USB prescale Factors
RCC_CFGR PLL Multiplication Factor
RCC_CFGR HSE Divider for PLL
RCC_CFGR PLL Clock Source
RCC ADC Clock Prescaler enable values
RCC_CFGR APB2 Prescale Factors
RCC_CFGR APB1 Prescale Factors
RCC_CFGR AHB Prescale Factors
RCC_CFGR System Clock Selection
RCC_APB2RSTR reset values
RCC_APB1RSTR reset values
RCC_AHBENR enable values
RCC_APB2ENR enable values
RCC_APB1ENR enable values
RCC_AHBRSTR reset values
Macros
#define RCC_CR MMIO32(RCC_BASE + 0x00)
#define RCC_CFGR MMIO32(RCC_BASE + 0x04)
#define RCC_CIR MMIO32(RCC_BASE + 0x08)
#define RCC_APB2RSTR MMIO32(RCC_BASE + 0x0c)
#define RCC_APB1RSTR MMIO32(RCC_BASE + 0x10)
#define RCC_AHBENR MMIO32(RCC_BASE + 0x14)
#define RCC_APB2ENR MMIO32(RCC_BASE + 0x18)
#define RCC_APB1ENR MMIO32(RCC_BASE + 0x1c)
#define RCC_BDCR MMIO32(RCC_BASE + 0x20)
#define RCC_CSR MMIO32(RCC_BASE + 0x24)
#define RCC_AHBRSTR MMIO32(RCC_BASE + 0x28) /* (**) */
#define RCC_CFGR2 MMIO32(RCC_BASE + 0x2c) /* (**) */
#define RCC_CR_PLL3RDY (1 << 29) /* (**) */
#define RCC_CR_PLL3ON (1 << 28) /* (**) */
#define RCC_CR_PLL2RDY (1 << 27) /* (**) */
#define RCC_CR_PLL2ON (1 << 26) /* (**) */
#define RCC_CR_PLLRDY (1 << 25)
#define RCC_CR_PLLON (1 << 24)
#define RCC_CR_CSSON (1 << 19)
#define RCC_CR_HSEBYP (1 << 18)
#define RCC_CR_HSERDY (1 << 17)
#define RCC_CR_HSEON (1 << 16)
#define RCC_CR_HSIRDY (1 << 1)
#define RCC_CR_HSION (1 << 0)
#define RCC_CFGR_USBPRE_PLL_VCO_CLK_DIV3 0x0
#define RCC_CFGR_USBPRE_PLL_VCO_CLK_DIV2 0x1
#define RCC_CFGR_SWS_SYSCLKSEL_HSICLK 0x0
#define RCC_CFGR_SWS_SYSCLKSEL_HSECLK 0x1
#define RCC_CFGR_SWS_SYSCLKSEL_PLLCLK 0x2
#define RCC_CIR_CSSC (1 << 23)
#define RCC_CIR_PLL3RDYC (1 << 22) /* (**) */
#define RCC_CIR_PLL2RDYC (1 << 21) /* (**) */
#define RCC_CIR_PLLRDYC (1 << 20)
#define RCC_CIR_HSERDYC (1 << 19)
#define RCC_CIR_HSIRDYC (1 << 18)
#define RCC_CIR_LSERDYC (1 << 17)
#define RCC_CIR_LSIRDYC (1 << 16)
#define RCC_CIR_PLL3RDYIE (1 << 14) /* (**) */
#define RCC_CIR_PLL2RDYIE (1 << 13) /* (**) */
#define RCC_CIR_PLLRDYIE (1 << 12)
#define RCC_CIR_HSERDYIE (1 << 11)
#define RCC_CIR_HSIRDYIE (1 << 10)
#define RCC_CIR_LSERDYIE (1 << 9)
#define RCC_CIR_LSIRDYIE (1 << 8)
#define RCC_CIR_CSSF (1 << 7)
#define RCC_CIR_PLL3RDYF (1 << 6) /* (**) */
#define RCC_CIR_PLL2RDYF (1 << 5) /* (**) */
#define RCC_CIR_PLLRDYF (1 << 4)
#define RCC_CIR_HSERDYF (1 << 3)
#define RCC_CIR_HSIRDYF (1 << 2)
#define RCC_CIR_LSERDYF (1 << 1)
#define RCC_CIR_LSIRDYF (1 << 0)
#define RCC_BDCR_BDRST (1 << 16)
#define RCC_BDCR_RTCEN (1 << 15)
#define RCC_BDCR_LSEBYP (1 << 2)
#define RCC_BDCR_LSERDY (1 << 1)
#define RCC_BDCR_LSEON (1 << 0)
#define RCC_CSR_LPWRRSTF (1 << 31)
#define RCC_CSR_WWDGRSTF (1 << 30)
#define RCC_CSR_IWDGRSTF (1 << 29)
#define RCC_CSR_SFTRSTF (1 << 28)
#define RCC_CSR_PORRSTF (1 << 27)
#define RCC_CSR_PINRSTF (1 << 26)
#define RCC_CSR_RMVF (1 << 24)
#define RCC_CSR_LSIRDY (1 << 1)
#define RCC_CSR_LSION (1 << 0)
#define RCC_CFGR2_I2S3SRC_SYSCLK 0x0
#define RCC_CFGR2_I2S3SRC_PLL3_VCO_CLK 0x1
#define RCC_CFGR2_I2S2SRC_SYSCLK 0x0
#define RCC_CFGR2_I2S2SRC_PLL3_VCO_CLK 0x1
#define RCC_CFGR2_PREDIV1SRC_HSE_CLK 0x0
#define RCC_CFGR2_PREDIV1SRC_PLL2_CLK 0x1
#define RCC_CFGR2_PLL2MUL (1 << 0)
#define RCC_CFGR2_PREDIV2 (1 << 0)
#define RCC_CFGR2_PREDIV1 (1 << 0)
#define RCC_CFGR2_PLL3MUL_PLL3_CLK_MUL8 0x6
#define RCC_CFGR2_PLL3MUL_PLL3_CLK_MUL9 0x7
#define RCC_CFGR2_PLL3MUL_PLL3_CLK_MUL10 0x8
#define RCC_CFGR2_PLL3MUL_PLL3_CLK_MUL11 0x9
#define RCC_CFGR2_PLL3MUL_PLL3_CLK_MUL12 0xa
#define RCC_CFGR2_PLL3MUL_PLL3_CLK_MUL13 0xb
#define RCC_CFGR2_PLL3MUL_PLL3_CLK_MUL14 0xc
#define RCC_CFGR2_PLL3MUL_PLL3_CLK_MUL16 0xe
#define RCC_CFGR2_PLL3MUL_PLL3_CLK_MUL20 0xf
#define RCC_CFGR2_PLL2MUL_PLL2_CLK_MUL8 0x6
#define RCC_CFGR2_PLL2MUL_PLL2_CLK_MUL9 0x7
#define RCC_CFGR2_PLL2MUL_PLL2_CLK_MUL10 0x8
#define RCC_CFGR2_PLL2MUL_PLL2_CLK_MUL11 0x9
#define RCC_CFGR2_PLL2MUL_PLL2_CLK_MUL12 0xa
#define RCC_CFGR2_PLL2MUL_PLL2_CLK_MUL13 0xb
#define RCC_CFGR2_PLL2MUL_PLL2_CLK_MUL14 0xc
#define RCC_CFGR2_PLL2MUL_PLL2_CLK_MUL16 0xe
#define RCC_CFGR2_PLL2MUL_PLL2_CLK_MUL20 0xf
#define RCC_CFGR2_PREDIV_NODIV 0x0
#define RCC_CFGR2_PREDIV_DIV2 0x1
#define RCC_CFGR2_PREDIV_DIV3 0x2
#define RCC_CFGR2_PREDIV_DIV4 0x3
#define RCC_CFGR2_PREDIV_DIV5 0x4
#define RCC_CFGR2_PREDIV_DIV6 0x5
#define RCC_CFGR2_PREDIV_DIV7 0x6
#define RCC_CFGR2_PREDIV_DIV8 0x7
#define RCC_CFGR2_PREDIV_DIV9 0x8
#define RCC_CFGR2_PREDIV_DIV10 0x9
#define RCC_CFGR2_PREDIV_DIV11 0xa
#define RCC_CFGR2_PREDIV_DIV12 0xb
#define RCC_CFGR2_PREDIV_DIV13 0xc
#define RCC_CFGR2_PREDIV_DIV14 0xd
#define RCC_CFGR2_PREDIV_DIV15 0xe
#define RCC_CFGR2_PREDIV_DIV16 0xf
#define RCC_CFGR2_PREDIV2_NODIV 0x0
#define RCC_CFGR2_PREDIV2_DIV2 0x1
#define RCC_CFGR2_PREDIV2_DIV3 0x2
#define RCC_CFGR2_PREDIV2_DIV4 0x3
#define RCC_CFGR2_PREDIV2_DIV5 0x4
#define RCC_CFGR2_PREDIV2_DIV6 0x5
#define RCC_CFGR2_PREDIV2_DIV7 0x6
#define RCC_CFGR2_PREDIV2_DIV8 0x7
#define RCC_CFGR2_PREDIV2_DIV9 0x8
#define RCC_CFGR2_PREDIV2_DIV10 0x9
#define RCC_CFGR2_PREDIV2_DIV11 0xa
#define RCC_CFGR2_PREDIV2_DIV12 0xb
#define RCC_CFGR2_PREDIV2_DIV13 0xc
#define RCC_CFGR2_PREDIV2_DIV14 0xd
#define RCC_CFGR2_PREDIV2_DIV15 0xe
#define RCC_CFGR2_PREDIV2_DIV16 0xf
Enumerations
enum osc_t {
PLL, PLL2, PLL3, HSE,
HSI, LSE, LSI
}
Functions
BEGIN_DECLS void rcc_osc_ready_int_clear (osc_t osc)
RCC Clear the Oscillator Ready Interrupt Flag.
void rcc_osc_ready_int_enable (osc_t osc)
RCC Enable the Oscillator Ready Interrupt.
void rcc_osc_ready_int_disable (osc_t osc)
RCC Disable the Oscillator Ready Interrupt.
int rcc_osc_ready_int_flag (osc_t osc)
RCC Read the Oscillator Ready Interrupt Flag.
void rcc_css_int_clear (void)
RCC Clear the Clock Security System Interrupt Flag.
int rcc_css_int_flag (void)
RCC Read the Clock Security System Interrupt Flag.
void rcc_wait_for_osc_ready (osc_t osc)
RCC Wait for Oscillator Ready.
void rcc_osc_on (osc_t osc)
RCC Turn on an Oscillator.
void rcc_osc_off (osc_t osc)
RCC Turn off an Oscillator.
void rcc_css_enable (void)
RCC Enable the Clock Security System.
void rcc_css_disable (void)
RCC Disable the Clock Security System.
void rcc_set_mco (u32 mcosrc)
void rcc_osc_bypass_enable (osc_t osc)
RCC Enable Bypass.
void rcc_osc_bypass_disable (osc_t osc)
RCC Disable Bypass.
void rcc_peripheral_enable_clock (volatile u32 *reg, u32 en)
RCC Enable Peripheral Clocks.
void rcc_peripheral_disable_clock (volatile u32 *reg, u32 en)
RCC Disable Peripheral Clocks.
void rcc_peripheral_reset (volatile u32 *reg, u32 reset)
RCC Reset Peripherals.
void rcc_peripheral_clear_reset (volatile u32 *reg, u32 clear_reset)
RCC Remove Reset on Peripherals.
void rcc_set_sysclk_source (u32 clk)
RCC Set the Source for the System Clock.
void rcc_set_pll_multiplication_factor (u32 mul)
RCC Set the PLL Multiplication Factor.
void rcc_set_pll2_multiplication_factor (u32 mul)
RCC Set the PLL2 Multiplication Factor.
void rcc_set_pll3_multiplication_factor (u32 mul)
RCC Set the PLL3 Multiplication Factor.
void rcc_set_pll_source (u32 pllsrc)
RCC Set the PLL Clock Source.
void rcc_set_pllxtpre (u32 pllxtpre)
RCC Set the HSE Frequency Divider used as PLL Clock Source.
void rcc_set_adcpre (u32 adcpre)
ADC Setup the A/D Clock.
void rcc_set_ppre2 (u32 ppre2)
RCC Set the APB2 Prescale Factor.
void rcc_set_ppre1 (u32 ppre1)
RCC Set the APB1 Prescale Factor.
void rcc_set_hpre (u32 hpre)
RCC Set the AHB Prescale Factor.
void rcc_set_usbpre (u32 usbpre)
RCC Set the USB Prescale Factor.
void rcc_set_prediv1 (u32 prediv)
void rcc_set_prediv2 (u32 prediv)
void rcc_set_prediv1_source (u32 rccsrc)
u32 rcc_system_clock_source (void)
RCC Get the System Clock Source.
void rcc_clock_setup_in_hsi_out_64mhz (void)
RCC Set System Clock PLL at 64MHz from HSI.
void rcc_clock_setup_in_hsi_out_48mhz (void)
RCC Set System Clock PLL at 48MHz from HSI.
void rcc_clock_setup_in_hsi_out_24mhz (void)
RCC Set System Clock PLL at 24MHz from HSI.
void rcc_clock_setup_in_hse_8mhz_out_24mhz (void)
RCC Set System Clock PLL at 24MHz from HSE at 8MHz.
void rcc_clock_setup_in_hse_8mhz_out_72mhz (void)
RCC Set System Clock PLL at 72MHz from HSE at 8MHz.
void rcc_clock_setup_in_hse_12mhz_out_72mhz (void)
RCC Set System Clock PLL at 24MHz from HSE at 12MHz.
void rcc_clock_setup_in_hse_16mhz_out_72mhz (void)
RCC Set System Clock PLL at 24MHz from HSE at 16MHz.
void rcc_clock_setup_in_hse_25mhz_out_72mhz (void)
RCC Set System Clock PLL at 72MHz from HSE at 25MHz.
void rcc_backupdomain_reset (void)
RCC Reset the backup domain.
Variables
u32 rcc_ppre1_frequency
Default ppre1 peripheral clock frequency after reset.
u32 rcc_ppre2_frequency
Default ppre2 peripheral clock frequency after reset.
Detailed Description
libopencm3 STM32F1xx Reset and Clock Control
Version
1.0.0
Author
© 2009 Federico Ruiz-Ugalde <memeruiz at gmail dot com>
© 2009 Uwe Hermann uwe@h.nosp@m.erma.nosp@m.nn-uw.nosp@m.e.de
Date
18 August 2012
LGPL License Terms libopencm3 License
Macro Definition Documentation
#define RCC_AHBENR MMIO32(RCC_BASE + 0x14)
Definition at line 53 of file rcc.h.
#define RCC_AHBRSTR MMIO32(RCC_BASE + 0x28) /* (**) */
Definition at line 58 of file rcc.h.
#define RCC_APB1ENR MMIO32(RCC_BASE + 0x1c)
Definition at line 55 of file rcc.h.
Referenced by rtc_auto_awake(), rtc_awake_from_off(), and rtc_awake_from_standby().
#define RCC_APB1RSTR MMIO32(RCC_BASE + 0x10)
Definition at line 52 of file rcc.h.
Referenced by i2c_reset(), and spi_reset().
#define RCC_APB2ENR MMIO32(RCC_BASE + 0x18)
Definition at line 54 of file rcc.h.
#define RCC_APB2RSTR MMIO32(RCC_BASE + 0x0c)
Definition at line 51 of file rcc.h.
Referenced by spi_reset().
#define RCC_BDCR MMIO32(RCC_BASE + 0x20)
Definition at line 56 of file rcc.h.
Referenced by rcc_backupdomain_reset(), rcc_osc_bypass_disable(), rcc_osc_bypass_enable(), rcc_osc_off(), rcc_osc_on(), rcc_wait_for_osc_ready(), rtc_auto_awake(), and rtc_awake_from_off().
#define RCC_BDCR_BDRST (1 << 16)
Definition at line 382 of file rcc.h.
Referenced by rcc_backupdomain_reset().
#define RCC_BDCR_LSEBYP (1 << 2)
Definition at line 385 of file rcc.h.
Referenced by rcc_osc_bypass_disable(), and rcc_osc_bypass_enable().
#define RCC_BDCR_LSEON (1 << 0)
Definition at line 387 of file rcc.h.
Referenced by rcc_osc_off(), rcc_osc_on(), and rtc_awake_from_off().
#define RCC_BDCR_LSERDY (1 << 1)
Definition at line 386 of file rcc.h.
Referenced by rcc_wait_for_osc_ready(), and rtc_awake_from_off().
#define RCC_BDCR_RTCEN (1 << 15)
Definition at line 383 of file rcc.h.
Referenced by rtc_auto_awake(), and rtc_awake_from_off().
#define RCC_CFGR MMIO32(RCC_BASE + 0x04)
Definition at line 49 of file rcc.h.
Referenced by rcc_set_adcpre(), rcc_set_hpre(), rcc_set_mco(), rcc_set_pll_multiplication_factor(), rcc_set_pll_source(), rcc_set_pllxtpre(), rcc_set_ppre1(), rcc_set_ppre2(), rcc_set_sysclk_source(), rcc_set_usbpre(), and rcc_system_clock_source().
#define RCC_CFGR2 MMIO32(RCC_BASE + 0x2c) /* (**) */
Definition at line 59 of file rcc.h.
Referenced by rcc_set_pll2_multiplication_factor(), rcc_set_pll3_multiplication_factor(), rcc_set_prediv1(), rcc_set_prediv1_source(), and rcc_set_prediv2().
#define RCC_CFGR2_I2S2SRC_PLL3_VCO_CLK 0x1
Definition at line 419 of file rcc.h.
#define RCC_CFGR2_I2S2SRC_SYSCLK 0x0
Definition at line 418 of file rcc.h.
#define RCC_CFGR2_I2S3SRC_PLL3_VCO_CLK 0x1
Definition at line 415 of file rcc.h.
#define RCC_CFGR2_I2S3SRC_SYSCLK 0x0
Definition at line 414 of file rcc.h.
#define RCC_CFGR2_PLL2MUL (1 << 0)
Definition at line 425 of file rcc.h.
#define RCC_CFGR2_PLL2MUL_PLL2_CLK_MUL10 0x8
Definition at line 443 of file rcc.h.
#define RCC_CFGR2_PLL2MUL_PLL2_CLK_MUL11 0x9
Definition at line 444 of file rcc.h.
#define RCC_CFGR2_PLL2MUL_PLL2_CLK_MUL12 0xa
Definition at line 445 of file rcc.h.
#define RCC_CFGR2_PLL2MUL_PLL2_CLK_MUL13 0xb
Definition at line 446 of file rcc.h.
#define RCC_CFGR2_PLL2MUL_PLL2_CLK_MUL14 0xc
Definition at line 447 of file rcc.h.
#define RCC_CFGR2_PLL2MUL_PLL2_CLK_MUL16 0xe
Definition at line 448 of file rcc.h.
#define RCC_CFGR2_PLL2MUL_PLL2_CLK_MUL20 0xf
Definition at line 449 of file rcc.h.
#define RCC_CFGR2_PLL2MUL_PLL2_CLK_MUL8 0x6
Definition at line 441 of file rcc.h.
Referenced by rcc_clock_setup_in_hse_25mhz_out_72mhz().
#define RCC_CFGR2_PLL2MUL_PLL2_CLK_MUL9 0x7
Definition at line 442 of file rcc.h.
#define RCC_CFGR2_PLL3MUL_PLL3_CLK_MUL10 0x8
Definition at line 432 of file rcc.h.
#define RCC_CFGR2_PLL3MUL_PLL3_CLK_MUL11 0x9
Definition at line 433 of file rcc.h.
#define RCC_CFGR2_PLL3MUL_PLL3_CLK_MUL12 0xa
Definition at line 434 of file rcc.h.
#define RCC_CFGR2_PLL3MUL_PLL3_CLK_MUL13 0xb
Definition at line 435 of file rcc.h.
#define RCC_CFGR2_PLL3MUL_PLL3_CLK_MUL14 0xc
Definition at line 436 of file rcc.h.
#define RCC_CFGR2_PLL3MUL_PLL3_CLK_MUL16 0xe
Definition at line 437 of file rcc.h.
#define RCC_CFGR2_PLL3MUL_PLL3_CLK_MUL20 0xf
Definition at line 438 of file rcc.h.
#define RCC_CFGR2_PLL3MUL_PLL3_CLK_MUL8 0x6
Definition at line 430 of file rcc.h.
#define RCC_CFGR2_PLL3MUL_PLL3_CLK_MUL9 0x7
Definition at line 431 of file rcc.h.
#define RCC_CFGR2_PREDIV1 (1 << 0)
Definition at line 427 of file rcc.h.
#define RCC_CFGR2_PREDIV1SRC_HSE_CLK 0x0
Definition at line 422 of file rcc.h.
#define RCC_CFGR2_PREDIV1SRC_PLL2_CLK 0x1
Definition at line 423 of file rcc.h.
Referenced by rcc_clock_setup_in_hse_25mhz_out_72mhz().
#define RCC_CFGR2_PREDIV2 (1 << 0)
Definition at line 426 of file rcc.h.
#define RCC_CFGR2_PREDIV2_DIV10 0x9
Definition at line 479 of file rcc.h.
#define RCC_CFGR2_PREDIV2_DIV11 0xa
Definition at line 480 of file rcc.h.
#define RCC_CFGR2_PREDIV2_DIV12 0xb
Definition at line 481 of file rcc.h.
#define RCC_CFGR2_PREDIV2_DIV13 0xc
Definition at line 482 of file rcc.h.
#define RCC_CFGR2_PREDIV2_DIV14 0xd
Definition at line 483 of file rcc.h.
#define RCC_CFGR2_PREDIV2_DIV15 0xe
Definition at line 484 of file rcc.h.
#define RCC_CFGR2_PREDIV2_DIV16 0xf
Definition at line 485 of file rcc.h.
#define RCC_CFGR2_PREDIV2_DIV2 0x1
Definition at line 471 of file rcc.h.
#define RCC_CFGR2_PREDIV2_DIV3 0x2
Definition at line 472 of file rcc.h.
#define RCC_CFGR2_PREDIV2_DIV4 0x3
Definition at line 473 of file rcc.h.
#define RCC_CFGR2_PREDIV2_DIV5 0x4
Definition at line 474 of file rcc.h.
Referenced by rcc_clock_setup_in_hse_25mhz_out_72mhz().
#define RCC_CFGR2_PREDIV2_DIV6 0x5
Definition at line 475 of file rcc.h.
#define RCC_CFGR2_PREDIV2_DIV7 0x6
Definition at line 476 of file rcc.h.
#define RCC_CFGR2_PREDIV2_DIV8 0x7
Definition at line 477 of file rcc.h.
#define RCC_CFGR2_PREDIV2_DIV9 0x8
Definition at line 478 of file rcc.h.
#define RCC_CFGR2_PREDIV2_NODIV 0x0
Definition at line 470 of file rcc.h.
#define RCC_CFGR2_PREDIV_DIV10 0x9
Definition at line 461 of file rcc.h.
#define RCC_CFGR2_PREDIV_DIV11 0xa
Definition at line 462 of file rcc.h.
#define RCC_CFGR2_PREDIV_DIV12 0xb
Definition at line 463 of file rcc.h.
#define RCC_CFGR2_PREDIV_DIV13 0xc
Definition at line 464 of file rcc.h.
#define RCC_CFGR2_PREDIV_DIV14 0xd
Definition at line 465 of file rcc.h.
#define RCC_CFGR2_PREDIV_DIV15 0xe
Definition at line 466 of file rcc.h.
#define RCC_CFGR2_PREDIV_DIV16 0xf
Definition at line 467 of file rcc.h.
#define RCC_CFGR2_PREDIV_DIV2 0x1
Definition at line 453 of file rcc.h.
#define RCC_CFGR2_PREDIV_DIV3 0x2
Definition at line 454 of file rcc.h.
#define RCC_CFGR2_PREDIV_DIV4 0x3
Definition at line 455 of file rcc.h.
#define RCC_CFGR2_PREDIV_DIV5 0x4
Definition at line 456 of file rcc.h.
Referenced by rcc_clock_setup_in_hse_25mhz_out_72mhz().
#define RCC_CFGR2_PREDIV_DIV6 0x5
Definition at line 457 of file rcc.h.
#define RCC_CFGR2_PREDIV_DIV7 0x6
Definition at line 458 of file rcc.h.
#define RCC_CFGR2_PREDIV_DIV8 0x7
Definition at line 459 of file rcc.h.
#define RCC_CFGR2_PREDIV_DIV9 0x8
Definition at line 460 of file rcc.h.
#define RCC_CFGR2_PREDIV_NODIV 0x0
Definition at line 452 of file rcc.h.
#define RCC_CFGR_SWS_SYSCLKSEL_HSECLK 0x1
Definition at line 207 of file rcc.h.
#define RCC_CFGR_SWS_SYSCLKSEL_HSICLK 0x0
Definition at line 206 of file rcc.h.
#define RCC_CFGR_SWS_SYSCLKSEL_PLLCLK 0x2
Definition at line 208 of file rcc.h.
#define RCC_CFGR_USBPRE_PLL_VCO_CLK_DIV2 0x1
Definition at line 107 of file rcc.h.
#define RCC_CFGR_USBPRE_PLL_VCO_CLK_DIV3 0x0
Definition at line 106 of file rcc.h.
Referenced by rcc_clock_setup_in_hse_25mhz_out_72mhz().
#define RCC_CIR MMIO32(RCC_BASE + 0x08)
Definition at line 50 of file rcc.h.
Referenced by rcc_css_int_clear(), rcc_css_int_flag(), rcc_osc_ready_int_clear(), rcc_osc_ready_int_disable(), rcc_osc_ready_int_enable(), and rcc_osc_ready_int_flag().
#define RCC_CIR_CSSC (1 << 23)
Definition at line 223 of file rcc.h.
Referenced by rcc_css_int_clear().
#define RCC_CIR_CSSF (1 << 7)
Definition at line 244 of file rcc.h.
Referenced by rcc_css_int_flag().
#define RCC_CIR_HSERDYC (1 << 19)
Definition at line 229 of file rcc.h.
Referenced by rcc_osc_ready_int_clear().
#define RCC_CIR_HSERDYF (1 << 3)
Definition at line 250 of file rcc.h.
Referenced by rcc_osc_ready_int_flag().
#define RCC_CIR_HSERDYIE (1 << 11)
Definition at line 238 of file rcc.h.
Referenced by rcc_osc_ready_int_disable(), and rcc_osc_ready_int_enable().
#define RCC_CIR_HSIRDYC (1 << 18)
Definition at line 230 of file rcc.h.
Referenced by rcc_osc_ready_int_clear().
#define RCC_CIR_HSIRDYF (1 << 2)
Definition at line 251 of file rcc.h.
Referenced by rcc_osc_ready_int_flag().
#define RCC_CIR_HSIRDYIE (1 << 10)
Definition at line 239 of file rcc.h.
Referenced by rcc_osc_ready_int_disable(), and rcc_osc_ready_int_enable().
#define RCC_CIR_LSERDYC (1 << 17)
Definition at line 231 of file rcc.h.
Referenced by rcc_osc_ready_int_clear().
#define RCC_CIR_LSERDYF (1 << 1)
Definition at line 252 of file rcc.h.
Referenced by rcc_osc_ready_int_flag().
#define RCC_CIR_LSERDYIE (1 << 9)
Definition at line 240 of file rcc.h.
Referenced by rcc_osc_ready_int_disable(), and rcc_osc_ready_int_enable().
#define RCC_CIR_LSIRDYC (1 << 16)
Definition at line 232 of file rcc.h.
Referenced by rcc_osc_ready_int_clear().
#define RCC_CIR_LSIRDYF (1 << 0)
Definition at line 253 of file rcc.h.
Referenced by rcc_osc_ready_int_flag().
#define RCC_CIR_LSIRDYIE (1 << 8)
Definition at line 241 of file rcc.h.
Referenced by rcc_osc_ready_int_disable(), and rcc_osc_ready_int_enable().
#define RCC_CIR_PLL2RDYC (1 << 21) /* (**) */
Definition at line 227 of file rcc.h.
Referenced by rcc_osc_ready_int_clear().
#define RCC_CIR_PLL2RDYF (1 << 5) /* (**) */
Definition at line 248 of file rcc.h.
Referenced by rcc_osc_ready_int_flag().
#define RCC_CIR_PLL2RDYIE (1 << 13) /* (**) */
Definition at line 236 of file rcc.h.
Referenced by rcc_osc_ready_int_disable(), and rcc_osc_ready_int_enable().
#define RCC_CIR_PLL3RDYC (1 << 22) /* (**) */
Definition at line 226 of file rcc.h.
Referenced by rcc_osc_ready_int_clear().
#define RCC_CIR_PLL3RDYF (1 << 6) /* (**) */
Definition at line 247 of file rcc.h.
Referenced by rcc_osc_ready_int_flag().
#define RCC_CIR_PLL3RDYIE (1 << 14) /* (**) */
Definition at line 235 of file rcc.h.
Referenced by rcc_osc_ready_int_disable(), and rcc_osc_ready_int_enable().
#define RCC_CIR_PLLRDYC (1 << 20)
Definition at line 228 of file rcc.h.
Referenced by rcc_osc_ready_int_clear().
#define RCC_CIR_PLLRDYF (1 << 4)
Definition at line 249 of file rcc.h.
Referenced by rcc_osc_ready_int_flag().
#define RCC_CIR_PLLRDYIE (1 << 12)
Definition at line 237 of file rcc.h.
Referenced by rcc_osc_ready_int_disable(), and rcc_osc_ready_int_enable().
#define RCC_CR MMIO32(RCC_BASE + 0x00)
Definition at line 48 of file rcc.h.
Referenced by rcc_css_disable(), rcc_css_enable(), rcc_osc_bypass_disable(), rcc_osc_bypass_enable(), rcc_osc_off(), rcc_osc_on(), rcc_wait_for_osc_ready(), and rtc_awake_from_off().
#define RCC_CR_CSSON (1 << 19)
Definition at line 69 of file rcc.h.
Referenced by rcc_css_disable(), and rcc_css_enable().
#define RCC_CR_HSEBYP (1 << 18)
Definition at line 70 of file rcc.h.
Referenced by rcc_osc_bypass_disable(), and rcc_osc_bypass_enable().
#define RCC_CR_HSEON (1 << 16)
Definition at line 72 of file rcc.h.
Referenced by rcc_osc_off(), rcc_osc_on(), and rtc_awake_from_off().
#define RCC_CR_HSERDY (1 << 17)
Definition at line 71 of file rcc.h.
Referenced by rcc_wait_for_osc_ready(), and rtc_awake_from_off().
#define RCC_CR_HSION (1 << 0)
Definition at line 76 of file rcc.h.
Referenced by rcc_osc_off(), and rcc_osc_on().
#define RCC_CR_HSIRDY (1 << 1)
Definition at line 75 of file rcc.h.
Referenced by rcc_wait_for_osc_ready().
#define RCC_CR_PLL2ON (1 << 26) /* (**) */
Definition at line 66 of file rcc.h.
Referenced by rcc_osc_off(), and rcc_osc_on().
#define RCC_CR_PLL2RDY (1 << 27) /* (**) */
Definition at line 65 of file rcc.h.
Referenced by rcc_wait_for_osc_ready().
#define RCC_CR_PLL3ON (1 << 28) /* (**) */
Definition at line 64 of file rcc.h.
Referenced by rcc_osc_off(), and rcc_osc_on().
#define RCC_CR_PLL3RDY (1 << 29) /* (**) */
Definition at line 63 of file rcc.h.
Referenced by rcc_wait_for_osc_ready().
#define RCC_CR_PLLON (1 << 24)
Definition at line 68 of file rcc.h.
Referenced by rcc_osc_off(), and rcc_osc_on().
#define RCC_CR_PLLRDY (1 << 25)
Definition at line 67 of file rcc.h.
Referenced by rcc_wait_for_osc_ready().
#define RCC_CSR MMIO32(RCC_BASE + 0x24)
Definition at line 57 of file rcc.h.
Referenced by rcc_osc_off(), rcc_osc_on(), rcc_wait_for_osc_ready(), and rtc_awake_from_off().
#define RCC_CSR_IWDGRSTF (1 << 29)
Definition at line 393 of file rcc.h.
#define RCC_CSR_LPWRRSTF (1 << 31)
Definition at line 391 of file rcc.h.
#define RCC_CSR_LSION (1 << 0)
Definition at line 399 of file rcc.h.
Referenced by rcc_osc_off(), rcc_osc_on(), and rtc_awake_from_off().
#define RCC_CSR_LSIRDY (1 << 1)
Definition at line 398 of file rcc.h.
Referenced by rcc_wait_for_osc_ready(), and rtc_awake_from_off().
#define RCC_CSR_PINRSTF (1 << 26)
Definition at line 396 of file rcc.h.
#define RCC_CSR_PORRSTF (1 << 27)
Definition at line 395 of file rcc.h.
#define RCC_CSR_RMVF (1 << 24)
Definition at line 397 of file rcc.h.
#define RCC_CSR_SFTRSTF (1 << 28)
Definition at line 394 of file rcc.h.
#define RCC_CSR_WWDGRSTF (1 << 30)
Definition at line 392 of file rcc.h.
Enumeration Type Documentation
enum osc_t
Enumerator:
PLL
PLL2
PLL3
HSE
HSI
LSE
LSI
Definition at line 493 of file rcc.h.
Function Documentation
void rcc_backupdomain_reset (void)
RCC Reset the backup domain.
The backup domain register is reset to disable all controls.
Definition at line 1206 of file rcc.c.
References RCC_BDCR, and RCC_BDCR_BDRST.
Referenced by rtc_awake_from_off().
void rcc_clock_setup_in_hse_12mhz_out_72mhz (void)
RCC Set System Clock PLL at 24MHz from HSE at 12MHz.
Definition at line 1022 of file rcc.c.
References FLASH_ACR_LATENCY_2WS, flash_set_ws(), HSE, HSI, PLL, RCC_CFGR_ADCPRE_PCLK2_DIV6, RCC_CFGR_HPRE_SYSCLK_NODIV, RCC_CFGR_PLLMUL_PLL_CLK_MUL6, RCC_CFGR_PLLSRC_HSE_CLK, RCC_CFGR_PLLXTPRE_HSE_CLK, RCC_CFGR_PPRE1_HCLK_DIV2, RCC_CFGR_PPRE2_HCLK_NODIV, RCC_CFGR_SW_SYSCLKSEL_HSECLK, RCC_CFGR_SW_SYSCLKSEL_HSICLK, RCC_CFGR_SW_SYSCLKSEL_PLLCLK, rcc_osc_on(), rcc_ppre1_frequency, rcc_ppre2_frequency, rcc_set_adcpre(), rcc_set_hpre(), rcc_set_pll_multiplication_factor(), rcc_set_pll_source(), rcc_set_pllxtpre(), rcc_set_ppre1(), rcc_set_ppre2(), rcc_set_sysclk_source(), and rcc_wait_for_osc_ready().
void rcc_clock_setup_in_hse_16mhz_out_72mhz (void)
RCC Set System Clock PLL at 24MHz from HSE at 16MHz.
Definition at line 1085 of file rcc.c.
References FLASH_ACR_LATENCY_2WS, flash_set_ws(), HSE, HSI, PLL, RCC_CFGR_ADCPRE_PCLK2_DIV6, RCC_CFGR_HPRE_SYSCLK_NODIV, RCC_CFGR_PLLMUL_PLL_CLK_MUL9, RCC_CFGR_PLLSRC_HSE_CLK, RCC_CFGR_PLLXTPRE_HSE_CLK_DIV2, RCC_CFGR_PPRE1_HCLK_DIV2, RCC_CFGR_PPRE2_HCLK_NODIV, RCC_CFGR_SW_SYSCLKSEL_HSECLK, RCC_CFGR_SW_SYSCLKSEL_HSICLK, RCC_CFGR_SW_SYSCLKSEL_PLLCLK, rcc_osc_on(), rcc_ppre1_frequency, rcc_ppre2_frequency, rcc_set_adcpre(), rcc_set_hpre(), rcc_set_pll_multiplication_factor(), rcc_set_pll_source(), rcc_set_pllxtpre(), rcc_set_ppre1(), rcc_set_ppre2(), rcc_set_sysclk_source(), and rcc_wait_for_osc_ready().
void rcc_clock_setup_in_hse_25mhz_out_72mhz (void)
RCC Set System Clock PLL at 72MHz from HSE at 25MHz.
Definition at line 1148 of file rcc.c.
References FLASH_ACR_LATENCY_2WS, flash_set_ws(), HSE, PLL, PLL2, RCC_CFGR2_PLL2MUL_PLL2_CLK_MUL8, RCC_CFGR2_PREDIV1SRC_PLL2_CLK, RCC_CFGR2_PREDIV2_DIV5, RCC_CFGR2_PREDIV_DIV5, RCC_CFGR_ADCPRE_PCLK2_DIV6, RCC_CFGR_HPRE_SYSCLK_NODIV, RCC_CFGR_PLLMUL_PLL_CLK_MUL9, RCC_CFGR_PLLSRC_PREDIV1_CLK, RCC_CFGR_PLLXTPRE_HSE_CLK, RCC_CFGR_PPRE1_HCLK_DIV2, RCC_CFGR_PPRE2_HCLK_NODIV, RCC_CFGR_SW_SYSCLKSEL_HSECLK, RCC_CFGR_SW_SYSCLKSEL_PLLCLK, RCC_CFGR_USBPRE_PLL_VCO_CLK_DIV3, rcc_osc_on(), rcc_ppre1_frequency, rcc_ppre2_frequency, rcc_set_adcpre(), rcc_set_hpre(), rcc_set_pll2_multiplication_factor(), rcc_set_pll_multiplication_factor(), rcc_set_pll_source(), rcc_set_pllxtpre(), rcc_set_ppre1(), rcc_set_ppre2(), rcc_set_prediv1(), rcc_set_prediv1_source(), rcc_set_prediv2(), rcc_set_sysclk_source(), rcc_set_usbpre(), and rcc_wait_for_osc_ready().
void rcc_clock_setup_in_hse_8mhz_out_24mhz (void)
RCC Set System Clock PLL at 24MHz from HSE at 8MHz.
Definition at line 896 of file rcc.c.
References FLASH_ACR_LATENCY_0WS, flash_set_ws(), HSE, HSI, PLL, RCC_CFGR_ADCPRE_PCLK2_DIV2, RCC_CFGR_HPRE_SYSCLK_NODIV, RCC_CFGR_PLLMUL_PLL_CLK_MUL3, RCC_CFGR_PLLSRC_HSE_CLK, RCC_CFGR_PLLXTPRE_HSE_CLK, RCC_CFGR_PPRE1_HCLK_NODIV, RCC_CFGR_PPRE2_HCLK_NODIV, RCC_CFGR_SW_SYSCLKSEL_HSECLK, RCC_CFGR_SW_SYSCLKSEL_HSICLK, RCC_CFGR_SW_SYSCLKSEL_PLLCLK, rcc_osc_on(), rcc_ppre1_frequency, rcc_ppre2_frequency, rcc_set_adcpre(), rcc_set_hpre(), rcc_set_pll_multiplication_factor(), rcc_set_pll_source(), rcc_set_pllxtpre(), rcc_set_ppre1(), rcc_set_ppre2(), rcc_set_sysclk_source(), and rcc_wait_for_osc_ready().
void rcc_clock_setup_in_hse_8mhz_out_72mhz (void)
RCC Set System Clock PLL at 72MHz from HSE at 8MHz.
Definition at line 959 of file rcc.c.
References FLASH_ACR_LATENCY_2WS, flash_set_ws(), HSE, HSI, PLL, RCC_CFGR_ADCPRE_PCLK2_DIV8, RCC_CFGR_HPRE_SYSCLK_NODIV, RCC_CFGR_PLLMUL_PLL_CLK_MUL9, RCC_CFGR_PLLSRC_HSE_CLK, RCC_CFGR_PLLXTPRE_HSE_CLK, RCC_CFGR_PPRE1_HCLK_DIV2, RCC_CFGR_PPRE2_HCLK_NODIV, RCC_CFGR_SW_SYSCLKSEL_HSECLK, RCC_CFGR_SW_SYSCLKSEL_HSICLK, RCC_CFGR_SW_SYSCLKSEL_PLLCLK, rcc_osc_on(), rcc_ppre1_frequency, rcc_ppre2_frequency, rcc_set_adcpre(), rcc_set_hpre(), rcc_set_pll_multiplication_factor(), rcc_set_pll_source(), rcc_set_pllxtpre(), rcc_set_ppre1(), rcc_set_ppre2(), rcc_set_sysclk_source(), and rcc_wait_for_osc_ready().
void rcc_clock_setup_in_hsi_out_24mhz (void)
RCC Set System Clock PLL at 24MHz from HSI.
Definition at line 845 of file rcc.c.
References FLASH_ACR_LATENCY_0WS, flash_set_ws(), HSI, PLL, RCC_CFGR_ADCPRE_PCLK2_DIV2, RCC_CFGR_HPRE_SYSCLK_NODIV, RCC_CFGR_PLLMUL_PLL_CLK_MUL6, RCC_CFGR_PLLSRC_HSI_CLK_DIV2, RCC_CFGR_PPRE1_HCLK_NODIV, RCC_CFGR_PPRE2_HCLK_NODIV, RCC_CFGR_SW_SYSCLKSEL_HSICLK, RCC_CFGR_SW_SYSCLKSEL_PLLCLK, rcc_osc_on(), rcc_ppre1_frequency, rcc_ppre2_frequency, rcc_set_adcpre(), rcc_set_hpre(), rcc_set_pll_multiplication_factor(), rcc_set_pll_source(), rcc_set_ppre1(), rcc_set_ppre2(), rcc_set_sysclk_source(), and rcc_wait_for_osc_ready().
void rcc_clock_setup_in_hsi_out_48mhz (void)
RCC Set System Clock PLL at 48MHz from HSI.
Definition at line 792 of file rcc.c.
References FLASH_ACR_LATENCY_1WS, flash_set_ws(), HSI, PLL, RCC_CFGR_ADCPRE_PCLK2_DIV8, RCC_CFGR_HPRE_SYSCLK_NODIV, RCC_CFGR_PLLMUL_PLL_CLK_MUL12, RCC_CFGR_PLLSRC_HSI_CLK_DIV2, RCC_CFGR_PPRE1_HCLK_DIV2, RCC_CFGR_PPRE2_HCLK_NODIV, RCC_CFGR_SW_SYSCLKSEL_HSICLK, RCC_CFGR_SW_SYSCLKSEL_PLLCLK, RCC_CFGR_USBPRE_PLL_CLK_NODIV, rcc_osc_on(), rcc_ppre1_frequency, rcc_ppre2_frequency, rcc_set_adcpre(), rcc_set_hpre(), rcc_set_pll_multiplication_factor(), rcc_set_pll_source(), rcc_set_ppre1(), rcc_set_ppre2(), rcc_set_sysclk_source(), rcc_set_usbpre(), and rcc_wait_for_osc_ready().
void rcc_clock_setup_in_hsi_out_64mhz (void)
RCC Set System Clock PLL at 64MHz from HSI.
Definition at line 740 of file rcc.c.
References FLASH_ACR_LATENCY_2WS, flash_set_ws(), HSI, PLL, RCC_CFGR_ADCPRE_PCLK2_DIV8, RCC_CFGR_HPRE_SYSCLK_NODIV, RCC_CFGR_PLLMUL_PLL_CLK_MUL16, RCC_CFGR_PLLSRC_HSI_CLK_DIV2, RCC_CFGR_PPRE1_HCLK_DIV2, RCC_CFGR_PPRE2_HCLK_NODIV, RCC_CFGR_SW_SYSCLKSEL_HSICLK, RCC_CFGR_SW_SYSCLKSEL_PLLCLK, rcc_osc_on(), rcc_ppre1_frequency, rcc_ppre2_frequency, rcc_set_adcpre(), rcc_set_hpre(), rcc_set_pll_multiplication_factor(), rcc_set_pll_source(), rcc_set_ppre1(), rcc_set_ppre2(), rcc_set_sysclk_source(), and rcc_wait_for_osc_ready().
void rcc_css_disable (void)
RCC Disable the Clock Security System.
Definition at line 348 of file rcc.c.
References RCC_CR, and RCC_CR_CSSON.
void rcc_css_enable (void)
RCC Enable the Clock Security System.
Definition at line 338 of file rcc.c.
References RCC_CR, and RCC_CR_CSSON.
void rcc_css_int_clear (void)
RCC Clear the Clock Security System Interrupt Flag.
Definition at line 202 of file rcc.c.
References RCC_CIR, and RCC_CIR_CSSC.
int rcc_css_int_flag (void)
RCC Read the Clock Security System Interrupt Flag.
Returns
int. Boolean value for flag set.
Definition at line 213 of file rcc.c.
References RCC_CIR, and RCC_CIR_CSSF.
void rcc_osc_bypass_disable (osc_t osc)
RCC Disable Bypass.
Re-enable the internal clock (high speed and low speed clocks only). The internal clock must be disabled (see rcc_osc_off) for this to have effect.
Note
The LSE clock is in the backup domain and cannot have bypass removed until the backup domain write protection has been removed (see pwr_disable_backup_domain_write_protect) or the backup domain has been reset (see rcc_backupdomain_reset).
Parameters
[in] osc enum osc_t. Oscillator ID. Only HSE and LSE have effect.
Definition at line 398 of file rcc.c.
References HSE, HSI, LSE, LSI, PLL, PLL2, PLL3, RCC_BDCR, RCC_BDCR_LSEBYP, RCC_CR, and RCC_CR_HSEBYP.
void rcc_osc_bypass_enable (osc_t osc)
RCC Enable Bypass.
Enable an external clock to bypass the internal clock (high speed and low speed clocks only). The external clock must be enabled (see rcc_osc_on) and the internal clock must be disabled (see rcc_osc_off) for this to have effect.
Note
The LSE clock is in the backup domain and cannot be bypassed until the backup domain write protection has been removed (see pwr_disable_backup_domain_write_protect).
Parameters
[in] osc enum osc_t. Oscillator ID. Only HSE and LSE have effect.
Definition at line 366 of file rcc.c.
References HSE, HSI, LSE, LSI, PLL, PLL2, PLL3, RCC_BDCR, RCC_BDCR_LSEBYP, RCC_CR, and RCC_CR_HSEBYP.
void rcc_osc_off (osc_t osc)
RCC Turn off an Oscillator.
Disable an oscillator and power off.
Note
An oscillator cannot be turned off if it is selected as the system clock.
The LSE clock is in the backup domain and cannot be disabled until the backup domain write protection has been removed (see pwr_disable_backup_domain_write_protect) or the backup domain has been (see reset rcc_backupdomain_reset).
Parameters
[in] osc enum osc_t. Oscillator ID
Definition at line 306 of file rcc.c.
References HSE, HSI, LSE, LSI, PLL, PLL2, PLL3, RCC_BDCR, RCC_BDCR_LSEON, RCC_CR, RCC_CR_HSEON, RCC_CR_HSION, RCC_CR_PLL2ON, RCC_CR_PLL3ON, RCC_CR_PLLON, RCC_CSR, and RCC_CSR_LSION.
void rcc_osc_on (osc_t osc)
RCC Turn on an Oscillator.
Enable an oscillator and power on. Each oscillator requires an amount of time to settle to a usable state. Refer to datasheets for time delay information. A status flag is available to indicate when the oscillator becomes ready (see rcc_osc_ready_int_flag and rcc_wait_for_osc_ready).
Note
The LSE clock is in the backup domain and cannot be enabled until the backup domain write protection has been removed (see pwr_disable_backup_domain_write_protect).
Parameters
[in] osc enum osc_t. Oscillator ID
Definition at line 265 of file rcc.c.
References HSE, HSI, LSE, LSI, PLL, PLL2, PLL3, RCC_BDCR, RCC_BDCR_LSEON, RCC_CR, RCC_CR_HSEON, RCC_CR_HSION, RCC_CR_PLL2ON, RCC_CR_PLL3ON, RCC_CR_PLLON, RCC_CSR, and RCC_CSR_LSION.
Referenced by rcc_clock_setup_in_hse_12mhz_out_72mhz(), rcc_clock_setup_in_hse_16mhz_out_72mhz(), rcc_clock_setup_in_hse_25mhz_out_72mhz(), rcc_clock_setup_in_hse_8mhz_out_24mhz(), rcc_clock_setup_in_hse_8mhz_out_72mhz(), rcc_clock_setup_in_hsi_out_24mhz(), rcc_clock_setup_in_hsi_out_48mhz(), and rcc_clock_setup_in_hsi_out_64mhz().
BEGIN_DECLS void rcc_osc_ready_int_clear (osc_t osc)
RCC Clear the Oscillator Ready Interrupt Flag.
Clear the interrupt flag that was set when a clock oscillator became ready to use.
Parameters
[in] osc enum osc_t. Oscillator ID
Definition at line 68 of file rcc.c.
References HSE, HSI, LSE, LSI, PLL, PLL2, PLL3, RCC_CIR, RCC_CIR_HSERDYC, RCC_CIR_HSIRDYC, RCC_CIR_LSERDYC, RCC_CIR_LSIRDYC, RCC_CIR_PLL2RDYC, RCC_CIR_PLL3RDYC, and RCC_CIR_PLLRDYC.
void rcc_osc_ready_int_disable (osc_t osc)
RCC Disable the Oscillator Ready Interrupt.
Parameters
[in] osc enum osc_t. Oscillator ID
Definition at line 134 of file rcc.c.
References HSE, HSI, LSE, LSI, PLL, PLL2, PLL3, RCC_CIR, RCC_CIR_HSERDYIE, RCC_CIR_HSIRDYIE, RCC_CIR_LSERDYIE, RCC_CIR_LSIRDYIE, RCC_CIR_PLL2RDYIE, RCC_CIR_PLL3RDYIE, and RCC_CIR_PLLRDYIE.
void rcc_osc_ready_int_enable (osc_t osc)
RCC Enable the Oscillator Ready Interrupt.
Parameters
[in] osc enum osc_t. Oscillator ID
Definition at line 101 of file rcc.c.
References HSE, HSI, LSE, LSI, PLL, PLL2, PLL3, RCC_CIR, RCC_CIR_HSERDYIE, RCC_CIR_HSIRDYIE, RCC_CIR_LSERDYIE, RCC_CIR_LSIRDYIE, RCC_CIR_PLL2RDYIE, RCC_CIR_PLL3RDYIE, and RCC_CIR_PLLRDYIE.
int rcc_osc_ready_int_flag (osc_t osc)
RCC Read the Oscillator Ready Interrupt Flag.
Parameters
[in] osc enum osc_t. Oscillator ID
Returns
int. Boolean value for flag set.
Definition at line 168 of file rcc.c.
References cm3_assert_not_reached, HSE, HSI, LSE, LSI, PLL, PLL2, PLL3, RCC_CIR, RCC_CIR_HSERDYF, RCC_CIR_HSIRDYF, RCC_CIR_LSERDYF, RCC_CIR_LSIRDYF, RCC_CIR_PLL2RDYF, RCC_CIR_PLL3RDYF, and RCC_CIR_PLLRDYF.
void rcc_peripheral_clear_reset (volatile u32 * reg, u32 clear_reset)
RCC Remove Reset on Peripherals.
Remove the reset on particular peripherals. There are three registers involved, each one controlling reset of peripherals associated with the AHB, APB1 and APB2 respectively. Several peripherals could have the reset removed simultaneously only if they are controlled by the same register.
Parameters
[in] *reg Unsigned int32. Pointer to a Reset Register (either RCC_AHBENR, RCC_APB1ENR or RCC_APB2ENR)
[in] clear_reset Unsigned int32. Logical OR of all resets to be removed:
If register is RCC_AHBRSTR, from RCC_AHBRSTR reset values
If register is RCC_APB1RSTR, from RCC_APB1RSTR reset values
If register is RCC_APB2RSTR, from RCC_APB2RSTR reset values
Definition at line 496 of file rcc.c.
Referenced by i2c_reset(), and spi_reset().
void rcc_peripheral_disable_clock (volatile u32 * reg, u32 en)
RCC Disable Peripheral Clocks.
Enable the clock on particular peripherals. There are three registers involved, each one controlling the enabling of clocks associated with the AHB, APB1 and APB2 respectively. Several peripherals could be disabled simultaneously only if they are controlled by the same register.
Parameters
[in] *reg Unsigned int32. Pointer to a Clock Enable Register (either RCC_AHBENR, RCC_APB1ENR or RCC_APB2ENR)
[in] en Unsigned int32. Logical OR of all enables to be used for disabling.
If register is RCC_AHBER, from RCC_AHBENR enable values
If register is RCC_APB1ENR, from RCC_APB1ENR enable values
If register is RCC_APB2ENR, from RCC_APB2ENR enable values
Definition at line 454 of file rcc.c.
void rcc_peripheral_enable_clock (volatile u32 * reg, u32 en)
RCC Enable Peripheral Clocks.
Enable the clock on particular peripherals. There are three registers involved, each one controlling the enabling of clocks associated with the AHB, APB1 and APB2 respectively. Several peripherals could be enabled simultaneously only if they are controlled by the same register.
Parameters
[in] *reg Unsigned int32. Pointer to a Clock Enable Register (either RCC_AHBENR, RCC_APB1ENR or RCC_APB2ENR)
[in] en Unsigned int32. Logical OR of all enables to be set
If register is RCC_AHBER, from RCC_AHBENR enable values
If register is RCC_APB1ENR, from RCC_APB1ENR enable values
If register is RCC_APB2ENR, from RCC_APB2ENR enable values
Definition at line 433 of file rcc.c.
void rcc_peripheral_reset (volatile u32 * reg, u32 reset)
RCC Reset Peripherals.
Reset particular peripherals. There are three registers involved, each one controlling reset of peripherals associated with the AHB, APB1 and APB2 respectively. Several peripherals could be reset simultaneously only if they are controlled by the same register.
Parameters
[in] *reg Unsigned int32. Pointer to a Reset Register (either RCC_AHBENR, RCC_APB1ENR or RCC_APB2ENR)
[in] reset Unsigned int32. Logical OR of all resets.
If register is RCC_AHBRSTR, from RCC_AHBRSTR reset values
If register is RCC_APB1RSTR, from RCC_APB1RSTR reset values
If register is RCC_APB2RSTR, from RCC_APB2RSTR reset values
Definition at line 475 of file rcc.c.
Referenced by i2c_reset(), and spi_reset().
void rcc_set_adcpre (u32 adcpre)
ADC Setup the A/D Clock.
The ADC's have a common clock prescale setting.
Parameters
[in] adcpre u32. Prescale divider taken from RCC ADC Clock Prescaler enable values
Definition at line 609 of file rcc.c.
References RCC_CFGR.
Referenced by rcc_clock_setup_in_hse_12mhz_out_72mhz(), rcc_clock_setup_in_hse_16mhz_out_72mhz(), rcc_clock_setup_in_hse_25mhz_out_72mhz(), rcc_clock_setup_in_hse_8mhz_out_24mhz(), rcc_clock_setup_in_hse_8mhz_out_72mhz(), rcc_clock_setup_in_hsi_out_24mhz(), rcc_clock_setup_in_hsi_out_48mhz(), and rcc_clock_setup_in_hsi_out_64mhz().
void rcc_set_hpre (u32 hpre)
RCC Set the AHB Prescale Factor.
Parameters
[in] hpre Unsigned int32. AHB prescale factor RCC_CFGR AHB Prescale Factors
Definition at line 656 of file rcc.c.
References RCC_CFGR.
Referenced by rcc_clock_setup_in_hse_12mhz_out_72mhz(), rcc_clock_setup_in_hse_16mhz_out_72mhz(), rcc_clock_setup_in_hse_25mhz_out_72mhz(), rcc_clock_setup_in_hse_8mhz_out_24mhz(), rcc_clock_setup_in_hse_8mhz_out_72mhz(), rcc_clock_setup_in_hsi_out_24mhz(), rcc_clock_setup_in_hsi_out_48mhz(), and rcc_clock_setup_in_hsi_out_64mhz().
void rcc_set_mco (u32 mcosrc)
Definition at line 707 of file rcc.c.
References RCC_CFGR.
void rcc_set_pll2_multiplication_factor (u32 mul)
RCC Set the PLL2 Multiplication Factor.
Note
This only has effect when the PLL is disabled.
Parameters
[in] mul Unsigned int32. PLL multiplication factor RCC_CFGR PLL Multiplication Factor
Definition at line 541 of file rcc.c.
References RCC_CFGR2.
Referenced by rcc_clock_setup_in_hse_25mhz_out_72mhz().
void rcc_set_pll3_multiplication_factor (u32 mul)
RCC Set the PLL3 Multiplication Factor.
Note
This only has effect when the PLL is disabled.
Parameters
[in] mul Unsigned int32. PLL multiplication factor RCC_CFGR PLL Multiplication Factor
Definition at line 558 of file rcc.c.
References RCC_CFGR2.
void rcc_set_pll_multiplication_factor (u32 mul)
RCC Set the PLL Multiplication Factor.
Note
This only has effect when the PLL is disabled.
Parameters
[in] mul Unsigned int32. PLL multiplication factor RCC_CFGR PLL Multiplication Factor
Definition at line 524 of file rcc.c.
References RCC_CFGR.
Referenced by rcc_clock_setup_in_hse_12mhz_out_72mhz(), rcc_clock_setup_in_hse_16mhz_out_72mhz(), rcc_clock_setup_in_hse_25mhz_out_72mhz(), rcc_clock_setup_in_hse_8mhz_out_24mhz(), rcc_clock_setup_in_hse_8mhz_out_72mhz(), rcc_clock_setup_in_hsi_out_24mhz(), rcc_clock_setup_in_hsi_out_48mhz(), and rcc_clock_setup_in_hsi_out_64mhz().
void rcc_set_pll_source (u32 pllsrc)
RCC Set the PLL Clock Source.
Note
This only has effect when the PLL is disabled.
Parameters
[in] pllsrc Unsigned int32. PLL clock source RCC_CFGR PLL Clock Source
Definition at line 575 of file rcc.c.
References RCC_CFGR.
Referenced by rcc_clock_setup_in_hse_12mhz_out_72mhz(), rcc_clock_setup_in_hse_16mhz_out_72mhz(), rcc_clock_setup_in_hse_25mhz_out_72mhz(), rcc_clock_setup_in_hse_8mhz_out_24mhz(), rcc_clock_setup_in_hse_8mhz_out_72mhz(), rcc_clock_setup_in_hsi_out_24mhz(), rcc_clock_setup_in_hsi_out_48mhz(), and rcc_clock_setup_in_hsi_out_64mhz().
void rcc_set_pllxtpre (u32 pllxtpre)
RCC Set the HSE Frequency Divider used as PLL Clock Source.
Note
This only has effect when the PLL is disabled.
Parameters
[in] pllxtpre Unsigned int32. HSE division factor RCC_CFGR HSE Divider for PLL
Definition at line 592 of file rcc.c.
References RCC_CFGR.
Referenced by rcc_clock_setup_in_hse_12mhz_out_72mhz(), rcc_clock_setup_in_hse_16mhz_out_72mhz(), rcc_clock_setup_in_hse_25mhz_out_72mhz(), rcc_clock_setup_in_hse_8mhz_out_24mhz(), and rcc_clock_setup_in_hse_8mhz_out_72mhz().
void rcc_set_ppre1 (u32 ppre1)
RCC Set the APB1 Prescale Factor.
Note
The APB1 clock frequency must not exceed 36MHz.
Parameters
[in] ppre1 Unsigned int32. APB1 prescale factor RCC_CFGR APB1 Prescale Factors
Definition at line 641 of file rcc.c.
References RCC_CFGR.
Referenced by rcc_clock_setup_in_hse_12mhz_out_72mhz(), rcc_clock_setup_in_hse_16mhz_out_72mhz(), rcc_clock_setup_in_hse_25mhz_out_72mhz(), rcc_clock_setup_in_hse_8mhz_out_24mhz(), rcc_clock_setup_in_hse_8mhz_out_72mhz(), rcc_clock_setup_in_hsi_out_24mhz(), rcc_clock_setup_in_hsi_out_48mhz(), and rcc_clock_setup_in_hsi_out_64mhz().
void rcc_set_ppre2 (u32 ppre2)
RCC Set the APB2 Prescale Factor.
Parameters
[in] ppre2 Unsigned int32. APB2 prescale factor RCC_CFGR APB2 Prescale Factors
Definition at line 624 of file rcc.c.
References RCC_CFGR.
Referenced by rcc_clock_setup_in_hse_12mhz_out_72mhz(), rcc_clock_setup_in_hse_16mhz_out_72mhz(), rcc_clock_setup_in_hse_25mhz_out_72mhz(), rcc_clock_setup_in_hse_8mhz_out_24mhz(), rcc_clock_setup_in_hse_8mhz_out_72mhz(), rcc_clock_setup_in_hsi_out_24mhz(), rcc_clock_setup_in_hsi_out_48mhz(), and rcc_clock_setup_in_hsi_out_64mhz().
void rcc_set_prediv1 (u32 prediv)
Definition at line 685 of file rcc.c.
References RCC_CFGR2.
Referenced by rcc_clock_setup_in_hse_25mhz_out_72mhz().
void rcc_set_prediv1_source (u32 rccsrc)
Definition at line 701 of file rcc.c.
References RCC_CFGR2.
Referenced by rcc_clock_setup_in_hse_25mhz_out_72mhz().
void rcc_set_prediv2 (u32 prediv)
Definition at line 693 of file rcc.c.
References RCC_CFGR2.
Referenced by rcc_clock_setup_in_hse_25mhz_out_72mhz().
void rcc_set_sysclk_source (u32 clk)
RCC Set the Source for the System Clock.
Parameters
[in] clk Unsigned int32. System Clock Selection RCC_CFGR System Clock Selection
Definition at line 507 of file rcc.c.
References RCC_CFGR.
Referenced by rcc_clock_setup_in_hse_12mhz_out_72mhz(), rcc_clock_setup_in_hse_16mhz_out_72mhz(), rcc_clock_setup_in_hse_25mhz_out_72mhz(), rcc_clock_setup_in_hse_8mhz_out_24mhz(), rcc_clock_setup_in_hse_8mhz_out_72mhz(), rcc_clock_setup_in_hsi_out_24mhz(), rcc_clock_setup_in_hsi_out_48mhz(), and rcc_clock_setup_in_hsi_out_64mhz().
void rcc_set_usbpre (u32 usbpre)
RCC Set the USB Prescale Factor.
The prescale factor can be set to 1 (no prescale) for use when the PLL clock is 48MHz, or 1.5 to generate the 48MHz USB clock from a 64MHz PLL clock.
Note
This bit cannot be reset while the USB clock is enabled.
Parameters
[in] usbpre Unsigned int32. USB prescale factor RCC_CFGR USB prescale Factors
Definition at line 676 of file rcc.c.
References RCC_CFGR.
Referenced by rcc_clock_setup_in_hse_25mhz_out_72mhz(), and rcc_clock_setup_in_hsi_out_48mhz().
u32 rcc_system_clock_source (void)
RCC Get the System Clock Source.
Returns
Unsigned int32. System clock source:
00 indicates HSE
01 indicates LSE
02 indicates PLL
Definition at line 724 of file rcc.c.
References RCC_CFGR.
void rcc_wait_for_osc_ready (osc_t osc)
RCC Wait for Oscillator Ready.
Parameters
[in] osc enum osc_t. Oscillator ID
Definition at line 224 of file rcc.c.
References HSE, HSI, LSE, LSI, PLL, PLL2, PLL3, RCC_BDCR, RCC_BDCR_LSERDY, RCC_CR, RCC_CR_HSERDY, RCC_CR_HSIRDY, RCC_CR_PLL2RDY, RCC_CR_PLL3RDY, RCC_CR_PLLRDY, RCC_CSR, and RCC_CSR_LSIRDY.
Referenced by rcc_clock_setup_in_hse_12mhz_out_72mhz(), rcc_clock_setup_in_hse_16mhz_out_72mhz(), rcc_clock_setup_in_hse_25mhz_out_72mhz(), rcc_clock_setup_in_hse_8mhz_out_24mhz(), rcc_clock_setup_in_hse_8mhz_out_72mhz(), rcc_clock_setup_in_hsi_out_24mhz(), rcc_clock_setup_in_hsi_out_48mhz(), and rcc_clock_setup_in_hsi_out_64mhz().
Variable Documentation
u32 rcc_ppre1_frequency
Default ppre1 peripheral clock frequency after reset.
Definition at line 56 of file rcc.c.
Referenced by rcc_clock_setup_in_hse_12mhz_out_72mhz(), rcc_clock_setup_in_hse_16mhz_out_72mhz(), rcc_clock_setup_in_hse_25mhz_out_72mhz(), rcc_clock_setup_in_hse_8mhz_out_24mhz(), rcc_clock_setup_in_hse_8mhz_out_72mhz(), rcc_clock_setup_in_hsi_out_24mhz(), rcc_clock_setup_in_hsi_out_48mhz(), rcc_clock_setup_in_hsi_out_64mhz(), and usart_set_baudrate().
u32 rcc_ppre2_frequency
Default ppre2 peripheral clock frequency after reset.
Definition at line 58 of file rcc.c.
Referenced by rcc_clock_setup_in_hse_12mhz_out_72mhz(), rcc_clock_setup_in_hse_16mhz_out_72mhz(), rcc_clock_setup_in_hse_25mhz_out_72mhz(), rcc_clock_setup_in_hse_8mhz_out_24mhz(), rcc_clock_setup_in_hse_8mhz_out_72mhz(), rcc_clock_setup_in_hsi_out_24mhz(), rcc_clock_setup_in_hsi_out_48mhz(), rcc_clock_setup_in_hsi_out_64mhz(), and usart_set_baudrate().