libopencm3: rtc.c File Reference
rtc.c File Reference
#include <libopencm3/stm32/rcc.h>
#include <libopencm3/stm32/rtc.h>
#include <libopencm3/stm32/pwr.h>
Functions
void rtc_awake_from_off (enum rcc_osc clock_source)
void rtc_enter_config_mode (void)
void rtc_exit_config_mode (void)
void rtc_set_alarm_time (uint32_t alarm_time)
void rtc_enable_alarm (void)
void rtc_disable_alarm (void)
void rtc_set_prescale_val (uint32_t prescale_val)
uint32_t rtc_get_counter_val (void)
uint32_t rtc_get_prescale_div_val (void)
uint32_t rtc_get_alarm_val (void)
void rtc_set_counter_val (uint32_t counter_val)
void rtc_interrupt_enable (rtcflag_t flag_val)
void rtc_interrupt_disable (rtcflag_t flag_val)
void rtc_clear_flag (rtcflag_t flag_val)
uint32_t rtc_check_flag (rtcflag_t flag_val)
void rtc_awake_from_standby (void)
void rtc_auto_awake (enum rcc_osc clock_source, uint32_t prescale_val)
Function Documentation
void rtc_auto_awake (enum rcc_osc clock_source, uint32_t prescale_val)
Definition at line 282 of file rtc.c.
References PWR_CR, PWR_CR_DBP, RCC_APB1ENR, RCC_APB1ENR_BKPEN, RCC_APB1ENR_PWREN, RCC_BDCR, RCC_BDCR_RTCEN, rtc_awake_from_off(), rtc_awake_from_standby(), and rtc_set_prescale_val().
void rtc_awake_from_off (enum rcc_osc clock_source)
Definition at line 41 of file rtc.c.
References HSE, HSI, LSE, LSI, PLL, PLL2, PLL3, PWR_CR, PWR_CR_DBP, RCC_APB1ENR, RCC_APB1ENR_BKPEN, RCC_APB1ENR_PWREN, rcc_backupdomain_reset(), RCC_BDCR, RCC_BDCR_LSEON, RCC_BDCR_LSERDY, RCC_BDCR_RTCEN, RCC_CR, RCC_CR_HSEON, RCC_CR_HSERDY, RCC_CSR, RCC_CSR_LSION, RCC_CSR_LSIRDY, RTC_CRL, RTC_CRL_RSF, and RTC_CRL_RTOFF.
Referenced by rtc_auto_awake().
void rtc_awake_from_standby (void)
Definition at line 263 of file rtc.c.
References PWR_CR, PWR_CR_DBP, RCC_APB1ENR, RCC_APB1ENR_BKPEN, RCC_APB1ENR_PWREN, RTC_CRL, RTC_CRL_RSF, and RTC_CRL_RTOFF.
Referenced by rtc_auto_awake().
uint32_t rtc_check_flag (rtcflag_t flag_val)
Definition at line 240 of file rtc.c.
References RTC_ALR, RTC_CRL, RTC_CRL_ALRF, RTC_CRL_OWF, RTC_CRL_SECF, RTC_OW, and RTC_SEC.
void rtc_clear_flag (rtcflag_t flag_val)
Definition at line 222 of file rtc.c.
References RTC_ALR, RTC_CRL, RTC_CRL_ALRF, RTC_CRL_OWF, RTC_CRL_SECF, RTC_OW, and RTC_SEC.
void rtc_disable_alarm (void)
Definition at line 144 of file rtc.c.
References RTC_CRH, RTC_CRH_ALRIE, rtc_enter_config_mode(), and rtc_exit_config_mode().
void rtc_enable_alarm (void)
Definition at line 137 of file rtc.c.
References RTC_CRH, RTC_CRH_ALRIE, rtc_enter_config_mode(), and rtc_exit_config_mode().
void rtc_enter_config_mode (void)
Definition at line 107 of file rtc.c.
References RTC_CRL, RTC_CRL_CNF, and RTC_CRL_RTOFF.
Referenced by rtc_disable_alarm(), rtc_enable_alarm(), rtc_interrupt_disable(), rtc_interrupt_enable(), rtc_set_alarm_time(), rtc_set_counter_val(), and rtc_set_prescale_val().
void rtc_exit_config_mode (void)
Definition at line 118 of file rtc.c.
References RTC_CRL, RTC_CRL_CNF, and RTC_CRL_RTOFF.
Referenced by rtc_disable_alarm(), rtc_enable_alarm(), rtc_interrupt_disable(), rtc_interrupt_enable(), rtc_set_alarm_time(), rtc_set_counter_val(), and rtc_set_prescale_val().
uint32_t rtc_get_alarm_val (void)
Definition at line 169 of file rtc.c.
References RTC_ALRH, and RTC_ALRL.
uint32_t rtc_get_counter_val (void)
Definition at line 159 of file rtc.c.
References RTC_CNTH, and RTC_CNTL.
uint32_t rtc_get_prescale_div_val (void)
Definition at line 164 of file rtc.c.
References RTC_DIVH, and RTC_DIVL.
void rtc_interrupt_disable (rtcflag_t flag_val)
Definition at line 202 of file rtc.c.
References RTC_ALR, RTC_CRH, RTC_CRH_ALRIE, RTC_CRH_OWIE, RTC_CRH_SECIE, rtc_enter_config_mode(), rtc_exit_config_mode(), RTC_OW, and RTC_SEC.
void rtc_interrupt_enable (rtcflag_t flag_val)
Definition at line 182 of file rtc.c.
References RTC_ALR, RTC_CRH, RTC_CRH_ALRIE, RTC_CRH_OWIE, RTC_CRH_SECIE, rtc_enter_config_mode(), rtc_exit_config_mode(), RTC_OW, and RTC_SEC.
void rtc_set_alarm_time (uint32_t alarm_time)
Definition at line 129 of file rtc.c.
References RTC_ALRH, RTC_ALRL, rtc_enter_config_mode(), and rtc_exit_config_mode().
void rtc_set_counter_val (uint32_t counter_val)
Definition at line 174 of file rtc.c.
References RTC_CNTH, RTC_CNTL, rtc_enter_config_mode(), and rtc_exit_config_mode().
void rtc_set_prescale_val (uint32_t prescale_val)
Definition at line 151 of file rtc.c.
References rtc_enter_config_mode(), rtc_exit_config_mode(), RTC_PRLH, and RTC_PRLL.
Referenced by rtc_auto_awake().