libopencm3: rtc.h File Reference
rtc.h File Reference
#include <libopencm3/stm32/memorymap.h>
#include <libopencm3/cm3/common.h>
#include <libopencm3/stm32/pwr.h>
#include <libopencm3/stm32/f1/rcc.h>
Macros
#define RTC_CRH MMIO32(RTC_BASE + 0x00)
#define RTC_CRL MMIO32(RTC_BASE + 0x04)
#define RTC_PRLH MMIO32(RTC_BASE + 0x08)
#define RTC_PRLL MMIO32(RTC_BASE + 0x0c)
#define RTC_DIVH MMIO32(RTC_BASE + 0x10)
#define RTC_DIVL MMIO32(RTC_BASE + 0x14)
#define RTC_CNTH MMIO32(RTC_BASE + 0x18)
#define RTC_CNTL MMIO32(RTC_BASE + 0x1c)
#define RTC_ALRH MMIO32(RTC_BASE + 0x20)
#define RTC_ALRL MMIO32(RTC_BASE + 0x24)
#define RTC_CRH_OWIE (1 << 2)
#define RTC_CRH_ALRIE (1 << 1)
#define RTC_CRH_SECIE (1 << 0)
#define RTC_CRL_RTOFF (1 << 5)
#define RTC_CRL_CNF (1 << 4)
#define RTC_CRL_RSF (1 << 3)
#define RTC_CRL_OWF (1 << 2)
#define RTC_CRL_ALRF (1 << 1)
#define RTC_CRL_SECF (1 << 0)
Enumerations
enum rtcflag_t { RTC_SEC, RTC_ALR, RTC_OW }
Functions
void rtc_awake_from_off (enum rcc_osc clock_source)
void rtc_enter_config_mode (void)
void rtc_exit_config_mode (void)
void rtc_set_alarm_time (uint32_t alarm_time)
void rtc_enable_alarm (void)
void rtc_disable_alarm (void)
void rtc_set_prescale_val (uint32_t prescale_val)
uint32_t rtc_get_counter_val (void)
uint32_t rtc_get_prescale_div_val (void)
uint32_t rtc_get_alarm_val (void)
void rtc_set_counter_val (uint32_t counter_val)
void rtc_interrupt_enable (rtcflag_t flag_val)
void rtc_interrupt_disable (rtcflag_t flag_val)
void rtc_clear_flag (rtcflag_t flag_val)
uint32_t rtc_check_flag (rtcflag_t flag_val)
void rtc_awake_from_standby (void)
void rtc_auto_awake (enum rcc_osc clock_source, uint32_t prescale_val)
Macro Definition Documentation
#define RTC_ALRH MMIO32(RTC_BASE + 0x20)
Definition at line 68 of file rtc.h.
Referenced by rtc_get_alarm_val(), and rtc_set_alarm_time().
#define RTC_ALRL MMIO32(RTC_BASE + 0x24)
Definition at line 69 of file rtc.h.
Referenced by rtc_get_alarm_val(), and rtc_set_alarm_time().
#define RTC_CNTH MMIO32(RTC_BASE + 0x18)
Definition at line 64 of file rtc.h.
Referenced by rtc_get_counter_val(), and rtc_set_counter_val().
#define RTC_CNTL MMIO32(RTC_BASE + 0x1c)
Definition at line 65 of file rtc.h.
Referenced by rtc_get_counter_val(), and rtc_set_counter_val().
#define RTC_CRH MMIO32(RTC_BASE + 0x00)
Definition at line 50 of file rtc.h.
Referenced by rtc_disable_alarm(), rtc_enable_alarm(), rtc_interrupt_disable(), and rtc_interrupt_enable().
#define RTC_CRH_ALRIE (1 << 1)
Definition at line 79 of file rtc.h.
Referenced by rtc_disable_alarm(), rtc_enable_alarm(), rtc_interrupt_disable(), and rtc_interrupt_enable().
#define RTC_CRH_OWIE (1 << 2)
Definition at line 76 of file rtc.h.
Referenced by rtc_interrupt_disable(), and rtc_interrupt_enable().
#define RTC_CRH_SECIE (1 << 0)
Definition at line 82 of file rtc.h.
Referenced by rtc_interrupt_disable(), and rtc_interrupt_enable().
#define RTC_CRL MMIO32(RTC_BASE + 0x04)
Definition at line 53 of file rtc.h.
Referenced by rtc_awake_from_off(), rtc_awake_from_standby(), rtc_check_flag(), rtc_clear_flag(), rtc_enter_config_mode(), and rtc_exit_config_mode().
#define RTC_CRL_ALRF (1 << 1)
Definition at line 101 of file rtc.h.
Referenced by rtc_check_flag(), and rtc_clear_flag().
#define RTC_CRL_CNF (1 << 4)
Definition at line 92 of file rtc.h.
Referenced by rtc_enter_config_mode(), and rtc_exit_config_mode().
#define RTC_CRL_OWF (1 << 2)
Definition at line 98 of file rtc.h.
Referenced by rtc_check_flag(), and rtc_clear_flag().
#define RTC_CRL_RSF (1 << 3)
Definition at line 95 of file rtc.h.
Referenced by rtc_awake_from_off(), and rtc_awake_from_standby().
#define RTC_CRL_RTOFF (1 << 5)
Definition at line 89 of file rtc.h.
Referenced by rtc_awake_from_off(), rtc_awake_from_standby(), rtc_enter_config_mode(), and rtc_exit_config_mode().
#define RTC_CRL_SECF (1 << 0)
Definition at line 104 of file rtc.h.
Referenced by rtc_check_flag(), and rtc_clear_flag().
#define RTC_DIVH MMIO32(RTC_BASE + 0x10)
Definition at line 60 of file rtc.h.
Referenced by rtc_get_prescale_div_val().
#define RTC_DIVL MMIO32(RTC_BASE + 0x14)
Definition at line 61 of file rtc.h.
Referenced by rtc_get_prescale_div_val().
#define RTC_PRLH MMIO32(RTC_BASE + 0x08)
Definition at line 56 of file rtc.h.
Referenced by rtc_set_prescale_val().
#define RTC_PRLL MMIO32(RTC_BASE + 0x0c)
Definition at line 57 of file rtc.h.
Referenced by rtc_set_prescale_val().
Enumeration Type Documentation
enum rtcflag_t
Enumerator
RTC_SEC
RTC_ALR
RTC_OW
Definition at line 144 of file rtc.h.
Function Documentation
void rtc_auto_awake (enum rcc_osc clock_source, uint32_t prescale_val)
Definition at line 282 of file rtc.c.
References PWR_CR, PWR_CR_DBP, RCC_APB1ENR, RCC_APB1ENR_BKPEN, RCC_APB1ENR_PWREN, RCC_BDCR, RCC_BDCR_RTCEN, rtc_awake_from_off(), rtc_awake_from_standby(), and rtc_set_prescale_val().
void rtc_awake_from_off (enum rcc_osc clock_source)
Definition at line 41 of file rtc.c.
References HSE, HSI, LSE, LSI, PLL, PLL2, PLL3, PWR_CR, PWR_CR_DBP, RCC_APB1ENR, RCC_APB1ENR_BKPEN, RCC_APB1ENR_PWREN, rcc_backupdomain_reset(), RCC_BDCR, RCC_BDCR_LSEON, RCC_BDCR_LSERDY, RCC_BDCR_RTCEN, RCC_CR, RCC_CR_HSEON, RCC_CR_HSERDY, RCC_CSR, RCC_CSR_LSION, RCC_CSR_LSIRDY, RTC_CRL, RTC_CRL_RSF, and RTC_CRL_RTOFF.
Referenced by rtc_auto_awake().
void rtc_awake_from_standby (void)
Definition at line 263 of file rtc.c.
References PWR_CR, PWR_CR_DBP, RCC_APB1ENR, RCC_APB1ENR_BKPEN, RCC_APB1ENR_PWREN, RTC_CRL, RTC_CRL_RSF, and RTC_CRL_RTOFF.
Referenced by rtc_auto_awake().
uint32_t rtc_check_flag (rtcflag_t flag_val)
Definition at line 240 of file rtc.c.
References RTC_ALR, RTC_CRL, RTC_CRL_ALRF, RTC_CRL_OWF, RTC_CRL_SECF, RTC_OW, and RTC_SEC.
void rtc_clear_flag (rtcflag_t flag_val)
Definition at line 222 of file rtc.c.
References RTC_ALR, RTC_CRL, RTC_CRL_ALRF, RTC_CRL_OWF, RTC_CRL_SECF, RTC_OW, and RTC_SEC.
void rtc_disable_alarm (void)
Definition at line 144 of file rtc.c.
References RTC_CRH, RTC_CRH_ALRIE, rtc_enter_config_mode(), and rtc_exit_config_mode().
void rtc_enable_alarm (void)
Definition at line 137 of file rtc.c.
References RTC_CRH, RTC_CRH_ALRIE, rtc_enter_config_mode(), and rtc_exit_config_mode().
void rtc_enter_config_mode (void)
Definition at line 107 of file rtc.c.
References RTC_CRL, RTC_CRL_CNF, and RTC_CRL_RTOFF.
Referenced by rtc_disable_alarm(), rtc_enable_alarm(), rtc_interrupt_disable(), rtc_interrupt_enable(), rtc_set_alarm_time(), rtc_set_counter_val(), and rtc_set_prescale_val().
void rtc_exit_config_mode (void)
Definition at line 118 of file rtc.c.
References RTC_CRL, RTC_CRL_CNF, and RTC_CRL_RTOFF.
Referenced by rtc_disable_alarm(), rtc_enable_alarm(), rtc_interrupt_disable(), rtc_interrupt_enable(), rtc_set_alarm_time(), rtc_set_counter_val(), and rtc_set_prescale_val().
uint32_t rtc_get_alarm_val (void)
Definition at line 169 of file rtc.c.
References RTC_ALRH, and RTC_ALRL.
uint32_t rtc_get_counter_val (void)
Definition at line 159 of file rtc.c.
References RTC_CNTH, and RTC_CNTL.
uint32_t rtc_get_prescale_div_val (void)
Definition at line 164 of file rtc.c.
References RTC_DIVH, and RTC_DIVL.
void rtc_interrupt_disable (rtcflag_t flag_val)
Definition at line 202 of file rtc.c.
References RTC_ALR, RTC_CRH, RTC_CRH_ALRIE, RTC_CRH_OWIE, RTC_CRH_SECIE, rtc_enter_config_mode(), rtc_exit_config_mode(), RTC_OW, and RTC_SEC.
void rtc_interrupt_enable (rtcflag_t flag_val)
Definition at line 182 of file rtc.c.
References RTC_ALR, RTC_CRH, RTC_CRH_ALRIE, RTC_CRH_OWIE, RTC_CRH_SECIE, rtc_enter_config_mode(), rtc_exit_config_mode(), RTC_OW, and RTC_SEC.
void rtc_set_alarm_time (uint32_t alarm_time)
Definition at line 129 of file rtc.c.
References RTC_ALRH, RTC_ALRL, rtc_enter_config_mode(), and rtc_exit_config_mode().
void rtc_set_counter_val (uint32_t counter_val)
Definition at line 174 of file rtc.c.
References RTC_CNTH, RTC_CNTL, rtc_enter_config_mode(), and rtc_exit_config_mode().
void rtc_set_prescale_val (uint32_t prescale_val)
Definition at line 151 of file rtc.c.
References rtc_enter_config_mode(), rtc_exit_config_mode(), RTC_PRLH, and RTC_PRLL.
Referenced by rtc_auto_awake().