libopencm3: flash_common_f24.h File Reference
flash_common_f24.h File Reference
#include <libopencm3/cm3/common.h>
#include <libopencm3/stm32/common/flash_common_f234.h>
Macros
#define FLASH_OPTCR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x14)
#define FLASH_ACR_DCRST (1 << 12)
#define FLASH_ACR_ICRST (1 << 11)
#define FLASH_ACR_DCE (1 << 10)
#define FLASH_ACR_ICE (1 << 9)
#define FLASH_ACR_PRFTEN (1 << 8)
#define FLASH_SR_BSY (1 << 16)
#define FLASH_SR_PGSERR (1 << 7)
#define FLASH_SR_PGPERR (1 << 6)
#define FLASH_SR_PGAERR (1 << 5)
#define FLASH_SR_WRPERR (1 << 4)
#define FLASH_SR_OPERR (1 << 1)
#define FLASH_SR_EOP (1 << 0)
#define FLASH_CR_LOCK (1 << 31)
#define FLASH_CR_ERRIE (1 << 25)
#define FLASH_CR_EOPIE (1 << 24)
#define FLASH_CR_STRT (1 << 16)
#define FLASH_CR_MER (1 << 2)
#define FLASH_CR_SER (1 << 1)
#define FLASH_CR_PG (1 << 0)
#define FLASH_CR_SECTOR_0 (0x00 << 3)
#define FLASH_CR_SECTOR_1 (0x01 << 3)
#define FLASH_CR_SECTOR_2 (0x02 << 3)
#define FLASH_CR_SECTOR_3 (0x03 << 3)
#define FLASH_CR_SECTOR_4 (0x04 << 3)
#define FLASH_CR_SECTOR_5 (0x05 << 3)
#define FLASH_CR_SECTOR_6 (0x06 << 3)
#define FLASH_CR_SECTOR_7 (0x07 << 3)
#define FLASH_CR_SECTOR_8 (0x08 << 3)
#define FLASH_CR_SECTOR_9 (0x09 << 3)
#define FLASH_CR_SECTOR_10 (0x0a << 3)
#define FLASH_CR_SECTOR_11 (0x0b << 3)
#define FLASH_CR_PROGRAM_X8 (0x00 << 8)
#define FLASH_CR_PROGRAM_X16 (0x01 << 8)
#define FLASH_CR_PROGRAM_X32 (0x02 << 8)
#define FLASH_CR_PROGRAM_X64 (0x03 << 8)
#define FLASH_OPTCR_NRST_STDBY (1 << 7)
#define FLASH_OPTCR_NRST_STOP (1 << 6)
#define FLASH_OPTCR_WDG_SW (1 << 5)
#define FLASH_OPTCR_OPTSTRT (1 << 1)
#define FLASH_OPTCR_OPTLOCK (1 << 0)
#define FLASH_OPTCR_BOR_LEVEL_3 (0x00 << 2)
#define FLASH_OPTCR_BOR_LEVEL_2 (0x01 << 2)
#define FLASH_OPTCR_BOR_LEVEL_1 (0x02 << 2)
#define FLASH_OPTCR_BOR_OFF (0x03 << 2)
#define FLASH_OPTKEYR_KEY1 ((uint32_t)0x08192a3b)
#define FLASH_OPTKEYR_KEY2 ((uint32_t)0x4c5d6e7f)
Functions
void flash_unlock_option_bytes (void)
void flash_lock_option_bytes (void)
void flash_clear_pgserr_flag (void)
void flash_clear_wrperr_flag (void)
void flash_clear_pgaerr_flag (void)
void flash_dcache_enable (void)
void flash_dcache_disable (void)
void flash_icache_enable (void)
void flash_icache_disable (void)
void flash_prefetch_enable (void)
void flash_prefetch_disable (void)
void flash_dcache_reset (void)
void flash_icache_reset (void)
void flash_erase_all_sectors (uint32_t program_size)
void flash_erase_sector (uint8_t sector, uint32_t program_size)
void flash_program_double_word (uint32_t address, uint64_t data)
void flash_program_word (uint32_t address, uint32_t data)
void flash_program_half_word (uint32_t address, uint16_t data)
void flash_program_byte (uint32_t address, uint8_t data)
void flash_program (uint32_t address, uint8_t *data, uint32_t len)
void flash_program_option_bytes (uint32_t data)
Macro Definition Documentation
#define FLASH_ACR_DCE (1 << 10)
Definition at line 45 of file flash_common_f24.h.
Referenced by flash_dcache_disable(), and flash_dcache_enable().
#define FLASH_ACR_DCRST (1 << 12)
Definition at line 43 of file flash_common_f24.h.
Referenced by flash_dcache_reset().
#define FLASH_ACR_ICE (1 << 9)
Definition at line 46 of file flash_common_f24.h.
Referenced by flash_icache_disable(), and flash_icache_enable().
#define FLASH_ACR_ICRST (1 << 11)
Definition at line 44 of file flash_common_f24.h.
Referenced by flash_icache_reset().
#define FLASH_ACR_PRFTEN (1 << 8)
Definition at line 47 of file flash_common_f24.h.
Referenced by flash_prefetch_disable(), and flash_prefetch_enable().
#define FLASH_CR_EOPIE (1 << 24)
Definition at line 63 of file flash_common_f24.h.
#define FLASH_CR_ERRIE (1 << 25)
Definition at line 62 of file flash_common_f24.h.
#define FLASH_CR_LOCK (1 << 31)
Definition at line 61 of file flash_common_f24.h.
Referenced by flash_lock(), and flash_unlock().
#define FLASH_CR_MER (1 << 2)
Definition at line 65 of file flash_common_f24.h.
Referenced by flash_erase_all_sectors().
#define FLASH_CR_PG (1 << 0)
Definition at line 67 of file flash_common_f24.h.
Referenced by flash_program_byte(), flash_program_double_word(), flash_program_half_word(), and flash_program_word().
#define FLASH_CR_PROGRAM_X16 (0x01 << 8)
Definition at line 81 of file flash_common_f24.h.
Referenced by flash_program_half_word().
#define FLASH_CR_PROGRAM_X32 (0x02 << 8)
Definition at line 82 of file flash_common_f24.h.
Referenced by flash_program_word().
#define FLASH_CR_PROGRAM_X64 (0x03 << 8)
Definition at line 83 of file flash_common_f24.h.
Referenced by flash_program_double_word().
#define FLASH_CR_PROGRAM_X8 (0x00 << 8)
Definition at line 80 of file flash_common_f24.h.
Referenced by flash_program_byte().
#define FLASH_CR_SECTOR_0 (0x00 << 3)
Definition at line 68 of file flash_common_f24.h.
#define FLASH_CR_SECTOR_1 (0x01 << 3)
Definition at line 69 of file flash_common_f24.h.
#define FLASH_CR_SECTOR_10 (0x0a << 3)
Definition at line 78 of file flash_common_f24.h.
#define FLASH_CR_SECTOR_11 (0x0b << 3)
Definition at line 79 of file flash_common_f24.h.
#define FLASH_CR_SECTOR_2 (0x02 << 3)
Definition at line 70 of file flash_common_f24.h.
#define FLASH_CR_SECTOR_3 (0x03 << 3)
Definition at line 71 of file flash_common_f24.h.
#define FLASH_CR_SECTOR_4 (0x04 << 3)
Definition at line 72 of file flash_common_f24.h.
#define FLASH_CR_SECTOR_5 (0x05 << 3)
Definition at line 73 of file flash_common_f24.h.
#define FLASH_CR_SECTOR_6 (0x06 << 3)
Definition at line 74 of file flash_common_f24.h.
#define FLASH_CR_SECTOR_7 (0x07 << 3)
Definition at line 75 of file flash_common_f24.h.
#define FLASH_CR_SECTOR_8 (0x08 << 3)
Definition at line 76 of file flash_common_f24.h.
#define FLASH_CR_SECTOR_9 (0x09 << 3)
Definition at line 77 of file flash_common_f24.h.
#define FLASH_CR_SER (1 << 1)
Definition at line 66 of file flash_common_f24.h.
Referenced by flash_erase_sector().
#define FLASH_CR_STRT (1 << 16)
Definition at line 64 of file flash_common_f24.h.
Referenced by flash_erase_all_sectors(), and flash_erase_sector().
#define FLASH_OPTCR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x14)
Definition at line 39 of file flash_common_f24.h.
Referenced by flash_lock_option_bytes(), flash_program_option_bytes(), and flash_unlock_option_bytes().
#define FLASH_OPTCR_BOR_LEVEL_1 (0x02 << 2)
Definition at line 96 of file flash_common_f24.h.
#define FLASH_OPTCR_BOR_LEVEL_2 (0x01 << 2)
Definition at line 95 of file flash_common_f24.h.
#define FLASH_OPTCR_BOR_LEVEL_3 (0x00 << 2)
Definition at line 94 of file flash_common_f24.h.
#define FLASH_OPTCR_BOR_OFF (0x03 << 2)
Definition at line 97 of file flash_common_f24.h.
#define FLASH_OPTCR_NRST_STDBY (1 << 7)
Definition at line 89 of file flash_common_f24.h.
#define FLASH_OPTCR_NRST_STOP (1 << 6)
Definition at line 90 of file flash_common_f24.h.
#define FLASH_OPTCR_OPTLOCK (1 << 0)
Definition at line 93 of file flash_common_f24.h.
Referenced by flash_lock_option_bytes(), flash_program_option_bytes(), and flash_unlock_option_bytes().
#define FLASH_OPTCR_OPTSTRT (1 << 1)
Definition at line 92 of file flash_common_f24.h.
Referenced by flash_program_option_bytes().
#define FLASH_OPTCR_WDG_SW (1 << 5)
Definition at line 91 of file flash_common_f24.h.
#define FLASH_OPTKEYR_KEY1 ((uint32_t)0x08192a3b)
Definition at line 101 of file flash_common_f24.h.
Referenced by flash_unlock_option_bytes().
#define FLASH_OPTKEYR_KEY2 ((uint32_t)0x4c5d6e7f)
Definition at line 102 of file flash_common_f24.h.
Referenced by flash_unlock_option_bytes().
#define FLASH_SR_BSY (1 << 16)
Definition at line 51 of file flash_common_f24.h.
Referenced by flash_clear_bsy_flag(), and flash_wait_for_last_operation().
#define FLASH_SR_EOP (1 << 0)
Definition at line 57 of file flash_common_f24.h.
Referenced by flash_clear_eop_flag().
#define FLASH_SR_OPERR (1 << 1)
Definition at line 56 of file flash_common_f24.h.
#define FLASH_SR_PGAERR (1 << 5)
Definition at line 54 of file flash_common_f24.h.
Referenced by flash_clear_pgaerr_flag().
#define FLASH_SR_PGPERR (1 << 6)
Definition at line 53 of file flash_common_f24.h.
Referenced by flash_clear_pgperr_flag().
#define FLASH_SR_PGSERR (1 << 7)
Definition at line 52 of file flash_common_f24.h.
Referenced by flash_clear_pgserr_flag().
#define FLASH_SR_WRPERR (1 << 4)
Definition at line 55 of file flash_common_f24.h.
Referenced by flash_clear_wrperr_flag().
Function Documentation
void flash_clear_pgaerr_flag (void)
Definition at line 74 of file flash_common_f24.c.
References FLASH_SR, and FLASH_SR_PGAERR.
Referenced by flash_clear_status_flags().
void flash_clear_pgserr_flag (void)
Definition at line 69 of file flash_common_f24.c.
References FLASH_SR, and FLASH_SR_PGSERR.
Referenced by flash_clear_status_flags().
void flash_clear_wrperr_flag (void)
Definition at line 79 of file flash_common_f24.c.
References FLASH_SR, and FLASH_SR_WRPERR.
Referenced by flash_clear_status_flags().
void flash_dcache_disable (void)
Definition at line 34 of file flash_common_f24.c.
References FLASH_ACR, and FLASH_ACR_DCE.
void flash_dcache_enable (void)
Definition at line 29 of file flash_common_f24.c.
References FLASH_ACR, and FLASH_ACR_DCE.
void flash_dcache_reset (void)
Definition at line 59 of file flash_common_f24.c.
References FLASH_ACR, and FLASH_ACR_DCRST.
void flash_erase_all_sectors (uint32_t program_size)
Definition at line 201 of file flash_common_f24.c.
References FLASH_CR, FLASH_CR_MER, FLASH_CR_STRT, flash_set_program_size(), and flash_wait_for_last_operation().
void flash_erase_sector (uint8_t sector, uint32_t program_size)
Definition at line 186 of file flash_common_f24.c.
References FLASH_CR, FLASH_CR_SER, FLASH_CR_STRT, flash_set_program_size(), and flash_wait_for_last_operation().
void flash_icache_disable (void)
Definition at line 44 of file flash_common_f24.c.
References FLASH_ACR, and FLASH_ACR_ICE.
void flash_icache_enable (void)
Definition at line 39 of file flash_common_f24.c.
References FLASH_ACR, and FLASH_ACR_ICE.
void flash_icache_reset (void)
Definition at line 64 of file flash_common_f24.c.
References FLASH_ACR, and FLASH_ACR_ICRST.
void flash_lock_option_bytes (void)
Definition at line 104 of file flash_common_f24.c.
References FLASH_OPTCR, and FLASH_OPTCR_OPTLOCK.
void flash_prefetch_disable (void)
Definition at line 54 of file flash_common_f24.c.
References FLASH_ACR, and FLASH_ACR_PRFTEN.
void flash_prefetch_enable (void)
Definition at line 49 of file flash_common_f24.c.
References FLASH_ACR, and FLASH_ACR_PRFTEN.
void flash_program (uint32_t address, uint8_t * data, uint32_t len)
Definition at line 175 of file flash_common_f24.c.
References flash_program_byte().
void flash_program_byte (uint32_t address, uint8_t data)
Definition at line 161 of file flash_common_f24.c.
References FLASH_CR, FLASH_CR_PG, FLASH_CR_PROGRAM_X8, flash_set_program_size(), flash_wait_for_last_operation(), and MMIO8.
Referenced by flash_program().
void flash_program_double_word (uint32_t address, uint64_t data)
Definition at line 109 of file flash_common_f24.c.
References FLASH_CR, FLASH_CR_PG, FLASH_CR_PROGRAM_X64, flash_set_program_size(), flash_wait_for_last_operation(), and MMIO64.
void flash_program_half_word (uint32_t address, uint16_t data)
Definition at line 147 of file flash_common_f24.c.
References FLASH_CR, FLASH_CR_PG, FLASH_CR_PROGRAM_X16, flash_set_program_size(), flash_wait_for_last_operation(), and MMIO16.
void flash_program_option_bytes (uint32_t data)
Definition at line 213 of file flash_common_f24.c.
References FLASH_OPTCR, FLASH_OPTCR_OPTLOCK, FLASH_OPTCR_OPTSTRT, flash_unlock_option_bytes(), and flash_wait_for_last_operation().
void flash_program_word (uint32_t address, uint32_t data)
Definition at line 128 of file flash_common_f24.c.
References FLASH_CR, FLASH_CR_PG, FLASH_CR_PROGRAM_X32, flash_set_program_size(), flash_wait_for_last_operation(), and MMIO32.
void flash_unlock_option_bytes (void)
Definition at line 94 of file flash_common_f24.c.
References FLASH_OPTCR, FLASH_OPTCR_OPTLOCK, FLASH_OPTKEYR, FLASH_OPTKEYR_KEY1, and FLASH_OPTKEYR_KEY2.
Referenced by flash_program_option_bytes().