libopencm3: flash_common_f24.c File Reference
flash_common_f24.c File Reference
#include <libopencm3/stm32/flash.h>
Functions
static void flash_set_program_size (uint32_t psize)
void flash_dcache_enable (void)
void flash_dcache_disable (void)
void flash_icache_enable (void)
void flash_icache_disable (void)
void flash_prefetch_enable (void)
void flash_prefetch_disable (void)
void flash_dcache_reset (void)
void flash_icache_reset (void)
void flash_set_ws (uint32_t ws)
void flash_unlock (void)
void flash_lock (void)
void flash_clear_pgserr_flag (void)
void flash_clear_pgperr_flag (void)
void flash_clear_pgaerr_flag (void)
void flash_clear_eop_flag (void)
void flash_clear_wrperr_flag (void)
void flash_clear_bsy_flag (void)
void flash_clear_status_flags (void)
void flash_unlock_option_bytes (void)
void flash_lock_option_bytes (void)
void flash_wait_for_last_operation (void)
void flash_program_double_word (uint32_t address, uint64_t data)
void flash_program_word (uint32_t address, uint32_t data)
void flash_program_half_word (uint32_t address, uint16_t data)
void flash_program_byte (uint32_t address, uint8_t data)
void flash_program (uint32_t address, uint8_t *data, uint32_t len)
void flash_erase_sector (uint8_t sector, uint32_t program_size)
void flash_erase_all_sectors (uint32_t program_size)
void flash_program_option_bytes (uint32_t data)
Function Documentation
void flash_clear_bsy_flag (void)
Definition at line 119 of file flash_common_f24.c.
Referenced by flash_clear_status_flags().
void flash_clear_eop_flag (void)
Definition at line 109 of file flash_common_f24.c.
Referenced by flash_clear_status_flags().
void flash_clear_pgaerr_flag (void)
Definition at line 104 of file flash_common_f24.c.
Referenced by flash_clear_status_flags().
void flash_clear_pgperr_flag (void)
Definition at line 99 of file flash_common_f24.c.
Referenced by flash_clear_status_flags().
void flash_clear_pgserr_flag (void)
Definition at line 94 of file flash_common_f24.c.
Referenced by flash_clear_status_flags().
void flash_clear_status_flags (void)
Definition at line 124 of file flash_common_f24.c.
References flash_clear_bsy_flag(), flash_clear_eop_flag(), flash_clear_pgaerr_flag(), flash_clear_pgperr_flag(), flash_clear_pgserr_flag(), and flash_clear_wrperr_flag().
void flash_clear_wrperr_flag (void)
Definition at line 114 of file flash_common_f24.c.
Referenced by flash_clear_status_flags().
void flash_dcache_disable (void)
Definition at line 34 of file flash_common_f24.c.
void flash_dcache_enable (void)
Definition at line 29 of file flash_common_f24.c.
void flash_dcache_reset (void)
Definition at line 59 of file flash_common_f24.c.
void flash_erase_all_sectors (uint32_t program_size)
Definition at line 246 of file flash_common_f24.c.
References flash_set_program_size(), and flash_wait_for_last_operation().
void flash_erase_sector (uint8_t sector, uint32_t program_size)
Definition at line 231 of file flash_common_f24.c.
References flash_set_program_size(), and flash_wait_for_last_operation().
void flash_icache_disable (void)
Definition at line 44 of file flash_common_f24.c.
void flash_icache_enable (void)
Definition at line 39 of file flash_common_f24.c.
void flash_icache_reset (void)
Definition at line 64 of file flash_common_f24.c.
void flash_lock (void)
Definition at line 89 of file flash_common_f24.c.
void flash_lock_option_bytes (void)
Definition at line 144 of file flash_common_f24.c.
void flash_prefetch_disable (void)
Definition at line 54 of file flash_common_f24.c.
void flash_prefetch_enable (void)
Definition at line 49 of file flash_common_f24.c.
void flash_program (uint32_t address, uint8_t * data, uint32_t len)
Definition at line 220 of file flash_common_f24.c.
References flash_program_byte().
void flash_program_byte (uint32_t address, uint8_t data)
Definition at line 206 of file flash_common_f24.c.
References flash_set_program_size(), flash_wait_for_last_operation(), and MMIO8.
Referenced by flash_program().
void flash_program_double_word (uint32_t address, uint64_t data)
Definition at line 154 of file flash_common_f24.c.
References flash_set_program_size(), flash_wait_for_last_operation(), and MMIO64.
void flash_program_half_word (uint32_t address, uint16_t data)
Definition at line 192 of file flash_common_f24.c.
References flash_set_program_size(), flash_wait_for_last_operation(), and MMIO16.
void flash_program_option_bytes (uint32_t data)
Definition at line 258 of file flash_common_f24.c.
References flash_unlock_option_bytes(), and flash_wait_for_last_operation().
void flash_program_word (uint32_t address, uint32_t data)
Definition at line 173 of file flash_common_f24.c.
References flash_set_program_size(), flash_wait_for_last_operation(), and MMIO32.
static void flash_set_program_size (uint32_t psize) inline static
Definition at line 23 of file flash_common_f24.c.
Referenced by flash_erase_all_sectors(), flash_erase_sector(), flash_program_byte(), flash_program_double_word(), flash_program_half_word(), and flash_program_word().
void flash_set_ws (uint32_t ws)
Definition at line 69 of file flash_common_f24.c.
Referenced by rcc_clock_setup_hse_3v3().
void flash_unlock (void)
Definition at line 79 of file flash_common_f24.c.
void flash_unlock_option_bytes (void)
Definition at line 134 of file flash_common_f24.c.
Referenced by flash_program_option_bytes().
void flash_wait_for_last_operation (void)
Definition at line 149 of file flash_common_f24.c.
Referenced by flash_erase_all_sectors(), flash_erase_sector(), flash_program_byte(), flash_program_double_word(), flash_program_half_word(), flash_program_option_bytes(), and flash_program_word().