libopencm3: SPI
SPI
STM32F2xx
libopencm3 STM32F2xx SPI
Functions
void spi_reset (u32 spi_peripheral)
SPI Reset.
int spi_init_master (u32 spi, u32 br, u32 cpol, u32 cpha, u32 dff, u32 lsbfirst)
Configure the SPI as Master.
void spi_enable (u32 spi)
SPI Enable.
void spi_disable (u32 spi)
SPI Disable.
void spi_write (u32 spi, u16 data)
SPI Data Write.
void spi_send (u32 spi, u16 data)
SPI Data Write with Blocking.
u16 spi_read (u32 spi)
SPI Data Read.
u16 spi_xfer (u32 spi, u16 data)
SPI Data Write and Read Exchange.
void spi_set_bidirectional_mode (u32 spi)
SPI Set Bidirectional Simplex Mode.
void spi_set_unidirectional_mode (u32 spi)
SPI Set Unidirectional Mode.
void spi_set_bidirectional_receive_only_mode (u32 spi)
SPI Set Bidirectional Simplex Receive Only Mode.
void spi_set_bidirectional_transmit_only_mode (u32 spi)
SPI Set Bidirectional Simplex Receive Only Mode.
void spi_enable_crc (u32 spi)
SPI Enable the CRC.
void spi_disable_crc (u32 spi)
SPI Disable the CRC.
void spi_set_next_tx_from_buffer (u32 spi)
SPI Next Transmit is a Data Word.
void spi_set_next_tx_from_crc (u32 spi)
SPI Next Transmit is a CRC Word.
void spi_set_dff_8bit (u32 spi)
SPI Set Data Frame Format to 8 bits.
void spi_set_dff_16bit (u32 spi)
SPI Set Data Frame Format to 16 bits.
void spi_set_full_duplex_mode (u32 spi)
SPI Set Full Duplex (3-wire) Mode.
void spi_set_receive_only_mode (u32 spi)
SPI Set Receive Only Mode for Simplex (2-wire) Unidirectional Transfers.
void spi_disable_software_slave_management (u32 spi)
SPI Enable Slave Management by Hardware.
void spi_enable_software_slave_management (u32 spi)
SPI Enable Slave Management by Software.
void spi_set_nss_high (u32 spi)
SPI Set the Software NSS Signal High.
void spi_set_nss_low (u32 spi)
SPI Set the Software NSS Signal Low.
void spi_send_lsb_first (u32 spi)
SPI Set to Send LSB First.
void spi_send_msb_first (u32 spi)
SPI Set to Send MSB First.
void spi_set_baudrate_prescaler (u32 spi, u8 baudrate)
SPI Set the Baudrate Prescaler.
void spi_set_master_mode (u32 spi)
SPI Set to Master Mode.
void spi_set_slave_mode (u32 spi)
SPI Set to Slave Mode.
void spi_set_clock_polarity_1 (u32 spi)
SPI Set the Clock Polarity to High when Idle.
void spi_set_clock_polarity_0 (u32 spi)
SPI Set the Clock Polarity to Low when Idle.
void spi_set_clock_phase_1 (u32 spi)
SPI Set the Clock Phase to Capture on Trailing Edge.
void spi_set_clock_phase_0 (u32 spi)
SPI Set the Clock Phase to Capture on Leading Edge.
void spi_enable_tx_buffer_empty_interrupt (u32 spi)
SPI Enable the Transmit Buffer Empty Interrupt.
void spi_disable_tx_buffer_empty_interrupt (u32 spi)
SPI Disable the Transmit Buffer Empty Interrupt.
void spi_enable_rx_buffer_not_empty_interrupt (u32 spi)
SPI Enable the Receive Buffer Ready Interrupt.
void spi_disable_rx_buffer_not_empty_interrupt (u32 spi)
SPI Disable the Receive Buffer Ready Interrupt.
void spi_enable_error_interrupt (u32 spi)
SPI Enable the Error Interrupt.
void spi_disable_error_interrupt (u32 spi)
SPI Disable the Error Interrupt.
void spi_enable_ss_output (u32 spi)
SPI Set the NSS Pin as an Output.
void spi_disable_ss_output (u32 spi)
SPI Set the NSS Pin as an Input.
void spi_enable_tx_dma (u32 spi)
SPI Enable Transmit Transfers via DMA.
void spi_disable_tx_dma (u32 spi)
SPI Disable Transmit Transfers via DMA.
void spi_enable_rx_dma (u32 spi)
SPI Enable Receive Transfers via DMA.
void spi_disable_rx_dma (u32 spi)
SPI Disable Receive Transfers via DMA.
Detailed Description
libopencm3 STM32F2xx SPI
Version
1.0.0
Author
© 2009 Uwe Hermann uwe@h.nosp@m.erma.nosp@m.nn-uw.nosp@m.e.de
© 2012 Ken Sarkies ksark.nosp@m.ies@.nosp@m.inter.nosp@m.node.nosp@m..on.n.nosp@m.et
Date
15 October 2012
Devices can have up to three SPI peripherals. The common 4-wire full-duplex mode of operation is supported, along with 3-wire variants using unidirectional communication modes or half-duplex bidirectional communication. A variety of options allows many of the SPI variants to be supported. Multimaster operation is also supported. A CRC can be generated and checked in hardware.
Note
Some JTAG pins need to be remapped if SPI is to be used.
The I2S protocol shares the SPI hardware so the two protocols cannot be used at the same time on the same peripheral.
Example: 1Mbps, positive clock polarity, leading edge trigger, 8-bit words, LSB first.
spi_init_master(SPI1, 1000000, SPI_CR1_CPOL_CLK_TO_0_WHEN_IDLE,
                SPI_CR1_CPHA_CLK_TRANSITION_1, SPI_CR1_DFF_8BIT,
                SPI_CR1_LSBFIRST);
spi_write(SPI1, 0x55);          // 8-bit write
spi_write(SPI1, 0xaa88);        // 16-bit write
reg8 = spi_read(SPI1);          // 8-bit read
reg16 = spi_read(SPI1);         // 16-bit read
LGPL License Terms libopencm3 License
Function Documentation
void spi_disable (u32 spi)
SPI Disable.
The SPI peripheral is disabled.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 172 of file spi_common_all.c.
References SPI_CR1, and SPI_CR1_SPE.
void spi_disable_crc (u32 spi)
SPI Disable the CRC.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 335 of file spi_common_all.c.
References SPI_CR1, and SPI_CR1_CRCEN.
void spi_disable_error_interrupt (u32 spi)
SPI Disable the Error Interrupt.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 641 of file spi_common_all.c.
References SPI_CR2, and SPI_CR2_ERRIE.
void spi_disable_rx_buffer_not_empty_interrupt (u32 spi)
SPI Disable the Receive Buffer Ready Interrupt.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 619 of file spi_common_all.c.
References SPI_CR2, and SPI_CR2_RXNEIE.
void spi_disable_rx_dma (u32 spi)
SPI Disable Receive Transfers via DMA.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 722 of file spi_common_all.c.
References SPI_CR2, and SPI_CR2_RXDMAEN.
void spi_disable_software_slave_management (u32 spi)
SPI Enable Slave Management by Hardware.
In slave mode the NSS hardware input is used as a select enable for the slave.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 422 of file spi_common_all.c.
References SPI_CR1, and SPI_CR1_SSM.
void spi_disable_ss_output (u32 spi)
SPI Set the NSS Pin as an Input.
In master mode this allows the master to sense the presence of other masters. If NSS is then pulled low the master is placed into slave mode. In slave mode NSS becomes a slave enable.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 670 of file spi_common_all.c.
References SPI_CR2, and SPI_CR2_SSOE.
void spi_disable_tx_buffer_empty_interrupt (u32 spi)
SPI Disable the Transmit Buffer Empty Interrupt.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 597 of file spi_common_all.c.
References SPI_CR2, and SPI_CR2_TXEIE.
void spi_disable_tx_dma (u32 spi)
SPI Disable Transmit Transfers via DMA.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 696 of file spi_common_all.c.
References SPI_CR2, and SPI_CR2_TXDMAEN.
void spi_enable (u32 spi)
SPI Enable.
The SPI peripheral is enabled.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 155 of file spi_common_all.c.
References SPI_CR1, and SPI_CR1_SPE.
void spi_enable_crc (u32 spi)
SPI Enable the CRC.
The SPI peripheral is set to use a CRC field for transmit and receive.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 324 of file spi_common_all.c.
References SPI_CR1, and SPI_CR1_CRCEN.
void spi_enable_error_interrupt (u32 spi)
SPI Enable the Error Interrupt.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 630 of file spi_common_all.c.
References SPI_CR2, and SPI_CR2_ERRIE.
void spi_enable_rx_buffer_not_empty_interrupt (u32 spi)
SPI Enable the Receive Buffer Ready Interrupt.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 608 of file spi_common_all.c.
References SPI_CR2, and SPI_CR2_RXNEIE.
void spi_enable_rx_dma (u32 spi)
SPI Enable Receive Transfers via DMA.
This allows received data streams to proceed unattended using DMA to move data from the receive buffer as data becomes available. The DMA channels provided for each SPI peripheral are given in the Technical Manual DMA section.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 711 of file spi_common_all.c.
References SPI_CR2, and SPI_CR2_RXDMAEN.
void spi_enable_software_slave_management (u32 spi)
SPI Enable Slave Management by Software.
In slave mode the NSS hardware input is replaced by an internal software enable/disable of the slave (spi_set_nss_high).
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 436 of file spi_common_all.c.
References SPI_CR1, and SPI_CR1_SSM.
void spi_enable_ss_output (u32 spi)
SPI Set the NSS Pin as an Output.
Normally used in master mode to allows the master to place all devices on the SPI bus into slave mode. Multimaster mode is not possible.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 655 of file spi_common_all.c.
References SPI_CR2, and SPI_CR2_SSOE.
void spi_enable_tx_buffer_empty_interrupt (u32 spi)
SPI Enable the Transmit Buffer Empty Interrupt.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 586 of file spi_common_all.c.
References SPI_CR2, and SPI_CR2_TXEIE.
void spi_enable_tx_dma (u32 spi)
SPI Enable Transmit Transfers via DMA.
This allows transmissions to proceed unattended using DMA to move data to the transmit buffer as it becomes available. The DMA channels provided for each SPI peripheral are given in the Technical Manual DMA section.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 685 of file spi_common_all.c.
References SPI_CR2, and SPI_CR2_TXDMAEN.
int spi_init_master (u32 spi, u32 br, u32 cpol, u32 cpha, u32 dff, u32 lsbfirst)
Configure the SPI as Master.
The SPI peripheral is configured as a master with communication parameters baudrate, data format 8/16 bits, frame format lsb/msb first, clock polarity and phase. The SPI enable, CRC enable and CRC next controls are not affected. These must be controlled separately.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
[in] br Unsigned int32. Baudrate SPI peripheral baud rates.
[in] cpol Unsigned int32. Clock polarity SPI clock polarity.
[in] cpha Unsigned int32. Clock Phase SPI clock phase.
[in] dff Unsigned int32. Data frame format 8/16 bits SPI data frame format.
[in] lsbfirst Unsigned int32. Frame format lsb/msb first SPI lsb/msb first.
Returns
int. Error code.
Definition at line 122 of file spi_common_all.c.
References SPI_CR1, SPI_CR1_CRCEN, SPI_CR1_CRCNEXT, SPI_CR1_MSTR, and SPI_CR1_SPE.
u16 spi_read (u32 spi)
SPI Data Read.
Data is read from the SPI interface after the incoming transfer has finished.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Returns
data Unsigned int16. 8 or 16 bit data.
Definition at line 224 of file spi_common_all.c.
References SPI_DR, SPI_SR, and SPI_SR_RXNE.
void spi_reset (u32 spi_peripheral)
SPI Reset.
The SPI peripheral and all its associated configuration registers are placed in the reset condition. The reset is effected via the RCC peripheral reset system.
Parameters
[in] spi_peripheral Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 83 of file spi_common_all.c.
References RCC_APB1RSTR, RCC_APB1RSTR_SPI2RST, RCC_APB1RSTR_SPI3RST, RCC_APB2RSTR, RCC_APB2RSTR_SPI1RST, rcc_peripheral_clear_reset(), rcc_peripheral_reset(), SPI1, SPI2, and SPI3.
void spi_send (u32 spi, u16 data)
SPI Data Write with Blocking.
Data is written to the SPI interface after the previous write transfer has finished.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
[in] data Unsigned int16. 8 or 16 bit data to be written.
Definition at line 205 of file spi_common_all.c.
References SPI_DR, SPI_SR, and SPI_SR_TXE.
void spi_send_lsb_first (u32 spi)
SPI Set to Send LSB First.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 477 of file spi_common_all.c.
References SPI_CR1, and SPI_CR1_LSBFIRST.
void spi_send_msb_first (u32 spi)
SPI Set to Send MSB First.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 488 of file spi_common_all.c.
References SPI_CR1, and SPI_CR1_LSBFIRST.
void spi_set_baudrate_prescaler (u32 spi, u8 baudrate)
SPI Set the Baudrate Prescaler.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
[in] baudrate Unsigned int8. Baudrate prescale value SPI peripheral baud rate prescale values.
Definition at line 502 of file spi_common_all.c.
References SPI_CR1.
void spi_set_bidirectional_mode (u32 spi)
SPI Set Bidirectional Simplex Mode.
The SPI peripheral is set for bidirectional transfers in two-wire simplex mode (using a clock wire and a bidirectional data wire).
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 266 of file spi_common_all.c.
References SPI_CR1, and SPI_CR1_BIDIMODE.
void spi_set_bidirectional_receive_only_mode (u32 spi)
SPI Set Bidirectional Simplex Receive Only Mode.
The SPI peripheral is set for bidirectional transfers in two-wire simplex mode (using a clock wire and a bidirectional data wire), and is placed in a receive state.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 295 of file spi_common_all.c.
References SPI_CR1, SPI_CR1_BIDIMODE, and SPI_CR1_BIDIOE.
void spi_set_bidirectional_transmit_only_mode (u32 spi)
SPI Set Bidirectional Simplex Receive Only Mode.
The SPI peripheral is set for bidirectional transfers in two-wire simplex mode (using a clock wire and a bidirectional data wire), and is placed in a transmit state.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 310 of file spi_common_all.c.
References SPI_CR1, SPI_CR1_BIDIMODE, and SPI_CR1_BIDIOE.
void spi_set_clock_phase_0 (u32 spi)
SPI Set the Clock Phase to Capture on Leading Edge.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 575 of file spi_common_all.c.
References SPI_CR1, and SPI_CR1_CPHA.
void spi_set_clock_phase_1 (u32 spi)
SPI Set the Clock Phase to Capture on Trailing Edge.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 564 of file spi_common_all.c.
References SPI_CR1, and SPI_CR1_CPHA.
void spi_set_clock_polarity_0 (u32 spi)
SPI Set the Clock Polarity to Low when Idle.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 553 of file spi_common_all.c.
References SPI_CR1, and SPI_CR1_CPOL.
void spi_set_clock_polarity_1 (u32 spi)
SPI Set the Clock Polarity to High when Idle.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 542 of file spi_common_all.c.
References SPI_CR1, and SPI_CR1_CPOL.
void spi_set_dff_16bit (u32 spi)
SPI Set Data Frame Format to 16 bits.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 387 of file spi_common_all.c.
References SPI_CR1, and SPI_CR1_DFF.
void spi_set_dff_8bit (u32 spi)
SPI Set Data Frame Format to 8 bits.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 376 of file spi_common_all.c.
References SPI_CR1, and SPI_CR1_DFF.
void spi_set_full_duplex_mode (u32 spi)
SPI Set Full Duplex (3-wire) Mode.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 398 of file spi_common_all.c.
References SPI_CR1, and SPI_CR1_RXONLY.
void spi_set_master_mode (u32 spi)
SPI Set to Master Mode.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 520 of file spi_common_all.c.
References SPI_CR1, and SPI_CR1_MSTR.
void spi_set_next_tx_from_buffer (u32 spi)
SPI Next Transmit is a Data Word.
The next transmission to take place is a data word from the transmit buffer. This must be called before transmission to distinguish between sending of a data or CRC word.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 350 of file spi_common_all.c.
References SPI_CR1, and SPI_CR1_CRCNEXT.
void spi_set_next_tx_from_crc (u32 spi)
SPI Next Transmit is a CRC Word.
The next transmission to take place is a crc word from the hardware crc unit. This must be called before transmission to distinguish between sending of a data or CRC word.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 365 of file spi_common_all.c.
References SPI_CR1, and SPI_CR1_CRCNEXT.
void spi_set_nss_high (u32 spi)
SPI Set the Software NSS Signal High.
In slave mode, and only when software slave management is used, this replaces the NSS signal with a slave select enable signal.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 452 of file spi_common_all.c.
References SPI_CR1, and SPI_CR1_SSI.
void spi_set_nss_low (u32 spi)
SPI Set the Software NSS Signal Low.
In slave mode, and only when software slave management is used, this replaces the NSS signal with a slave select disable signal.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 466 of file spi_common_all.c.
References SPI_CR1, and SPI_CR1_SSI.
void spi_set_receive_only_mode (u32 spi)
SPI Set Receive Only Mode for Simplex (2-wire) Unidirectional Transfers.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 409 of file spi_common_all.c.
References SPI_CR1, and SPI_CR1_RXONLY.
void spi_set_slave_mode (u32 spi)
SPI Set to Slave Mode.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 531 of file spi_common_all.c.
References SPI_CR1, and SPI_CR1_MSTR.
void spi_set_unidirectional_mode (u32 spi)
SPI Set Unidirectional Mode.
The SPI peripheral is set for unidirectional transfers. This is used in full duplex mode or when the SPI is placed in two-wire simplex mode that uses a clock wire and a unidirectional data wire.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
Definition at line 281 of file spi_common_all.c.
References SPI_CR1, and SPI_CR1_BIDIMODE.
void spi_write (u32 spi, u16 data)
SPI Data Write.
Data is written to the SPI interface.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
[in] data Unsigned int16. 8 or 16 bit data to be written.
Definition at line 190 of file spi_common_all.c.
References SPI_DR.
Referenced by spi_xfer().
u16 spi_xfer (u32 spi, u16 data)
SPI Data Write and Read Exchange.
Data is written to the SPI interface, then a read is done after the incoming transfer has finished.
Parameters
[in] spi Unsigned int32. SPI peripheral identifier SPI Register base address.
[in] data Unsigned int16. 8 or 16 bit data to be written.
Returns
data Unsigned int16. 8 or 16 bit data.
Definition at line 245 of file spi_common_all.c.
References SPI_DR, SPI_SR, SPI_SR_RXNE, and spi_write().