libopencm3: DMA Defines
DMA Defines
STM32F2xx Defines
Defined Constants and Types for the STM32F2xx DMA Controller.
Modules
DMA Stream Number
DMA Interrupt Flag Offsets within stream flag group.
DMA Stream Data transfer direction
DMA Stream Peripheral Word Width
DMA Stream Memory Word Width
DMA Stream Priority Levels
DMA Peripheral Burst Length
DMA Memory Burst Length
DMA Channel Select
FIFO Threshold selection
FIFO Status
Functions
BEGIN_DECLS void dma_stream_reset (u32 dma, u8 stream)
DMA Stream Reset.
void dma_clear_interrupt_flags (u32 dma, u8 stream, u32 interrupts)
DMA Stream Clear Interrupt Flag.
bool dma_get_interrupt_flag (u32 dma, u8 stream, u32 interrupt)
DMA Stream Read Interrupt Flag.
void dma_set_transfer_mode (u32 dma, u8 stream, u32 direction)
DMA Stream Enable Transfer Direction.
void dma_set_priority (u32 dma, u8 stream, u32 prio)
DMA Stream Set Priority.
void dma_set_memory_size (u32 dma, u8 stream, u32 mem_size)
DMA Stream Set Memory Word Width.
void dma_set_peripheral_size (u32 dma, u8 stream, u32 peripheral_size)
DMA Stream Set Peripheral Word Width.
void dma_enable_memory_increment_mode (u32 dma, u8 stream)
DMA Stream Enable Memory Increment after Transfer.
void dma_disable_memory_increment_mode (u32 dma, u8 channel)
DMA Channel Disable Memory Increment after Transfer.
void dma_enable_peripheral_increment_mode (u32 dma, u8 stream)
DMA Channel Enable Variable Sized Peripheral Increment after Transfer.
void dma_disable_peripheral_increment_mode (u32 dma, u8 channel)
DMA Channel Disable Peripheral Increment after Transfer.
void dma_enable_fixed_peripheral_increment_mode (u32 dma, u8 stream)
DMA Channel Enable Fixed Sized Peripheral Increment after Transfer.
void dma_enable_circular_mode (u32 dma, u8 stream)
DMA Stream Enable Memory Circular Mode.
void dma_channel_select (u32 dma, u8 stream, u32 channel)
DMA Stream Channel Select.
void dma_set_memory_burst (u32 dma, u8 stream, u32 burst)
DMA Stream Set Memory Burst Configuration.
void dma_set_peripheral_burst (u32 dma, u8 stream, u32 burst)
DMA Stream Set Peripheral Burst Configuration.
void dma_set_initial_target (u32 dma, u8 stream, u8 memory)
DMA Stream Set Initial Target Memory.
u8 dma_get_target (u32 dma, u8 stream)
DMA Stream Read Current Memory Target.
void dma_enable_double_buffer_mode (u32 dma, u8 stream)
DMA Stream Enable Double Buffer Mode.
void dma_disable_double_buffer_mode (u32 dma, u8 stream)
DMA Stream Disable Double Buffer Mode.
void dma_set_peripheral_flow_control (u32 dma, u8 stream)
DMA Stream Set Peripheral Flow Control.
void dma_set_dma_flow_control (u32 dma, u8 stream)
DMA Stream Set DMA Flow Control.
void dma_enable_transfer_error_interrupt (u32 dma, u8 stream)
DMA Stream Enable Interrupt on Transfer Error.
void dma_disable_transfer_error_interrupt (u32 dma, u8 stream)
DMA Stream Disable Interrupt on Transfer Error.
void dma_enable_half_transfer_interrupt (u32 dma, u8 stream)
DMA Stream Enable Interrupt on Transfer Half Complete.
void dma_disable_half_transfer_interrupt (u32 dma, u8 stream)
DMA Stream Disable Interrupt on Transfer Half Complete.
void dma_enable_transfer_complete_interrupt (u32 dma, u8 stream)
DMA Stream Enable Interrupt on Transfer Complete.
void dma_disable_transfer_complete_interrupt (u32 dma, u8 stream)
DMA Stream Disable Interrupt on Transfer Complete.
u32 dma_fifo_status (u32 dma, u8 stream)
DMA Get FIFO Status.
void dma_enable_direct_mode_error_interrupt (u32 dma, u8 stream)
DMA Stream Enable Interrupt on Direct Mode Error.
void dma_disable_direct_mode_error_interrupt (u32 dma, u8 stream)
DMA Stream Disable Interrupt on Direct Mode Error.
void dma_enable_fifo_error_interrupt (u32 dma, u8 stream)
DMA Enable Interrupt on FIFO Error.
void dma_disable_fifo_error_interrupt (u32 dma, u8 stream)
DMA Disable Interrupt on FIFO Error.
void dma_enable_direct_mode (u32 dma, u8 stream)
DMA Enable Direct Mode.
void dma_enable_fifo_mode (u32 dma, u8 stream)
DMA Enable FIFO Mode.
void dma_set_fifo_threshold (u32 dma, u8 stream, u32 threshold)
DMA Set FIFO Threshold.
void dma_enable_stream (u32 dma, u8 stream)
DMA Stream Enable.
void dma_disable_stream (u32 dma, u8 stream)
DMA Stream Disable.
void dma_set_peripheral_address (u32 dma, u8 stream, u32 address)
DMA Stream Set the Peripheral Address.
void dma_set_memory_address (u32 dma, u8 stream, u32 address)
DMA Stream Set the Base Memory Address 0.
void dma_set_memory_address_1 (u32 dma, u8 stream, u32 address)
DMA Stream Set the Base Memory Address 1.
void dma_set_number_of_data (u32 dma, u8 stream, u16 number)
DMA Stream Set the Transfer Block Size.
Detailed Description
Defined Constants and Types for the STM32F2xx DMA Controller.
Version
1.0.0
Date
18 October 2012
LGPL License Terms libopencm3 License
Author
© 2011 Fergus Noble fergu.nosp@m.snob.nosp@m.le@gm.nosp@m.ail..nosp@m.com
© 2012 Ken Sarkies ksark.nosp@m.ies@.nosp@m.inter.nosp@m.node.nosp@m..on.n.nosp@m.et
Function Documentation
void dma_channel_select (u32 dma, u8 stream, u32 channel)
DMA Stream Channel Select.
Associate an input channel to the stream. Not every channel is allocated to a hardware DMA request signal. The allocations for each stream are given in the STM32F4 Reference Manual.
Ensure that the stream is disabled otherwise the setting will not be changed.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
[in] channel unsigned int8. Channel selection DMA Channel Select
Definition at line 337 of file dma_common_f24.c.
void dma_clear_interrupt_flags (u32 dma, u8 stream, u32 interrupts)
DMA Stream Clear Interrupt Flag.
The interrupt flag for the stream is cleared. More than one interrupt for the same stream may be cleared by using the bitwise OR of the interrupt flags.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
[in] interrupts unsigned int32. Bitwise OR of interrupt numbers: DMA Interrupt Flag Offsets within stream flag group.
Definition at line 96 of file dma_common_f24.c.
Referenced by dma_enable_direct_mode_error_interrupt(), dma_enable_fifo_error_interrupt(), dma_enable_half_transfer_interrupt(), dma_enable_transfer_complete_interrupt(), and dma_enable_transfer_error_interrupt().
void dma_disable_direct_mode_error_interrupt (u32 dma, u8 stream)
DMA Stream Disable Interrupt on Direct Mode Error.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
Definition at line 579 of file dma_common_f24.c.
void dma_disable_double_buffer_mode (u32 dma, u8 stream)
DMA Stream Disable Double Buffer Mode.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
Definition at line 446 of file dma_common_f24.c.
void dma_disable_fifo_error_interrupt (u32 dma, u8 stream)
DMA Disable Interrupt on FIFO Error.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
Definition at line 604 of file dma_common_f24.c.
void dma_disable_half_transfer_interrupt (u32 dma, u8 stream)
DMA Stream Disable Interrupt on Transfer Half Complete.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
Definition at line 529 of file dma_common_f24.c.
void dma_disable_memory_increment_mode (u32 dma, u8 stream)
DMA Channel Disable Memory Increment after Transfer.
Ensure that the stream is disabled otherwise the setting will not be changed.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
Definition at line 245 of file dma_common_f24.c.
void dma_disable_peripheral_increment_mode (u32 dma, u8 stream)
DMA Channel Disable Peripheral Increment after Transfer.
Ensure that the stream is disabled otherwise the setting will not be changed.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
Definition at line 278 of file dma_common_f24.c.
void dma_disable_stream (u32 dma, u8 stream)
DMA Stream Disable.
Note
The DMA stream registers retain their values when the stream is disabled.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
Definition at line 693 of file dma_common_f24.c.
void dma_disable_transfer_complete_interrupt (u32 dma, u8 stream)
DMA Stream Disable Interrupt on Transfer Complete.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
Definition at line 554 of file dma_common_f24.c.
void dma_disable_transfer_error_interrupt (u32 dma, u8 stream)
DMA Stream Disable Interrupt on Transfer Error.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
Definition at line 504 of file dma_common_f24.c.
void dma_enable_circular_mode (u32 dma, u8 stream)
DMA Stream Enable Memory Circular Mode.
After the number of bytes/words to be transferred has been completed, the original transfer block size, memory and peripheral base addresses are reloaded and the process repeats.
Ensure that the stream is disabled otherwise the setting will not be changed.
Note
This cannot be used with memory to memory mode. It is disabled automatically if the peripheral is selected as the flow controller. It is enabled automatically if double buffered mode is selected.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
Definition at line 318 of file dma_common_f24.c.
void dma_enable_direct_mode (u32 dma, u8 stream)
DMA Enable Direct Mode.
Direct mode is the default. Data is transferred as soon as a DMA request is received. The FIFO is not used. This must not be set when memory to memory mode is selected.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
Definition at line 636 of file dma_common_f24.c.
void dma_enable_direct_mode_error_interrupt (u32 dma, u8 stream)
DMA Stream Enable Interrupt on Direct Mode Error.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
Definition at line 566 of file dma_common_f24.c.
References dma_clear_interrupt_flags().
void dma_enable_double_buffer_mode (u32 dma, u8 stream)
DMA Stream Enable Double Buffer Mode.
Double buffer mode is used for memory to/from peripheral transfers only, and in circular mode which is automatically enabled. Two memory buffers must be established with pointers stored in the memory pointer registers.
Ensure that the stream is disabled otherwise the setting will not be changed.
Note
This cannot be used with memory to memory mode.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
Definition at line 434 of file dma_common_f24.c.
void dma_enable_fifo_error_interrupt (u32 dma, u8 stream)
DMA Enable Interrupt on FIFO Error.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
Definition at line 591 of file dma_common_f24.c.
References dma_clear_interrupt_flags().
void dma_enable_fifo_mode (u32 dma, u8 stream)
DMA Enable FIFO Mode.
Data is transferred via a FIFO.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
Definition at line 650 of file dma_common_f24.c.
void dma_enable_fixed_peripheral_increment_mode (u32 dma, u8 stream)
DMA Channel Enable Fixed Sized Peripheral Increment after Transfer.
Following each transfer the current peripheral address is incremented by 4 regardless of the data size. The value held by the base peripheral address register is unchanged.
Ensure that the stream is disabled otherwise the setting will not be changed.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
Definition at line 296 of file dma_common_f24.c.
void dma_enable_half_transfer_interrupt (u32 dma, u8 stream)
DMA Stream Enable Interrupt on Transfer Half Complete.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
Definition at line 516 of file dma_common_f24.c.
References dma_clear_interrupt_flags().
void dma_enable_memory_increment_mode (u32 dma, u8 stream)
DMA Stream Enable Memory Increment after Transfer.
Following each transfer the current memory address is incremented by 1, 2 or 4 depending on the data size set in dma_set_memory_size. The value held by the base memory address register is unchanged.
Ensure that the stream is disabled otherwise the setting will not be changed.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
Definition at line 231 of file dma_common_f24.c.
void dma_enable_peripheral_increment_mode (u32 dma, u8 stream)
DMA Channel Enable Variable Sized Peripheral Increment after Transfer.
Following each transfer the current peripheral address is incremented by 1, 2 or 4 depending on the data size set in dma_set_peripheral_size. The value held by the base peripheral address register is unchanged.
Ensure that the stream is disabled otherwise the setting will not be changed.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
Definition at line 263 of file dma_common_f24.c.
void dma_enable_stream (u32 dma, u8 stream)
DMA Stream Enable.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
Definition at line 679 of file dma_common_f24.c.
void dma_enable_transfer_complete_interrupt (u32 dma, u8 stream)
DMA Stream Enable Interrupt on Transfer Complete.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
Definition at line 541 of file dma_common_f24.c.
References dma_clear_interrupt_flags().
void dma_enable_transfer_error_interrupt (u32 dma, u8 stream)
DMA Stream Enable Interrupt on Transfer Error.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
Definition at line 491 of file dma_common_f24.c.
References dma_clear_interrupt_flags().
u32 dma_fifo_status (u32 dma, u8 stream)
DMA Get FIFO Status.
Status of FIFO (empty. full or partial filled states) is returned. This has no meaning if direct mode is enabled (as the FIFO is not used).
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
Returns
u32 FIFO Status FIFO Status
Definition at line 620 of file dma_common_f24.c.
bool dma_get_interrupt_flag (u32 dma, u8 stream, u32 interrupt)
DMA Stream Read Interrupt Flag.
The interrupt flag for the stream is returned.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
[in] interrupt unsigned int32. Interrupt number: DMA Interrupt Flag Offsets within stream flag group.
Returns
bool interrupt flag is set.
Definition at line 122 of file dma_common_f24.c.
u8 dma_get_target (u32 dma, u8 stream)
DMA Stream Read Current Memory Target.
In double buffer mode, return the current memory target (M0 or M1). It is possible to update the memory pointer in the register that is not currently in use. An attempt to change the register currently in use will cause the stream to be disabled and the transfer error flag to be set.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
Returns
unsigned int8. Memory buffer in use: 0 or 1
Definition at line 413 of file dma_common_f24.c.
void dma_set_dma_flow_control (u32 dma, u8 stream)
DMA Stream Set DMA Flow Control.
Set the DMA controller to control DMA flow. This is the default.
Ensure that the stream is disabled otherwise the setting will not be changed.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
Definition at line 479 of file dma_common_f24.c.
void dma_set_fifo_threshold (u32 dma, u8 stream, u32 threshold)
DMA Set FIFO Threshold.
This is the filled level at which data is transferred out of the FIFO to the destination.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
[in] threshold unsigned int8. Threshold setting FIFO Threshold selection
Definition at line 666 of file dma_common_f24.c.
void dma_set_initial_target (u32 dma, u8 stream, u8 memory)
DMA Stream Set Initial Target Memory.
In double buffered mode, set the target memory (M0 or M1) to be used for the first transfer.
Ensure that the stream is disabled otherwise the setting will not be changed.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
[in] memory unsigned int8. Initial memory pointer to use: 0 or 1
Definition at line 393 of file dma_common_f24.c.
void dma_set_memory_address (u32 dma, u8 stream, u32 address)
DMA Stream Set the Base Memory Address 0.
Set the address pointer to the memory location for DMA transfers. The DMA stream must normally be disabled before setting this address, however it is possible to change this in double buffer mode when the current target is memory area 1 (see dma_get_target).
This is the default base memory address used in direct mode.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
[in] address unsigned int32. Memory Initial Address.
Definition at line 733 of file dma_common_f24.c.
void dma_set_memory_address_1 (u32 dma, u8 stream, u32 address)
DMA Stream Set the Base Memory Address 1.
Set the address pointer to the memory location for DMA transfers. The DMA stream must normally be disabled before setting this address, however it is possible to change this in double buffer mode when the current target is memory area 0 (see dma_get_target).
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
[in] address unsigned int32. Memory Initial Address.
Definition at line 753 of file dma_common_f24.c.
void dma_set_memory_burst (u32 dma, u8 stream, u32 burst)
DMA Stream Set Memory Burst Configuration.
Set the memory burst type to none, 4 8 or 16 word length. This is forced to none if direct mode is used.
Ensure that the stream is disabled otherwise the setting will not be changed.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
[in] burst unsigned int8. Memory Burst selection DMA Memory Burst Length
Definition at line 355 of file dma_common_f24.c.
void dma_set_memory_size (u32 dma, u8 stream, u32 mem_size)
DMA Stream Set Memory Word Width.
Set the memory word width 8 bits, 16 bits, or 32 bits. Refer to datasheet for alignment information if the source and destination widths do not match.
Ensure that the stream is disabled otherwise the setting will not be changed.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
[in] mem_size unsigned int32. Memory word width DMA Stream Memory Word Width.
Definition at line 191 of file dma_common_f24.c.
void dma_set_number_of_data (u32 dma, u8 stream, u16 number)
DMA Stream Set the Transfer Block Size.
Note
The DMA stream must be disabled before setting this count value. The count is not changed if the stream is enabled.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
[in] number unsigned int16. Number of data words to transfer (65535 maximum).
Definition at line 771 of file dma_common_f24.c.
void dma_set_peripheral_address (u32 dma, u8 stream, u32 address)
DMA Stream Set the Peripheral Address.
Set the address of the peripheral register to or from which data is to be transferred. Refer to the documentation for the specific peripheral.
Note
The DMA stream must be disabled before setting this address. This function has no effect if the stream is enabled.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
[in] address unsigned int32. Peripheral Address.
Definition at line 712 of file dma_common_f24.c.
void dma_set_peripheral_burst (u32 dma, u8 stream, u32 burst)
DMA Stream Set Peripheral Burst Configuration.
Set the memory burst type to none, 4 8 or 16 word length. This is forced to none if direct mode is used.
Ensure that the stream is disabled otherwise the setting will not be changed.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
[in] burst unsigned int8. Peripheral Burst selection DMA Peripheral Burst Length
Definition at line 374 of file dma_common_f24.c.
void dma_set_peripheral_flow_control (u32 dma, u8 stream)
DMA Stream Set Peripheral Flow Control.
Set the peripheral to control DMA flow. Useful when the number of transfers is unknown. This is forced off when memory to memory mode is selected.
Ensure that the stream is disabled otherwise the setting will not be changed.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
Definition at line 463 of file dma_common_f24.c.
void dma_set_peripheral_size (u32 dma, u8 stream, u32 peripheral_size)
DMA Stream Set Peripheral Word Width.
Set the peripheral word width 8 bits, 16 bits, or 32 bits. Refer to datasheet for alignment information if the source and destination widths do not match, or if the peripheral does not support byte or half-word writes.
Ensure that the stream is disabled otherwise the setting will not be changed.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
[in] peripheral_size unsigned int32. Peripheral word width DMA Stream Peripheral Word Width.
Definition at line 212 of file dma_common_f24.c.
void dma_set_priority (u32 dma, u8 stream, u32 prio)
DMA Stream Set Priority.
Stream Priority has four levels: low to very high. This has precedence over the hardware priority. In the event of equal software priority the lower numbered stream has priority.
Ensure that the stream is disabled otherwise the setting will not be changed.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
[in] prio unsigned int32. Priority level DMA Stream Priority Levels.
Definition at line 172 of file dma_common_f24.c.
void dma_set_transfer_mode (u32 dma, u8 stream, u32 direction)
DMA Stream Enable Transfer Direction.
Set peripheral to memory, memory to peripheral or memory to memory. If memory to memory mode is selected, circular mode and double buffer modes are disabled. Ensure that these modes are not enabled at a later time.
Ensure that the stream is disabled otherwise the setting will not be changed.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
[in] direction unsigned int32. Data transfer direction DMA Stream Data transfer direction
Definition at line 146 of file dma_common_f24.c.
BEGIN_DECLS void dma_stream_reset (u32 dma, u8 stream)
DMA Stream Reset.
The specified stream is disabled and configuration registers are cleared.
Parameters
[in] dma unsigned int32. DMA controller base address: DMA1 or DMA2
[in] stream unsigned int8. Stream number: DMA Stream Number
Definition at line 59 of file dma_common_f24.c.