libopencm3: ADC
ADC
STM32F3xx
libopencm3 STM32F3xx Analog to Digital Converters
Functions
void adc_enable_analog_watchdog_regular (uint32_t adc)
ADC Enable Analog Watchdog for Regular Conversions.
void adc_disable_analog_watchdog_regular (uint32_t adc)
ADC Enable Analog Watchdog for Regular Conversions.
void adc_enable_analog_watchdog_injected (uint32_t adc)
ADC Enable Analog Watchdog for Injected Conversions.
void adc_disable_analog_watchdog_injected (uint32_t adc)
ADC Disable Analog Watchdog for Injected Conversions.
void adc_enable_discontinuous_mode_regular (uint32_t adc, uint8_t length)
ADC Enable Discontinuous Mode for Regular Conversions.
void adc_disable_discontinuous_mode_regular (uint32_t adc)
ADC Disable Discontinuous Mode for Regular Conversions.
void adc_enable_discontinuous_mode_injected (uint32_t adc)
ADC Enable Discontinuous Mode for Injected Conversions.
void adc_disable_discontinuous_mode_injected (uint32_t adc)
ADC Disable Discontinuous Mode for Injected Conversions.
void adc_enable_automatic_injected_group_conversion (uint32_t adc)
ADC Enable Automatic Injected Conversions.
void adc_disable_automatic_injected_group_conversion (uint32_t adc)
ADC Disable Automatic Injected Conversions.
void adc_enable_analog_watchdog_on_all_channels (uint32_t adc)
ADC Enable Analog Watchdog for All Regular and/or Injected Channels.
void adc_enable_analog_watchdog_on_selected_channel (uint32_t adc, uint8_t channel)
ADC Enable Analog Watchdog for a Selected Channel.
void adc_enable_eoc_interrupt_injected (uint32_t adc)
ADC Set Scan Mode.
void adc_disable_eoc_interrupt_injected (uint32_t adc)
ADC Disable Injected End-Of-Conversion Interrupt.
void adc_enable_eos_interrupt_injected (uint32_t adc)
ADC Enable Injected End-Of-Sequence Interrupt.
void adc_disable_eos_interrupt_injected (uint32_t adc)
ADC Disable Injected End-Of-Sequence Interrupt.
void adc_enable_all_awd_interrupt (uint32_t adc)
ADC Enable Analog Watchdog Interrupt.
void adc_disable_all_awd_interrupt (uint32_t adc)
ADC Disable Analog Watchdog Interrupt.
void adc_enable_eos_interrupt (uint32_t adc)
ADC Enable Regular End-Of-Sequence Interrupt.
void adc_disable_eos_interrupt (uint32_t adc)
ADC Disable Regular End-Of-Sequence Interrupt.
void adc_start_conversion_injected (uint32_t adc)
ADC Software Triggered Conversion on Injected Channels.
void adc_set_watchdog_high_threshold (uint32_t adc, uint8_t threshold)
ADC Set Analog Watchdog Upper Threshold.
void adc_set_watchdog_low_threshold (uint32_t adc, uint8_t threshold)
ADC Set Analog Watchdog Lower Threshold.
void adc_set_injected_sequence (uint32_t adc, uint8_t length, uint8_t channel[])
ADC Set an Injected Channel Conversion Sequence.
bool adc_eoc_injected (uint32_t adc)
ADC Read the End-of-Conversion Flag for Injected Conversion.
bool adc_eos_injected (uint32_t adc)
ADC Read the End-of-Sequence Flag for Injected Conversions.
uint32_t adc_read_injected (uint32_t adc, uint8_t reg)
ADC Read from an Injected Conversion Result Register.
void adc_set_injected_offset (uint32_t adc, uint8_t reg, uint32_t offset)
ADC Set the Injected Channel Data Offset.
void adc_set_clk_prescale (uint32_t adc, uint32_t prescale)
ADC Set Clock Prescale.
void adc_set_multi_mode (uint32_t adc, uint32_t mode)
ADC Set Dual/Triple Mode.
void adc_enable_external_trigger_regular (uint32_t adc, uint32_t trigger, uint32_t polarity)
ADC Enable an External Trigger for Regular Channels.
void adc_disable_external_trigger_regular (uint32_t adc)
ADC Disable an External Trigger for Regular Channels.
void adc_enable_external_trigger_injected (uint32_t adc, uint32_t trigger, uint32_t polarity)
ADC Enable an External Trigger for Injected Channels.
void adc_disable_external_trigger_injected (uint32_t adc)
ADC Disable an External Trigger for Injected Channels.
bool adc_awd (uint32_t adc)
ADC Set DMA to Continue.
void adc_enable_regulator (uint32_t adc)
Enable the ADC Voltage regulator Before any use of the ADC, the ADC Voltage regulator must be enabled.
void adc_disable_regulator (uint32_t adc)
Disable the ADC Voltage regulator You can disable the adc vreg when not in use to save power.
void adc_power_off (uint32_t adc)
ADC Off.
void adc_enable_scan_mode (uint32_t adc)
ADC Set Scan Mode.
void adc_disable_scan_mode (uint32_t adc)
ADC Disable Scan Mode.
void adc_enable_awd_interrupt (uint32_t adc)
ADC Enable Analog Watchdog Interrupt.
void adc_disable_awd_interrupt (uint32_t adc)
ADC Disable Analog Watchdog Interrupt.
void adc_enable_eoc_interrupt (uint32_t adc)
ADC Enable Regular End-Of-Conversion Interrupt.
void adc_disable_eoc_interrupt (uint32_t adc)
ADC Disable Regular End-Of-Conversion Interrupt.
void adc_set_left_aligned (uint32_t adc)
ADC Set the Data as Left Aligned.
void adc_set_right_aligned (uint32_t adc)
ADC Set the Data as Right Aligned.
bool adc_eoc (uint32_t adc)
ADC Read the End-of-Conversion Flag.
uint32_t adc_read_regular (uint32_t adc)
ADC Read from the Regular Conversion Result Register.
void adc_set_continuous_conversion_mode (uint32_t adc)
ADC Enable Continuous Conversion Mode.
void adc_set_single_conversion_mode (uint32_t adc)
ADC Enable Single Conversion Mode.
void adc_set_watchdog_high_threshold (uint32_t adc, uint16_t threshold)
ADC Set Analog Watchdog Upper Threshold.
void adc_set_watchdog_low_threshold (uint32_t adc, uint16_t threshold)
ADC Set Analog Watchdog Lower Threshold.
void adc_set_regular_sequence (uint32_t adc, uint8_t length, uint8_t channel[])
ADC Set a Regular Channel Conversion Sequence.
void adc_start_conversion_regular (uint32_t adc)
ADC Software Triggered Conversion on Regular Channels.
void adc_enable_dma (uint32_t adc)
ADC Enable DMA Transfers.
void adc_disable_dma (uint32_t adc)
ADC Disable DMA Transfers.
bool adc_eos (uint32_t adc)
ADC Read the End-of-Sequence Flag for Regular Conversions.
void adc_power_on_async (uint32_t adc)
Turn on the ADC (async)
bool adc_is_power_on (uint32_t adc)
Is the ADC powered up and ready?
void adc_power_on (uint32_t adc)
Turn on the ADC.
void adc_power_off_async (uint32_t adc)
Turn off the ADC (async) This will actually block if it needs to turn off a currently running conversion, as per ref man.
bool adc_is_power_off (uint32_t adc)
Is the ADC powered down?
void adc_set_resolution (uint32_t adc, uint16_t resolution)
ADC Set Resolution.
void adc_enable_overrun_interrupt (uint32_t adc)
ADC Enable the Overrun Interrupt.
void adc_disable_overrun_interrupt (uint32_t adc)
ADC Disable the Overrun Interrupt.
bool adc_get_overrun_flag (uint32_t adc)
ADC Read the Overrun Flag.
void adc_clear_overrun_flag (uint32_t adc)
ADC Clear Overrun Flags.
void adc_enable_temperature_sensor (void)
Enable the temperature sensor (only) The channel this is available on is unfortunately not consistent, even though the bit used to enable it is.
void adc_disable_temperature_sensor (void)
Disable the temperature sensor (only)
void adc_enable_vrefint (void)
Enable the internal voltage reference (only) The channel this is available on is unfortunately not consistent, even though the bit used to enable it is.
void adc_disable_vrefint (void)
Disable the internal voltage reference (only)
void adc_set_sample_time (uint32_t adc, uint8_t channel, uint8_t time)
ADC Set the Sample Time for a Single Channel.
void adc_set_sample_time_on_all_channels (uint32_t adc, uint8_t time)
ADC Set the Sample Time for All Channels.
Detailed Description
libopencm3 STM32F3xx Analog to Digital Converters
Author
© 2012 Ken Sarkies ksark.nosp@m.ies@.nosp@m.inter.nosp@m.node.nosp@m..on.n.nosp@m.et
Date
30 August 2012
This library supports the A/D Converter Control System in the STM32 series of ARM Cortex Microcontrollers by ST Microelectronics.
Devices can have up to three A/D converters each with their own set of registers. However all the A/D converters share a common clock which is prescaled from the APB2 clock by default by a minimum factor of 2 to a maximum of 8. The ADC resolution can be set to 12, 10, 8 or 6 bits.
Each A/D converter has up to 19 channels:
On ADC1 the analog channels 16 is internally connected to the temperature sensor, channel 17 to VREFINT, and channel 18 to VBATT.
On ADC2 and ADC3 the analog channels 16 - 18 are not used.
The conversions can occur as a one-off conversion whereby the process stops once conversion is complete. The conversions can also be continuous wherein a new conversion starts immediately the previous conversion has ended.
Conversion can occur as a single channel conversion or a scan of a group of channels in either continuous or one-off mode. If more than one channel is converted in a scan group, DMA must be used to transfer the data as there is only one result register available. An interrupt can be set to occur at the end* of conversion, which occurs after all channels have been scanned.
A discontinuous mode allows a subgroup of group of a channels to be converted in bursts of a given length.
Injected conversions allow a second group of channels to be converted separately from the regular group. An interrupt can be set to occur at the end of conversion, which occurs after all channels have been scanned.
Basic ADC Handling API.
Example 1: Simple single channel conversion polled. Enable the peripheral clock and ADC, reset ADC and set the prescaler divider. Set multiple mode to independent.
gpio_mode_setup(GPIOA, GPIO_MODE_ANALOG, GPIO_PUPD_NONE, GPIO1);
rcc_peripheral_enable_clock(&RCC_APB2ENR, RCC_APB2ENR_ADC1EN);
adc_set_clk_prescale(RCC_CFGR_ADCPRE_BY2);
adc_disable_scan_mode(ADC1);
adc_set_single_conversion_mode(ADC1);
adc_set_sample_time(ADC1, ADC_CHANNEL0, ADC_SMPR1_SMP_1DOT5CYC);
uint8_t channels[] = ADC_CHANNEL0;
adc_set_regular_sequence(ADC1, 1, channels);
adc_set_multi_mode(ADC_CCR_MULTI_INDEPENDENT);
adc_power_on(ADC1);
adc_start_conversion_regular(ADC1);
while (! adc_eoc(ADC1));
reg16 = adc_read_regular(ADC1);
LGPL License Terms libopencm3 License
Author
© 2009 Edward Cheeseman evbui.nosp@m.lder.nosp@m.@user.nosp@m.s.so.nosp@m.urcef.nosp@m.orge.nosp@m..net
© 2012 Ken Sarkies ksark.nosp@m.ies@.nosp@m.inter.nosp@m.node.nosp@m..on.n.nosp@m.et
© 2014 Karl Palsson karlp.nosp@m.@twe.nosp@m.ak.ne.nosp@m.t.au
This library supports one style of the Analog to Digital Conversion System in the STM32 series of ARM Cortex Microcontrollers by ST Microelectronics.
The style of ADC Peripheral supported by this code is found in the F1, F2, F37x, F38x, F4, and L1 series devices (at the time of writing) but is quite different to the style found on the F0 and F30x and F31x. Devices can have up to three A/D converters each with their own set of registers. However all the A/D converters share a common clock. On most devices, this is prescaled from the APB2 clock by default by a minimum factor of 2 to a maximum of 8, though on the L1 this is always a divider from the HSI. (And therefore HSI must be enabled before attempting to enable the ADC)
Each A/D converter has up to ADC_MAX_CHANNELS channels:
On ADC1 the analog channels 16 and 17 are internally connected to the temperature sensor and VREFINT, respectively.
On ADC2 (if available) the analog channels 16 and 17 are internally connected to VSS.
On ADC3 (if available) the analog channels 9, 14, 15, 16 and 17 are internally connected to VSS.
The conversions can occur as a one-off conversion whereby the process stops once conversion is complete. The conversions can also be continuous wherein a new conversion starts immediately the previous conversion has ended.
Conversion can occur as a single channel conversion or a scan of a group of channels in either continuous or one-off mode. If more than one channel is converted in a scan group, DMA must be used to transfer the data as there is only one result register available. An interrupt can be set to occur at the end of conversion, which occurs after all channels have been scanned.
A discontinuous mode allows a subgroup of group of a channels to be converted in bursts of a given length.
Injected conversions allow a second group of channels to be converted separately from the regular group. An interrupt can be set to occur at the end of conversion, which occurs after all channels have been scanned.
Basic ADC Handling API.
Example 1: Simple single channel conversion polled. Enable the peripheral clock and ADC, reset ADC and set the prescaler divider. Set dual mode to independent (default). Enable triggering for a software trigger.
rcc_periph_clock_enable(RCC_ADC1);
adc_power_off(ADC1);
rcc_periph_reset_pulse(RST_ADC1);
rcc_set_adcpre(RCC_CFGR_ADCPRE_PCLK2_DIV2);
adc_set_dual_mode(ADC_CR1_DUALMOD_IND);
adc_disable_scan_mode(ADC1);
adc_set_single_conversion_mode(ADC1);
adc_set_sample_time(ADC1, ADC_CHANNEL0, ADC_SMPR1_SMP_1DOT5CYC);
adc_enable_trigger(ADC1, ADC_CR2_EXTSEL_SWSTART);
adc_power_on(ADC1);
adc_reset_calibration(ADC1);
adc_calibration(ADC1);
adc_start_conversion_regular(ADC1);
while (! adc_eoc(ADC1));
reg16 = adc_read_regular(ADC1);
LGPL License Terms libopencm3 License
Author
© 2015 Karl Palsson karlp.nosp@m.@twe.nosp@m.ak.ne.nosp@m.t.au
This library supports one style of the Analog to Digital Conversion System in the STM32 series of ARM Cortex Microcontrollers by ST Microelectronics.
The style of ADC Peripheral supported by this code is found in the F0, L0 and F30x series devices (at the time of writing)
LGPL License Terms libopencm3 License
Author
© 2016 Karl Palsson karlp.nosp@m.@twe.nosp@m.ak.ne.nosp@m.t.au
This provides the "multi" extensions to the "v2" ADC peripheral. This is those devices that support injected channels and per channel sampling times. At the time of writing, this is the STM32F30x and the STM32L4x
LGPL License Terms libopencm3 License
Function Documentation
bool adc_awd (uint32_t adc)
ADC Set DMA to Continue.
This must be set to allow DMA to continue to operate after the last conversion in the DMA sequence. This allows DMA to be used in continuous circular mode.
Parameters
[in] adc Unsigned int32. ADC block register address base adc_reg_baseADC Set DMA to Terminate
This must be set to allow DMA to terminate after the last conversion in the DMA sequence. This can avoid overrun errors.
Parameters
[in] adc Unsigned int32. ADC block register address base adc_reg_baseADC Read the Analog Watchdog Flag
This flag is set when the converted voltage crosses the high or low thresholds.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
Returns
bool. AWD flag.
Definition at line 772 of file adc.c.
References ADC_ISR, ADC_ISR_AWD1, ADC_ISR_AWD2, and ADC_ISR_AWD3.
void adc_clear_overrun_flag (uint32_t adc)
ADC Clear Overrun Flags.
The overrun flag is cleared. Note that if an overrun occurs, DMA is terminated. The flag must be cleared and the DMA stream and ADC reinitialised to resume conversions (see the reference manual).
Parameters
[in] adc Unsigned int32. ADC base address (ADC register base addresses)
Definition at line 263 of file adc_common_v2.c.
References ADC_ISR, and ADC_ISR_OVR.
void adc_disable_all_awd_interrupt (uint32_t adc)
ADC Disable Analog Watchdog Interrupt.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
Definition at line 401 of file adc.c.
References ADC_IER, ADC_IER_AWD1IE, ADC_IER_AWD2IE, and ADC_IER_AWD3IE.
void adc_disable_analog_watchdog_injected (uint32_t adc)
ADC Disable Analog Watchdog for Injected Conversions.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
Definition at line 145 of file adc.c.
References ADC_CFGR1, ADC_CFGR1_JAWD1EN, ADC_CR1, and ADC_CR1_JAWDEN.
void adc_disable_analog_watchdog_regular (uint32_t adc)
ADC Enable Analog Watchdog for Regular Conversions.
ADC Disable Analog Watchdog for Regular Conversions.
The analog watchdog allows the monitoring of an analog signal between two threshold levels. The thresholds must be preset. Comparison is done before data alignment takes place, so the thresholds are left-aligned.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
[in] adc Unsigned int32. ADC block register address base ADC register base addresses.
Definition at line 117 of file adc.c.
References ADC_CFGR1, ADC_CFGR1_AWD1EN, ADC_CR1, and ADC_CR1_AWDEN.
void adc_disable_automatic_injected_group_conversion (uint32_t adc)
ADC Disable Automatic Injected Conversions.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
Definition at line 239 of file adc.c.
References ADC_CFGR1, ADC_CFGR1_JAUTO, ADC_CR1, and ADC_CR1_JAUTO.
void adc_disable_awd_interrupt (uint32_t adc)
ADC Disable Analog Watchdog Interrupt.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
Definition at line 372 of file adc_common_v1.c.
References ADC_CR1, and ADC_CR1_AWDIE.
void adc_disable_discontinuous_mode_injected (uint32_t adc)
ADC Disable Discontinuous Mode for Injected Conversions.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
Definition at line 210 of file adc.c.
References ADC_CFGR1, ADC_CFGR1_JDISCEN, ADC_CR1, and ADC_CR1_JDISCEN.
void adc_disable_discontinuous_mode_regular (uint32_t adc)
ADC Disable Discontinuous Mode for Regular Conversions.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
Definition at line 182 of file adc.c.
References ADC_CFGR1, ADC_CFGR1_DISCEN, ADC_CR1, and ADC_CR1_DISCEN.
void adc_disable_dma (uint32_t adc)
ADC Disable DMA Transfers.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
[in] adc Unsigned int32. ADC base address (ADC register base addresses)
Definition at line 746 of file adc_common_v1.c.
References ADC_CFGR1, ADC_CFGR1_DMAEN, ADC_CR2, and ADC_CR2_DMA.
void adc_disable_eoc_interrupt (uint32_t adc)
ADC Disable Regular End-Of-Conversion Interrupt.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
[in] adc Unsigned int32. ADC base address (ADC register base addresses)
Definition at line 395 of file adc_common_v1.c.
References ADC_CR1, ADC_CR1_EOCIE, ADC_IER, and ADC_IER_EOCIE.
void adc_disable_eoc_interrupt_injected (uint32_t adc)
ADC Disable Injected End-Of-Conversion Interrupt.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
Definition at line 350 of file adc.c.
References ADC_CR1, ADC_CR1_JEOCIE, ADC_IER, and ADC_IER_JEOCIE.
void adc_disable_eos_interrupt (uint32_t adc)
ADC Disable Regular End-Of-Sequence Interrupt.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
Definition at line 427 of file adc.c.
References ADC_IER, and ADC_IER_EOSIE.
void adc_disable_eos_interrupt_injected (uint32_t adc)
ADC Disable Injected End-Of-Sequence Interrupt.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
Definition at line 374 of file adc.c.
References ADC_IER, and ADC_IER_JEOSIE.
void adc_disable_external_trigger_injected (uint32_t adc)
ADC Disable an External Trigger for Injected Channels.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
Definition at line 721 of file adc.c.
References ADC_JSQR, and ADC_JSQR_JEXTEN_MASK.
Referenced by adc_enable_automatic_injected_group_conversion().
void adc_disable_external_trigger_regular (uint32_t adc)
ADC Disable an External Trigger for Regular Channels.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
Definition at line 685 of file adc.c.
References ADC_CFGR1, and ADC_CFGR1_EXTEN_MASK.
void adc_disable_overrun_interrupt (uint32_t adc)
ADC Disable the Overrun Interrupt.
Parameters
[in] adc Unsigned int32. ADC base address (ADC register base addresses)
Definition at line 236 of file adc_common_v2.c.
References ADC_IER, and ADC_IER_OVRIE.
void adc_disable_regulator (uint32_t adc)
Disable the ADC Voltage regulator You can disable the adc vreg when not in use to save power.
Parameters
[in] adc ADC block register address base
See also
adc_enable_regulator
Definition at line 799 of file adc.c.
References ADC_CR, ADC_CR_ADVREGEN_DISABLE, and ADC_CR_ADVREGEN_MASK.
void adc_disable_scan_mode (uint32_t adc)
ADC Disable Scan Mode.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
Definition at line 328 of file adc_common_v1.c.
References ADC_CR1, and ADC_CR1_SCAN.
void adc_disable_temperature_sensor (void)
Disable the temperature sensor (only)
See also
adc_enable_temperature_sensor
Definition at line 315 of file adc_common_v2.c.
References ADC1, ADC_CCR, and ADC_CCR_TSEN.
void adc_disable_vrefint (void)
Disable the internal voltage reference (only)
See also
adc_enable_vrefint
Definition at line 336 of file adc_common_v2.c.
References ADC1, ADC_CCR, and ADC_CCR_VREFEN.
void adc_enable_all_awd_interrupt (uint32_t adc)
ADC Enable Analog Watchdog Interrupt.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
Definition at line 387 of file adc.c.
References ADC_IER, ADC_IER_AWD1IE, ADC_IER_AWD2IE, and ADC_IER_AWD3IE.
void adc_enable_analog_watchdog_injected (uint32_t adc)
ADC Enable Analog Watchdog for Injected Conversions.
The analog watchdog allows the monitoring of an analog signal between two threshold levels. The thresholds must be preset. Comparison is done before data alignment takes place, so the thresholds are left-aligned.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
Definition at line 133 of file adc.c.
References ADC_CFGR1, ADC_CFGR1_JAWD1EN, ADC_CR1, and ADC_CR1_JAWDEN.
void adc_enable_analog_watchdog_on_all_channels (uint32_t adc)
ADC Enable Analog Watchdog for All Regular and/or Injected Channels.
The analog watchdog allows the monitoring of an analog signal between two threshold levels. The thresholds must be preset. Comparison is done before data alignment takes place, so the thresholds are left-aligned.
Note
The analog watchdog must be enabled for either or both of the regular or injected channels. If neither are enabled, the analog watchdog feature will be disabled.
adc_enable_analog_watchdog_injected, adc_enable_analog_watchdog_regular.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
Definition at line 261 of file adc.c.
References ADC_CFGR1, ADC_CFGR1_AWD1SGL, ADC_CR1, and ADC_CR1_AWDSGL.
void adc_enable_analog_watchdog_on_selected_channel (uint32_t adc, uint8_t channel)
ADC Enable Analog Watchdog for a Selected Channel.
The analog watchdog allows the monitoring of an analog signal between two threshold levels. The thresholds must be preset. Comparison is done before data alignment takes place, so the thresholds are left-aligned.
Note
The analog watchdog must be enabled for either or both of the regular or injected channels. If neither are enabled, the analog watchdog feature will be disabled. If both are enabled, the same channel number is monitored adc_enable_analog_watchdog_injected, adc_enable_analog_watchdog_regular.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
[in] channel Unsigned int8. ADC channel numbe ADC watchdog channel
The analog watchdog allows the monitoring of an analog signal between two threshold levels. The thresholds must be preset. Comparison is done before data alignment takes place, so the thresholds are left-aligned.
Note
The analog watchdog must be enabled for either or both of the regular or injected channels. If neither are enabled, the analog watchdog feature will be disabled. If both are enabled, the same channel number is monitored. adc_enable_analog_watchdog_injected, adc_enable_analog_watchdog_regular.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
[in] channel Unsigned int8. ADC channel number ADC watchdog channel
Definition at line 285 of file adc.c.
References ADC_CFGR1, ADC_CFGR1_AWD1CH, ADC_CFGR1_AWD1SGL, ADC_CR1, ADC_CR1_AWDCH_MASK, and ADC_CR1_AWDSGL.
void adc_enable_analog_watchdog_regular (uint32_t adc)
ADC Enable Analog Watchdog for Regular Conversions.
The analog watchdog allows the monitoring of an analog signal between two threshold levels. The thresholds must be preset. Comparison is done before data alignment takes place, so the thresholds are left-aligned.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
The analog watchdog allows the monitoring of an analog signal between two threshold levels. The thresholds must be preset. Comparison is done before data alignment takes place, so the thresholds are left-aligned.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses.
Definition at line 102 of file adc.c.
References ADC_CFGR1, ADC_CFGR1_AWD1EN, ADC_CR1, and ADC_CR1_AWDEN.
void adc_enable_automatic_injected_group_conversion (uint32_t adc)
ADC Enable Automatic Injected Conversions.
The ADC converts a defined injected group of channels immediately after the regular channels have been converted. The external trigger on the injected channels is disabled as required.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
Definition at line 226 of file adc.c.
References ADC_CFGR1, ADC_CFGR1_JAUTO, ADC_CR1, ADC_CR1_JAUTO, and adc_disable_external_trigger_injected().
void adc_enable_awd_interrupt (uint32_t adc)
ADC Enable Analog Watchdog Interrupt.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
Definition at line 361 of file adc_common_v1.c.
References ADC_CR1, and ADC_CR1_AWDIE.
void adc_enable_discontinuous_mode_injected (uint32_t adc)
ADC Enable Discontinuous Mode for Injected Conversions.
In this mode the ADC converts sequentially one channel of the defined group of injected channels, cycling back to the first channel in the group once the entire group has been converted.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
Definition at line 198 of file adc.c.
References ADC_CFGR1, ADC_CFGR1_JDISCEN, ADC_CR1, and ADC_CR1_JDISCEN.
void adc_enable_discontinuous_mode_regular (uint32_t adc, uint8_t length)
ADC Enable Discontinuous Mode for Regular Conversions.
In this mode the ADC converts, on each trigger, a subgroup of up to 8 of the defined regular channel group. The subgroup is defined by the number of consecutive channels to be converted. After a subgroup has been converted the next trigger will start conversion of the immediately following subgroup of the same length or until the whole group has all been converted. When the whole group has been converted, the next trigger will restart conversion of the subgroup at the beginning of the whole group.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
[in] length Unsigned int8. Number of channels in the group ADC Number of channels in discontinuous mode.
In this mode the ADC converts, on each trigger, a subgroup of up to 8 of the defined regular channel group. The subgroup is defined by the number of consecutive channels to be converted. After a subgroup has been converted the next trigger will start conversion of the immediately following subgroup of the same length or until the whole group has all been converted. When the the whole group has been converted, the next trigger will restart conversion of the subgroup at the beginning of the whole group.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
[in] length Unsigned int8. Number of channels in the group ADC Number of channels in discontinuous mode.
Definition at line 166 of file adc.c.
References ADC_CFGR1, ADC_CFGR1_DISCEN, ADC_CFGR1_DISCNUM_SHIFT, ADC_CR1, ADC_CR1_DISCEN, and ADC_CR1_DISCNUM_SHIFT.
void adc_enable_dma (uint32_t adc)
ADC Enable DMA Transfers.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
[in] adc Unsigned int32. ADC base address (ADC register base addresses)
Definition at line 735 of file adc_common_v1.c.
References ADC_CFGR1, ADC_CFGR1_DMAEN, ADC_CR2, and ADC_CR2_DMA.
void adc_enable_eoc_interrupt (uint32_t adc)
ADC Enable Regular End-Of-Conversion Interrupt.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
[in] adc Unsigned int32. ADC base address (ADC register base addresses)
Definition at line 384 of file adc_common_v1.c.
References ADC_CR1, ADC_CR1_EOCIE, ADC_IER, and ADC_IER_EOCIE.
void adc_enable_eoc_interrupt_injected (uint32_t adc)
ADC Set Scan Mode.
ADC Enable Injected End-Of-Conversion Interrupt.
In this mode a conversion consists of a scan of the predefined set of channels, regular and injected, each channel conversion immediately following the previous one. It can use single, continuous or discontinuous mode.
Parameters
[in] adc Unsigned int32. ADC block register address base adc_reg_baseADC Disable Scan Mode
[in] adc Unsigned int32. ADC block register address base adc_reg_baseADC Enable Injected End-Of-Conversion Interrupt
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
Definition at line 338 of file adc.c.
References ADC_CR1, ADC_CR1_JEOCIE, ADC_IER, and ADC_IER_JEOCIE.
void adc_enable_eos_interrupt (uint32_t adc)
ADC Enable Regular End-Of-Sequence Interrupt.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
Definition at line 415 of file adc.c.
References ADC_IER, and ADC_IER_EOSIE.
void adc_enable_eos_interrupt_injected (uint32_t adc)
ADC Enable Injected End-Of-Sequence Interrupt.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
Definition at line 362 of file adc.c.
References ADC_IER, and ADC_IER_JEOSIE.
void adc_enable_external_trigger_injected (uint32_t adc, uint32_t trigger, uint32_t polarity)
ADC Enable an External Trigger for Injected Channels.
This enables an external trigger for set of defined injected channels, and sets the polarity of the trigger event: rising or falling edge or both.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
[in] trigger Unsigned int8. Trigger identifier adc_trigger_injected
[in] polarity Unsigned int32. Trigger polarity adc_trigger_polarity_injected
Definition at line 704 of file adc.c.
References ADC_JSQR, ADC_JSQR_JEXTEN_MASK, and ADC_JSQR_JEXTSEL_MASK.
void adc_enable_external_trigger_regular (uint32_t adc, uint32_t trigger, uint32_t polarity)
ADC Enable an External Trigger for Regular Channels.
This enables an external trigger for set of defined regular channels, and sets the polarity of the trigger event: rising or falling edge or both. Note that if the trigger polarity is zero, triggering is disabled.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
[in] trigger Unsigned int32. Trigger identifier adc_trigger_regular
[in] polarity Unsigned int32. Trigger polarity adc_trigger_polarity_regular
Definition at line 668 of file adc.c.
References ADC_CFGR1, ADC_CFGR1_EXTEN_MASK, and ADC_CFGR1_EXTSEL_MASK.
void adc_enable_overrun_interrupt (uint32_t adc)
ADC Enable the Overrun Interrupt.
The overrun interrupt is generated when data is not read from a result register before the next conversion is written. If DMA is enabled, all transfers are terminated and any conversion sequence is aborted.
Parameters
[in] adc Unsigned int32. ADC base address (ADC register base addresses)
Definition at line 227 of file adc_common_v2.c.
References ADC_IER, and ADC_IER_OVRIE.
void adc_enable_regulator (uint32_t adc)
Enable the ADC Voltage regulator Before any use of the ADC, the ADC Voltage regulator must be enabled.
You must wait up to 10uSecs afterwards before trying anything else.
Parameters
[in] adc ADC block register address base
See also
adc_disable_regulator
Definition at line 787 of file adc.c.
References ADC_CR, ADC_CR_ADVREGEN_ENABLE, and ADC_CR_ADVREGEN_MASK.
void adc_enable_scan_mode (uint32_t adc)
ADC Set Scan Mode.
In this mode a conversion consists of a scan of the predefined set of channels, regular and injected, each channel conversion immediately following the previous one. It can use single, continuous or discontinuous mode.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
Definition at line 317 of file adc_common_v1.c.
References ADC_CR1, and ADC_CR1_SCAN.
void adc_enable_temperature_sensor (void)
Enable the temperature sensor (only) The channel this is available on is unfortunately not consistent, even though the bit used to enable it is.
See also
adc_disable_temperature_sensor
Definition at line 306 of file adc_common_v2.c.
References ADC1, ADC_CCR, and ADC_CCR_TSEN.
void adc_enable_vrefint (void)
Enable the internal voltage reference (only) The channel this is available on is unfortunately not consistent, even though the bit used to enable it is.
FIXME - on f3, you can actually have it on ADC34 as well!
See also
adc_disable_vrefint
Definition at line 327 of file adc_common_v2.c.
References ADC1, ADC_CCR, and ADC_CCR_VREFEN.
bool adc_eoc (uint32_t adc)
ADC Read the End-of-Conversion Flag.
This flag is set after all channels of a regular or injected group have been converted.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
Returns
bool. End of conversion flag.
This flag is set by hardware at the end of each regular conversion of a channel when a new data is available in the ADCx_DR register.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
Returns
bool. End of conversion flag.
Definition at line 435 of file adc_common_v1.c.
References ADC_ISR, ADC_ISR_EOC, ADC_SR, and ADC_SR_EOC.
bool adc_eoc_injected (uint32_t adc)
ADC Read the End-of-Conversion Flag for Injected Conversion.
This flag is set by hardware at the end of each injected conversion of a channel when a new data is available in the corresponding ADCx_JDRy register.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
Returns
bool. End of conversion flag.
This flag is set after all channels of an injected group have been converted.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
Returns
bool. End of conversion flag.
Definition at line 536 of file adc.c.
References ADC_ISR, ADC_ISR_JEOC, ADC_SR, and ADC_SR_JEOC.
bool adc_eos (uint32_t adc)
ADC Read the End-of-Sequence Flag for Regular Conversions.
This flag is set after all channels of an regular group have been converted.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
Returns
bool. End of conversion flag.
Definition at line 62 of file adc_common_v2.c.
References ADC_ISR, and ADC_ISR_EOS.
bool adc_eos_injected (uint32_t adc)
ADC Read the End-of-Sequence Flag for Injected Conversions.
This flag is set after all channels of an injected group have been converted.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
Returns
bool. End of conversion flag.
Definition at line 551 of file adc.c.
References ADC_ISR, and ADC_ISR_JEOS.
bool adc_get_overrun_flag (uint32_t adc)
ADC Read the Overrun Flag.
The overrun flag is set when data is not read from a result register before the next conversion is written. If DMA is enabled, all transfers are terminated and any conversion sequence is aborted.
Parameters
[in] adc Unsigned int32. ADC base address (ADC register base addresses)
Definition at line 249 of file adc_common_v2.c.
References ADC_ISR, and ADC_ISR_OVR.
bool adc_is_power_off (uint32_t adc)
Is the ADC powered down?
See also
adc_power_off_async
Parameters
adc ADC Block register address base ADC register base addresses
Definition at line 127 of file adc_common_v2.c.
References ADC_CR, and ADC_CR_ADEN.
Referenced by adc_power_off().
bool adc_is_power_on (uint32_t adc)
Is the ADC powered up and ready?
See also
adc_power_on_async
Parameters
adc ADC Block register address base ADC register base addresses
Returns
true if adc is ready for use
Definition at line 83 of file adc_common_v2.c.
References ADC_ISR, and ADC_ISR_ADRDY.
Referenced by adc_power_on().
void adc_power_off (uint32_t adc)
ADC Off.
Turn off the ADC This will actually block if it needs to turn off a currently running conversion, as per ref man.
Turn off the ADC to reduce power consumption to a few microamps.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses.
See also
adc_power_off_async
Parameters
adc ADC Block register address base ADC register base addresses
Definition at line 107 of file adc_common_v1.c.
References ADC_CR2, ADC_CR2_ADON, adc_is_power_off(), and adc_power_off_async().
void adc_power_off_async (uint32_t adc)
Turn off the ADC (async) This will actually block if it needs to turn off a currently running conversion, as per ref man.
(Handles injected on hardware that supports injected conversions.
See also
adc_wait_power_off
Parameters
adc ADC Block register address base ADC register base addresses
Definition at line 107 of file adc_common_v2.c.
References ADC_CR, ADC_CR_ADDIS, ADC_CR_ADSTART, ADC_CR_ADSTP, ADC_CR_JADSTART, and ADC_CR_JADSTP.
Referenced by adc_power_off().
void adc_power_on (uint32_t adc)
Turn on the ADC.
See also
adc_power_on_async
Parameters
adc ADC Block register address base ADC register base addresses
Definition at line 93 of file adc_common_v2.c.
References adc_is_power_on(), and adc_power_on_async().
void adc_power_on_async (uint32_t adc)
Turn on the ADC (async)
See also
adc_wait_power_on
Parameters
adc ADC Block register address base ADC register base addresses
Definition at line 72 of file adc_common_v2.c.
References ADC_CR, and ADC_CR_ADEN.
Referenced by adc_power_on().
uint32_t adc_read_injected (uint32_t adc, uint8_t reg)
ADC Read from an Injected Conversion Result Register.
The result read back from the selected injected result register (one of four) is 12 bits, right or left aligned within the first 16 bits. The result can have a negative value if the injected channel offset has been set
See also
adc_set_injected_offset.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
[in] reg Unsigned int8. Register number (1 ... 4).
Returns
Unsigned int32 conversion result.
Definition at line 571 of file adc.c.
References ADC_JDR1, ADC_JDR2, ADC_JDR3, and ADC_JDR4.
uint32_t adc_read_regular (uint32_t adc)
ADC Read from the Regular Conversion Result Register.
The result read back is 12 bits, right or left aligned within the first 16 bits. For ADC1 only, the higher 16 bits will hold the result from ADC2 if an appropriate dual mode has been set
See also
adc_set_dual_mode.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
Returns
Unsigned int32 conversion result.
The result read back is 12 bits, right or left aligned within the first 16 bits.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
Returns
Unsigned int32 conversion result.
Definition at line 465 of file adc_common_v1.c.
References ADC_DR.
void adc_set_clk_prescale (uint32_t adc, uint32_t prescale)
ADC Set Clock Prescale.
The ADC clock taken from the APB2 clock can be scaled down by 2, 4, 6 or 8.
Parameters
[in] prescale Unsigned int32. Prescale value for ADC Clock adc_ccr_adcpre
Definition at line 630 of file adc.c.
References ADC_CCR, and ADC_CCR_CKMODE_MASK.
void adc_set_continuous_conversion_mode (uint32_t adc)
ADC Enable Continuous Conversion Mode.
Enable Continuous Conversion Mode In this mode the ADC starts a new conversion of a single channel or a channel group immediately following completion of the previous channel group conversion.
In this mode the ADC starts a new conversion of a single channel or a channel group immediately following completion of the previous channel group conversion.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
[in] adc ADC block register address base ADC register base addresses
Definition at line 507 of file adc_common_v1.c.
References ADC_CFGR1, ADC_CFGR1_CONT, ADC_CR2, and ADC_CR2_CONT.
void adc_set_injected_offset (uint32_t adc, uint8_t reg, uint32_t offset)
ADC Set the Injected Channel Data Offset.
This value is subtracted from the injected channel results after conversion is complete, and can result in negative results. A separate value can be specified for each injected data register.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
[in] reg Unsigned int8. Register number (1 ... 4).
[in] offset Unsigned int32.
Definition at line 599 of file adc.c.
References ADC_OFR1, ADC_OFR1_OFFSET1_EN, ADC_OFR2, ADC_OFR2_OFFSET2_EN, ADC_OFR3, ADC_OFR3_OFFSET3_EN, ADC_OFR4, and ADC_OFR4_OFFSET4_EN.
void adc_set_injected_sequence (uint32_t adc, uint8_t length, uint8_t channel[])
ADC Set an Injected Channel Conversion Sequence.
Defines a sequence of channels to be converted as an injected group with a length from 1 to 4 channels. If this is called during conversion, the current conversion is reset and conversion begins again with the newly defined group.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
[in] length Unsigned int8. Number of channels in the group.
[in] channel Unsigned int8[]. Set of channels in sequence, integers 0..18
Definition at line 506 of file adc.c.
References ADC_JSQR, ADC_JSQR_JL_VAL, and ADC_JSQR_JSQ_VAL.
void adc_set_left_aligned (uint32_t adc)
ADC Set the Data as Left Aligned.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses.
[in] adc Unsigned int32. ADC base address (ADC register base addresses)
Definition at line 408 of file adc_common_v1.c.
References ADC_CFGR1, ADC_CFGR1_ALIGN, ADC_CR2, and ADC_CR2_ALIGN.
void adc_set_multi_mode (uint32_t adc, uint32_t mode)
ADC Set Dual/Triple Mode.
The multiple mode uses ADC1 as master, ADC2 and optionally ADC3 in a slave arrangement. This setting is applied to ADC1 only.
The various modes possible are described in the reference manual.
Parameters
[in] mode Unsigned int32. Multiple mode selection from adc_multi_mode
Definition at line 648 of file adc.c.
References ADC_CCR.
void adc_set_regular_sequence (uint32_t adc, uint8_t length, uint8_t channel[])
ADC Set a Regular Channel Conversion Sequence.
Define a sequence of channels to be converted as a regular group with a length from 1 to ADC_REGULAR_SEQUENCE_MAX channels. If this is called during conversion, the current conversion is reset and conversion begins again with the newly defined group.
Parameters
[in] adc Unsigned int32. ADC block base address ADC register base addresses.
[in] length Unsigned int8. Number of channels in the group.
[in] channel Unsigned int8[]. Set of channels in sequence, integers 0..31.
Define a sequence of channels to be converted as a regular group with a length from 1 to 16 channels. If this is called during conversion, the current conversion is reset and conversion begins again with the newly defined group.
Parameters
[in] adc ADC block register address base ADC register base addresses
[in] length Number of channels in the group, range 0..16
[in] channel Set of channels in sequence, range ADC Channel Numbers
Definition at line 574 of file adc_common_v1.c.
References ADC_SQR1, ADC_SQR1_L_LSB, ADC_SQR1_L_SHIFT, ADC_SQR2, ADC_SQR3, and ADC_SQR4.
void adc_set_resolution (uint32_t adc, uint16_t resolution)
ADC Set Resolution.
ADC Resolution can be reduced from 12 bits to 10, 8 or 6 bits for a corresponding reduction in conversion time.
Parameters
[in] adc Unsigned int32. ADC base address (ADC register base addresses)
[in] resolution Unsigned int16. Resolution value (adc_api_res)
Definition at line 178 of file adc_common_v2.c.
References ADC_CFGR1, and ADC_CFGR1_RES_MASK.
void adc_set_right_aligned (uint32_t adc)
ADC Set the Data as Right Aligned.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses.
[in] adc Unsigned int32. ADC base address (ADC register base addresses)
Definition at line 420 of file adc_common_v1.c.
References ADC_CFGR1, ADC_CFGR1_ALIGN, ADC_CR2, and ADC_CR2_ALIGN.
void adc_set_sample_time (uint32_t adc, uint8_t channel, uint8_t time)
ADC Set the Sample Time for a Single Channel.
The sampling time can be selected in ADC clock cycles, exact values depend on the device.
Parameters
[in] adc ADC block register address base ADC register base addresses
[in] channel ADC Channel integer ADC Channel Numbers
[in] time Sampling time selection from ADC Sample Time Selection values
Definition at line 46 of file adc_common_v2_multi.c.
References ADC_SMPR1, and ADC_SMPR2.
void adc_set_sample_time_on_all_channels (uint32_t adc, uint8_t time)
ADC Set the Sample Time for All Channels.
The sampling time can be selected in ADC clock cycles, exact values depend on the device.
Parameters
[in] adc ADC block register address base ADC register base addresses
[in] time Sampling time selection from ADC Sample Time Selection values
Definition at line 71 of file adc_common_v2_multi.c.
References ADC_SMPR1, and ADC_SMPR2.
void adc_set_single_conversion_mode (uint32_t adc)
ADC Enable Single Conversion Mode.
Enable Single Conversion Mode In this mode the ADC performs a conversion of one channel or a channel group and stops.
In this mode the ADC performs a conversion of one channel or a channel group and stops.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses.
[in] adc ADC block register address base ADC register base addresses
Definition at line 523 of file adc_common_v1.c.
References ADC_CFGR1, ADC_CFGR1_CONT, ADC_CR2, and ADC_CR2_CONT.
void adc_set_watchdog_high_threshold (uint32_t adc, uint8_t threshold)
ADC Set Analog Watchdog Upper Threshold.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
[in] threshold Unsigned int8. Upper threshold value
Definition at line 461 of file adc.c.
References ADC_TR1, ADC_TR2, and ADC_TR3.
void adc_set_watchdog_high_threshold (uint32_t adc, uint16_t threshold)
ADC Set Analog Watchdog Upper Threshold.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
[in] threshold Unsigned int8. Upper threshold value
Definition at line 535 of file adc_common_v1.c.
References ADC_HT_MSK.
void adc_set_watchdog_low_threshold (uint32_t adc, uint8_t threshold)
ADC Set Analog Watchdog Lower Threshold.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
[in] threshold Unsigned int8. Lower threshold value
Definition at line 480 of file adc.c.
References ADC_TR1, ADC_TR2, and ADC_TR3.
void adc_set_watchdog_low_threshold (uint32_t adc, uint16_t threshold)
ADC Set Analog Watchdog Lower Threshold.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
[in] threshold Unsigned int8. Lower threshold value
Definition at line 551 of file adc_common_v1.c.
References ADC_LT_MSK.
void adc_start_conversion_injected (uint32_t adc)
ADC Software Triggered Conversion on Injected Channels.
This starts conversion on a set of defined injected channels. It is cleared by hardware once conversion starts.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses
This starts conversion on a set of defined injected channels if the ADC trigger is set to be a software trigger. It is cleared by hardware once conversion starts.
Special F1 Note this is a software trigger and requires triggering to be enabled and the trigger source to be set appropriately otherwise conversion will not start. This is not the same as the ADC start conversion operation.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses.
Definition at line 443 of file adc.c.
References ADC_CR, ADC_CR2, and ADC_CR_JADSTART.
void adc_start_conversion_regular (uint32_t adc)
ADC Software Triggered Conversion on Regular Channels.
This starts conversion on a set of defined regular channels if the ADC trigger is set to be a software trigger. It is cleared by hardware once conversion starts.
Special F1 Note this is a software trigger and requires triggering to be enabled and the trigger source to be set appropriately otherwise conversion will not start. This is not the same as the ADC start conversion operation.
Parameters
[in] adc Unsigned int32. ADC block register address base ADC register base addresses.
This starts conversion on a set of defined regular channels. It is cleared by hardware once conversion starts.
Parameters
[in] adc ADC block register address base ADC register base addresses
Definition at line 695 of file adc_common_v1.c.
References ADC_CR, ADC_CR2, and ADC_CR_ADSTART.