libopencm3: I2C
I2C
STM32F3xx
libopencm3 STM32F3xx I2C
Functions
void i2c_reset (uint32_t i2c)
I2C Reset.
void i2c_peripheral_enable (uint32_t i2c)
I2C Peripheral Enable.
void i2c_peripheral_disable (uint32_t i2c)
I2C Peripheral Disable.
void i2c_send_start (uint32_t i2c)
I2C Send Start Condition.
void i2c_send_stop (uint32_t i2c)
I2C Send Stop Condition.
void i2c_clear_stop (uint32_t i2c)
I2C Clear Stop Flag.
void i2c_set_own_7bit_slave_address (uint32_t i2c, uint8_t slave)
I2C Set the 7 bit Slave Address for the Peripheral.
void i2c_set_own_10bit_slave_address (uint32_t i2c, uint16_t slave)
I2C Set the 10 bit Slave Address for the Peripheral.
void i2c_send_data (uint32_t i2c, uint8_t data)
I2C Send Data.
uint8_t i2c_get_data (uint32_t i2c)
I2C Get Data.
void i2c_enable_analog_filter (uint32_t i2c)
void i2c_disable_analog_filter (uint32_t i2c)
void i2c_set_digital_filter (uint32_t i2c, uint8_t dnf_setting)
void i2c_set_prescaler (uint32_t i2c, uint8_t presc)
void i2c_set_data_setup_time (uint32_t i2c, uint8_t s_time)
void i2c_set_data_hold_time (uint32_t i2c, uint8_t h_time)
void i2c_set_scl_high_period (uint32_t i2c, uint8_t period)
void i2c_set_scl_low_period (uint32_t i2c, uint8_t period)
void i2c_enable_stretching (uint32_t i2c)
void i2c_disable_stretching (uint32_t i2c)
void i2c_100khz_i2cclk8mhz (uint32_t i2c)
void i2c_set_7bit_addr_mode (uint32_t i2c)
void i2c_set_10bit_addr_mode (uint32_t i2c)
void i2c_set_7bit_address (uint32_t i2c, uint8_t addr)
void i2c_set_10bit_address (uint32_t i2c, uint16_t addr)
void i2c_set_write_transfer_dir (uint32_t i2c)
void i2c_set_read_transfer_dir (uint32_t i2c)
void i2c_set_bytes_to_transfer (uint32_t i2c, uint32_t n_bytes)
uint8_t i2c_is_start (uint32_t i2c)
void i2c_enable_autoend (uint32_t i2c)
void i2c_disable_autoend (uint32_t i2c)
uint8_t i2c_nack (uint32_t i2c)
uint8_t i2c_busy (uint32_t i2c)
uint8_t i2c_transmit_int_status (uint32_t i2c)
uint8_t i2c_transfer_complete (uint32_t i2c)
uint8_t i2c_received_data (uint32_t i2c)
void i2c_enable_interrupt (uint32_t i2c, uint32_t interrupt)
I2C Enable Interrupt.
void i2c_disable_interrupt (uint32_t i2c, uint32_t interrupt)
I2C Disable Interrupt.
void i2c_enable_rxdma (uint32_t i2c)
I2C Enable reception DMA.
void i2c_disable_rxdma (uint32_t i2c)
I2C Disable reception DMA.
void i2c_enable_txdma (uint32_t i2c)
I2C Enable transmission DMA.
void i2c_disable_txdma (uint32_t i2c)
I2C Disable transmission DMA.
void write_i2c (uint32_t i2c, uint8_t i2c_addr, uint8_t reg, uint8_t size, uint8_t *data)
void read_i2c (uint32_t i2c, uint8_t i2c_addr, uint8_t reg, uint8_t size, uint8_t *data)
void i2c_set_clock_frequency (uint32_t i2c, uint8_t freq)
I2C Set Peripheral Clock Frequency.
void i2c_set_fast_mode (uint32_t i2c)
I2C Set Fast Mode.
void i2c_set_standard_mode (uint32_t i2c)
I2C Set Standard Mode.
void i2c_set_ccr (uint32_t i2c, uint16_t freq)
I2C Set Bus Clock Frequency.
void i2c_set_trise (uint32_t i2c, uint16_t trise)
I2C Set the Rise Time.
void i2c_send_7bit_address (uint32_t i2c, uint8_t slave, uint8_t readwrite)
I2C Send the 7-bit Slave Address.
void i2c_enable_ack (uint32_t i2c)
I2C Enable ACK.
void i2c_disable_ack (uint32_t i2c)
I2C Disable ACK.
void i2c_nack_next (uint32_t i2c)
I2C NACK Next Byte.
void i2c_nack_current (uint32_t i2c)
I2C NACK Next Byte.
void i2c_set_dutycycle (uint32_t i2c, uint32_t dutycycle)
I2C Set clock duty cycle.
void i2c_enable_dma (uint32_t i2c)
I2C Enable DMA.
void i2c_disable_dma (uint32_t i2c)
I2C Disable DMA.
void i2c_set_dma_last_transfer (uint32_t i2c)
I2C Set DMA last transfer.
void i2c_clear_dma_last_transfer (uint32_t i2c)
I2C Clear DMA last transfer.
Detailed Description
libopencm3 STM32F3xx I2C
Version
1.0.0
Date
15 October 2012
LGPL License Terms libopencm3 License
Author
© 2010 Thomas Otto tommi.nosp@m.@via.nosp@m.dmin..nosp@m.org
© 2012 Ken Sarkies ksark.nosp@m.ies@.nosp@m.inter.nosp@m.node.nosp@m..on.n.nosp@m.et
Devices can have up to three I2C peripherals. The peripherals support SMBus and PMBus variants.
A peripheral begins after reset in Slave mode. To become a Master a start condition must be generated. The peripheral will remain in Master mode unless a multimaster contention is lost or a stop condition is generated.
Function Documentation
void i2c_100khz_i2cclk8mhz (uint32_t i2c)
Definition at line 237 of file i2c.c.
References i2c_set_data_hold_time(), i2c_set_data_setup_time(), i2c_set_prescaler(), i2c_set_scl_high_period(), and i2c_set_scl_low_period().
uint8_t i2c_busy (uint32_t i2c)
Definition at line 312 of file i2c.c.
References I2C_ISR, and I2C_ISR_BUSY.
Referenced by read_i2c(), and write_i2c().
void i2c_clear_dma_last_transfer (uint32_t i2c)
I2C Clear DMA last transfer.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 415 of file i2c_common_all.c.
References I2C_CR2, and I2C_CR2_LAST.
void i2c_clear_stop (uint32_t i2c)
I2C Clear Stop Flag.
Clear the "Send Stop" flag in the I2C config register
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 122 of file i2c.c.
References I2C_CR1, I2C_CR1_STOP, I2C_ICR, and I2C_ICR_STOPCF.
void i2c_disable_ack (uint32_t i2c)
I2C Disable ACK.
Disables acking of own 7/10 bit address
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 337 of file i2c_common_all.c.
References I2C_CR1, and I2C_CR1_ACK.
void i2c_disable_analog_filter (uint32_t i2c)
Definition at line 186 of file i2c.c.
References I2C_CR1, and I2C_CR1_ANFOFF.
void i2c_disable_autoend (uint32_t i2c)
Definition at line 298 of file i2c.c.
References I2C_CR2, and I2C_CR2_AUTOEND.
Referenced by read_i2c().
void i2c_disable_dma (uint32_t i2c)
I2C Disable DMA.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 395 of file i2c_common_all.c.
References I2C_CR2, and I2C_CR2_DMAEN.
void i2c_disable_interrupt (uint32_t i2c, uint32_t interrupt)
I2C Disable Interrupt.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
[in] interrupt Unsigned int32. Interrupt to disable.
Definition at line 366 of file i2c.c.
References I2C_CR1, and I2C_CR2.
void i2c_disable_rxdma (uint32_t i2c)
I2C Disable reception DMA.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 386 of file i2c.c.
References I2C_CR1, and I2C_CR1_RXDMAEN.
void i2c_disable_stretching (uint32_t i2c)
Definition at line 232 of file i2c.c.
References I2C_CR1, and I2C_CR1_NOSTRETCH.
void i2c_disable_txdma (uint32_t i2c)
I2C Disable transmission DMA.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 406 of file i2c.c.
References I2C_CR1, and I2C_CR1_TXDMAEN.
void i2c_enable_ack (uint32_t i2c)
I2C Enable ACK.
Enables acking of own 7/10 bit address
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 326 of file i2c_common_all.c.
References I2C_CR1, and I2C_CR1_ACK.
void i2c_enable_analog_filter (uint32_t i2c)
Definition at line 181 of file i2c.c.
References I2C_CR1, and I2C_CR1_ANFOFF.
void i2c_enable_autoend (uint32_t i2c)
Definition at line 293 of file i2c.c.
References I2C_CR2, and I2C_CR2_AUTOEND.
Referenced by read_i2c(), and write_i2c().
void i2c_enable_dma (uint32_t i2c)
I2C Enable DMA.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 385 of file i2c_common_all.c.
References I2C_CR2, and I2C_CR2_DMAEN.
void i2c_enable_interrupt (uint32_t i2c, uint32_t interrupt)
I2C Enable Interrupt.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
[in] interrupt Unsigned int32. Interrupt to enable.
Definition at line 355 of file i2c.c.
References I2C_CR1, and I2C_CR2.
void i2c_enable_rxdma (uint32_t i2c)
I2C Enable reception DMA.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 376 of file i2c.c.
References I2C_CR1, and I2C_CR1_RXDMAEN.
void i2c_enable_stretching (uint32_t i2c)
Definition at line 227 of file i2c.c.
References I2C_CR1, and I2C_CR1_NOSTRETCH.
void i2c_enable_txdma (uint32_t i2c)
I2C Enable transmission DMA.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 396 of file i2c.c.
References I2C_CR1, and I2C_CR1_TXDMAEN.
uint8_t i2c_get_data (uint32_t i2c)
I2C Get Data.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 176 of file i2c.c.
References I2C_DR, and I2C_RXDR.
Referenced by read_i2c().
uint8_t i2c_is_start (uint32_t i2c)
Definition at line 284 of file i2c.c.
References I2C_CR2, and I2C_CR2_START.
Referenced by read_i2c(), and write_i2c().
uint8_t i2c_nack (uint32_t i2c)
Definition at line 303 of file i2c.c.
References I2C_ISR, and I2C_ISR_NACKF.
Referenced by read_i2c(), and write_i2c().
void i2c_nack_current (uint32_t i2c)
I2C NACK Next Byte.
Causes the I2C controller to NACK the reception of the current byte
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 360 of file i2c_common_all.c.
References I2C_CR1, and I2C_CR1_POS.
void i2c_nack_next (uint32_t i2c)
I2C NACK Next Byte.
Causes the I2C controller to NACK the reception of the next byte
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 348 of file i2c_common_all.c.
References I2C_CR1, and I2C_CR1_POS.
void i2c_peripheral_disable (uint32_t i2c)
I2C Peripheral Disable.
This must not be reset while in Master mode until a communication has finished. In Slave mode, the peripheral is disabled only after communication has ended.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 81 of file i2c.c.
References I2C_CR1, and I2C_CR1_PE.
void i2c_peripheral_enable (uint32_t i2c)
I2C Peripheral Enable.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 66 of file i2c.c.
References I2C_CR1, and I2C_CR1_PE.
uint8_t i2c_received_data (uint32_t i2c)
Definition at line 339 of file i2c.c.
References I2C_ISR, and I2C_ISR_RXNE.
Referenced by read_i2c().
void i2c_reset (uint32_t i2c)
I2C Reset.
The I2C peripheral and all its associated configuration registers are placed in the reset condition. The reset is effected via the RCC peripheral reset system.
Parameters
[in] i2c Unsigned int32. I2C peripheral identifier I2C register base address.
Definition at line 46 of file i2c.c.
References I2C1, I2C2, RCC_APB1RSTR, RCC_APB1RSTR_I2C1RST, RCC_APB1RSTR_I2C2RST, rcc_periph_reset_pulse(), rcc_peripheral_clear_reset(), rcc_peripheral_reset(), RST_I2C1, and RST_I2C2.
void i2c_send_7bit_address (uint32_t i2c, uint8_t slave, uint8_t readwrite)
I2C Send the 7-bit Slave Address.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
[in] slave Unsigned int16. Slave address 0...1023.
[in] readwrite Unsigned int8. Single bit to instruct slave to receive or send I2C Read/Write bit.
Definition at line 283 of file i2c_common_all.c.
References I2C_DR.
void i2c_send_data (uint32_t i2c, uint8_t data)
I2C Send Data.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
[in] data Unsigned int8. Byte to send.
Definition at line 166 of file i2c.c.
References I2C_DR, and I2C_TXDR.
Referenced by read_i2c(), and write_i2c().
void i2c_send_start (uint32_t i2c)
I2C Send Start Condition.
If in Master mode this will cause a restart condition to occur at the end of the current transmission. If in Slave mode, this will initiate a start condition when the current bus activity is completed.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 96 of file i2c.c.
References I2C_CR1, I2C_CR1_START, I2C_CR2, and I2C_CR2_START.
Referenced by read_i2c(), and write_i2c().
void i2c_send_stop (uint32_t i2c)
I2C Send Stop Condition.
After the current byte transfer this will initiate a stop condition if in Master mode, or simply release the bus if in Slave mode.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 110 of file i2c.c.
References I2C_CR1, I2C_CR1_STOP, I2C_CR2, and I2C_CR2_STOP.
void i2c_set_10bit_addr_mode (uint32_t i2c)
Definition at line 251 of file i2c.c.
References I2C_CR2, and I2C_CR2_ADD10.
void i2c_set_10bit_address (uint32_t i2c, uint16_t addr)
Definition at line 262 of file i2c.c.
References I2C_CR2, I2C_CR2_SADD_10BIT_MASK, and I2C_CR2_SADD_10BIT_SHIFT.
void i2c_set_7bit_addr_mode (uint32_t i2c)
Definition at line 246 of file i2c.c.
References I2C_CR2, and I2C_CR2_ADD10.
void i2c_set_7bit_address (uint32_t i2c, uint8_t addr)
Definition at line 256 of file i2c.c.
References I2C_CR2, I2C_CR2_SADD_7BIT_MASK, and I2C_CR2_SADD_7BIT_SHIFT.
Referenced by read_i2c(), and write_i2c().
void i2c_set_bytes_to_transfer (uint32_t i2c, uint32_t n_bytes)
Definition at line 278 of file i2c.c.
References I2C_CR2, I2C_CR2_NBYTES_MASK, and I2C_CR2_NBYTES_SHIFT.
Referenced by read_i2c(), and write_i2c().
void i2c_set_ccr (uint32_t i2c, uint16_t freq)
I2C Set Bus Clock Frequency.
Set the bus clock frequency. This is a 12 bit number (0...4095) calculated from the formulae given in the STM32F1 reference manual in the description of the CCR field. It is a divisor of the peripheral clock frequency i2c_set_clock_frequency modified by the fast mode setting i2c_set_fast_mode
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
[in] freq Unsigned int16. Bus Clock Frequency Setting 0...4095.
Definition at line 248 of file i2c_common_all.c.
References I2C_CCR.
void i2c_set_clock_frequency (uint32_t i2c, uint8_t freq)
I2C Set Peripheral Clock Frequency.
Set the peripheral clock frequency: 2MHz to 36MHz (the APB frequency). Note that this is not the I2C bus clock. This is set in conjunction with the Clock Control register to generate the Master bus clock, see i2c_set_ccr
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
[in] freq Unsigned int8. Clock Frequency Setting I2C clock frequency settings.
Definition at line 185 of file i2c_common_all.c.
References I2C_CR2.
void i2c_set_data_hold_time (uint32_t i2c, uint8_t h_time)
Definition at line 209 of file i2c.c.
References I2C_TIMINGR, I2C_TIMINGR_SDADEL_MASK, and I2C_TIMINGR_SDADEL_SHIFT.
Referenced by i2c_100khz_i2cclk8mhz().
void i2c_set_data_setup_time (uint32_t i2c, uint8_t s_time)
Definition at line 203 of file i2c.c.
References I2C_TIMINGR, I2C_TIMINGR_SCLDEL_MASK, and I2C_TIMINGR_SCLDEL_SHIFT.
Referenced by i2c_100khz_i2cclk8mhz().
void i2c_set_digital_filter (uint32_t i2c, uint8_t dnf_setting)
Definition at line 191 of file i2c.c.
References I2C_CR1, and I2C_CR1_DNF_MASK.
void i2c_set_dma_last_transfer (uint32_t i2c)
I2C Set DMA last transfer.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 405 of file i2c_common_all.c.
References I2C_CR2, and I2C_CR2_LAST.
void i2c_set_dutycycle (uint32_t i2c, uint32_t dutycycle)
I2C Set clock duty cycle.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
[in] dutycycle Unsigned int32. I2C duty cycle I2C peripheral clock duty cycles.
Definition at line 371 of file i2c_common_all.c.
References I2C_CCR, I2C_CCR_DUTY, and I2C_CCR_DUTY_DIV2.
void i2c_set_fast_mode (uint32_t i2c)
I2C Set Fast Mode.
Set the clock frequency to the high clock rate mode (up to 400kHz). The actual clock frequency must be set with i2c_set_clock_frequency
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 214 of file i2c_common_all.c.
References I2C_CCR, and I2C_CCR_FS.
void i2c_set_own_10bit_slave_address (uint32_t i2c, uint16_t slave)
I2C Set the 10 bit Slave Address for the Peripheral.
This sets an address for Slave mode operation, in 10 bit form.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
[in] slave Unsigned int16. Slave address 0...1023.
This sets an address for Slave mode operation, in 10 bit form.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
[in] slave Unsigned int16. Slave address 0...1023.
Definition at line 154 of file i2c.c.
References I2C_OAR1, I2C_OAR1_ADDMODE, and I2C_OAR1_OA1MODE.
void i2c_set_own_7bit_slave_address (uint32_t i2c, uint8_t slave)
I2C Set the 7 bit Slave Address for the Peripheral.
This sets an address for Slave mode operation, in 7 bit form.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
[in] slave Unsigned int8. Slave address 0...127.
Definition at line 136 of file i2c.c.
References I2C_OAR1, and I2C_OAR1_OA1MODE.
void i2c_set_prescaler (uint32_t i2c, uint8_t presc)
Definition at line 197 of file i2c.c.
References I2C_TIMINGR, I2C_TIMINGR_PRESC_MASK, and I2C_TIMINGR_PRESC_SHIFT.
Referenced by i2c_100khz_i2cclk8mhz().
void i2c_set_read_transfer_dir (uint32_t i2c)
Definition at line 273 of file i2c.c.
References I2C_CR2, and I2C_CR2_RD_WRN.
Referenced by read_i2c().
void i2c_set_scl_high_period (uint32_t i2c, uint8_t period)
Definition at line 215 of file i2c.c.
References I2C_TIMINGR, I2C_TIMINGR_SCLH_MASK, and I2C_TIMINGR_SCLH_SHIFT.
Referenced by i2c_100khz_i2cclk8mhz().
void i2c_set_scl_low_period (uint32_t i2c, uint8_t period)
Definition at line 221 of file i2c.c.
References I2C_TIMINGR, I2C_TIMINGR_SCLL_MASK, and I2C_TIMINGR_SCLL_SHIFT.
Referenced by i2c_100khz_i2cclk8mhz().
void i2c_set_standard_mode (uint32_t i2c)
I2C Set Standard Mode.
Set the clock frequency to the standard clock rate mode (up to 100kHz). The actual clock frequency must be set with i2c_set_clock_frequency
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
Definition at line 228 of file i2c_common_all.c.
References I2C_CCR, and I2C_CCR_FS.
void i2c_set_trise (uint32_t i2c, uint16_t trise)
I2C Set the Rise Time.
Set the maximum rise time on the bus according to the I2C specification, as 1 more than the specified rise time in peripheral clock cycles. This is a 6 bit number.
Parameters
[in] i2c Unsigned int32. I2C register base address I2C register base address.
[in] trise Unsigned int16. Rise Time Setting 0...63.
Definition at line 269 of file i2c_common_all.c.
References I2C_TRISE.
void i2c_set_write_transfer_dir (uint32_t i2c)
Definition at line 268 of file i2c.c.
References I2C_CR2, and I2C_CR2_RD_WRN.
Referenced by read_i2c(), and write_i2c().
uint8_t i2c_transfer_complete (uint32_t i2c)
Definition at line 330 of file i2c.c.
References I2C_ISR, and I2C_ISR_TC.
uint8_t i2c_transmit_int_status (uint32_t i2c)
Definition at line 321 of file i2c.c.
References I2C_ISR, and I2C_ISR_TXIS.
Referenced by read_i2c(), and write_i2c().
void read_i2c (uint32_t i2c, uint8_t i2c_addr, uint8_t reg, uint8_t size, uint8_t * data)
Definition at line 447 of file i2c.c.
References i2c_busy(), i2c_disable_autoend(), i2c_enable_autoend(), i2c_get_data(), i2c_is_start(), i2c_nack(), i2c_received_data(), i2c_send_data(), i2c_send_start(), i2c_set_7bit_address(), i2c_set_bytes_to_transfer(), i2c_set_read_transfer_dir(), i2c_set_write_transfer_dir(), and i2c_transmit_int_status().
void write_i2c (uint32_t i2c, uint8_t i2c_addr, uint8_t reg, uint8_t size, uint8_t * data)
Definition at line 411 of file i2c.c.
References i2c_busy(), i2c_enable_autoend(), i2c_is_start(), i2c_nack(), i2c_send_data(), i2c_send_start(), i2c_set_7bit_address(), i2c_set_bytes_to_transfer(), i2c_set_write_transfer_dir(), and i2c_transmit_int_status().