libopencm3: rcc.c File Reference
rcc.c File Reference
#include <libopencm3/cm3/assert.h>
#include <libopencm3/stm32/f3/rcc.h>
#include <libopencm3/stm32/f3/flash.h>
#include <libopencm3/stm32/f3/i2c.h>
Functions
void rcc_osc_ready_int_clear (enum osc osc)
void rcc_osc_ready_int_enable (enum osc osc)
void rcc_osc_ready_int_disable (enum osc osc)
int rcc_osc_ready_int_flag (enum osc osc)
void rcc_css_int_clear (void)
int rcc_css_int_flag (void)
void rcc_wait_for_osc_ready (enum osc osc)
void rcc_wait_for_osc_not_ready (enum osc osc)
void rcc_wait_for_sysclk_status (enum osc osc)
void rcc_osc_on (enum osc osc)
void rcc_osc_off (enum osc osc)
void rcc_css_enable (void)
void rcc_css_disable (void)
void rcc_osc_bypass_enable (enum osc osc)
void rcc_osc_bypass_disable (enum osc osc)
void rcc_peripheral_enable_clock (volatile uint32_t *reg, uint32_t en)
void rcc_peripheral_disable_clock (volatile uint32_t *reg, uint32_t en)
void rcc_peripheral_reset (volatile uint32_t *reg, uint32_t reset)
void rcc_peripheral_clear_reset (volatile uint32_t *reg, uint32_t clear_reset)
void rcc_set_sysclk_source (uint32_t clk)
void rcc_set_pll_source (uint32_t pllsrc)
void rcc_set_ppre2 (uint32_t ppre2)
void rcc_set_ppre1 (uint32_t ppre1)
void rcc_set_hpre (uint32_t hpre)
void rcc_set_main_pll_hsi (uint32_t pll)
uint32_t rcc_get_system_clock_source (void)
void rcc_clock_setup_hsi (const clock_scale_t *clock)
void rcc_backupdomain_reset (void)
void rcc_set_i2c_clock_hsi (uint32_t i2c)
void rcc_set_i2c_clock_sysclk (uint32_t i2c)
uint32_t rcc_get_i2c_clocks (void)
void rcc_usb_prescale_1_5 (void)
void rcc_usb_prescale_1 (void)
Variables
uint32_t rcc_ppre1_frequency = 8000000
uint32_t rcc_ppre2_frequency = 8000000
const clock_scale_t hsi_8mhz [CLOCK_END]
Function Documentation
void rcc_backupdomain_reset (void)
Definition at line 440 of file rcc.c.
References RCC_BDCR, and RCC_BDCR_BDRST.
void rcc_clock_setup_hsi (const clock_scale_t * clock)
Definition at line 404 of file rcc.c.
References clock_scale_t::apb1_frequency, clock_scale_t::apb2_frequency, clock_scale_t::flash_config, flash_set_ws(), clock_scale_t::hpre, HSI, clock_scale_t::pll, PLL, clock_scale_t::pllsrc, clock_scale_t::ppre1, clock_scale_t::ppre2, RCC_CFGR_SW_HSI, RCC_CFGR_SW_PLL, rcc_osc_off(), rcc_osc_on(), rcc_ppre1_frequency, rcc_ppre2_frequency, rcc_set_hpre(), rcc_set_main_pll_hsi(), rcc_set_pll_source(), rcc_set_ppre1(), rcc_set_ppre2(), rcc_set_sysclk_source(), rcc_wait_for_osc_not_ready(), rcc_wait_for_osc_ready(), and rcc_wait_for_sysclk_status().
void rcc_css_disable (void)
Definition at line 285 of file rcc.c.
References RCC_CR, and RCC_CR_CSSON.
void rcc_css_enable (void)
Definition at line 280 of file rcc.c.
References RCC_CR, and RCC_CR_CSSON.
void rcc_css_int_clear (void)
Definition at line 167 of file rcc.c.
References RCC_CIR, and RCC_CIR_CSSC.
int rcc_css_int_flag (void)
Definition at line 172 of file rcc.c.
References RCC_CIR, and RCC_CIR_CSSF.
uint32_t rcc_get_i2c_clocks (void)
Definition at line 469 of file rcc.c.
References RCC_CFGR3, RCC_CFGR3_I2C1SW, and RCC_CFGR3_I2C2SW.
uint32_t rcc_get_system_clock_source (void)
Definition at line 397 of file rcc.c.
References RCC_CFGR.
void rcc_osc_bypass_disable (enum osc osc)
Definition at line 307 of file rcc.c.
References HSE, HSI, LSE, LSI, PLL, RCC_BDCR, RCC_BDCR_LSEBYP, RCC_CR, and RCC_CR_HSEBYP.
void rcc_osc_bypass_enable (enum osc osc)
Definition at line 290 of file rcc.c.
References HSE, HSI, LSE, LSI, PLL, RCC_BDCR, RCC_BDCR_LSEBYP, RCC_CR, and RCC_CR_HSEBYP.
void rcc_osc_off (enum osc osc)
Definition at line 259 of file rcc.c.
References HSE, HSI, LSE, LSI, PLL, RCC_BDCR, RCC_BDCR_LSEON, RCC_CR, RCC_CR_HSEON, RCC_CR_HSION, RCC_CR_PLLON, RCC_CSR, and RCC_CSR_LSION.
Referenced by rcc_clock_setup_hsi().
void rcc_osc_on (enum osc osc)
Definition at line 238 of file rcc.c.
References HSE, HSI, LSE, LSI, PLL, RCC_BDCR, RCC_BDCR_LSEON, RCC_CR, RCC_CR_HSEON, RCC_CR_HSION, RCC_CR_PLLON, RCC_CSR, and RCC_CSR_LSION.
Referenced by rcc_clock_setup_hsi().
void rcc_osc_ready_int_clear (enum osc osc)
Definition at line 81 of file rcc.c.
References HSE, HSI, LSE, LSI, PLL, RCC_CIR, RCC_CIR_HSERDYC, RCC_CIR_HSIRDYC, RCC_CIR_LSERDYC, RCC_CIR_LSIRDYC, and RCC_CIR_PLLRDYC.
void rcc_osc_ready_int_disable (enum osc osc)
Definition at line 123 of file rcc.c.
References HSE, HSI, LSE, LSI, PLL, RCC_CIR, RCC_CIR_HSERDYIE, RCC_CIR_HSIRDYIE, RCC_CIR_LSERDYIE, RCC_CIR_LSIRDYIE, and RCC_CIR_PLLRDYIE.
void rcc_osc_ready_int_enable (enum osc osc)
Definition at line 102 of file rcc.c.
References HSE, HSI, LSE, LSI, PLL, RCC_CIR, RCC_CIR_HSERDYIE, RCC_CIR_HSIRDYIE, RCC_CIR_LSERDYIE, RCC_CIR_LSIRDYIE, and RCC_CIR_PLLRDYIE.
int rcc_osc_ready_int_flag (enum osc osc)
Definition at line 144 of file rcc.c.
References cm3_assert_not_reached, HSE, HSI, LSE, LSI, PLL, RCC_CIR, RCC_CIR_HSERDYF, RCC_CIR_HSIRDYF, RCC_CIR_LSERDYF, RCC_CIR_LSIRDYF, and RCC_CIR_PLLRDYF.
void rcc_peripheral_clear_reset (volatile uint32_t * reg, uint32_t clear_reset)
Definition at line 339 of file rcc.c.
Referenced by i2c_reset(), spi_reset(), and timer_reset().
void rcc_peripheral_disable_clock (volatile uint32_t * reg, uint32_t en)
Definition at line 329 of file rcc.c.
void rcc_peripheral_enable_clock (volatile uint32_t * reg, uint32_t en)
Definition at line 324 of file rcc.c.
void rcc_peripheral_reset (volatile uint32_t * reg, uint32_t reset)
Definition at line 334 of file rcc.c.
Referenced by i2c_reset(), spi_reset(), and timer_reset().
void rcc_set_hpre (uint32_t hpre)
Definition at line 380 of file rcc.c.
References RCC_CFGR.
Referenced by rcc_clock_setup_hsi().
void rcc_set_i2c_clock_hsi (uint32_t i2c)
Definition at line 449 of file rcc.c.
References I2C1, I2C2, RCC_CFGR3, RCC_CFGR3_I2C1SW, and RCC_CFGR3_I2C2SW.
void rcc_set_i2c_clock_sysclk (uint32_t i2c)
Definition at line 459 of file rcc.c.
References I2C1, I2C2, RCC_CFGR3, RCC_CFGR3_I2C1SW, and RCC_CFGR3_I2C2SW.
void rcc_set_main_pll_hsi (uint32_t pll)
Definition at line 390 of file rcc.c.
References RCC_CFGR, RCC_CFGR_PLLMUL_MASK, and RCC_CFGR_PLLMUL_SHIFT.
Referenced by rcc_clock_setup_hsi().
void rcc_set_pll_source (uint32_t pllsrc)
Definition at line 353 of file rcc.c.
References RCC_CFGR, and RCC_CFGR_PLLSRC.
Referenced by rcc_clock_setup_hsi().
void rcc_set_ppre1 (uint32_t ppre1)
Definition at line 371 of file rcc.c.
References RCC_CFGR.
Referenced by rcc_clock_setup_hsi().
void rcc_set_ppre2 (uint32_t ppre2)
Definition at line 362 of file rcc.c.
References RCC_CFGR.
Referenced by rcc_clock_setup_hsi().
void rcc_set_sysclk_source (uint32_t clk)
Definition at line 344 of file rcc.c.
References RCC_CFGR.
Referenced by rcc_clock_setup_hsi().
void rcc_usb_prescale_1 (void)
Definition at line 479 of file rcc.c.
References RCC_CFGR, and RCC_CFGR_USBPRES.
void rcc_usb_prescale_1_5 (void)
Definition at line 474 of file rcc.c.
References RCC_CFGR, and RCC_CFGR_USBPRES.
void rcc_wait_for_osc_not_ready (enum osc osc)
Definition at line 199 of file rcc.c.
References HSE, HSI, LSE, LSI, PLL, RCC_BDCR, RCC_BDCR_LSERDY, RCC_CR, RCC_CR_HSERDY, RCC_CR_HSIRDY, RCC_CR_PLLRDY, RCC_CSR, and RCC_CSR_LSIRDY.
Referenced by rcc_clock_setup_hsi().
void rcc_wait_for_osc_ready (enum osc osc)
Definition at line 177 of file rcc.c.
References HSE, HSI, LSE, LSI, PLL, RCC_BDCR, RCC_BDCR_LSERDY, RCC_CR, RCC_CR_HSERDY, RCC_CR_HSIRDY, RCC_CR_PLLRDY, RCC_CSR, and RCC_CSR_LSIRDY.
Referenced by rcc_clock_setup_hsi().
void rcc_wait_for_sysclk_status (enum osc osc)
Definition at line 220 of file rcc.c.
References HSE, HSI, PLL, RCC_CFGR, RCC_CFGR_SWS_HSE, RCC_CFGR_SWS_HSI, and RCC_CFGR_SWS_PLL.
Referenced by rcc_clock_setup_hsi().
Variable Documentation
const clock_scale_t hsi_8mhz[CLOCK_END]
Definition at line 45 of file rcc.c.
uint32_t rcc_ppre1_frequency = 8000000
Definition at line 42 of file rcc.c.
Referenced by rcc_clock_setup_hsi(), and usart_set_baudrate().
uint32_t rcc_ppre2_frequency = 8000000
Definition at line 43 of file rcc.c.
Referenced by rcc_clock_setup_hsi(), and usart_set_baudrate().