libopencm3: Flash_file
Flash_file
Functions
void flash_prefetch_buffer_enable (void)
Enable the FLASH Prefetch Buffer.
void flash_prefetch_buffer_disable (void)
Disable the FLASH Prefetch Buffer.
void flash_set_ws (uint32_t ws)
Set the Number of Wait States.
void flash_unlock (void)
Unlock the Flash Program and Erase Controller.
void flash_lock (void)
Lock the Flash Program and Erase Controller.
void flash_clear_pgerr_flag (void)
Clear the Programming Error Status Flag.
void flash_clear_eop_flag (void)
Clear the End of Operation Status Flag.
void flash_clear_wrprterr_flag (void)
Clear the Write Protect Error Status Flag.
void flash_clear_bsy_flag (void)
Clear the Busy Status Flag.
void flash_wait_for_last_operation (void)
Wait until Last Operation has Ended.
void flash_program_word (uint32_t address, uint32_t data)
Program a 32 bit Word to FLASH.
void flash_unlock_option_bytes (void)
Unlock the Option Byte Access.
void flash_erase_option_bytes (void)
Erase All Option Bytes.
void flash_program_option_bytes (uint32_t address, uint16_t data)
Program the Option Bytes.
void flash_clear_pgperr_flag (void)
Clear the Programming Error Status Flag.
static void flash_set_program_size (uint32_t psize)
Set the Program Parallelism Size.
void flash_dcache_enable (void)
Enable the Data Cache.
void flash_dcache_disable (void)
Disable the Data Cache.
void flash_icache_enable (void)
Enable the Instruction Cache.
void flash_icache_disable (void)
Disable the Instruction Cache.
void flash_prefetch_enable (void)
Enable the FLASH Prefetch Buffer.
void flash_prefetch_disable (void)
Disable the FLASH Prefetch Buffer.
void flash_dcache_reset (void)
Reset the Data Cache.
void flash_icache_reset (void)
Reset the Instruction Cache.
void flash_clear_pgserr_flag (void)
Clear the Programming Sequence Error Flag.
void flash_clear_pgaerr_flag (void)
Clear the Programming Alignment Error Flag.
void flash_clear_wrperr_flag (void)
Clear the Write Protect Error Flag.
void flash_clear_status_flags (void)
Clear All Status Flags.
void flash_lock_option_bytes (void)
Lock the Option Byte Access.
void flash_program_double_word (uint32_t address, uint64_t data)
Program a 64 bit Word to FLASH.
void flash_program_half_word (uint32_t address, uint16_t data)
Program a Half Word to FLASH.
void flash_program_byte (uint32_t address, uint8_t data)
Program an 8 bit Byte to FLASH.
void flash_program (uint32_t address, uint8_t *data, uint32_t len)
Program a Data Block to FLASH.
void flash_erase_sector (uint8_t sector, uint32_t program_size)
Erase a Sector of FLASH.
void flash_erase_all_sectors (uint32_t program_size)
Erase All FLASH.
void flash_program_option_bytes (uint32_t data)
Program the Option Bytes.
Detailed Description
Function Documentation
void flash_clear_bsy_flag (void)
Clear the Busy Status Flag.
Definition at line 135 of file flash_common_f01.c.
References FLASH_SR, and FLASH_SR_BSY.
Referenced by flash_clear_status_flags().
void flash_clear_eop_flag (void)
Clear the End of Operation Status Flag.
Definition at line 115 of file flash_common_f01.c.
References FLASH_SR, and FLASH_SR_EOP.
Referenced by flash_clear_status_flags().
void flash_clear_pgaerr_flag (void)
Clear the Programming Alignment Error Flag.
Definition at line 151 of file flash_common_f24.c.
References FLASH_SR, and FLASH_SR_PGAERR.
Referenced by flash_clear_status_flags().
void flash_clear_pgerr_flag (void)
Clear the Programming Error Status Flag.
Definition at line 105 of file flash_common_f01.c.
References FLASH_SR, and FLASH_SR_PGERR.
void flash_clear_pgperr_flag (void)
Clear the Programming Error Status Flag.
Definition at line 83 of file flash_common_f234.c.
References FLASH_SR, and FLASH_SR_PGPERR.
Referenced by flash_clear_status_flags().
void flash_clear_pgserr_flag (void)
Clear the Programming Sequence Error Flag.
This flag is set when incorrect programming configuration has been made.
Definition at line 141 of file flash_common_f24.c.
References FLASH_SR, and FLASH_SR_PGSERR.
Referenced by flash_clear_status_flags().
void flash_clear_status_flags (void)
Clear All Status Flags.
Program error, end of operation, write protect error, busy.
Definition at line 172 of file flash_common_f24.c.
References flash_clear_bsy_flag(), flash_clear_eop_flag(), flash_clear_pgaerr_flag(), flash_clear_pgperr_flag(), flash_clear_pgserr_flag(), and flash_clear_wrperr_flag().
void flash_clear_wrperr_flag (void)
Clear the Write Protect Error Flag.
Definition at line 161 of file flash_common_f24.c.
References FLASH_SR, and FLASH_SR_WRPERR.
Referenced by flash_clear_status_flags().
void flash_clear_wrprterr_flag (void)
Clear the Write Protect Error Status Flag.
Definition at line 125 of file flash_common_f01.c.
References FLASH_SR, and FLASH_SR_WRPRTERR.
void flash_dcache_disable (void)
Disable the Data Cache.
Definition at line 59 of file flash_common_f24.c.
References FLASH_ACR, and FLASH_ACR_DCE.
void flash_dcache_enable (void)
Enable the Data Cache.
Definition at line 49 of file flash_common_f24.c.
References FLASH_ACR, and FLASH_ACR_DCE.
void flash_dcache_reset (void)
Reset the Data Cache.
The data cache must be disabled for this to have effect.
Definition at line 119 of file flash_common_f24.c.
References FLASH_ACR, and FLASH_ACR_DCRST.
void flash_erase_all_sectors (uint32_t program_size)
Erase All FLASH.
This performs all operations necessary to erase all sectors in the FLASH memory.
Parameters
program_size 0 (8-bit), 1 (16-bit), 2 (32-bit), 3 (64-bit)
Definition at line 381 of file flash_common_f24.c.
References FLASH_CR, FLASH_CR_MER, FLASH_CR_STRT, flash_set_program_size(), and flash_wait_for_last_operation().
void flash_erase_option_bytes (void)
Erase All Option Bytes.
This performs all operations necessary to erase the option bytes. These must first be fully erased before attempting to program them, therefore it is recommended to check these after an erase attempt.
Definition at line 193 of file flash_common_f01.c.
References FLASH_CR, FLASH_CR_OPTER, FLASH_CR_OPTWRE, FLASH_CR_STRT, flash_unlock_option_bytes(), and flash_wait_for_last_operation().
void flash_erase_sector (uint8_t sector, uint32_t program_size)
Erase a Sector of FLASH.
This performs all operations necessary to erase a sector in FLASH memory. The page should be checked to ensure that it was properly erased. A sector must first be fully erased before attempting to program it.
See the reference manual or the FLASH programming manual for details.
Parameters
[in] uint32_t sector (0 - 11 for some parts, 0-23 on others)
program_size 0 (8-bit), 1 (16-bit), 2 (32-bit), 3 (64-bit)
Definition at line 357 of file flash_common_f24.c.
References FLASH_CR, FLASH_CR_SER, FLASH_CR_SNB_MASK, FLASH_CR_SNB_SHIFT, FLASH_CR_STRT, flash_set_program_size(), and flash_wait_for_last_operation().
void flash_icache_disable (void)
Disable the Instruction Cache.
Definition at line 79 of file flash_common_f24.c.
References FLASH_ACR, and FLASH_ACR_ICE.
void flash_icache_enable (void)
Enable the Instruction Cache.
Definition at line 69 of file flash_common_f24.c.
References FLASH_ACR, and FLASH_ACR_ICE.
void flash_icache_reset (void)
Reset the Instruction Cache.
The instruction cache must be disabled for this to have effect.
Definition at line 130 of file flash_common_f24.c.
References FLASH_ACR, and FLASH_ACR_ICRST.
void flash_lock (void)
Lock the Flash Program and Erase Controller.
Used to prevent spurious writes to FLASH.
Definition at line 95 of file flash_common_f01.c.
References FLASH_CR, and FLASH_CR_LOCK.
void flash_lock_option_bytes (void)
Lock the Option Byte Access.
This disables write access to the option bytes. It is locked by default on reset.
Definition at line 206 of file flash_common_f24.c.
References FLASH_OPTCR, and FLASH_OPTCR_OPTLOCK.
void flash_prefetch_buffer_disable (void)
Disable the FLASH Prefetch Buffer.
Note carefully the clock restrictions under which the prefetch buffer may be set to disabled. See the reference manual for details.
Definition at line 52 of file flash_common_f01.c.
References FLASH_ACR, and FLASH_ACR_PRFTBE.
void flash_prefetch_buffer_enable (void)
Enable the FLASH Prefetch Buffer.
This buffer is used for instruction fetches and is enabled by default after reset.
Note carefully the clock restrictions under which the prefetch buffer may be enabled or disabled. Changes are normally made while the clock is running in the power-on low frequency mode before being set to a higher speed mode. See the reference manual for details.
Definition at line 40 of file flash_common_f01.c.
References FLASH_ACR, and FLASH_ACR_PRFTBE.
void flash_prefetch_disable (void)
Disable the FLASH Prefetch Buffer.
Note carefully the clock restrictions under which the prefetch buffer may be set to disabled. See the reference manual for details.
Definition at line 108 of file flash_common_f24.c.
References FLASH_ACR, and FLASH_ACR_PRFTEN.
void flash_prefetch_enable (void)
Enable the FLASH Prefetch Buffer.
This buffer is used for instruction fetches and is enabled by default after reset.
Note carefully the clock restrictions under which the prefetch buffer may be enabled or disabled. Changes are normally made while the clock is running in the power-on low frequency mode before being set to a higher speed mode. See the reference manual for details.
Definition at line 96 of file flash_common_f24.c.
References FLASH_ACR, and FLASH_ACR_PRFTEN.
void flash_program (uint32_t address, uint8_t * data, uint32_t len)
Program a Data Block to FLASH.
This programs an arbitrary length data block to FLASH memory. The program error flag should be checked separately for the event that memory was not properly erased.
Parameters
[in] uint32_t address. Starting address in Flash.
[in] uint8_t *data. Pointer to start of data block.
[in] uint32_t len. Length of data block.
Definition at line 333 of file flash_common_f24.c.
References flash_program_byte().
void flash_program_byte (uint32_t address, uint8_t data)
Program an 8 bit Byte to FLASH.
This performs all operations necessary to program an 8 bit byte to FLASH memory. The program error flag should be checked separately for the event that memory was not properly erased.
Parameters
[in] uint32_t address
[in] uint8_t data.
Definition at line 307 of file flash_common_f24.c.
References FLASH_CR, FLASH_CR_PG, FLASH_CR_PROGRAM_X8, flash_set_program_size(), and flash_wait_for_last_operation().
Referenced by flash_program().
void flash_program_double_word (uint32_t address, uint64_t data)
Program a 64 bit Word to FLASH.
This performs all operations necessary to program a 64 bit word to FLASH memory. The program error flag should be checked separately for the event that memory was not properly erased.
Parameters
[in] uint32_t address
[in] uint64_t data.
Definition at line 222 of file flash_common_f24.c.
References FLASH_CR, FLASH_CR_PG, FLASH_CR_PROGRAM_X64, flash_set_program_size(), and flash_wait_for_last_operation().
void flash_program_half_word (uint32_t address, uint16_t data)
Program a Half Word to FLASH.
This performs all operations necessary to program a 16 bit word to FLASH memory. The program error flag should be checked separately for the event that memory was not properly erased.
Parameters
[in] uint32_t address
[in] uint16_t data.
Definition at line 282 of file flash_common_f24.c.
References FLASH_CR, FLASH_CR_PG, FLASH_CR_PROGRAM_X16, flash_set_program_size(), and flash_wait_for_last_operation().
Referenced by flash_program_word().
void flash_program_option_bytes (uint32_t address, uint16_t data)
Program the Option Bytes.
This performs all operations necessary to program the option bytes. The write protect error flag should be checked separately for the event that an option byte had not been properly erased before calling this function.
Only the lower 8 bits of the data is significant.
Parameters
[in] uint32_t address. Address of option byte from flash_options.
[in] uint16_t data.
Definition at line 220 of file flash_common_f01.c.
References FLASH_CR, FLASH_CR_OPTPG, FLASH_CR_OPTWRE, flash_unlock_option_bytes(), and flash_wait_for_last_operation().
void flash_program_option_bytes (uint32_t data)
Program the Option Bytes.
This performs all operations necessary to program the option bytes. The option bytes do not need to be erased first.
Parameters
[in] uint32_t data to be programmed.
Definition at line 402 of file flash_common_f24.c.
References FLASH_OPTCR, FLASH_OPTCR_OPTLOCK, FLASH_OPTCR_OPTSTRT, flash_unlock_option_bytes(), and flash_wait_for_last_operation().
void flash_program_word (uint32_t address, uint32_t data)
Program a 32 bit Word to FLASH.
This performs all operations necessary to program a 32 bit word to FLASH memory. The program error flag should be checked separately for the event that memory was not properly erased.
Status bit polling is used to detect end of operation.
Parameters
[in] uint32_t address. Full address of flash word to be programmed.
[in] uint32_t data.
This performs all operations necessary to program a 32 bit word to FLASH memory. The program error flag should be checked separately for the event that memory was not properly erased.
Parameters
[in] uint32_t address
[in] uint32_t data.
Definition at line 165 of file flash_common_f01.c.
References FLASH_CR, FLASH_CR_PG, FLASH_CR_PROGRAM_X32, flash_program_half_word(), flash_set_program_size(), and flash_wait_for_last_operation().
static void flash_set_program_size (uint32_t psize) inline static
Set the Program Parallelism Size.
Set the programming word width. Note carefully the power supply voltage restrictions under which the different word sizes may be used. See the programming manual for more information.
Parameters
[in] psize The programming word width one of: Flash programming width
Definition at line 38 of file flash_common_f24.c.
References FLASH_CR, FLASH_CR_PROGRAM_MASK, and FLASH_CR_PROGRAM_SHIFT.
Referenced by flash_erase_all_sectors(), flash_erase_sector(), flash_program_byte(), flash_program_double_word(), flash_program_half_word(), and flash_program_word().
void flash_set_ws (uint32_t ws)
Set the Number of Wait States.
Used to match the system clock to the FLASH memory access time. See the reference manual for more information on clock speed ranges for each wait state. The latency must be changed to the appropriate value before any increase in clock speed, or after any decrease in clock speed.
Parameters
[in] uint32_t ws: values from flash_latency.
Used to match the system clock to the FLASH memory access time. See the programming manual for more information on clock speed ranges. The latency must be changed to the appropriate value before any increase in clock speed, or after any decrease in clock speed.
Parameters
[in] uint32_t ws: values from flash_latency.
Definition at line 67 of file flash_common_f01.c.
References FLASH_ACR, and FLASH_ACR_LATENCY.
void flash_unlock (void)
Unlock the Flash Program and Erase Controller.
This enables write access to the Flash memory. It is locked by default on reset.
Definition at line 79 of file flash_common_f01.c.
References FLASH_CR, FLASH_CR_LOCK, FLASH_KEYR, FLASH_KEYR_KEY1, and FLASH_KEYR_KEY2.
void flash_unlock_option_bytes (void)
Unlock the Option Byte Access.
This enables write access to the option bytes. It is locked by default on reset.
Definition at line 178 of file flash_common_f01.c.
References FLASH_KEYR_KEY1, FLASH_KEYR_KEY2, FLASH_OPTCR, FLASH_OPTCR_OPTLOCK, FLASH_OPTKEYR, FLASH_OPTKEYR_KEY1, and FLASH_OPTKEYR_KEY2.
Referenced by flash_erase_option_bytes(), and flash_program_option_bytes().
void flash_wait_for_last_operation (void)
Wait until Last Operation has Ended.
This loops indefinitely until an operation (write or erase) has completed by testing the busy flag.
Definition at line 147 of file flash_common_f01.c.
References flash_get_status_flags(), FLASH_SR, and FLASH_SR_BSY.
Referenced by flash_erase_all_sectors(), flash_erase_option_bytes(), flash_erase_sector(), flash_program_byte(), flash_program_double_word(), flash_program_half_word(), flash_program_option_bytes(), and flash_program_word().