libopencm3: exti_common_all.c File Reference
exti_common_all.c File Reference
#include <libopencm3/stm32/memorymap.h>
#include <libopencm3/stm32/exti.h>
#include <libopencm3/stm32/gpio.h>
#include <libopencm3/stm32/syscfg.h>
Functions
void exti_set_trigger (uint32_t extis, enum exti_trigger_type trig)
void exti_enable_request (uint32_t extis)
void exti_disable_request (uint32_t extis)
void exti_reset_request (uint32_t extis)
uint32_t exti_get_flag_status (uint32_t exti)
void exti_select_source (uint32_t exti, uint32_t gpioport)
Function Documentation
void exti_disable_request (uint32_t extis)
Definition at line 58 of file exti_common_all.c.
Referenced by rtc_disable_wakeup_timer_interrupt().
void exti_enable_request (uint32_t extis)
Definition at line 49 of file exti_common_all.c.
Referenced by rtc_enable_wakeup_timer_interrupt().
uint32_t exti_get_flag_status (uint32_t exti)
Definition at line 79 of file exti_common_all.c.
void exti_reset_request (uint32_t extis)
Definition at line 71 of file exti_common_all.c.
void exti_select_source (uint32_t exti, uint32_t gpioport)
Definition at line 90 of file exti_common_all.c.
void exti_set_trigger (uint32_t extis, enum exti_trigger_type trig)
Definition at line 31 of file exti_common_all.c.
Referenced by rtc_enable_wakeup_timer_interrupt().