libopencm3: flash_common_f234.c File Reference
flash_common_f234.c File Reference
#include <libopencm3/stm32/flash.h>
Functions
void flash_set_ws (uint32_t ws)
void flash_unlock (void)
void flash_lock (void)
void flash_clear_pgperr_flag (void)
void flash_clear_eop_flag (void)
void flash_clear_bsy_flag (void)
void flash_wait_for_last_operation (void)
Function Documentation
void flash_clear_bsy_flag (void)
Definition at line 58 of file flash_common_f234.c.
References FLASH_SR, and FLASH_SR_BSY.
Referenced by flash_clear_status_flags().
void flash_clear_eop_flag (void)
Definition at line 53 of file flash_common_f234.c.
References FLASH_SR, and FLASH_SR_EOP.
Referenced by flash_clear_status_flags().
void flash_clear_pgperr_flag (void)
Definition at line 48 of file flash_common_f234.c.
References FLASH_SR, and FLASH_SR_PGPERR.
Referenced by flash_clear_status_flags().
void flash_lock (void)
Definition at line 43 of file flash_common_f234.c.
References FLASH_CR, and FLASH_CR_LOCK.
void flash_set_ws (uint32_t ws)
Definition at line 23 of file flash_common_f234.c.
References FLASH_ACR.
Referenced by rcc_clock_setup_hse_3v3().
void flash_unlock (void)
Definition at line 33 of file flash_common_f234.c.
References FLASH_CR, FLASH_CR_LOCK, FLASH_KEYR, FLASH_KEYR_KEY1, and FLASH_KEYR_KEY2.
void flash_wait_for_last_operation (void)
Definition at line 64 of file flash_common_f234.c.
References FLASH_SR, and FLASH_SR_BSY.
Referenced by flash_erase_all_sectors(), flash_erase_sector(), flash_program_byte(), flash_program_double_word(), flash_program_half_word(), flash_program_option_bytes(), and flash_program_word().