libopencm3: flash.h File Reference
flash.h File Reference
#include <libopencm3/stm32/memorymap.h>
#include <libopencm3/cm3/common.h>
Macros
#define FLASH_ACR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x00)
#define FLASH_KEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x04)
#define FLASH_OPTKEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x08)
#define FLASH_SR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x0C)
#define FLASH_CR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x10)
#define FLASH_OPTCR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x14)
#define FLASH_ACR_DCRST (1 << 12)
#define FLASH_ACR_ICRST (1 << 11)
#define FLASH_ACR_DCE (1 << 10)
#define FLASH_ACR_ICE (1 << 9)
#define FLASH_ACR_PRFTEN (1 << 8)
#define FLASH_ACR_LATENCY_0WS 0x00
#define FLASH_ACR_LATENCY_1WS 0x01
#define FLASH_ACR_LATENCY_2WS 0x02
#define FLASH_ACR_LATENCY_3WS 0x03
#define FLASH_ACR_LATENCY_4WS 0x04
#define FLASH_ACR_LATENCY_5WS 0x05
#define FLASH_ACR_LATENCY_6WS 0x06
#define FLASH_ACR_LATENCY_7WS 0x07
#define FLASH_SR_BSY (1 << 16)
#define FLASH_SR_PGSERR (1 << 7)
#define FLASH_SR_PGPERR (1 << 6)
#define FLASH_SR_PGAERR (1 << 5)
#define FLASH_SR_WRPERR (1 << 4)
#define FLASH_SR_OPERR (1 << 1)
#define FLASH_SR_EOP (1 << 0)
#define FLASH_CR_LOCK (1 << 31)
#define FLASH_CR_ERRIE (1 << 25)
#define FLASH_CR_EOPIE (1 << 24)
#define FLASH_CR_STRT (1 << 16)
#define FLASH_CR_MER (1 << 2)
#define FLASH_CR_SER (1 << 1)
#define FLASH_CR_PG (1 << 0)
#define FLASH_CR_SECTOR_0 (0x00 << 3)
#define FLASH_CR_SECTOR_1 (0x01 << 3)
#define FLASH_CR_SECTOR_2 (0x02 << 3)
#define FLASH_CR_SECTOR_3 (0x03 << 3)
#define FLASH_CR_SECTOR_4 (0x04 << 3)
#define FLASH_CR_SECTOR_5 (0x05 << 3)
#define FLASH_CR_SECTOR_6 (0x06 << 3)
#define FLASH_CR_SECTOR_7 (0x07 << 3)
#define FLASH_CR_SECTOR_8 (0x08 << 3)
#define FLASH_CR_SECTOR_9 (0x09 << 3)
#define FLASH_CR_SECTOR_10 (0x0a << 3)
#define FLASH_CR_SECTOR_11 (0x0b << 3)
#define FLASH_CR_PROGRAM_X8 (0x00 << 8)
#define FLASH_CR_PROGRAM_X16 (0x01 << 8)
#define FLASH_CR_PROGRAM_X32 (0x02 << 8)
#define FLASH_CR_PROGRAM_X64 (0x03 << 8)
#define FLASH_OPTCR_NRST_STDBY (1 << 7)
#define FLASH_OPTCR_NRST_STOP (1 << 6)
#define FLASH_OPTCR_WDG_SW (1 << 5)
#define FLASH_OPTCR_OPTSTRT (1 << 1)
#define FLASH_OPTCR_OPTLOCK (1 << 0)
#define FLASH_OPTCR_BOR_LEVEL_3 (0x00 << 2)
#define FLASH_OPTCR_BOR_LEVEL_2 (0x01 << 2)
#define FLASH_OPTCR_BOR_LEVEL_1 (0x02 << 2)
#define FLASH_OPTCR_BOR_OFF (0x03 << 2)
#define FLASH_KEYR_KEY1 ((u32)0x45670123)
#define FLASH_KEYR_KEY2 ((u32)0xcdef89ab)
#define FLASH_OPTKEYR_KEY1 ((u32)0x08192a3b)
#define FLASH_OPTKEYR_KEY2 ((u32)0x4c5d6e7f)
Functions
BEGIN_DECLS void flash_dcache_enable (void)
void flash_dcache_disable (void)
void flash_icache_enable (void)
void flash_icache_disable (void)
void flash_prefetch_enable (void)
void flash_prefetch_disable (void)
void flash_dcache_reset (void)
void flash_icache_reset (void)
void flash_set_ws (u32 ws)
void flash_unlock (void)
void flash_lock (void)
void flash_clear_pgserr_flag (void)
void flash_clear_pgperr_flag (void)
void flash_clear_pgaerr_flag (void)
void flash_clear_eop_flag (void)
void flash_clear_wrperr_flag (void)
void flash_clear_bsy_flag (void)
void flash_clear_status_flags (void)
void flash_unlock_option_bytes (void)
void flash_lock_option_bytes (void)
void flash_erase_all_sectors (u32 program_size)
void flash_erase_sector (u32 sector, u32 program_size)
void flash_program_double_word (u32 address, u64 data, u32 program_size)
void flash_program_word (u32 address, u32 data, u32 program_size)
void flash_program_half_word (u32 address, u16 data, u32 program_size)
void flash_program_byte (u32 address, u8 data, u32 program_size)
void flash_wait_for_last_operation (void)
void flash_program_option_bytes (u32 data)
Macro Definition Documentation
#define FLASH_ACR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x00)
Definition at line 36 of file flash.h.
Referenced by flash_data_cache_enable(), flash_dcache_disable(), flash_dcache_reset(), flash_icache_disable(), flash_icache_enable(), flash_icache_reset(), flash_prefetch_disable(), flash_prefetch_enable(), and flash_set_ws().
#define FLASH_ACR_DCE (1 << 10)
Definition at line 47 of file flash.h.
Referenced by flash_data_cache_enable(), and flash_dcache_disable().
#define FLASH_ACR_DCRST (1 << 12)
Definition at line 45 of file flash.h.
Referenced by flash_dcache_reset().
#define FLASH_ACR_ICE (1 << 9)
Definition at line 48 of file flash.h.
Referenced by flash_icache_disable(), and flash_icache_enable().
#define FLASH_ACR_ICRST (1 << 11)
Definition at line 46 of file flash.h.
Referenced by flash_icache_reset().
#define FLASH_ACR_LATENCY_0WS 0x00
Definition at line 50 of file flash.h.
#define FLASH_ACR_LATENCY_1WS 0x01
Definition at line 51 of file flash.h.
#define FLASH_ACR_LATENCY_2WS 0x02
Definition at line 52 of file flash.h.
#define FLASH_ACR_LATENCY_3WS 0x03
Definition at line 53 of file flash.h.
#define FLASH_ACR_LATENCY_4WS 0x04
Definition at line 54 of file flash.h.
#define FLASH_ACR_LATENCY_5WS 0x05
Definition at line 55 of file flash.h.
#define FLASH_ACR_LATENCY_6WS 0x06
Definition at line 56 of file flash.h.
#define FLASH_ACR_LATENCY_7WS 0x07
Definition at line 57 of file flash.h.
#define FLASH_ACR_PRFTEN (1 << 8)
Definition at line 49 of file flash.h.
Referenced by flash_prefetch_disable(), and flash_prefetch_enable().
#define FLASH_CR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x10)
Definition at line 40 of file flash.h.
Referenced by flash_erase_all_sectors(), flash_erase_sector(), flash_lock(), flash_program_byte(), flash_program_double_word(), flash_program_half_word(), flash_program_word(), and flash_set_program_size().
#define FLASH_CR_EOPIE (1 << 24)
Definition at line 73 of file flash.h.
#define FLASH_CR_ERRIE (1 << 25)
Definition at line 72 of file flash.h.
#define FLASH_CR_LOCK (1 << 31)
Definition at line 71 of file flash.h.
Referenced by flash_lock().
#define FLASH_CR_MER (1 << 2)
Definition at line 75 of file flash.h.
Referenced by flash_erase_all_sectors().
#define FLASH_CR_PG (1 << 0)
Definition at line 77 of file flash.h.
Referenced by flash_program_byte(), flash_program_double_word(), flash_program_half_word(), and flash_program_word().
#define FLASH_CR_PROGRAM_X16 (0x01 << 8)
Definition at line 91 of file flash.h.
#define FLASH_CR_PROGRAM_X32 (0x02 << 8)
Definition at line 92 of file flash.h.
#define FLASH_CR_PROGRAM_X64 (0x03 << 8)
Definition at line 93 of file flash.h.
#define FLASH_CR_PROGRAM_X8 (0x00 << 8)
Definition at line 90 of file flash.h.
#define FLASH_CR_SECTOR_0 (0x00 << 3)
Definition at line 78 of file flash.h.
#define FLASH_CR_SECTOR_1 (0x01 << 3)
Definition at line 79 of file flash.h.
#define FLASH_CR_SECTOR_10 (0x0a << 3)
Definition at line 88 of file flash.h.
#define FLASH_CR_SECTOR_11 (0x0b << 3)
Definition at line 89 of file flash.h.
#define FLASH_CR_SECTOR_2 (0x02 << 3)
Definition at line 80 of file flash.h.
#define FLASH_CR_SECTOR_3 (0x03 << 3)
Definition at line 81 of file flash.h.
#define FLASH_CR_SECTOR_4 (0x04 << 3)
Definition at line 82 of file flash.h.
#define FLASH_CR_SECTOR_5 (0x05 << 3)
Definition at line 83 of file flash.h.
#define FLASH_CR_SECTOR_6 (0x06 << 3)
Definition at line 84 of file flash.h.
#define FLASH_CR_SECTOR_7 (0x07 << 3)
Definition at line 85 of file flash.h.
#define FLASH_CR_SECTOR_8 (0x08 << 3)
Definition at line 86 of file flash.h.
#define FLASH_CR_SECTOR_9 (0x09 << 3)
Definition at line 87 of file flash.h.
#define FLASH_CR_SER (1 << 1)
Definition at line 76 of file flash.h.
Referenced by flash_erase_sector().
#define FLASH_CR_STRT (1 << 16)
Definition at line 74 of file flash.h.
Referenced by flash_erase_all_sectors(), and flash_erase_sector().
#define FLASH_KEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x04)
Definition at line 37 of file flash.h.
Referenced by flash_unlock().
#define FLASH_KEYR_KEY1 ((u32)0x45670123)
Definition at line 111 of file flash.h.
Referenced by flash_unlock().
#define FLASH_KEYR_KEY2 ((u32)0xcdef89ab)
Definition at line 112 of file flash.h.
Referenced by flash_unlock().
#define FLASH_OPTCR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x14)
Definition at line 41 of file flash.h.
Referenced by flash_lock_option_bytes(), and flash_program_option_bytes().
#define FLASH_OPTCR_BOR_LEVEL_1 (0x02 << 2)
Definition at line 106 of file flash.h.
#define FLASH_OPTCR_BOR_LEVEL_2 (0x01 << 2)
Definition at line 105 of file flash.h.
#define FLASH_OPTCR_BOR_LEVEL_3 (0x00 << 2)
Definition at line 104 of file flash.h.
#define FLASH_OPTCR_BOR_OFF (0x03 << 2)
Definition at line 107 of file flash.h.
#define FLASH_OPTCR_NRST_STDBY (1 << 7)
Definition at line 99 of file flash.h.
#define FLASH_OPTCR_NRST_STOP (1 << 6)
Definition at line 100 of file flash.h.
#define FLASH_OPTCR_OPTLOCK (1 << 0)
Definition at line 103 of file flash.h.
Referenced by flash_lock_option_bytes(), and flash_program_option_bytes().
#define FLASH_OPTCR_OPTSTRT (1 << 1)
Definition at line 102 of file flash.h.
Referenced by flash_program_option_bytes().
#define FLASH_OPTCR_WDG_SW (1 << 5)
Definition at line 101 of file flash.h.
#define FLASH_OPTKEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x08)
Definition at line 38 of file flash.h.
Referenced by flash_unlock_option_bytes().
#define FLASH_OPTKEYR_KEY1 ((u32)0x08192a3b)
Definition at line 113 of file flash.h.
Referenced by flash_unlock_option_bytes().
#define FLASH_OPTKEYR_KEY2 ((u32)0x4c5d6e7f)
Definition at line 114 of file flash.h.
Referenced by flash_unlock_option_bytes().
#define FLASH_SR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x0C)
Definition at line 39 of file flash.h.
Referenced by flash_clear_bsy_flag(), flash_clear_eop_flag(), flash_clear_pgaerr_flag(), flash_clear_pgperr_flag(), flash_clear_pgserr_flag(), flash_clear_wrperr_flag(), and flash_wait_for_last_operation().
#define FLASH_SR_BSY (1 << 16)
Definition at line 61 of file flash.h.
Referenced by flash_clear_bsy_flag(), and flash_wait_for_last_operation().
#define FLASH_SR_EOP (1 << 0)
Definition at line 67 of file flash.h.
Referenced by flash_clear_eop_flag().
#define FLASH_SR_OPERR (1 << 1)
Definition at line 66 of file flash.h.
#define FLASH_SR_PGAERR (1 << 5)
Definition at line 64 of file flash.h.
Referenced by flash_clear_pgaerr_flag().
#define FLASH_SR_PGPERR (1 << 6)
Definition at line 63 of file flash.h.
Referenced by flash_clear_pgperr_flag().
#define FLASH_SR_PGSERR (1 << 7)
Definition at line 62 of file flash.h.
Referenced by flash_clear_pgserr_flag().
#define FLASH_SR_WRPERR (1 << 4)
Definition at line 65 of file flash.h.
Referenced by flash_clear_wrperr_flag().
Function Documentation
void flash_clear_bsy_flag (void)
Definition at line 116 of file flash.c.
References FLASH_SR, and FLASH_SR_BSY.
Referenced by flash_clear_status_flags().
void flash_clear_eop_flag (void)
Definition at line 106 of file flash.c.
References FLASH_SR, and FLASH_SR_EOP.
Referenced by flash_clear_status_flags().
void flash_clear_pgaerr_flag (void)
Definition at line 101 of file flash.c.
References FLASH_SR, and FLASH_SR_PGAERR.
Referenced by flash_clear_status_flags().
void flash_clear_pgperr_flag (void)
Definition at line 96 of file flash.c.
References FLASH_SR, and FLASH_SR_PGPERR.
Referenced by flash_clear_status_flags().
void flash_clear_pgserr_flag (void)
Definition at line 91 of file flash.c.
References FLASH_SR, and FLASH_SR_PGSERR.
Referenced by flash_clear_status_flags().
void flash_clear_status_flags (void)
Definition at line 121 of file flash.c.
References flash_clear_bsy_flag(), flash_clear_eop_flag(), flash_clear_pgaerr_flag(), flash_clear_pgperr_flag(), flash_clear_pgserr_flag(), and flash_clear_wrperr_flag().
void flash_clear_wrperr_flag (void)
Definition at line 111 of file flash.c.
References FLASH_SR, and FLASH_SR_WRPERR.
Referenced by flash_clear_status_flags().
void flash_dcache_disable (void)
Definition at line 34 of file flash.c.
References FLASH_ACR, and FLASH_ACR_DCE.
BEGIN_DECLS void flash_dcache_enable (void)
void flash_dcache_reset (void)
Definition at line 59 of file flash.c.
References FLASH_ACR, and FLASH_ACR_DCRST.
void flash_erase_all_sectors (u32 program_size)
Definition at line 229 of file flash.c.
References FLASH_CR, FLASH_CR_MER, FLASH_CR_STRT, flash_set_program_size(), and flash_wait_for_last_operation().
void flash_erase_sector (u32 sector, u32 program_size)
Definition at line 214 of file flash.c.
References FLASH_CR, FLASH_CR_SER, FLASH_CR_STRT, flash_set_program_size(), and flash_wait_for_last_operation().
void flash_icache_disable (void)
Definition at line 44 of file flash.c.
References FLASH_ACR, and FLASH_ACR_ICE.
void flash_icache_enable (void)
Definition at line 39 of file flash.c.
References FLASH_ACR, and FLASH_ACR_ICE.
void flash_icache_reset (void)
Definition at line 64 of file flash.c.
References FLASH_ACR, and FLASH_ACR_ICRST.
void flash_lock (void)
Definition at line 86 of file flash.c.
References FLASH_CR, and FLASH_CR_LOCK.
void flash_lock_option_bytes (void)
Definition at line 137 of file flash.c.
References FLASH_OPTCR, and FLASH_OPTCR_OPTLOCK.
void flash_prefetch_disable (void)
Definition at line 54 of file flash.c.
References FLASH_ACR, and FLASH_ACR_PRFTEN.
void flash_prefetch_enable (void)
Definition at line 49 of file flash.c.
References FLASH_ACR, and FLASH_ACR_PRFTEN.
void flash_program_byte (u32 address, u8 data, u32 program_size)
Definition at line 200 of file flash.c.
References FLASH_CR, FLASH_CR_PG, flash_set_program_size(), flash_wait_for_last_operation(), and MMIO8.
void flash_program_double_word (u32 address, u64 data, u32 program_size)
Definition at line 148 of file flash.c.
References FLASH_CR, FLASH_CR_PG, flash_set_program_size(), flash_wait_for_last_operation(), and MMIO64.
void flash_program_half_word (u32 address, u16 data, u32 program_size)
Definition at line 186 of file flash.c.
References FLASH_CR, FLASH_CR_PG, flash_set_program_size(), flash_wait_for_last_operation(), and MMIO16.
void flash_program_option_bytes (u32 data)
Definition at line 241 of file flash.c.
References FLASH_OPTCR, FLASH_OPTCR_OPTLOCK, FLASH_OPTCR_OPTSTRT, flash_unlock_option_bytes(), and flash_wait_for_last_operation().
void flash_program_word (u32 address, u32 data, u32 program_size)
Definition at line 167 of file flash.c.
References FLASH_CR, FLASH_CR_PG, flash_set_program_size(), flash_wait_for_last_operation(), and MMIO32.
void flash_set_ws (u32 ws)
Definition at line 69 of file flash.c.
References FLASH_ACR.
Referenced by rcc_clock_setup_hse_3v3().
void flash_unlock (void)
Definition at line 79 of file flash.c.
References FLASH_KEYR, FLASH_KEYR_KEY1, and FLASH_KEYR_KEY2.
void flash_unlock_option_bytes (void)
Definition at line 131 of file flash.c.
References FLASH_OPTKEYR, FLASH_OPTKEYR_KEY1, and FLASH_OPTKEYR_KEY2.
Referenced by flash_program_option_bytes().
void flash_wait_for_last_operation (void)
Definition at line 142 of file flash.c.
References FLASH_SR, and FLASH_SR_BSY.
Referenced by flash_erase_all_sectors(), flash_erase_sector(), flash_program_byte(), flash_program_double_word(), flash_program_half_word(), flash_program_option_bytes(), and flash_program_word().