libopencm3: USART
USART
STM32F4xx
libopencm3 STM32F4xx USART
Functions
void usart_set_baudrate (uint32_t usart, uint32_t baud)
USART Set Baudrate.
void usart_set_databits (uint32_t usart, uint32_t bits)
USART Set Word Length.
void usart_set_stopbits (uint32_t usart, uint32_t stopbits)
USART Set Stop Bit(s).
void usart_set_parity (uint32_t usart, uint32_t parity)
USART Set Parity.
void usart_set_mode (uint32_t usart, uint32_t mode)
USART Set Rx/Tx Mode.
void usart_set_flow_control (uint32_t usart, uint32_t flowcontrol)
USART Set Hardware Flow Control.
void usart_enable (uint32_t usart)
USART Enable.
void usart_disable (uint32_t usart)
USART Disable.
void usart_send_blocking (uint32_t usart, uint16_t data)
USART Send Data Word with Blocking.
uint16_t usart_recv_blocking (uint32_t usart)
USART Read a Received Data Word with Blocking.
void usart_enable_rx_dma (uint32_t usart)
USART Receiver DMA Enable.
void usart_disable_rx_dma (uint32_t usart)
USART Receiver DMA Disable.
void usart_enable_tx_dma (uint32_t usart)
USART Transmitter DMA Enable.
void usart_disable_tx_dma (uint32_t usart)
USART Transmitter DMA Disable.
void usart_enable_rx_interrupt (uint32_t usart)
USART Receiver Interrupt Enable.
void usart_disable_rx_interrupt (uint32_t usart)
USART Receiver Interrupt Disable.
void usart_enable_tx_interrupt (uint32_t usart)
USART Transmitter Interrupt Enable.
void usart_disable_tx_interrupt (uint32_t usart)
USART Transmitter Interrupt Disable.
void usart_enable_error_interrupt (uint32_t usart)
USART Error Interrupt Enable.
void usart_disable_error_interrupt (uint32_t usart)
USART Error Interrupt Disable.
void usart_send (uint32_t usart, uint16_t data)
USART Send a Data Word.
uint16_t usart_recv (uint32_t usart)
USART Read a Received Data Word.
void usart_wait_send_ready (uint32_t usart)
USART Wait for Transmit Data Buffer Empty.
void usart_wait_recv_ready (uint32_t usart)
USART Wait for Received Data Available.
bool usart_get_flag (uint32_t usart, uint32_t flag)
USART Read a Status Flag.
bool usart_get_interrupt_source (uint32_t usart, uint32_t flag)
USART Return Interrupt Source.
Detailed Description
libopencm3 STM32F4xx USART
Version
1.0.0
Date
30 August 2012
LGPL License Terms libopencm3 License
Author
© 2009 Uwe Hermann uwe@h.nosp@m.erma.nosp@m.nn-uw.nosp@m.e.de
This library supports the USART/UART in the STM32F series of ARM Cortex Microcontrollers by ST Microelectronics.
Devices can have up to 3 USARTs and 2 UARTs.
Function Documentation
void usart_disable (uint32_t usart)
USART Disable.
At the end of the current frame, the USART is disabled to reduce power.
Parameters
[in] usart unsigned 32 bit. USART block register address base USART register base addresses
Definition at line 194 of file usart_common_all.c.
References USART_CR1, and USART_CR1_UE.
void usart_disable_error_interrupt (uint32_t usart)
USART Error Interrupt Disable.
Parameters
[in] usart unsigned 32 bit. USART block register address base USART register base addresses
Definition at line 361 of file usart_common_all.c.
References USART_CR3, and USART_CR3_EIE.
void usart_disable_rx_dma (uint32_t usart)
USART Receiver DMA Disable.
Parameters
[in] usart unsigned 32 bit. USART block register address base USART register base addresses
Definition at line 258 of file usart_common_all.c.
References USART_CR3, and USART_CR3_DMAR.
void usart_disable_rx_interrupt (uint32_t usart)
USART Receiver Interrupt Disable.
Parameters
[in] usart unsigned 32 bit. USART block register address base USART register base addresses
Definition at line 313 of file usart_common_all.c.
References USART_CR1, and USART_CR1_RXNEIE.
void usart_disable_tx_dma (uint32_t usart)
USART Transmitter DMA Disable.
Parameters
[in] usart unsigned 32 bit. USART block register address base USART register base addresses
Definition at line 288 of file usart_common_all.c.
References USART_CR3, and USART_CR3_DMAT.
void usart_disable_tx_interrupt (uint32_t usart)
USART Transmitter Interrupt Disable.
Parameters
[in] usart unsigned 32 bit. USART block register address base USART register base addresses
Definition at line 337 of file usart_common_all.c.
References USART_CR1, and USART_CR1_TXEIE.
void usart_enable (uint32_t usart)
USART Enable.
Parameters
[in] usart unsigned 32 bit. USART block register address base USART register base addresses
Definition at line 180 of file usart_common_all.c.
References USART_CR1, and USART_CR1_UE.
void usart_enable_error_interrupt (uint32_t usart)
USART Error Interrupt Enable.
Parameters
[in] usart unsigned 32 bit. USART block register address base USART register base addresses
Definition at line 349 of file usart_common_all.c.
References USART_CR3, and USART_CR3_EIE.
void usart_enable_rx_dma (uint32_t usart)
USART Receiver DMA Enable.
DMA is available on:
USART1 Rx DMA1 channel 5.
USART2 Rx DMA1 channel 6.
USART3 Rx DMA1 channel 3.
UART4 Rx DMA2 channel 3.
Parameters
[in] usart unsigned 32 bit. USART block register address base USART register base addresses
Definition at line 246 of file usart_common_all.c.
References USART_CR3, and USART_CR3_DMAR.
void usart_enable_rx_interrupt (uint32_t usart)
USART Receiver Interrupt Enable.
Parameters
[in] usart unsigned 32 bit. USART block register address base USART register base addresses
Definition at line 300 of file usart_common_all.c.
References USART_CR1, and USART_CR1_RXNEIE.
void usart_enable_tx_dma (uint32_t usart)
USART Transmitter DMA Enable.
DMA is available on:
USART1 Tx DMA1 channel 4.
USART2 Tx DMA1 channel 7.
USART3 Tx DMA1 channel 2.
UART4 Tx DMA2 channel 5.
Parameters
[in] usart unsigned 32 bit. USART block register address base USART register base addresses
Definition at line 276 of file usart_common_all.c.
References USART_CR3, and USART_CR3_DMAT.
void usart_enable_tx_interrupt (uint32_t usart)
USART Transmitter Interrupt Enable.
Parameters
[in] usart unsigned 32 bit. USART block register address base USART register base addresses
Definition at line 325 of file usart_common_all.c.
References USART_CR1, and USART_CR1_TXEIE.
bool usart_get_flag (uint32_t usart, uint32_t flag)
USART Read a Status Flag.
Parameters
[in] usart unsigned 32 bit. USART block register address base USART register base addresses
[in] flag Unsigned int32. Status register flag USART Status register Flags.
Returns
boolean: flag set.
Definition at line 107 of file usart_common_f124.c.
References USART_SR.
bool usart_get_interrupt_source (uint32_t usart, uint32_t flag)
USART Return Interrupt Source.
Returns true if the specified interrupt flag (IDLE, RXNE, TC, TXE or OE) was set and the interrupt was enabled. If the specified flag is not an interrupt flag, the function returns false.
Parameters
[in] usart unsigned 32 bit. USART block register address base USART register base addresses
[in] flag Unsigned int32. Status register flag USART Status register Flags.
Returns
boolean: flag and interrupt enable both set.
Definition at line 129 of file usart_common_f124.c.
References USART_CR1, USART_CR3, USART_CR3_CTSIE, USART_SR, USART_SR_IDLE, USART_SR_ORE, and USART_SR_TXE.
uint16_t usart_recv (uint32_t usart)
USART Read a Received Data Word.
If parity is enabled the MSB (bit 7 or 8 depending on the word length) is the parity bit.
Parameters
[in] usart unsigned 32 bit. USART block register address base USART register base addresses
Returns
unsigned 16 bit data word.
Definition at line 61 of file usart_common_f124.c.
References USART_DR, and USART_DR_MASK.
Referenced by usart_recv_blocking().
uint16_t usart_recv_blocking (uint32_t usart)
USART Read a Received Data Word with Blocking.
Wait until a data word has been received then return the word.
Parameters
[in] usart unsigned 32 bit. USART block register address base USART register base addresses
Returns
unsigned 16 bit data word.
Definition at line 226 of file usart_common_all.c.
References usart_recv(), and usart_wait_recv_ready().
void usart_send (uint32_t usart, uint16_t data)
USART Send a Data Word.
Parameters
[in] usart unsigned 32 bit. USART block register address base USART register base addresses
[in] data unsigned 16 bit.
Definition at line 44 of file usart_common_f124.c.
References USART_DR, and USART_DR_MASK.
Referenced by usart_send_blocking().
void usart_send_blocking (uint32_t usart, uint16_t data)
USART Send Data Word with Blocking.
Blocks until the transmit data buffer becomes empty then writes the next data word for transmission.
Parameters
[in] usart unsigned 32 bit. USART block register address base USART register base addresses
[in] data unsigned 16 bit.
Definition at line 210 of file usart_common_all.c.
References usart_send(), and usart_wait_send_ready().
void usart_set_baudrate (uint32_t usart, uint32_t baud)
USART Set Baudrate.
The baud rate is computed from the APB high-speed prescaler clock (for USART1/6) or the APB low-speed prescaler clock (for other USARTs). These values must be correctly set before calling this function (refer to the rcc_clock_setup-* functions in RCC).
Parameters
[in] usart unsigned 32 bit. USART block register address base USART register base addresses
[in] baud unsigned 32 bit. Baud rate specified in Hz.
Definition at line 49 of file usart_common_all.c.
References rcc_ppre1_frequency, rcc_ppre2_frequency, USART1, USART6, and USART_BRR.
void usart_set_databits (uint32_t usart, uint32_t bits)
USART Set Word Length.
The word length is set to 8 or 9 bits. Note that the last bit will be a parity bit if parity is enabled, in which case the data length will be 7 or 8 bits respectively.
Parameters
[in] usart unsigned 32 bit. USART block register address base USART register base addresses
[in] bits unsigned 32 bit. Word length in bits 8 or 9.
Definition at line 88 of file usart_common_all.c.
References USART_CR1, and USART_CR1_M.
void usart_set_flow_control (uint32_t usart, uint32_t flowcontrol)
USART Set Hardware Flow Control.
The flow control bit can be selected as none, RTS, CTS or RTS+CTS.
Parameters
[in] usart unsigned 32 bit. USART block register address base USART register base addresses
[in] flowcontrol unsigned 32 bit. Flowcontrol USART Hardware Flow Control Selection.
Definition at line 164 of file usart_common_all.c.
References USART_CR3, and USART_FLOWCONTROL_MASK.
void usart_set_mode (uint32_t usart, uint32_t mode)
USART Set Rx/Tx Mode.
The mode can be selected as Rx only, Tx only or Rx+Tx.
Parameters
[in] usart unsigned 32 bit. USART block register address base USART register base addresses
[in] mode unsigned 32 bit. Mode USART Tx/Rx Mode Selection.
Definition at line 145 of file usart_common_all.c.
References USART_CR1, and USART_MODE_MASK.
void usart_set_parity (uint32_t usart, uint32_t parity)
USART Set Parity.
The parity bit can be selected as none, even or odd.
Parameters
[in] usart unsigned 32 bit. USART block register address base USART register base addresses
[in] parity unsigned 32 bit. Parity USART Parity Selection.
Definition at line 126 of file usart_common_all.c.
References USART_CR1, and USART_PARITY_MASK.
void usart_set_stopbits (uint32_t usart, uint32_t stopbits)
USART Set Stop Bit(s).
The stop bits are specified as 0.5, 1, 1.5 or 2.
Parameters
[in] usart unsigned 32 bit. USART block register address base USART register base addresses
[in] stopbits unsigned 32 bit. Stop bits USART Stop Bit Selection.
Definition at line 107 of file usart_common_all.c.
References USART_CR2, and USART_CR2_STOPBITS_MASK.
void usart_wait_recv_ready (uint32_t usart)
USART Wait for Received Data Available.
Blocks until the receive data buffer holds a valid received data word.
Parameters
[in] usart unsigned 32 bit. USART block register address base USART register base addresses
Definition at line 92 of file usart_common_f124.c.
References USART_SR, and USART_SR_RXNE.
Referenced by usart_recv_blocking().
void usart_wait_send_ready (uint32_t usart)
USART Wait for Transmit Data Buffer Empty.
Blocks until the transmit data buffer becomes empty and is ready to accept the next data word.
Parameters
[in] usart unsigned 32 bit. USART block register address base USART register base addresses
Definition at line 77 of file usart_common_f124.c.
References USART_SR, and USART_SR_TXE.
Referenced by usart_send_blocking().