libopencm3: FLASH Defines
FLASH Defines
STM32L1xx Defines
Defined Constants and Types for the STM32L1xx FLASH Memory.
Modules
FLASH Wait States
Flash programming width
Macros
#define FLASH_ACR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x00)
#define FLASH_PECR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x04)
#define FLASH_PDKEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x08)
#define FLASH_PEKEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x0C)
#define FLASH_PRGKEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x10)
#define FLASH_OPTKEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x14)
#define FLASH_SR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x18)
#define FLASH_OBR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x1c)
#define FLASH_WRPR1 MMIO32(FLASH_MEM_INTERFACE_BASE + 0x20)
#define FLASH_WRPR2 MMIO32(FLASH_MEM_INTERFACE_BASE + 0x80)
#define FLASH_WRPR3 MMIO32(FLASH_MEM_INTERFACE_BASE + 0x84)
#define FLASH_ACR_RUNPD (1 << 4)
#define FLASH_ACR_SLEEPPD (1 << 3)
#define FLASH_ACR_ACC64 (1 << 2)
#define FLASH_ACR_PRFTEN (1 << 1)
#define FLASH_PECR_OBL_LAUNCH (1 << 18)
#define FLASH_PECR_ERRIE (1 << 17)
#define FLASH_PECR_EOPIE (1 << 16)
#define FLASH_PECR_PARALLBANK (1 << 15)
#define FLASH_PECR_FPRG (1 << 10)
#define FLASH_PECR_ERASE (1 << 9)
#define FLASH_PECR_FTDW (1 << 8)
#define FLASH_PECR_FTDW (1 << 8)
#define FLASH_PECR_DATA (1 << 4)
#define FLASH_PECR_PROG (1 << 3)
#define FLASH_PECR_OPTLOCK (1 << 2)
#define FLASH_PECR_PRGLOCK (1 << 1)
#define FLASH_PECR_PELOCK (1 << 0)
#define FLASH_PDKEYR_PDKEY1 ((uint32_t)0x04152637)
#define FLASH_PDKEYR_PDKEY2 ((uint32_t)0xFAFBFCFD)
#define FLASH_PEKEYR_PEKEY1 ((uint32_t)0x89ABCDEF)
#define FLASH_PEKEYR_PEKEY2 ((uint32_t)0x02030405)
#define FLASH_PRGKEYR_PRGKEY1 ((uint32_t)0x8C9DAEBF)
#define FLASH_PRGKEYR_PRGKEY2 ((uint32_t)0x13141516)
#define FLASH_OPTKEYR_OPTKEY1 ((uint32_t)0xFBEAD9C8)
#define FLASH_OPTKEYR_OPTKEY2 ((uint32_t)0x24252627)
#define FLASH_SR_OPTVERRUSR (1 << 12)
#define FLASH_SR_OPTVERR (1 << 11)
#define FLASH_SR_SIZEERR (1 << 10)
#define FLASH_SR_PGAERR (1 << 9)
#define FLASH_SR_WRPERR (1 << 8)
#define FLASH_SR_READY (1 << 3)
#define FLASH_SR_ENDHV (1 << 2)
#define FLASH_SR_EOP (1 << 1)
#define FLASH_SR_BSY (1 << 0)
#define FLASH_OBR_BFB2 (1 << 23)
#define FLASH_OBR_NRST_STDBY (1 << 22)
#define FLASH_OBR_NRST_STOP (1 << 21)
#define FLASH_OBR_IWDG_SW (1 << 20)
#define FLASH_OBR_BOR_OFF (0x0 << 16)
#define FLASH_OBR_BOR_LEVEL_1 (0x8 << 16)
#define FLASH_OBR_BOR_LEVEL_2 (0x9 << 16)
#define FLASH_OBR_BOR_LEVEL_3 (0xa << 16)
#define FLASH_OBR_BOR_LEVEL_4 (0xb << 16)
#define FLASH_OBR_BOR_LEVEL_5 (0xc << 16)
#define FLASH_OBR_RDPRT_LEVEL_0 (0xaa)
#define FLASH_OBR_RDPRT_LEVEL_1 (0x00)
#define FLASH_OBR_RDPRT_LEVEL_2 (0xcc)
#define FLASH_ACR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x00)
#define FLASH_KEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x04)
#define FLASH_OPTKEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x08)
#define FLASH_SR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x0C)
#define FLASH_CR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x10)
#define FLASH_AR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x14)
#define FLASH_OBR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x1C)
#define FLASH_WRPR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x20)
#define FLASH_KEYR2 MMIO32(FLASH_MEM_INTERFACE_BASE + 0x44)
#define FLASH_SR2 MMIO32(FLASH_MEM_INTERFACE_BASE + 0x4C)
#define FLASH_CR2 MMIO32(FLASH_MEM_INTERFACE_BASE + 0x50)
#define FLASH_AR2 MMIO32(FLASH_MEM_INTERFACE_BASE + 0x54)
#define FLASH_OPTION_BYTE(i) MMIO16(INFO_BASE+0x0800 + (i)*2)
#define FLASH_ACR_LATENCY_SHIFT 0
#define FLASH_ACR_LATENCY 7
#define FLASH_ACR_PRFTBS (1 << 5)
#define FLASH_ACR_PRFTBE (1 << 4)
#define FLASH_SR_EOP (1 << 5)
#define FLASH_SR_WRPRTERR (1 << 4)
#define FLASH_SR_PGERR (1 << 2)
#define FLASH_SR_BSY (1 << 0)
#define FLASH_CR_EOPIE (1 << 12)
#define FLASH_CR_ERRIE (1 << 10)
#define FLASH_CR_OPTWRE (1 << 9)
#define FLASH_CR_LOCK (1 << 7)
#define FLASH_CR_STRT (1 << 6)
#define FLASH_CR_OPTER (1 << 5)
#define FLASH_CR_OPTPG (1 << 4)
#define FLASH_CR_MER (1 << 2)
#define FLASH_CR_PER (1 << 1)
#define FLASH_CR_PG (1 << 0)
#define FLASH_OBR_RDPRT_SHIFT 1
#define FLASH_OBR_OPTERR (1 << 0)
#define FLASH_KEYR_KEY1 ((uint32_t)0x45670123)
#define FLASH_KEYR_KEY2 ((uint32_t)0xcdef89ab)
#define FLASH_ACR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x00)
#define FLASH_KEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x04)
#define FLASH_OPTKEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x08)
#define FLASH_SR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x0C)
#define FLASH_CR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x10)
#define FLASH_ACR_LATENCY_0WS 0x00
#define FLASH_ACR_LATENCY_1WS 0x01
#define FLASH_ACR_LATENCY_2WS 0x02
#define FLASH_ACR_LATENCY_3WS 0x03
#define FLASH_ACR_LATENCY_4WS 0x04
#define FLASH_ACR_LATENCY_5WS 0x05
#define FLASH_ACR_LATENCY_6WS 0x06
#define FLASH_ACR_LATENCY_7WS 0x07
#define FLASH_KEYR_KEY1 ((uint32_t)0x45670123)
#define FLASH_KEYR_KEY2 ((uint32_t)0xcdef89ab)
#define FLASH_OPTCR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x14)
#define FLASH_OPTCR1 MMIO32(FLASH_MEM_INTERFACE_BASE + 0x18)
#define FLASH_ACR_DCRST (1 << 12)
#define FLASH_ACR_ICRST (1 << 11)
#define FLASH_ACR_DCE (1 << 10)
#define FLASH_ACR_ICE (1 << 9)
#define FLASH_ACR_PRFTEN (1 << 8)
#define FLASH_SR_BSY (1 << 16)
#define FLASH_SR_PGSERR (1 << 7)
#define FLASH_SR_PGPERR (1 << 6)
#define FLASH_SR_PGAERR (1 << 5)
#define FLASH_SR_WRPERR (1 << 4)
#define FLASH_SR_OPERR (1 << 1)
#define FLASH_SR_EOP (1 << 0)
#define FLASH_CR_LOCK (1 << 31)
#define FLASH_CR_ERRIE (1 << 25)
#define FLASH_CR_EOPIE (1 << 24)
#define FLASH_CR_STRT (1 << 16)
#define FLASH_CR_MER (1 << 2)
#define FLASH_CR_SER (1 << 1)
#define FLASH_CR_PG (1 << 0)
#define FLASH_CR_SNB_SHIFT 3
#define FLASH_CR_SNB_MASK 0x1f
#define FLASH_CR_PROGRAM_MASK 0x3
#define FLASH_CR_PROGRAM_SHIFT 8
#define FLASH_OPTCR_NRST_STDBY (1 << 7)
#define FLASH_OPTCR_NRST_STOP (1 << 6)
#define FLASH_OPTCR_WDG_SW (1 << 5)
#define FLASH_OPTCR_OPTSTRT (1 << 1)
#define FLASH_OPTCR_OPTLOCK (1 << 0)
#define FLASH_OPTCR_BOR_LEVEL_3 (0x00 << 2)
#define FLASH_OPTCR_BOR_LEVEL_2 (0x01 << 2)
#define FLASH_OPTCR_BOR_LEVEL_1 (0x02 << 2)
#define FLASH_OPTCR_BOR_OFF (0x03 << 2)
#define FLASH_OPTKEYR_KEY1 ((uint32_t)0x08192a3b)
#define FLASH_OPTKEYR_KEY2 ((uint32_t)0x4c5d6e7f)
Functions
void flash_64bit_enable (void)
Enable 64 Bit Programming Mode.
void flash_64bit_disable (void)
Enable 32 Bit Programming Mode.
void flash_prefetch_enable (void)
Enable the FLASH Prefetch Buffer.
void flash_prefetch_disable (void)
Disable the FLASH Prefetch Buffer.
void flash_set_ws (uint32_t ws)
Set the Number of Wait States.
void flash_unlock_pecr (void)
void flash_lock_pecr (void)
void flash_unlock_progmem (void)
void flash_lock_progmem (void)
void flash_unlock_option_bytes (void)
Unlock the Option Byte Access.
void flash_lock_option_bytes (void)
Lock the Option Byte Access.
void flash_unlock (void)
Unlock the Flash Program and Erase Controller.
void flash_lock (void)
Lock the Flash Program and Erase Controller.
void eeprom_program_word (uint32_t address, uint32_t data)
Write a word to eeprom.
void eeprom_program_words (uint32_t address, uint32_t *data, int length_in_words)
Write a block of words to eeprom.
void flash_prefetch_buffer_enable (void)
Enable the FLASH Prefetch Buffer.
void flash_prefetch_buffer_disable (void)
Disable the FLASH Prefetch Buffer.
void flash_clear_pgerr_flag (void)
Clear the Programming Error Status Flag.
void flash_clear_wrprterr_flag (void)
Clear the Write Protect Error Status Flag.
void flash_clear_status_flags (void)
Clear All Status Flags.
uint32_t flash_get_status_flags (void)
void flash_program_half_word (uint32_t address, uint16_t data)
Program a Half Word to FLASH.
void flash_erase_page (uint32_t page_address)
void flash_erase_all_pages (void)
void flash_erase_option_bytes (void)
Erase All Option Bytes.
void flash_program_option_bytes (uint32_t address, uint16_t data)
Program the Option Bytes.
void flash_clear_pgperr_flag (void)
Clear the Programming Error Status Flag.
void flash_clear_pgserr_flag (void)
Clear the Programming Sequence Error Flag.
void flash_clear_wrperr_flag (void)
Clear the Write Protect Error Flag.
void flash_clear_pgaerr_flag (void)
Clear the Programming Alignment Error Flag.
void flash_dcache_enable (void)
Enable the Data Cache.
void flash_dcache_disable (void)
Disable the Data Cache.
void flash_icache_enable (void)
Enable the Instruction Cache.
void flash_icache_disable (void)
Disable the Instruction Cache.
void flash_dcache_reset (void)
Reset the Data Cache.
void flash_icache_reset (void)
Reset the Instruction Cache.
void flash_erase_all_sectors (uint32_t program_size)
Erase All FLASH.
void flash_erase_sector (uint8_t sector, uint32_t program_size)
Erase a Sector of FLASH.
void flash_program_double_word (uint32_t address, uint64_t data)
Program a 64 bit Word to FLASH.
void flash_program_byte (uint32_t address, uint8_t data)
Program an 8 bit Byte to FLASH.
void flash_program (uint32_t address, uint8_t *data, uint32_t len)
Program a Data Block to FLASH.
void flash_program_option_bytes (uint32_t data)
Program the Option Bytes.
Detailed Description
Defined Constants and Types for the STM32L1xx FLASH Memory.
Version
1.0.0
Author
© 2012 Karl Palsson karlp.nosp@m.@twe.nosp@m.ak.ne.nosp@m.t.au
Date
14 January 2014
LGPL License Terms libopencm3 License
Author
© 2010 Thomas Otto tommi.nosp@m.@via.nosp@m.dmin..nosp@m.org
© 2010 Mark Butler mbutl.nosp@m.er@p.nosp@m.hysic.nosp@m.s.ot.nosp@m.ago.a.nosp@m.c.nz
Macro Definition Documentation
#define FLASH_ACR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x00)
Definition at line 40 of file flash_common_f01.h.
#define FLASH_ACR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x00)
Definition at line 45 of file flash_common_f234.h.
#define FLASH_ACR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x00)
Definition at line 49 of file flash.h.
Referenced by flash_64bit_disable(), flash_64bit_enable(), flash_dcache_disable(), flash_dcache_enable(), flash_dcache_reset(), flash_icache_disable(), flash_icache_enable(), flash_icache_reset(), flash_prefetch_buffer_disable(), flash_prefetch_buffer_enable(), flash_prefetch_disable(), flash_prefetch_enable(), and flash_set_ws().
#define FLASH_ACR_ACC64 (1 << 2)
Definition at line 65 of file flash.h.
Referenced by flash_64bit_disable(), and flash_64bit_enable().
#define FLASH_ACR_DCE (1 << 10)
Definition at line 54 of file flash_common_f24.h.
Referenced by flash_dcache_disable(), and flash_dcache_enable().
#define FLASH_ACR_DCRST (1 << 12)
Definition at line 52 of file flash_common_f24.h.
Referenced by flash_dcache_reset().
#define FLASH_ACR_ICE (1 << 9)
Definition at line 55 of file flash_common_f24.h.
Referenced by flash_icache_disable(), and flash_icache_enable().
#define FLASH_ACR_ICRST (1 << 11)
Definition at line 53 of file flash_common_f24.h.
Referenced by flash_icache_reset().
#define FLASH_ACR_LATENCY 7
Definition at line 61 of file flash_common_f01.h.
Referenced by flash_set_ws().
#define FLASH_ACR_LATENCY_0WS 0x00
Definition at line 53 of file flash_common_f234.h.
#define FLASH_ACR_LATENCY_1WS 0x01
Definition at line 54 of file flash_common_f234.h.
#define FLASH_ACR_LATENCY_2WS 0x02
Definition at line 55 of file flash_common_f234.h.
#define FLASH_ACR_LATENCY_3WS 0x03
Definition at line 56 of file flash_common_f234.h.
#define FLASH_ACR_LATENCY_4WS 0x04
Definition at line 57 of file flash_common_f234.h.
#define FLASH_ACR_LATENCY_5WS 0x05
Definition at line 58 of file flash_common_f234.h.
#define FLASH_ACR_LATENCY_6WS 0x06
Definition at line 59 of file flash_common_f234.h.
#define FLASH_ACR_LATENCY_7WS 0x07
Definition at line 60 of file flash_common_f234.h.
#define FLASH_ACR_LATENCY_SHIFT 0
Definition at line 60 of file flash_common_f01.h.
#define FLASH_ACR_PRFTBE (1 << 4)
Definition at line 64 of file flash_common_f01.h.
Referenced by flash_prefetch_buffer_disable(), and flash_prefetch_buffer_enable().
#define FLASH_ACR_PRFTBS (1 << 5)
Definition at line 63 of file flash_common_f01.h.
#define FLASH_ACR_PRFTEN (1 << 8)
Definition at line 56 of file flash_common_f24.h.
#define FLASH_ACR_PRFTEN (1 << 1)
Definition at line 66 of file flash.h.
Referenced by flash_prefetch_disable(), and flash_prefetch_enable().
#define FLASH_ACR_RUNPD (1 << 4)
Definition at line 63 of file flash.h.
#define FLASH_ACR_SLEEPPD (1 << 3)
Definition at line 64 of file flash.h.
#define FLASH_AR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x14)
Definition at line 45 of file flash_common_f01.h.
#define FLASH_AR2 MMIO32(FLASH_MEM_INTERFACE_BASE + 0x54)
Definition at line 52 of file flash_common_f01.h.
#define FLASH_CR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x10)
Definition at line 44 of file flash_common_f01.h.
Referenced by flash_erase_all_sectors(), flash_erase_option_bytes(), flash_erase_sector(), flash_lock(), flash_program_byte(), flash_program_double_word(), flash_program_half_word(), flash_program_option_bytes(), flash_program_word(), flash_set_program_size(), and flash_unlock().
#define FLASH_CR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x10)
Definition at line 49 of file flash_common_f234.h.
#define FLASH_CR2 MMIO32(FLASH_MEM_INTERFACE_BASE + 0x50)
Definition at line 51 of file flash_common_f01.h.
#define FLASH_CR_EOPIE (1 << 24)
Definition at line 72 of file flash_common_f24.h.
#define FLASH_CR_EOPIE (1 << 12)
Definition at line 75 of file flash_common_f01.h.
#define FLASH_CR_ERRIE (1 << 25)
Definition at line 71 of file flash_common_f24.h.
#define FLASH_CR_ERRIE (1 << 10)
Definition at line 76 of file flash_common_f01.h.
#define FLASH_CR_LOCK (1 << 31)
Definition at line 70 of file flash_common_f24.h.
#define FLASH_CR_LOCK (1 << 7)
Definition at line 78 of file flash_common_f01.h.
Referenced by flash_lock(), and flash_unlock().
#define FLASH_CR_MER (1 << 2)
Definition at line 74 of file flash_common_f24.h.
#define FLASH_CR_MER (1 << 2)
Definition at line 82 of file flash_common_f01.h.
Referenced by flash_erase_all_sectors().
#define FLASH_CR_OPTER (1 << 5)
Definition at line 80 of file flash_common_f01.h.
Referenced by flash_erase_option_bytes().
#define FLASH_CR_OPTPG (1 << 4)
Definition at line 81 of file flash_common_f01.h.
Referenced by flash_program_option_bytes().
#define FLASH_CR_OPTWRE (1 << 9)
Definition at line 77 of file flash_common_f01.h.
Referenced by flash_erase_option_bytes(), and flash_program_option_bytes().
#define FLASH_CR_PER (1 << 1)
Definition at line 83 of file flash_common_f01.h.
#define FLASH_CR_PG (1 << 0)
Definition at line 76 of file flash_common_f24.h.
#define FLASH_CR_PG (1 << 0)
Definition at line 84 of file flash_common_f01.h.
Referenced by flash_program_byte(), flash_program_double_word(), flash_program_half_word(), and flash_program_word().
#define FLASH_CR_PROGRAM_MASK 0x3
Definition at line 79 of file flash_common_f24.h.
Referenced by flash_set_program_size().
#define FLASH_CR_PROGRAM_SHIFT 8
Definition at line 80 of file flash_common_f24.h.
Referenced by flash_set_program_size().
#define FLASH_CR_SER (1 << 1)
Definition at line 75 of file flash_common_f24.h.
Referenced by flash_erase_sector().
#define FLASH_CR_SNB_MASK 0x1f
Definition at line 78 of file flash_common_f24.h.
Referenced by flash_erase_sector().
#define FLASH_CR_SNB_SHIFT 3
Definition at line 77 of file flash_common_f24.h.
Referenced by flash_erase_sector().
#define FLASH_CR_STRT (1 << 16)
Definition at line 73 of file flash_common_f24.h.
#define FLASH_CR_STRT (1 << 6)
Definition at line 79 of file flash_common_f01.h.
Referenced by flash_erase_all_sectors(), flash_erase_option_bytes(), and flash_erase_sector().
#define FLASH_KEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x04)
Definition at line 41 of file flash_common_f01.h.
Referenced by flash_unlock().
#define FLASH_KEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x04)
Definition at line 46 of file flash_common_f234.h.
#define FLASH_KEYR2 MMIO32(FLASH_MEM_INTERFACE_BASE + 0x44)
Definition at line 49 of file flash_common_f01.h.
#define FLASH_KEYR_KEY1 ((uint32_t)0x45670123)
Definition at line 68 of file flash_common_f234.h.
#define FLASH_KEYR_KEY1 ((uint32_t)0x45670123)
Definition at line 93 of file flash_common_f01.h.
Referenced by flash_unlock(), and flash_unlock_option_bytes().
#define FLASH_KEYR_KEY2 ((uint32_t)0xcdef89ab)
Definition at line 69 of file flash_common_f234.h.
#define FLASH_KEYR_KEY2 ((uint32_t)0xcdef89ab)
Definition at line 94 of file flash_common_f01.h.
Referenced by flash_unlock(), and flash_unlock_option_bytes().
#define FLASH_OBR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x1C)
Definition at line 46 of file flash_common_f01.h.
#define FLASH_OBR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x1c)
Definition at line 56 of file flash.h.
#define FLASH_OBR_BFB2 (1 << 23)
Definition at line 118 of file flash.h.
#define FLASH_OBR_BOR_LEVEL_1 (0x8 << 16)
Definition at line 123 of file flash.h.
#define FLASH_OBR_BOR_LEVEL_2 (0x9 << 16)
Definition at line 124 of file flash.h.
#define FLASH_OBR_BOR_LEVEL_3 (0xa << 16)
Definition at line 125 of file flash.h.
#define FLASH_OBR_BOR_LEVEL_4 (0xb << 16)
Definition at line 126 of file flash.h.
#define FLASH_OBR_BOR_LEVEL_5 (0xc << 16)
Definition at line 127 of file flash.h.
#define FLASH_OBR_BOR_OFF (0x0 << 16)
Definition at line 122 of file flash.h.
#define FLASH_OBR_IWDG_SW (1 << 20)
Definition at line 121 of file flash.h.
#define FLASH_OBR_NRST_STDBY (1 << 22)
Definition at line 119 of file flash.h.
#define FLASH_OBR_NRST_STOP (1 << 21)
Definition at line 120 of file flash.h.
#define FLASH_OBR_OPTERR (1 << 0)
Definition at line 89 of file flash_common_f01.h.
#define FLASH_OBR_RDPRT_LEVEL_0 (0xaa)
Definition at line 128 of file flash.h.
#define FLASH_OBR_RDPRT_LEVEL_1 (0x00)
Definition at line 129 of file flash.h.
#define FLASH_OBR_RDPRT_LEVEL_2 (0xcc)
Definition at line 130 of file flash.h.
#define FLASH_OBR_RDPRT_SHIFT 1
Definition at line 88 of file flash_common_f01.h.
#define FLASH_OPTCR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x14)
Definition at line 47 of file flash_common_f24.h.
Referenced by flash_lock_option_bytes(), and flash_program_option_bytes().
#define FLASH_OPTCR1 MMIO32(FLASH_MEM_INTERFACE_BASE + 0x18)
Definition at line 48 of file flash_common_f24.h.
#define FLASH_OPTCR_BOR_LEVEL_1 (0x02 << 2)
Definition at line 102 of file flash_common_f24.h.
#define FLASH_OPTCR_BOR_LEVEL_2 (0x01 << 2)
Definition at line 101 of file flash_common_f24.h.
#define FLASH_OPTCR_BOR_LEVEL_3 (0x00 << 2)
Definition at line 100 of file flash_common_f24.h.
#define FLASH_OPTCR_BOR_OFF (0x03 << 2)
Definition at line 103 of file flash_common_f24.h.
#define FLASH_OPTCR_NRST_STDBY (1 << 7)
Definition at line 95 of file flash_common_f24.h.
#define FLASH_OPTCR_NRST_STOP (1 << 6)
Definition at line 96 of file flash_common_f24.h.
#define FLASH_OPTCR_OPTLOCK (1 << 0)
Definition at line 99 of file flash_common_f24.h.
Referenced by flash_lock_option_bytes(), and flash_program_option_bytes().
#define FLASH_OPTCR_OPTSTRT (1 << 1)
Definition at line 98 of file flash_common_f24.h.
Referenced by flash_program_option_bytes().
#define FLASH_OPTCR_WDG_SW (1 << 5)
Definition at line 97 of file flash_common_f24.h.
#define FLASH_OPTION_BYTE (i) MMIO16(INFO_BASE+0x0800 + (i)*2)
Definition at line 56 of file flash_common_f01.h.
#define FLASH_OPTKEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x08)
Definition at line 42 of file flash_common_f01.h.
#define FLASH_OPTKEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x08)
Definition at line 47 of file flash_common_f234.h.
#define FLASH_OPTKEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x14)
Definition at line 54 of file flash.h.
Referenced by flash_unlock_option_bytes().
#define FLASH_OPTKEYR_KEY1 ((uint32_t)0x08192a3b)
Definition at line 111 of file flash_common_f24.h.
#define FLASH_OPTKEYR_KEY2 ((uint32_t)0x4c5d6e7f)
Definition at line 112 of file flash_common_f24.h.
#define FLASH_OPTKEYR_OPTKEY1 ((uint32_t)0xFBEAD9C8)
Definition at line 102 of file flash.h.
Referenced by flash_unlock_option_bytes().
#define FLASH_OPTKEYR_OPTKEY2 ((uint32_t)0x24252627)
Definition at line 103 of file flash.h.
Referenced by flash_unlock_option_bytes().
#define FLASH_PDKEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x08)
Definition at line 51 of file flash.h.
#define FLASH_PDKEYR_PDKEY1 ((uint32_t)0x04152637)
Definition at line 90 of file flash.h.
#define FLASH_PDKEYR_PDKEY2 ((uint32_t)0xFAFBFCFD)
Definition at line 91 of file flash.h.
#define FLASH_PECR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x04)
Definition at line 50 of file flash.h.
Referenced by eeprom_program_word(), eeprom_program_words(), flash_lock_option_bytes(), flash_lock_pecr(), and flash_lock_progmem().
#define FLASH_PECR_DATA (1 << 4)
Definition at line 83 of file flash.h.
#define FLASH_PECR_EOPIE (1 << 16)
Definition at line 77 of file flash.h.
#define FLASH_PECR_ERASE (1 << 9)
Definition at line 80 of file flash.h.
#define FLASH_PECR_ERRIE (1 << 17)
Definition at line 76 of file flash.h.
#define FLASH_PECR_FPRG (1 << 10)
Definition at line 79 of file flash.h.
#define FLASH_PECR_FTDW (1 << 8)
Definition at line 82 of file flash.h.
Referenced by eeprom_program_word(), and eeprom_program_words().
#define FLASH_PECR_FTDW (1 << 8)
Definition at line 82 of file flash.h.
#define FLASH_PECR_OBL_LAUNCH (1 << 18)
Definition at line 75 of file flash.h.
#define FLASH_PECR_OPTLOCK (1 << 2)
Definition at line 85 of file flash.h.
Referenced by flash_lock_option_bytes().
#define FLASH_PECR_PARALLBANK (1 << 15)
Definition at line 78 of file flash.h.
#define FLASH_PECR_PELOCK (1 << 0)
Definition at line 87 of file flash.h.
Referenced by flash_lock_pecr().
#define FLASH_PECR_PRGLOCK (1 << 1)
Definition at line 86 of file flash.h.
Referenced by flash_lock_progmem().
#define FLASH_PECR_PROG (1 << 3)
Definition at line 84 of file flash.h.
#define FLASH_PEKEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x0C)
Definition at line 52 of file flash.h.
Referenced by flash_unlock_pecr().
#define FLASH_PEKEYR_PEKEY1 ((uint32_t)0x89ABCDEF)
Definition at line 94 of file flash.h.
Referenced by flash_unlock_pecr().
#define FLASH_PEKEYR_PEKEY2 ((uint32_t)0x02030405)
Definition at line 95 of file flash.h.
Referenced by flash_unlock_pecr().
#define FLASH_PRGKEYR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x10)
Definition at line 53 of file flash.h.
Referenced by flash_unlock_progmem().
#define FLASH_PRGKEYR_PRGKEY1 ((uint32_t)0x8C9DAEBF)
Definition at line 98 of file flash.h.
Referenced by flash_unlock_progmem().
#define FLASH_PRGKEYR_PRGKEY2 ((uint32_t)0x13141516)
Definition at line 99 of file flash.h.
Referenced by flash_unlock_progmem().
#define FLASH_SR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x0C)
Definition at line 43 of file flash_common_f01.h.
#define FLASH_SR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x0C)
Definition at line 48 of file flash_common_f234.h.
#define FLASH_SR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x18)
Definition at line 55 of file flash.h.
Referenced by eeprom_program_words(), flash_clear_bsy_flag(), flash_clear_eop_flag(), flash_clear_pgaerr_flag(), flash_clear_pgerr_flag(), flash_clear_pgperr_flag(), flash_clear_pgserr_flag(), flash_clear_wrperr_flag(), flash_clear_wrprterr_flag(), and flash_wait_for_last_operation().
#define FLASH_SR2 MMIO32(FLASH_MEM_INTERFACE_BASE + 0x4C)
Definition at line 50 of file flash_common_f01.h.
#define FLASH_SR_BSY (1 << 16)
Definition at line 60 of file flash_common_f24.h.
#define FLASH_SR_BSY (1 << 0)
Definition at line 71 of file flash_common_f01.h.
#define FLASH_SR_BSY (1 << 0)
Definition at line 115 of file flash.h.
Referenced by eeprom_program_words(), flash_clear_bsy_flag(), and flash_wait_for_last_operation().
#define FLASH_SR_ENDHV (1 << 2)
Definition at line 113 of file flash.h.
#define FLASH_SR_EOP (1 << 0)
Definition at line 66 of file flash_common_f24.h.
#define FLASH_SR_EOP (1 << 5)
Definition at line 68 of file flash_common_f01.h.
#define FLASH_SR_EOP (1 << 1)
Definition at line 114 of file flash.h.
Referenced by flash_clear_eop_flag().
#define FLASH_SR_OPERR (1 << 1)
Definition at line 65 of file flash_common_f24.h.
#define FLASH_SR_OPTVERR (1 << 11)
Definition at line 108 of file flash.h.
#define FLASH_SR_OPTVERRUSR (1 << 12)
Definition at line 107 of file flash.h.
#define FLASH_SR_PGAERR (1 << 5)
Definition at line 63 of file flash_common_f24.h.
#define FLASH_SR_PGAERR (1 << 9)
Definition at line 110 of file flash.h.
Referenced by flash_clear_pgaerr_flag().
#define FLASH_SR_PGERR (1 << 2)
Definition at line 70 of file flash_common_f01.h.
Referenced by flash_clear_pgerr_flag().
#define FLASH_SR_PGPERR (1 << 6)
Definition at line 62 of file flash_common_f24.h.
Referenced by flash_clear_pgperr_flag().
#define FLASH_SR_PGSERR (1 << 7)
Definition at line 61 of file flash_common_f24.h.
Referenced by flash_clear_pgserr_flag().
#define FLASH_SR_READY (1 << 3)
Definition at line 112 of file flash.h.
#define FLASH_SR_SIZEERR (1 << 10)
Definition at line 109 of file flash.h.
#define FLASH_SR_WRPERR (1 << 4)
Definition at line 64 of file flash_common_f24.h.
#define FLASH_SR_WRPERR (1 << 8)
Definition at line 111 of file flash.h.
Referenced by flash_clear_wrperr_flag().
#define FLASH_SR_WRPRTERR (1 << 4)
Definition at line 69 of file flash_common_f01.h.
Referenced by flash_clear_wrprterr_flag().
#define FLASH_WRPR MMIO32(FLASH_MEM_INTERFACE_BASE + 0x20)
Definition at line 47 of file flash_common_f01.h.
#define FLASH_WRPR1 MMIO32(FLASH_MEM_INTERFACE_BASE + 0x20)
Definition at line 57 of file flash.h.
#define FLASH_WRPR2 MMIO32(FLASH_MEM_INTERFACE_BASE + 0x80)
Definition at line 58 of file flash.h.
#define FLASH_WRPR3 MMIO32(FLASH_MEM_INTERFACE_BASE + 0x84)
Definition at line 59 of file flash.h.
Function Documentation
void eeprom_program_word (uint32_t address, uint32_t data)
Write a word to eeprom.
Parameters
address assumed to be in the eeprom space, no checking
data word to write
Definition at line 176 of file flash.c.
References flash_lock_pecr(), FLASH_PECR, FLASH_PECR_FTDW, and flash_unlock_pecr().
void eeprom_program_words (uint32_t address, uint32_t * data, int length_in_words)
Write a block of words to eeprom.
Writes a block of words to EEPROM at the requested address, erasing if necessary, and locking afterwards. Only wordwise writing is safe for writing any value
Parameters
[in] address must point to EEPROM space, no checking!
[in] data pointer to data to write
[in] length size of of data in WORDS!
Definition at line 193 of file flash.c.
References flash_lock_pecr(), FLASH_PECR, FLASH_PECR_FTDW, FLASH_SR, FLASH_SR_BSY, and flash_unlock_pecr().
void flash_64bit_disable (void)
Enable 32 Bit Programming Mode.
This mode is a low power mode. It must be used at low frequencies and does not allow prefetch or wait states to be used.
Definition at line 69 of file flash.c.
References FLASH_ACR, and FLASH_ACR_ACC64.
void flash_64bit_enable (void)
Enable 64 Bit Programming Mode.
Definition at line 57 of file flash.c.
References FLASH_ACR, and FLASH_ACR_ACC64.
Referenced by rcc_clock_setup_hsi(), rcc_clock_setup_msi(), and rcc_clock_setup_pll().
void flash_clear_pgaerr_flag (void)
Clear the Programming Alignment Error Flag.
Definition at line 151 of file flash_common_f24.c.
References FLASH_SR, and FLASH_SR_PGAERR.
Referenced by flash_clear_status_flags().
void flash_clear_pgerr_flag (void)
Clear the Programming Error Status Flag.
Definition at line 105 of file flash_common_f01.c.
References FLASH_SR, and FLASH_SR_PGERR.
void flash_clear_pgperr_flag (void)
Clear the Programming Error Status Flag.
Definition at line 83 of file flash_common_f234.c.
References FLASH_SR, and FLASH_SR_PGPERR.
Referenced by flash_clear_status_flags().
void flash_clear_pgserr_flag (void)
Clear the Programming Sequence Error Flag.
This flag is set when incorrect programming configuration has been made.
Definition at line 141 of file flash_common_f24.c.
References FLASH_SR, and FLASH_SR_PGSERR.
Referenced by flash_clear_status_flags().
void flash_clear_status_flags (void)
Clear All Status Flags.
Program error, end of operation, write protect error, busy.
Definition at line 172 of file flash_common_f24.c.
References flash_clear_bsy_flag(), flash_clear_eop_flag(), flash_clear_pgaerr_flag(), flash_clear_pgperr_flag(), flash_clear_pgserr_flag(), and flash_clear_wrperr_flag().
void flash_clear_wrperr_flag (void)
Clear the Write Protect Error Flag.
Definition at line 161 of file flash_common_f24.c.
References FLASH_SR, and FLASH_SR_WRPERR.
Referenced by flash_clear_status_flags().
void flash_clear_wrprterr_flag (void)
Clear the Write Protect Error Status Flag.
Definition at line 125 of file flash_common_f01.c.
References FLASH_SR, and FLASH_SR_WRPRTERR.
void flash_dcache_disable (void)
Disable the Data Cache.
Definition at line 59 of file flash_common_f24.c.
References FLASH_ACR, and FLASH_ACR_DCE.
void flash_dcache_enable (void)
Enable the Data Cache.
Definition at line 49 of file flash_common_f24.c.
References FLASH_ACR, and FLASH_ACR_DCE.
void flash_dcache_reset (void)
Reset the Data Cache.
The data cache must be disabled for this to have effect.
Definition at line 119 of file flash_common_f24.c.
References FLASH_ACR, and FLASH_ACR_DCRST.
void flash_erase_all_pages (void)
void flash_erase_all_sectors (uint32_t program_size)
Erase All FLASH.
This performs all operations necessary to erase all sectors in the FLASH memory.
Parameters
program_size 0 (8-bit), 1 (16-bit), 2 (32-bit), 3 (64-bit)
Definition at line 381 of file flash_common_f24.c.
References FLASH_CR, FLASH_CR_MER, FLASH_CR_STRT, flash_set_program_size(), and flash_wait_for_last_operation().
void flash_erase_option_bytes (void)
Erase All Option Bytes.
This performs all operations necessary to erase the option bytes. These must first be fully erased before attempting to program them, therefore it is recommended to check these after an erase attempt.
Definition at line 193 of file flash_common_f01.c.
References FLASH_CR, FLASH_CR_OPTER, FLASH_CR_OPTWRE, FLASH_CR_STRT, flash_unlock_option_bytes(), and flash_wait_for_last_operation().
void flash_erase_page (uint32_t page_address)
void flash_erase_sector (uint8_t sector, uint32_t program_size)
Erase a Sector of FLASH.
This performs all operations necessary to erase a sector in FLASH memory. The page should be checked to ensure that it was properly erased. A sector must first be fully erased before attempting to program it.
See the reference manual or the FLASH programming manual for details.
Parameters
[in] uint32_t sector (0 - 11 for some parts, 0-23 on others)
program_size 0 (8-bit), 1 (16-bit), 2 (32-bit), 3 (64-bit)
Definition at line 357 of file flash_common_f24.c.
References FLASH_CR, FLASH_CR_SER, FLASH_CR_SNB_MASK, FLASH_CR_SNB_SHIFT, FLASH_CR_STRT, flash_set_program_size(), and flash_wait_for_last_operation().
uint32_t flash_get_status_flags (void)
Referenced by flash_wait_for_last_operation().
void flash_icache_disable (void)
Disable the Instruction Cache.
Definition at line 79 of file flash_common_f24.c.
References FLASH_ACR, and FLASH_ACR_ICE.
void flash_icache_enable (void)
Enable the Instruction Cache.
Definition at line 69 of file flash_common_f24.c.
References FLASH_ACR, and FLASH_ACR_ICE.
void flash_icache_reset (void)
Reset the Instruction Cache.
The instruction cache must be disabled for this to have effect.
Definition at line 130 of file flash_common_f24.c.
References FLASH_ACR, and FLASH_ACR_ICRST.
void flash_lock (void)
Lock the Flash Program and Erase Controller.
Used to prevent spurious writes to FLASH.
Lock the Flash Program and Erase Controller.
Used to prevent spurious writes to FLASH.
Definition at line 95 of file flash_common_f01.c.
References FLASH_CR, FLASH_CR_LOCK, flash_lock_option_bytes(), flash_lock_pecr(), and flash_lock_progmem().
void flash_lock_option_bytes (void)
Lock the Option Byte Access.
This disables write access to the option bytes. It is locked by default on reset.
Definition at line 206 of file flash_common_f24.c.
References FLASH_OPTCR, FLASH_OPTCR_OPTLOCK, FLASH_PECR, and FLASH_PECR_OPTLOCK.
Referenced by flash_lock().
void flash_lock_pecr (void)
Definition at line 129 of file flash.c.
References FLASH_PECR, and FLASH_PECR_PELOCK.
Referenced by eeprom_program_word(), eeprom_program_words(), and flash_lock().
void flash_lock_progmem (void)
Definition at line 139 of file flash.c.
References FLASH_PECR, and FLASH_PECR_PRGLOCK.
Referenced by flash_lock().
void flash_prefetch_buffer_disable (void)
Disable the FLASH Prefetch Buffer.
Note carefully the clock restrictions under which the prefetch buffer may be set to disabled. See the reference manual for details.
Definition at line 52 of file flash_common_f01.c.
References FLASH_ACR, and FLASH_ACR_PRFTBE.
void flash_prefetch_buffer_enable (void)
Enable the FLASH Prefetch Buffer.
This buffer is used for instruction fetches and is enabled by default after reset.
Note carefully the clock restrictions under which the prefetch buffer may be enabled or disabled. Changes are normally made while the clock is running in the power-on low frequency mode before being set to a higher speed mode. See the reference manual for details.
Definition at line 40 of file flash_common_f01.c.
References FLASH_ACR, and FLASH_ACR_PRFTBE.
void flash_prefetch_disable (void)
Disable the FLASH Prefetch Buffer.
Note carefully the clock restrictions under which the prefetch buffer may be set to disabled. See the reference manual for details.
Note carefully the restrictions under which the prefetch buffer may be set to disabled. See the reference and programming manuals for details.
Note carefully the clock restrictions under which the prefetch buffer may be set to disabled. See the reference manual for details.
Definition at line 108 of file flash_common_f24.c.
References FLASH_ACR, and FLASH_ACR_PRFTEN.
void flash_prefetch_enable (void)
Enable the FLASH Prefetch Buffer.
This buffer is used for instruction fetches and is enabled by default after reset.
Note carefully the clock restrictions under which the prefetch buffer may be enabled or disabled. Changes are normally made while the clock is running in the power-on low frequency mode before being set to a higher speed mode. See the reference manual for details.
This buffer is used for instruction fetches and is enabled by default after reset.
Note carefully the restrictions under which the prefetch buffer may be enabled or disabled. Prefetch is only available when 64-bit access is enabled.
This buffer is used for instruction fetches and is enabled by default after reset.
Note carefully the clock restrictions under which the prefetch buffer may be enabled or disabled. Changes are normally made while the clock is running in the power-on low frequency mode before being set to a higher speed mode. See the reference manual for details.
Definition at line 96 of file flash_common_f24.c.
References FLASH_ACR, and FLASH_ACR_PRFTEN.
Referenced by rcc_clock_setup_hsi(), rcc_clock_setup_msi(), and rcc_clock_setup_pll().
void flash_program (uint32_t address, uint8_t * data, uint32_t len)
Program a Data Block to FLASH.
This programs an arbitrary length data block to FLASH memory. The program error flag should be checked separately for the event that memory was not properly erased.
Parameters
[in] uint32_t address. Starting address in Flash.
[in] uint8_t *data. Pointer to start of data block.
[in] uint32_t len. Length of data block.
Definition at line 333 of file flash_common_f24.c.
References flash_program_byte().
void flash_program_byte (uint32_t address, uint8_t data)
Program an 8 bit Byte to FLASH.
This performs all operations necessary to program an 8 bit byte to FLASH memory. The program error flag should be checked separately for the event that memory was not properly erased.
Parameters
[in] uint32_t address
[in] uint8_t data.
Definition at line 307 of file flash_common_f24.c.
References FLASH_CR, FLASH_CR_PG, FLASH_CR_PROGRAM_X8, flash_set_program_size(), and flash_wait_for_last_operation().
Referenced by flash_program().
void flash_program_double_word (uint32_t address, uint64_t data)
Program a 64 bit Word to FLASH.
This performs all operations necessary to program a 64 bit word to FLASH memory. The program error flag should be checked separately for the event that memory was not properly erased.
Parameters
[in] uint32_t address
[in] uint64_t data.
Definition at line 222 of file flash_common_f24.c.
References FLASH_CR, FLASH_CR_PG, FLASH_CR_PROGRAM_X64, flash_set_program_size(), and flash_wait_for_last_operation().
void flash_program_half_word (uint32_t address, uint16_t data)
Program a Half Word to FLASH.
This performs all operations necessary to program a 16 bit word to FLASH memory. The program error flag should be checked separately for the event that memory was not properly erased.
Parameters
[in] uint32_t address
[in] uint16_t data.
Definition at line 282 of file flash_common_f24.c.
References FLASH_CR, FLASH_CR_PG, FLASH_CR_PROGRAM_X16, flash_set_program_size(), and flash_wait_for_last_operation().
Referenced by flash_program_word().
void flash_program_option_bytes (uint32_t address, uint16_t data)
Program the Option Bytes.
This performs all operations necessary to program the option bytes. The write protect error flag should be checked separately for the event that an option byte had not been properly erased before calling this function.
Only the lower 8 bits of the data is significant.
Parameters
[in] uint32_t address. Address of option byte from flash_options.
[in] uint16_t data.
Definition at line 220 of file flash_common_f01.c.
References FLASH_CR, FLASH_CR_OPTPG, FLASH_CR_OPTWRE, flash_unlock_option_bytes(), and flash_wait_for_last_operation().
void flash_program_option_bytes (uint32_t data)
Program the Option Bytes.
This performs all operations necessary to program the option bytes. The option bytes do not need to be erased first.
Parameters
[in] uint32_t data to be programmed.
Definition at line 402 of file flash_common_f24.c.
References FLASH_OPTCR, FLASH_OPTCR_OPTLOCK, FLASH_OPTCR_OPTSTRT, flash_unlock_option_bytes(), and flash_wait_for_last_operation().
void flash_set_ws (uint32_t ws)
Set the Number of Wait States.
Used to match the system clock to the FLASH memory access time. See the reference manual for more information on clock speed ranges for each wait state. The latency must be changed to the appropriate value before any increase in clock speed, or after any decrease in clock speed.
Parameters
[in] uint32_t ws: values from FLASH Wait States.
Used to match the system clock to the FLASH memory access time. See the programming manual for more information on clock speed ranges. The latency must be changed to the appropriate value before any increase in clock speed, or after any decrease in clock speed.
Parameters
[in] uint32_t ws: values from FLASH Wait States.
Used to match the system clock to the FLASH memory access time. See the programming manual for more information on clock speed and voltage ranges. The latency must be changed to the appropriate value before any increase in clock speed, or after any decrease in clock speed. A latency setting of zero only applies if 64-bit mode is not used.
Parameters
[in] uint32_t ws: values from FLASH Wait States.
Used to match the system clock to the FLASH memory access time. See the reference manual for more information on clock speed ranges for each wait state. The latency must be changed to the appropriate value before any increase in clock speed, or after any decrease in clock speed.
Parameters
[in] uint32_t ws: values from FLASH Wait States.
Used to match the system clock to the FLASH memory access time. See the programming manual for more information on clock speed ranges. The latency must be changed to the appropriate value before any increase in clock speed, or after any decrease in clock speed.
Parameters
[in] uint32_t ws: values from FLASH Wait States.
Definition at line 67 of file flash_common_f01.c.
References FLASH_ACR, and FLASH_ACR_LATENCY.
Referenced by rcc_clock_setup_hsi(), rcc_clock_setup_msi(), and rcc_clock_setup_pll().
void flash_unlock (void)
Unlock the Flash Program and Erase Controller.
This enables write access to the Flash memory. It is locked by default on reset.
Unlock the Flash Program and Erase Controller.
This enables write access to the Flash memory. It is locked by default on reset.
Definition at line 79 of file flash_common_f01.c.
References FLASH_CR, FLASH_CR_LOCK, FLASH_KEYR, FLASH_KEYR_KEY1, FLASH_KEYR_KEY2, flash_unlock_option_bytes(), flash_unlock_pecr(), and flash_unlock_progmem().
void flash_unlock_option_bytes (void)
Unlock the Option Byte Access.
This enables write access to the option bytes. It is locked by default on reset.
Definition at line 178 of file flash_common_f01.c.
References FLASH_KEYR_KEY1, FLASH_KEYR_KEY2, FLASH_OPTKEYR, FLASH_OPTKEYR_OPTKEY1, FLASH_OPTKEYR_OPTKEY2, and flash_unlock_pecr().
Referenced by flash_erase_option_bytes(), flash_program_option_bytes(), and flash_unlock().
void flash_unlock_pecr (void)
Definition at line 124 of file flash.c.
References FLASH_PEKEYR, FLASH_PEKEYR_PEKEY1, and FLASH_PEKEYR_PEKEY2.
Referenced by eeprom_program_word(), eeprom_program_words(), flash_unlock(), flash_unlock_option_bytes(), and flash_unlock_progmem().
void flash_unlock_progmem (void)
Definition at line 133 of file flash.c.
References FLASH_PRGKEYR, FLASH_PRGKEYR_PRGKEY1, FLASH_PRGKEYR_PRGKEY2, and flash_unlock_pecr().
Referenced by flash_unlock().