libopencm3: RCC
RCC
STM32L1xx
libopencm3 STM32F1xx Reset and Clock Control
Functions
void rcc_osc_ready_int_clear (enum rcc_osc osc)
void rcc_osc_ready_int_enable (enum rcc_osc osc)
void rcc_osc_ready_int_disable (enum rcc_osc osc)
int rcc_osc_ready_int_flag (enum rcc_osc osc)
void rcc_css_int_clear (void)
int rcc_css_int_flag (void)
void rcc_wait_for_osc_ready (enum rcc_osc osc)
void rcc_wait_for_sysclk_status (enum rcc_osc osc)
void rcc_osc_on (enum rcc_osc osc)
void rcc_osc_off (enum rcc_osc osc)
void rcc_css_enable (void)
void rcc_css_disable (void)
void rcc_osc_bypass_enable (enum rcc_osc osc)
void rcc_osc_bypass_disable (enum rcc_osc osc)
void rcc_set_sysclk_source (uint32_t clk)
void rcc_set_pll_configuration (uint32_t source, uint32_t multiplier, uint32_t divisor)
void rcc_set_pll_source (uint32_t pllsrc)
void rcc_set_ppre2 (uint32_t ppre2)
void rcc_set_ppre1 (uint32_t ppre1)
void rcc_set_hpre (uint32_t hpre)
void rcc_set_rtcpre (uint32_t rtcpre)
uint32_t rcc_system_clock_source (void)
void rcc_rtc_select_clock (uint32_t clock)
void rcc_clock_setup_msi (const struct rcc_clock_scale *clock)
void rcc_clock_setup_hsi (const struct rcc_clock_scale *clock)
void rcc_clock_setup_pll (const struct rcc_clock_scale *clock)
Variables
uint32_t rcc_ahb_frequency = 2097000
uint32_t rcc_apb1_frequency = 2097000
uint32_t rcc_apb2_frequency = 2097000
const struct rcc_clock_scale rcc_clock_config [RCC_CLOCK_CONFIG_END]
Detailed Description
libopencm3 STM32F1xx Reset and Clock Control
Version
1.0.0
This library supports the Reset and Clock Control System in the STM32L1xx series of ARM Cortex Microcontrollers by ST Microelectronics.
Clock settings and resets for many peripherals are given here rather than in the corresponding peripheral library.
The library also provides a number of common configurations for the processor system clock. Not all possible configurations are included.
Function Documentation
void rcc_clock_setup_hsi (const struct rcc_clock_scale * clock)
Definition at line 493 of file rcc.c.
References rcc_clock_scale::ahb_frequency, rcc_clock_scale::apb1_frequency, rcc_clock_scale::apb2_frequency, flash_64bit_enable(), rcc_clock_scale::flash_config, flash_prefetch_enable(), flash_set_ws(), rcc_clock_scale::hpre, rcc_clock_scale::ppre1, rcc_clock_scale::ppre2, pwr_set_vos_scale(), rcc_ahb_frequency, rcc_apb1_frequency, RCC_APB1ENR, RCC_APB1ENR_PWREN, rcc_apb2_frequency, RCC_CFGR_SW_SYSCLKSEL_HSICLK, RCC_HSI, rcc_osc_on(), rcc_peripheral_enable_clock(), rcc_set_hpre(), rcc_set_ppre1(), rcc_set_ppre2(), rcc_set_sysclk_source(), rcc_wait_for_osc_ready(), and rcc_clock_scale::voltage_scale.
void rcc_clock_setup_msi (const struct rcc_clock_scale * clock)
Definition at line 455 of file rcc.c.
References rcc_clock_scale::ahb_frequency, rcc_clock_scale::apb1_frequency, rcc_clock_scale::apb2_frequency, flash_64bit_enable(), rcc_clock_scale::flash_config, flash_prefetch_enable(), flash_set_ws(), rcc_clock_scale::hpre, rcc_clock_scale::msi_range, rcc_clock_scale::ppre1, rcc_clock_scale::ppre2, pwr_set_vos_scale(), rcc_ahb_frequency, rcc_apb1_frequency, RCC_APB1ENR, RCC_APB1ENR_PWREN, rcc_apb2_frequency, RCC_CFGR_SW_SYSCLKSEL_MSICLK, RCC_ICSCR, RCC_ICSCR_MSIRANGE_MASK, RCC_ICSCR_MSIRANGE_SHIFT, RCC_MSI, rcc_osc_on(), rcc_peripheral_enable_clock(), rcc_set_hpre(), rcc_set_ppre1(), rcc_set_ppre2(), rcc_set_sysclk_source(), rcc_wait_for_osc_ready(), and rcc_clock_scale::voltage_scale.
void rcc_clock_setup_pll (const struct rcc_clock_scale * clock)
Definition at line 525 of file rcc.c.
References rcc_clock_scale::ahb_frequency, rcc_clock_scale::apb1_frequency, rcc_clock_scale::apb2_frequency, flash_64bit_enable(), rcc_clock_scale::flash_config, flash_prefetch_enable(), flash_set_ws(), rcc_clock_scale::hpre, rcc_clock_scale::pll_div, rcc_clock_scale::pll_mul, rcc_clock_scale::pll_source, rcc_clock_scale::ppre1, rcc_clock_scale::ppre2, pwr_set_vos_scale(), rcc_ahb_frequency, rcc_apb1_frequency, RCC_APB1ENR, RCC_APB1ENR_PWREN, rcc_apb2_frequency, RCC_CFGR_PLLSRC_HSE_CLK, RCC_CFGR_SW_SYSCLKSEL_PLLCLK, RCC_HSE, RCC_HSI, rcc_osc_on(), rcc_peripheral_enable_clock(), RCC_PLL, rcc_set_hpre(), rcc_set_pll_configuration(), rcc_set_ppre1(), rcc_set_ppre2(), rcc_set_sysclk_source(), rcc_wait_for_osc_ready(), and rcc_clock_scale::voltage_scale.
void rcc_css_disable (void)
Definition at line 333 of file rcc.c.
References RCC_CR, and RCC_CR_CSSON.
void rcc_css_enable (void)
Definition at line 328 of file rcc.c.
References RCC_CR, and RCC_CR_CSSON.
void rcc_css_int_clear (void)
Definition at line 221 of file rcc.c.
References RCC_CIR, and RCC_CIR_CSSC.
int rcc_css_int_flag (void)
Definition at line 226 of file rcc.c.
References RCC_CIR, and RCC_CIR_CSSF.
void rcc_osc_bypass_disable (enum rcc_osc osc)
Definition at line 356 of file rcc.c.
References RCC_CR, RCC_CR_HSEBYP, RCC_CSR, RCC_CSR_LSEBYP, RCC_HSE, RCC_HSI, RCC_LSE, RCC_LSI, RCC_MSI, and RCC_PLL.
void rcc_osc_bypass_enable (enum rcc_osc osc)
Definition at line 338 of file rcc.c.
References RCC_CR, RCC_CR_HSEBYP, RCC_CSR, RCC_CSR_LSEBYP, RCC_HSE, RCC_HSI, RCC_LSE, RCC_LSI, RCC_MSI, and RCC_PLL.
void rcc_osc_off (enum rcc_osc osc)
Definition at line 304 of file rcc.c.
References RCC_CR, RCC_CR_HSEON, RCC_CR_HSION, RCC_CR_MSION, RCC_CR_PLLON, RCC_CSR, RCC_CSR_LSEON, RCC_CSR_LSION, RCC_HSE, RCC_HSI, RCC_LSE, RCC_LSI, RCC_MSI, and RCC_PLL.
void rcc_osc_on (enum rcc_osc osc)
Definition at line 280 of file rcc.c.
References RCC_CR, RCC_CR_HSEON, RCC_CR_HSION, RCC_CR_MSION, RCC_CR_PLLON, RCC_CSR, RCC_CSR_LSEON, RCC_CSR_LSION, RCC_HSE, RCC_HSI, RCC_LSE, RCC_LSI, RCC_MSI, and RCC_PLL.
Referenced by rcc_clock_setup_hsi(), rcc_clock_setup_msi(), and rcc_clock_setup_pll().
void rcc_osc_ready_int_clear (enum rcc_osc osc)
Definition at line 122 of file rcc.c.
References RCC_CIR, RCC_CIR_HSERDYC, RCC_CIR_HSIRDYC, RCC_CIR_LSERDYC, RCC_CIR_LSIRDYC, RCC_CIR_MSIRDYC, RCC_CIR_PLLRDYC, RCC_HSE, RCC_HSI, RCC_LSE, RCC_LSI, RCC_MSI, and RCC_PLL.
void rcc_osc_ready_int_disable (enum rcc_osc osc)
Definition at line 170 of file rcc.c.
References RCC_CIR, RCC_CIR_HSERDYIE, RCC_CIR_HSIRDYIE, RCC_CIR_LSERDYIE, RCC_CIR_LSIRDYIE, RCC_CIR_MSIRDYIE, RCC_CIR_PLLRDYIE, RCC_HSE, RCC_HSI, RCC_LSE, RCC_LSI, RCC_MSI, and RCC_PLL.
void rcc_osc_ready_int_enable (enum rcc_osc osc)
Definition at line 146 of file rcc.c.
References RCC_CIR, RCC_CIR_HSERDYIE, RCC_CIR_HSIRDYIE, RCC_CIR_LSERDYIE, RCC_CIR_LSIRDYIE, RCC_CIR_MSIRDYIE, RCC_CIR_PLLRDYIE, RCC_HSE, RCC_HSI, RCC_LSE, RCC_LSI, RCC_MSI, and RCC_PLL.
int rcc_osc_ready_int_flag (enum rcc_osc osc)
Definition at line 194 of file rcc.c.
References RCC_CIR, RCC_CIR_HSERDYF, RCC_CIR_HSIRDYF, RCC_CIR_LSERDYF, RCC_CIR_LSIRDYF, RCC_CIR_MSIRDYF, RCC_CIR_PLLRDYF, RCC_HSE, RCC_HSI, RCC_LSE, RCC_LSI, RCC_MSI, and RCC_PLL.
void rcc_rtc_select_clock (uint32_t clock)
Definition at line 449 of file rcc.c.
References RCC_CSR, RCC_CSR_RTCSEL_MASK, and RCC_CSR_RTCSEL_SHIFT.
void rcc_set_hpre (uint32_t hpre)
Definition at line 425 of file rcc.c.
References RCC_CFGR.
Referenced by rcc_clock_setup_hsi(), rcc_clock_setup_msi(), and rcc_clock_setup_pll().
void rcc_set_pll_configuration (uint32_t source, uint32_t multiplier, uint32_t divisor)
Definition at line 383 of file rcc.c.
References RCC_CFGR, RCC_CFGR_PLLDIV_MASK, RCC_CFGR_PLLDIV_SHIFT, RCC_CFGR_PLLMUL_MASK, and RCC_CFGR_PLLMUL_SHIFT.
Referenced by rcc_clock_setup_pll().
void rcc_set_pll_source (uint32_t pllsrc)
Definition at line 398 of file rcc.c.
References RCC_CFGR.
void rcc_set_ppre1 (uint32_t ppre1)
Definition at line 416 of file rcc.c.
References RCC_CFGR.
Referenced by rcc_clock_setup_hsi(), rcc_clock_setup_msi(), and rcc_clock_setup_pll().
void rcc_set_ppre2 (uint32_t ppre2)
Definition at line 407 of file rcc.c.
References RCC_CFGR.
Referenced by rcc_clock_setup_hsi(), rcc_clock_setup_msi(), and rcc_clock_setup_pll().
void rcc_set_rtcpre (uint32_t rtcpre)
Definition at line 434 of file rcc.c.
References RCC_CR.
void rcc_set_sysclk_source (uint32_t clk)
Definition at line 374 of file rcc.c.
References RCC_CFGR.
Referenced by rcc_clock_setup_hsi(), rcc_clock_setup_msi(), and rcc_clock_setup_pll().
uint32_t rcc_system_clock_source (void)
Definition at line 443 of file rcc.c.
References RCC_CFGR.
void rcc_wait_for_osc_ready (enum rcc_osc osc)
Definition at line 231 of file rcc.c.
References RCC_CR, RCC_CR_HSERDY, RCC_CR_HSIRDY, RCC_CR_MSIRDY, RCC_CR_PLLRDY, RCC_CSR, RCC_CSR_LSERDY, RCC_CSR_LSIRDY, RCC_HSE, RCC_HSI, RCC_LSE, RCC_LSI, RCC_MSI, and RCC_PLL.
Referenced by rcc_clock_setup_hsi(), rcc_clock_setup_msi(), and rcc_clock_setup_pll().
void rcc_wait_for_sysclk_status (enum rcc_osc osc)
Definition at line 255 of file rcc.c.
References RCC_CFGR, RCC_CFGR_SWS_SYSCLKSEL_HSECLK, RCC_CFGR_SWS_SYSCLKSEL_HSICLK, RCC_CFGR_SWS_SYSCLKSEL_MSICLK, RCC_CFGR_SWS_SYSCLKSEL_PLLCLK, RCC_HSE, RCC_HSI, RCC_MSI, and RCC_PLL.
Variable Documentation
uint32_t rcc_ahb_frequency = 2097000
Definition at line 47 of file rcc.c.
Referenced by rcc_clock_setup_hsi(), rcc_clock_setup_msi(), and rcc_clock_setup_pll().
uint32_t rcc_apb1_frequency = 2097000
Definition at line 48 of file rcc.c.
Referenced by rcc_clock_setup_hsi(), rcc_clock_setup_msi(), rcc_clock_setup_pll(), and usart_set_baudrate().
uint32_t rcc_apb2_frequency = 2097000
Definition at line 49 of file rcc.c.
Referenced by rcc_clock_setup_hsi(), rcc_clock_setup_msi(), rcc_clock_setup_pll(), and usart_set_baudrate().
const struct rcc_clock_scale rcc_clock_config[RCC_CLOCK_CONFIG_END]
Definition at line 51 of file rcc.c.