libopencm3: RCC Defines
RCC Defines
STM32L1xx Defines
libopencm3 STM32L1xx Reset and Clock Control
Data Structures
struct clock_scale_t
Modules
RCC_AHBENR enable values
RCC_APB2ENR enable values
RCC_APB1ENR enable values
Macros
#define RCC_CR MMIO32(RCC_BASE + 0x00)
#define RCC_ICSCR MMIO32(RCC_BASE + 0x04)
#define RCC_CFGR MMIO32(RCC_BASE + 0x08)
#define RCC_CIR MMIO32(RCC_BASE + 0x0c)
#define RCC_AHBRSTR MMIO32(RCC_BASE + 0x10)
#define RCC_APB2RSTR MMIO32(RCC_BASE + 0x14)
#define RCC_APB1RSTR MMIO32(RCC_BASE + 0x18)
#define RCC_AHBENR MMIO32(RCC_BASE + 0x1c)
#define RCC_APB2ENR MMIO32(RCC_BASE + 0x20)
#define RCC_APB1ENR MMIO32(RCC_BASE + 0x24)
#define RCC_AHBLPENR MMIO32(RCC_BASE + 0x28)
#define RCC_APB2LPENR MMIO32(RCC_BASE + 0x2c)
#define RCC_APB1LPENR MMIO32(RCC_BASE + 0x30)
#define RCC_CSR MMIO32(RCC_BASE + 0x34)
#define RCC_CR_CSSON (1 << 28)
#define RCC_CR_PLLRDY (1 << 25)
#define RCC_CR_PLLON (1 << 24)
#define RCC_CR_HSEBYP (1 << 18)
#define RCC_CR_HSERDY (1 << 17)
#define RCC_CR_HSEON (1 << 16)
#define RCC_CR_MSIRDY (1 << 9)
#define RCC_CR_MSION (1 << 8)
#define RCC_CR_HSIRDY (1 << 1)
#define RCC_CR_HSION (1 << 0)
#define RCC_CR_RTCPRE_DIV2 0
#define RCC_CR_RTCPRE_DIV4 1
#define RCC_CR_RTCPRE_DIV8 2
#define RCC_CR_RTCPRE_DIV16 3
#define RCC_CR_RTCPRE_SHIFT 29
#define RCC_CR_RTCPRE_MASK 0x3
#define RCC_ICSCR_MSITRIM_SHIFT 24
#define RCC_ICSCR_MSITRIM_MASK 0xff
#define RCC_ICSCR_MSICAL_SHIFT 16
#define RCC_ICSCR_MSICAL_MASK 0xff
#define RCC_ICSCR_MSIRANGE_SHIFT 13
#define RCC_ICSCR_MSIRANGE_MASK 0x7
#define RCC_ICSCR_MSIRANGE_65KHZ 0x0
#define RCC_ICSCR_MSIRANGE_131KHZ 0x1
#define RCC_ICSCR_MSIRANGE_262KHZ 0x2
#define RCC_ICSCR_MSIRANGE_524KHZ 0x3
#define RCC_ICSCR_MSIRANGE_1MHZ 0x4
#define RCC_ICSCR_MSIRANGE_2MHZ 0x5
#define RCC_ICSCR_MSIRANGE_4MHZ 0x6
#define RCC_ICSCR_HSITRIM_SHIFT 8
#define RCC_ICSCR_HSITRIM_MASK 0x1f
#define RCC_ICSCR_HSICAL_SHIFT 0
#define RCC_ICSCR_HSICAL_MASK 0xff
#define RCC_CFGR_MCOPRE_DIV1 0
#define RCC_CFGR_MCOPRE_DIV2 1
#define RCC_CFGR_MCOPRE_DIV4 2
#define RCC_CFGR_MCOPRE_DIV8 3
#define RCC_CFGR_MCOPRE_DIV16 4
#define RCC_CFGR_MCO_NOCLK 0x0
#define RCC_CFGR_MCO_SYSCLK 0x1
#define RCC_CFGR_MCO_HSICLK 0x2
#define RCC_CFGR_MCO_MSICLK 0x3
#define RCC_CFGR_MCO_HSECLK 0x4
#define RCC_CFGR_MCO_PLLCLK 0x5
#define RCC_CFGR_MCO_LSICLK 0x6
#define RCC_CFGR_MCO_LSECLK 0x7
#define RCC_CFGR_PLLDIV_DIV2 0x1
#define RCC_CFGR_PLLDIV_DIV3 0x2
#define RCC_CFGR_PLLDIV_DIV4 0x3
#define RCC_CFGR_PLLDIV_SHIFT 22
#define RCC_CFGR_PLLDIV_MASK 0x3
#define RCC_CFGR_PLLMUL_MUL3 0x0
#define RCC_CFGR_PLLMUL_MUL4 0x1
#define RCC_CFGR_PLLMUL_MUL6 0x2
#define RCC_CFGR_PLLMUL_MUL8 0x3
#define RCC_CFGR_PLLMUL_MUL12 0x4
#define RCC_CFGR_PLLMUL_MUL16 0x5
#define RCC_CFGR_PLLMUL_MUL24 0x6
#define RCC_CFGR_PLLMUL_MUL32 0x7
#define RCC_CFGR_PLLMUL_MUL48 0x8
#define RCC_CFGR_PLLMUL_SHIFT 18
#define RCC_CFGR_PLLMUL_MASK 0xf
#define RCC_CFGR_PLLSRC_HSI_CLK 0x0
#define RCC_CFGR_PLLSRC_HSE_CLK 0x1
#define RCC_CFGR_PPRE2_HCLK_NODIV 0x0
#define RCC_CFGR_PPRE2_HCLK_DIV2 0x4
#define RCC_CFGR_PPRE2_HCLK_DIV4 0x5
#define RCC_CFGR_PPRE2_HCLK_DIV8 0x6
#define RCC_CFGR_PPRE2_HCLK_DIV16 0x7
#define RCC_CFGR_PPRE1_HCLK_NODIV 0x0
#define RCC_CFGR_PPRE1_HCLK_DIV2 0x4
#define RCC_CFGR_PPRE1_HCLK_DIV4 0x5
#define RCC_CFGR_PPRE1_HCLK_DIV8 0x6
#define RCC_CFGR_PPRE1_HCLK_DIV16 0x7
#define RCC_CFGR_HPRE_SYSCLK_NODIV 0x0
#define RCC_CFGR_HPRE_SYSCLK_DIV2 0x8
#define RCC_CFGR_HPRE_SYSCLK_DIV4 0x9
#define RCC_CFGR_HPRE_SYSCLK_DIV8 0xa
#define RCC_CFGR_HPRE_SYSCLK_DIV16 0xb
#define RCC_CFGR_HPRE_SYSCLK_DIV64 0xc
#define RCC_CFGR_HPRE_SYSCLK_DIV128 0xd
#define RCC_CFGR_HPRE_SYSCLK_DIV256 0xe
#define RCC_CFGR_HPRE_SYSCLK_DIV512 0xf
#define RCC_CFGR_SWS_SYSCLKSEL_MSICLK 0x0
#define RCC_CFGR_SWS_SYSCLKSEL_HSICLK 0x1
#define RCC_CFGR_SWS_SYSCLKSEL_HSECLK 0x2
#define RCC_CFGR_SWS_SYSCLKSEL_PLLCLK 0x3
#define RCC_CFGR_SW_SYSCLKSEL_MSICLK 0x0
#define RCC_CFGR_SW_SYSCLKSEL_HSICLK 0x1
#define RCC_CFGR_SW_SYSCLKSEL_HSECLK 0x2
#define RCC_CFGR_SW_SYSCLKSEL_PLLCLK 0x3
#define RCC_CIR_CSSC (1 << 23)
#define RCC_CIR_MSIRDYC (1 << 21)
#define RCC_CIR_PLLRDYC (1 << 20)
#define RCC_CIR_HSERDYC (1 << 19)
#define RCC_CIR_HSIRDYC (1 << 18)
#define RCC_CIR_LSERDYC (1 << 17)
#define RCC_CIR_LSIRDYC (1 << 16)
#define RCC_CIR_MSIRDYIE (1 << 13)
#define RCC_CIR_PLLRDYIE (1 << 12)
#define RCC_CIR_HSERDYIE (1 << 11)
#define RCC_CIR_HSIRDYIE (1 << 10)
#define RCC_CIR_LSERDYIE (1 << 9)
#define RCC_CIR_LSIRDYIE (1 << 8)
#define RCC_CIR_CSSF (1 << 7)
#define RCC_CIR_MSIRDYF (1 << 5) /* (**) */
#define RCC_CIR_PLLRDYF (1 << 4)
#define RCC_CIR_HSERDYF (1 << 3)
#define RCC_CIR_HSIRDYF (1 << 2)
#define RCC_CIR_LSERDYF (1 << 1)
#define RCC_CIR_LSIRDYF (1 << 0)
#define RCC_AHBRSTR_DMA1RST (1 << 24)
#define RCC_AHBRSTR_FLITFRST (1 << 15)
#define RCC_AHBRSTR_CRCRST (1 << 12)
#define RCC_AHBRSTR_GPIOHRST (1 << 5)
#define RCC_AHBRSTR_GPIOERST (1 << 4)
#define RCC_AHBRSTR_GPIODRST (1 << 3)
#define RCC_AHBRSTR_GPIOCRST (1 << 2)
#define RCC_AHBRSTR_GPIOBRST (1 << 1)
#define RCC_AHBRSTR_GPIOARST (1 << 0)
#define RCC_APB2RSTR_USART1RST (1 << 14)
#define RCC_APB2RSTR_SPI1RST (1 << 12)
#define RCC_APB2RSTR_ADC1RST (1 << 9)
#define RCC_APB2RSTR_TIM11RST (1 << 4)
#define RCC_APB2RSTR_TIM10RST (1 << 3)
#define RCC_APB2RSTR_TIM9RST (1 << 2)
#define RCC_APB2RSTR_SYSCFGRST (1 << 0)
#define RCC_APB1RSTR_COMPRST (1 << 31)
#define RCC_APB1RSTR_DACRST (1 << 29)
#define RCC_APB1RSTR_PWRRST (1 << 28)
#define RCC_APB1RSTR_USBRST (1 << 23)
#define RCC_APB1RSTR_I2C2RST (1 << 22)
#define RCC_APB1RSTR_I2C1RST (1 << 21)
#define RCC_APB1RSTR_USART3RST (1 << 18)
#define RCC_APB1RSTR_USART2RST (1 << 17)
#define RCC_APB1RSTR_SPI2RST (1 << 14)
#define RCC_APB1RSTR_WWDGRST (1 << 11)
#define RCC_APB1RSTR_LCDRST (1 << 9)
#define RCC_APB1RSTR_TIM7RST (1 << 5)
#define RCC_APB1RSTR_TIM6RST (1 << 4)
#define RCC_APB1RSTR_TIM5RST (1 << 3)
#define RCC_APB1RSTR_TIM4RST (1 << 2)
#define RCC_APB1RSTR_TIM3RST (1 << 1)
#define RCC_APB1RSTR_TIM2RST (1 << 0)
#define RCC_AHBLPENR_DMA1LPEN (1 << 24)
#define RCC_AHBLPENR_SRAMLPEN (1 << 16)
#define RCC_AHBLPENR_FLITFLPEN (1 << 15)
#define RCC_AHBLPENR_CRCLPEN (1 << 12)
#define RCC_AHBLPENR_GPIOHLPEN (1 << 5)
#define RCC_AHBLPENR_GPIOELPEN (1 << 4)
#define RCC_AHBLPENR_GPIODLPEN (1 << 3)
#define RCC_AHBLPENR_GPIOCLPEN (1 << 2)
#define RCC_AHBLPENR_GPIOBLPEN (1 << 1)
#define RCC_AHBLPENR_GPIOALPEN (1 << 0)
#define RCC_APB2LPENR_USART1LPEN (1 << 14)
#define RCC_APB2LPENR_SPI1LPEN (1 << 12)
#define RCC_APB2LPENR_ADC1LPEN (1 << 9)
#define RCC_APB2LPENR_TIM11LPEN (1 << 4)
#define RCC_APB2LPENR_TIM10LPEN (1 << 3)
#define RCC_APB2LPENR_TIM9LPEN (1 << 2)
#define RCC_APB2LPENR_SYSCFGLPEN (1 << 0)
#define RCC_APB1LPENR_COMPLPEN (1 << 31)
#define RCC_APB1LPENR_DACLPEN (1 << 29)
#define RCC_APB1LPENR_PWRLPEN (1 << 28)
#define RCC_APB1LPENR_USBLPEN (1 << 23)
#define RCC_APB1LPENR_I2C2LPEN (1 << 22)
#define RCC_APB1LPENR_I2C1LPEN (1 << 21)
#define RCC_APB1LPENR_USART3LPEN (1 << 18)
#define RCC_APB1LPENR_USART2LPEN (1 << 17)
#define RCC_APB1LPENR_SPI2LPEN (1 << 14)
#define RCC_APB1LPENR_WWDGLPEN (1 << 11)
#define RCC_APB1LPENR_LCDLPEN (1 << 9)
#define RCC_APB1LPENR_TIM7LPEN (1 << 5)
#define RCC_APB1LPENR_TIM6LPEN (1 << 4)
#define RCC_APB1LPENR_TIM4LPEN (1 << 2)
#define RCC_APB1LPENR_TIM3LPEN (1 << 1)
#define RCC_APB1LPENR_TIM2LPEN (1 << 0)
#define RCC_CSR_LPWRRSTF (1 << 31)
#define RCC_CSR_WWDGRSTF (1 << 30)
#define RCC_CSR_IWDGRSTF (1 << 29)
#define RCC_CSR_SFTRSTF (1 << 28)
#define RCC_CSR_PORRSTF (1 << 27)
#define RCC_CSR_PINRSTF (1 << 26)
#define RCC_CSR_OBLRSTF (1 << 25)
#define RCC_CSR_RMVF (1 << 24)
#define RCC_CSR_RTCRST (1 << 23)
#define RCC_CSR_RTCEN (1 << 22)
#define RCC_CSR_RTCSEL_SHIFT (16)
#define RCC_CSR_RTCSEL_MASK (0x3)
#define RCC_CSR_RTCSEL_NONE (0x0)
#define RCC_CSR_RTCSEL_LSE (0x1)
#define RCC_CSR_RTCSEL_LSI (0x2)
#define RCC_CSR_RTCSEL_HSI (0x3)
#define RCC_CSR_LSECSSD (1 << 12)
#define RCC_CSR_LSECSSON (1 << 11)
#define RCC_CSR_LSEBYP (1 << 10)
#define RCC_CSR_LSERDY (1 << 9)
#define RCC_CSR_LSEON (1 << 8)
#define RCC_CSR_LSIRDY (1 << 1)
#define RCC_CSR_LSION (1 << 0)
Enumerations
enum clock_config_entry_t {
CLOCK_VRANGE1_HSI_PLL_24MHZ, CLOCK_VRANGE1_HSI_PLL_32MHZ, CLOCK_VRANGE1_HSI_RAW_16MHZ, CLOCK_VRANGE1_HSI_RAW_4MHZ,
CLOCK_VRANGE1_MSI_RAW_4MHZ, CLOCK_VRANGE1_MSI_RAW_2MHZ, CLOCK_CONFIG_END
}
enum osc_t {
PLL, HSE, HSI, MSI,
LSE, LSI
}
Functions
BEGIN_DECLS void rcc_osc_ready_int_clear (osc_t osc)
void rcc_osc_ready_int_enable (osc_t osc)
void rcc_osc_ready_int_disable (osc_t osc)
int rcc_osc_ready_int_flag (osc_t osc)
void rcc_css_int_clear (void)
int rcc_css_int_flag (void)
void rcc_wait_for_osc_ready (osc_t osc)
void rcc_wait_for_sysclk_status (osc_t osc)
void rcc_osc_on (osc_t osc)
void rcc_osc_off (osc_t osc)
void rcc_css_enable (void)
void rcc_css_disable (void)
void rcc_osc_bypass_enable (osc_t osc)
void rcc_osc_bypass_disable (osc_t osc)
void rcc_peripheral_enable_clock (volatile u32 *reg, u32 en)
void rcc_peripheral_disable_clock (volatile u32 *reg, u32 en)
void rcc_peripheral_reset (volatile u32 *reg, u32 reset)
void rcc_peripheral_clear_reset (volatile u32 *reg, u32 clear_reset)
void rcc_set_sysclk_source (u32 clk)
void rcc_set_pll_configuration (u32 source, u32 multiplier, u32 divisor)
void rcc_set_pll_source (u32 pllsrc)
void rcc_set_adcpre (u32 adcpre)
void rcc_set_ppre2 (u32 ppre2)
void rcc_set_ppre1 (u32 ppre1)
void rcc_set_hpre (u32 hpre)
void rcc_set_usbpre (u32 usbpre)
void rcc_set_rtcpre (u32 rtcpre)
u32 rcc_system_clock_source (void)
void rcc_rtc_select_clock (u32 clock)
void rcc_clock_setup_msi (const clock_scale_t *clock)
void rcc_clock_setup_hsi (const clock_scale_t *clock)
void rcc_clock_setup_pll (const clock_scale_t *clock)
void rcc_backupdomain_reset (void)
Variables
const clock_scale_t clock_config [CLOCK_CONFIG_END]
u32 rcc_ppre1_frequency
u32 rcc_ppre2_frequency
Detailed Description
libopencm3 STM32L1xx Reset and Clock Control
Version
1.0.0
Author
© 2009 Federico Ruiz-Ugalde <memeruiz at gmail dot com>
© 2009 Uwe Hermann uwe@h.nosp@m.erma.nosp@m.nn-uw.nosp@m.e.de
© 2012 Karl Palsson karlp.nosp@m.@twe.nosp@m.ak.ne.nosp@m.t.au
Date
11 November 2012
LGPL License Terms libopencm3 License
Macro Definition Documentation
#define RCC_AHBENR MMIO32(RCC_BASE + 0x1c)
Definition at line 60 of file rcc.h.
#define RCC_AHBLPENR MMIO32(RCC_BASE + 0x28)
Definition at line 63 of file rcc.h.
#define RCC_AHBLPENR_CRCLPEN (1 << 12)
Definition at line 324 of file rcc.h.
#define RCC_AHBLPENR_DMA1LPEN (1 << 24)
Definition at line 321 of file rcc.h.
#define RCC_AHBLPENR_FLITFLPEN (1 << 15)
Definition at line 323 of file rcc.h.
#define RCC_AHBLPENR_GPIOALPEN (1 << 0)
Definition at line 330 of file rcc.h.
#define RCC_AHBLPENR_GPIOBLPEN (1 << 1)
Definition at line 329 of file rcc.h.
#define RCC_AHBLPENR_GPIOCLPEN (1 << 2)
Definition at line 328 of file rcc.h.
#define RCC_AHBLPENR_GPIODLPEN (1 << 3)
Definition at line 327 of file rcc.h.
#define RCC_AHBLPENR_GPIOELPEN (1 << 4)
Definition at line 326 of file rcc.h.
#define RCC_AHBLPENR_GPIOHLPEN (1 << 5)
Definition at line 325 of file rcc.h.
#define RCC_AHBLPENR_SRAMLPEN (1 << 16)
Definition at line 322 of file rcc.h.
#define RCC_AHBRSTR MMIO32(RCC_BASE + 0x10)
Definition at line 57 of file rcc.h.
#define RCC_AHBRSTR_CRCRST (1 << 12)
Definition at line 226 of file rcc.h.
#define RCC_AHBRSTR_DMA1RST (1 << 24)
Definition at line 224 of file rcc.h.
#define RCC_AHBRSTR_FLITFRST (1 << 15)
Definition at line 225 of file rcc.h.
#define RCC_AHBRSTR_GPIOARST (1 << 0)
Definition at line 232 of file rcc.h.
#define RCC_AHBRSTR_GPIOBRST (1 << 1)
Definition at line 231 of file rcc.h.
#define RCC_AHBRSTR_GPIOCRST (1 << 2)
Definition at line 230 of file rcc.h.
#define RCC_AHBRSTR_GPIODRST (1 << 3)
Definition at line 229 of file rcc.h.
#define RCC_AHBRSTR_GPIOERST (1 << 4)
Definition at line 228 of file rcc.h.
#define RCC_AHBRSTR_GPIOHRST (1 << 5)
Definition at line 227 of file rcc.h.
#define RCC_APB1ENR MMIO32(RCC_BASE + 0x24)
Definition at line 62 of file rcc.h.
Referenced by rcc_clock_setup_hsi(), rcc_clock_setup_msi(), and rcc_clock_setup_pll().
#define RCC_APB1LPENR MMIO32(RCC_BASE + 0x30)
Definition at line 65 of file rcc.h.
#define RCC_APB1LPENR_COMPLPEN (1 << 31)
Definition at line 340 of file rcc.h.
#define RCC_APB1LPENR_DACLPEN (1 << 29)
Definition at line 341 of file rcc.h.
#define RCC_APB1LPENR_I2C1LPEN (1 << 21)
Definition at line 345 of file rcc.h.
#define RCC_APB1LPENR_I2C2LPEN (1 << 22)
Definition at line 344 of file rcc.h.
#define RCC_APB1LPENR_LCDLPEN (1 << 9)
Definition at line 350 of file rcc.h.
#define RCC_APB1LPENR_PWRLPEN (1 << 28)
Definition at line 342 of file rcc.h.
#define RCC_APB1LPENR_SPI2LPEN (1 << 14)
Definition at line 348 of file rcc.h.
#define RCC_APB1LPENR_TIM2LPEN (1 << 0)
Definition at line 355 of file rcc.h.
#define RCC_APB1LPENR_TIM3LPEN (1 << 1)
Definition at line 354 of file rcc.h.
#define RCC_APB1LPENR_TIM4LPEN (1 << 2)
Definition at line 353 of file rcc.h.
#define RCC_APB1LPENR_TIM6LPEN (1 << 4)
Definition at line 352 of file rcc.h.
#define RCC_APB1LPENR_TIM7LPEN (1 << 5)
Definition at line 351 of file rcc.h.
#define RCC_APB1LPENR_USART2LPEN (1 << 17)
Definition at line 347 of file rcc.h.
#define RCC_APB1LPENR_USART3LPEN (1 << 18)
Definition at line 346 of file rcc.h.
#define RCC_APB1LPENR_USBLPEN (1 << 23)
Definition at line 343 of file rcc.h.
#define RCC_APB1LPENR_WWDGLPEN (1 << 11)
Definition at line 349 of file rcc.h.
#define RCC_APB1RSTR MMIO32(RCC_BASE + 0x18)
Definition at line 59 of file rcc.h.
Referenced by i2c_reset(), spi_reset(), and timer_reset().
#define RCC_APB1RSTR_COMPRST (1 << 31)
Definition at line 246 of file rcc.h.
#define RCC_APB1RSTR_DACRST (1 << 29)
Definition at line 247 of file rcc.h.
#define RCC_APB1RSTR_I2C1RST (1 << 21)
Definition at line 251 of file rcc.h.
Referenced by i2c_reset().
#define RCC_APB1RSTR_I2C2RST (1 << 22)
Definition at line 250 of file rcc.h.
Referenced by i2c_reset().
#define RCC_APB1RSTR_LCDRST (1 << 9)
Definition at line 256 of file rcc.h.
#define RCC_APB1RSTR_PWRRST (1 << 28)
Definition at line 248 of file rcc.h.
#define RCC_APB1RSTR_SPI2RST (1 << 14)
Definition at line 254 of file rcc.h.
Referenced by spi_reset().
#define RCC_APB1RSTR_TIM2RST (1 << 0)
Definition at line 262 of file rcc.h.
Referenced by timer_reset().
#define RCC_APB1RSTR_TIM3RST (1 << 1)
Definition at line 261 of file rcc.h.
Referenced by timer_reset().
#define RCC_APB1RSTR_TIM4RST (1 << 2)
Definition at line 260 of file rcc.h.
Referenced by timer_reset().
#define RCC_APB1RSTR_TIM5RST (1 << 3)
Definition at line 259 of file rcc.h.
Referenced by timer_reset().
#define RCC_APB1RSTR_TIM6RST (1 << 4)
Definition at line 258 of file rcc.h.
Referenced by timer_reset().
#define RCC_APB1RSTR_TIM7RST (1 << 5)
Definition at line 257 of file rcc.h.
Referenced by timer_reset().
#define RCC_APB1RSTR_USART2RST (1 << 17)
Definition at line 253 of file rcc.h.
#define RCC_APB1RSTR_USART3RST (1 << 18)
Definition at line 252 of file rcc.h.
#define RCC_APB1RSTR_USBRST (1 << 23)
Definition at line 249 of file rcc.h.
#define RCC_APB1RSTR_WWDGRST (1 << 11)
Definition at line 255 of file rcc.h.
#define RCC_APB2ENR MMIO32(RCC_BASE + 0x20)
Definition at line 61 of file rcc.h.
#define RCC_APB2LPENR MMIO32(RCC_BASE + 0x2c)
Definition at line 64 of file rcc.h.
#define RCC_APB2LPENR_ADC1LPEN (1 << 9)
Definition at line 334 of file rcc.h.
#define RCC_APB2LPENR_SPI1LPEN (1 << 12)
Definition at line 333 of file rcc.h.
#define RCC_APB2LPENR_SYSCFGLPEN (1 << 0)
Definition at line 338 of file rcc.h.
#define RCC_APB2LPENR_TIM10LPEN (1 << 3)
Definition at line 336 of file rcc.h.
#define RCC_APB2LPENR_TIM11LPEN (1 << 4)
Definition at line 335 of file rcc.h.
#define RCC_APB2LPENR_TIM9LPEN (1 << 2)
Definition at line 337 of file rcc.h.
#define RCC_APB2LPENR_USART1LPEN (1 << 14)
Definition at line 332 of file rcc.h.
#define RCC_APB2RSTR MMIO32(RCC_BASE + 0x14)
Definition at line 58 of file rcc.h.
Referenced by spi_reset(), and timer_reset().
#define RCC_APB2RSTR_ADC1RST (1 << 9)
Definition at line 238 of file rcc.h.
#define RCC_APB2RSTR_SPI1RST (1 << 12)
Definition at line 237 of file rcc.h.
Referenced by spi_reset().
#define RCC_APB2RSTR_SYSCFGRST (1 << 0)
Definition at line 242 of file rcc.h.
#define RCC_APB2RSTR_TIM10RST (1 << 3)
Definition at line 240 of file rcc.h.
#define RCC_APB2RSTR_TIM11RST (1 << 4)
Definition at line 239 of file rcc.h.
#define RCC_APB2RSTR_TIM9RST (1 << 2)
Definition at line 241 of file rcc.h.
#define RCC_APB2RSTR_USART1RST (1 << 14)
Definition at line 236 of file rcc.h.
#define RCC_CFGR MMIO32(RCC_BASE + 0x08)
Definition at line 55 of file rcc.h.
Referenced by rcc_set_hpre(), rcc_set_pll_configuration(), rcc_set_pll_source(), rcc_set_ppre1(), rcc_set_ppre2(), rcc_set_sysclk_source(), rcc_system_clock_source(), and rcc_wait_for_sysclk_status().
#define RCC_CFGR_HPRE_SYSCLK_DIV128 0xd
Definition at line 175 of file rcc.h.
#define RCC_CFGR_HPRE_SYSCLK_DIV16 0xb
Definition at line 173 of file rcc.h.
#define RCC_CFGR_HPRE_SYSCLK_DIV2 0x8
Definition at line 170 of file rcc.h.
#define RCC_CFGR_HPRE_SYSCLK_DIV256 0xe
Definition at line 176 of file rcc.h.
#define RCC_CFGR_HPRE_SYSCLK_DIV4 0x9
Definition at line 171 of file rcc.h.
#define RCC_CFGR_HPRE_SYSCLK_DIV512 0xf
Definition at line 177 of file rcc.h.
#define RCC_CFGR_HPRE_SYSCLK_DIV64 0xc
Definition at line 174 of file rcc.h.
#define RCC_CFGR_HPRE_SYSCLK_DIV8 0xa
Definition at line 172 of file rcc.h.
#define RCC_CFGR_HPRE_SYSCLK_NODIV 0x0
Definition at line 169 of file rcc.h.
#define RCC_CFGR_MCO_HSECLK 0x4
Definition at line 125 of file rcc.h.
#define RCC_CFGR_MCO_HSICLK 0x2
Definition at line 123 of file rcc.h.
#define RCC_CFGR_MCO_LSECLK 0x7
Definition at line 128 of file rcc.h.
#define RCC_CFGR_MCO_LSICLK 0x6
Definition at line 127 of file rcc.h.
#define RCC_CFGR_MCO_MSICLK 0x3
Definition at line 124 of file rcc.h.
#define RCC_CFGR_MCO_NOCLK 0x0
Definition at line 121 of file rcc.h.
#define RCC_CFGR_MCO_PLLCLK 0x5
Definition at line 126 of file rcc.h.
#define RCC_CFGR_MCO_SYSCLK 0x1
Definition at line 122 of file rcc.h.
#define RCC_CFGR_MCOPRE_DIV1 0
Definition at line 114 of file rcc.h.
#define RCC_CFGR_MCOPRE_DIV16 4
Definition at line 118 of file rcc.h.
#define RCC_CFGR_MCOPRE_DIV2 1
Definition at line 115 of file rcc.h.
#define RCC_CFGR_MCOPRE_DIV4 2
Definition at line 116 of file rcc.h.
#define RCC_CFGR_MCOPRE_DIV8 3
Definition at line 117 of file rcc.h.
#define RCC_CFGR_PLLDIV_DIV2 0x1
Definition at line 131 of file rcc.h.
#define RCC_CFGR_PLLDIV_DIV3 0x2
Definition at line 132 of file rcc.h.
#define RCC_CFGR_PLLDIV_DIV4 0x3
Definition at line 133 of file rcc.h.
#define RCC_CFGR_PLLDIV_MASK 0x3
Definition at line 135 of file rcc.h.
Referenced by rcc_set_pll_configuration().
#define RCC_CFGR_PLLDIV_SHIFT 22
Definition at line 134 of file rcc.h.
Referenced by rcc_set_pll_configuration().
#define RCC_CFGR_PLLMUL_MASK 0xf
Definition at line 148 of file rcc.h.
Referenced by rcc_set_pll_configuration().
#define RCC_CFGR_PLLMUL_MUL12 0x4
Definition at line 142 of file rcc.h.
#define RCC_CFGR_PLLMUL_MUL16 0x5
Definition at line 143 of file rcc.h.
#define RCC_CFGR_PLLMUL_MUL24 0x6
Definition at line 144 of file rcc.h.
#define RCC_CFGR_PLLMUL_MUL3 0x0
Definition at line 138 of file rcc.h.
#define RCC_CFGR_PLLMUL_MUL32 0x7
Definition at line 145 of file rcc.h.
#define RCC_CFGR_PLLMUL_MUL4 0x1
Definition at line 139 of file rcc.h.
#define RCC_CFGR_PLLMUL_MUL48 0x8
Definition at line 146 of file rcc.h.
#define RCC_CFGR_PLLMUL_MUL6 0x2
Definition at line 140 of file rcc.h.
#define RCC_CFGR_PLLMUL_MUL8 0x3
Definition at line 141 of file rcc.h.
#define RCC_CFGR_PLLMUL_SHIFT 18
Definition at line 147 of file rcc.h.
Referenced by rcc_set_pll_configuration().
#define RCC_CFGR_PLLSRC_HSE_CLK 0x1
Definition at line 152 of file rcc.h.
#define RCC_CFGR_PLLSRC_HSI_CLK 0x0
Definition at line 151 of file rcc.h.
#define RCC_CFGR_PPRE1_HCLK_DIV16 0x7
Definition at line 166 of file rcc.h.
#define RCC_CFGR_PPRE1_HCLK_DIV2 0x4
Definition at line 163 of file rcc.h.
#define RCC_CFGR_PPRE1_HCLK_DIV4 0x5
Definition at line 164 of file rcc.h.
#define RCC_CFGR_PPRE1_HCLK_DIV8 0x6
Definition at line 165 of file rcc.h.
#define RCC_CFGR_PPRE1_HCLK_NODIV 0x0
Definition at line 162 of file rcc.h.
#define RCC_CFGR_PPRE2_HCLK_DIV16 0x7
Definition at line 159 of file rcc.h.
#define RCC_CFGR_PPRE2_HCLK_DIV2 0x4
Definition at line 156 of file rcc.h.
#define RCC_CFGR_PPRE2_HCLK_DIV4 0x5
Definition at line 157 of file rcc.h.
#define RCC_CFGR_PPRE2_HCLK_DIV8 0x6
Definition at line 158 of file rcc.h.
#define RCC_CFGR_PPRE2_HCLK_NODIV 0x0
Definition at line 155 of file rcc.h.
#define RCC_CFGR_SW_SYSCLKSEL_HSECLK 0x2
Definition at line 188 of file rcc.h.
#define RCC_CFGR_SW_SYSCLKSEL_HSICLK 0x1
Definition at line 187 of file rcc.h.
Referenced by rcc_clock_setup_hsi().
#define RCC_CFGR_SW_SYSCLKSEL_MSICLK 0x0
Definition at line 186 of file rcc.h.
Referenced by rcc_clock_setup_msi().
#define RCC_CFGR_SW_SYSCLKSEL_PLLCLK 0x3
Definition at line 189 of file rcc.h.
Referenced by rcc_clock_setup_pll().
#define RCC_CFGR_SWS_SYSCLKSEL_HSECLK 0x2
Definition at line 182 of file rcc.h.
Referenced by rcc_wait_for_sysclk_status().
#define RCC_CFGR_SWS_SYSCLKSEL_HSICLK 0x1
Definition at line 181 of file rcc.h.
Referenced by rcc_wait_for_sysclk_status().
#define RCC_CFGR_SWS_SYSCLKSEL_MSICLK 0x0
Definition at line 180 of file rcc.h.
Referenced by rcc_wait_for_sysclk_status().
#define RCC_CFGR_SWS_SYSCLKSEL_PLLCLK 0x3
Definition at line 183 of file rcc.h.
Referenced by rcc_wait_for_sysclk_status().
#define RCC_CIR MMIO32(RCC_BASE + 0x0c)
Definition at line 56 of file rcc.h.
Referenced by rcc_css_int_clear(), rcc_css_int_flag(), rcc_osc_ready_int_clear(), rcc_osc_ready_int_disable(), rcc_osc_ready_int_enable(), and rcc_osc_ready_int_flag().
#define RCC_CIR_CSSC (1 << 23)
Definition at line 194 of file rcc.h.
Referenced by rcc_css_int_clear().
#define RCC_CIR_CSSF (1 << 7)
Definition at line 213 of file rcc.h.
Referenced by rcc_css_int_flag().
#define RCC_CIR_HSERDYC (1 << 19)
Definition at line 199 of file rcc.h.
Referenced by rcc_osc_ready_int_clear().
#define RCC_CIR_HSERDYF (1 << 3)
Definition at line 218 of file rcc.h.
Referenced by rcc_osc_ready_int_flag().
#define RCC_CIR_HSERDYIE (1 << 11)
Definition at line 207 of file rcc.h.
Referenced by rcc_osc_ready_int_disable(), and rcc_osc_ready_int_enable().
#define RCC_CIR_HSIRDYC (1 << 18)
Definition at line 200 of file rcc.h.
Referenced by rcc_osc_ready_int_clear().
#define RCC_CIR_HSIRDYF (1 << 2)
Definition at line 219 of file rcc.h.
Referenced by rcc_osc_ready_int_flag().
#define RCC_CIR_HSIRDYIE (1 << 10)
Definition at line 208 of file rcc.h.
Referenced by rcc_osc_ready_int_disable(), and rcc_osc_ready_int_enable().
#define RCC_CIR_LSERDYC (1 << 17)
Definition at line 201 of file rcc.h.
Referenced by rcc_osc_ready_int_clear().
#define RCC_CIR_LSERDYF (1 << 1)
Definition at line 220 of file rcc.h.
Referenced by rcc_osc_ready_int_flag().
#define RCC_CIR_LSERDYIE (1 << 9)
Definition at line 209 of file rcc.h.
Referenced by rcc_osc_ready_int_disable(), and rcc_osc_ready_int_enable().
#define RCC_CIR_LSIRDYC (1 << 16)
Definition at line 202 of file rcc.h.
Referenced by rcc_osc_ready_int_clear().
#define RCC_CIR_LSIRDYF (1 << 0)
Definition at line 221 of file rcc.h.
Referenced by rcc_osc_ready_int_flag().
#define RCC_CIR_LSIRDYIE (1 << 8)
Definition at line 210 of file rcc.h.
Referenced by rcc_osc_ready_int_disable(), and rcc_osc_ready_int_enable().
#define RCC_CIR_MSIRDYC (1 << 21)
Definition at line 197 of file rcc.h.
Referenced by rcc_osc_ready_int_clear().
#define RCC_CIR_MSIRDYF (1 << 5) /* (**) */
Definition at line 216 of file rcc.h.
Referenced by rcc_osc_ready_int_flag().
#define RCC_CIR_MSIRDYIE (1 << 13)
Definition at line 205 of file rcc.h.
Referenced by rcc_osc_ready_int_disable(), and rcc_osc_ready_int_enable().
#define RCC_CIR_PLLRDYC (1 << 20)
Definition at line 198 of file rcc.h.
Referenced by rcc_osc_ready_int_clear().
#define RCC_CIR_PLLRDYF (1 << 4)
Definition at line 217 of file rcc.h.
Referenced by rcc_osc_ready_int_flag().
#define RCC_CIR_PLLRDYIE (1 << 12)
Definition at line 206 of file rcc.h.
Referenced by rcc_osc_ready_int_disable(), and rcc_osc_ready_int_enable().
#define RCC_CR MMIO32(RCC_BASE + 0x00)
Definition at line 53 of file rcc.h.
Referenced by rcc_css_disable(), rcc_css_enable(), rcc_osc_bypass_disable(), rcc_osc_bypass_enable(), rcc_osc_off(), rcc_osc_on(), rcc_set_rtcpre(), and rcc_wait_for_osc_ready().
#define RCC_CR_CSSON (1 << 28)
Definition at line 71 of file rcc.h.
Referenced by rcc_css_disable(), and rcc_css_enable().
#define RCC_CR_HSEBYP (1 << 18)
Definition at line 74 of file rcc.h.
Referenced by rcc_osc_bypass_disable(), and rcc_osc_bypass_enable().
#define RCC_CR_HSEON (1 << 16)
Definition at line 76 of file rcc.h.
Referenced by rcc_osc_off(), and rcc_osc_on().
#define RCC_CR_HSERDY (1 << 17)
Definition at line 75 of file rcc.h.
Referenced by rcc_wait_for_osc_ready().
#define RCC_CR_HSION (1 << 0)
Definition at line 80 of file rcc.h.
Referenced by rcc_osc_off(), and rcc_osc_on().
#define RCC_CR_HSIRDY (1 << 1)
Definition at line 79 of file rcc.h.
Referenced by rcc_wait_for_osc_ready().
#define RCC_CR_MSION (1 << 8)
Definition at line 78 of file rcc.h.
Referenced by rcc_osc_off(), and rcc_osc_on().
#define RCC_CR_MSIRDY (1 << 9)
Definition at line 77 of file rcc.h.
Referenced by rcc_wait_for_osc_ready().
#define RCC_CR_PLLON (1 << 24)
Definition at line 73 of file rcc.h.
Referenced by rcc_osc_off(), and rcc_osc_on().
#define RCC_CR_PLLRDY (1 << 25)
Definition at line 72 of file rcc.h.
Referenced by rcc_wait_for_osc_ready().
#define RCC_CR_RTCPRE_DIV16 3
Definition at line 85 of file rcc.h.
#define RCC_CR_RTCPRE_DIV2 0
Definition at line 82 of file rcc.h.
#define RCC_CR_RTCPRE_DIV4 1
Definition at line 83 of file rcc.h.
#define RCC_CR_RTCPRE_DIV8 2
Definition at line 84 of file rcc.h.
#define RCC_CR_RTCPRE_MASK 0x3
Definition at line 87 of file rcc.h.
#define RCC_CR_RTCPRE_SHIFT 29
Definition at line 86 of file rcc.h.
#define RCC_CSR MMIO32(RCC_BASE + 0x34)
Definition at line 66 of file rcc.h.
Referenced by rcc_osc_bypass_disable(), rcc_osc_bypass_enable(), rcc_osc_off(), rcc_osc_on(), rcc_rtc_select_clock(), and rcc_wait_for_osc_ready().
#define RCC_CSR_IWDGRSTF (1 << 29)
Definition at line 362 of file rcc.h.
#define RCC_CSR_LPWRRSTF (1 << 31)
Definition at line 360 of file rcc.h.
#define RCC_CSR_LSEBYP (1 << 10)
Definition at line 378 of file rcc.h.
Referenced by rcc_osc_bypass_disable(), and rcc_osc_bypass_enable().
#define RCC_CSR_LSECSSD (1 << 12)
Definition at line 376 of file rcc.h.
#define RCC_CSR_LSECSSON (1 << 11)
Definition at line 377 of file rcc.h.
#define RCC_CSR_LSEON (1 << 8)
Definition at line 380 of file rcc.h.
Referenced by rcc_osc_off(), and rcc_osc_on().
#define RCC_CSR_LSERDY (1 << 9)
Definition at line 379 of file rcc.h.
Referenced by rcc_wait_for_osc_ready().
#define RCC_CSR_LSION (1 << 0)
Definition at line 382 of file rcc.h.
Referenced by rcc_osc_off(), and rcc_osc_on().
#define RCC_CSR_LSIRDY (1 << 1)
Definition at line 381 of file rcc.h.
Referenced by rcc_wait_for_osc_ready().
#define RCC_CSR_OBLRSTF (1 << 25)
Definition at line 366 of file rcc.h.
#define RCC_CSR_PINRSTF (1 << 26)
Definition at line 365 of file rcc.h.
#define RCC_CSR_PORRSTF (1 << 27)
Definition at line 364 of file rcc.h.
#define RCC_CSR_RMVF (1 << 24)
Definition at line 367 of file rcc.h.
#define RCC_CSR_RTCEN (1 << 22)
Definition at line 369 of file rcc.h.
#define RCC_CSR_RTCRST (1 << 23)
Definition at line 368 of file rcc.h.
#define RCC_CSR_RTCSEL_HSI (0x3)
Definition at line 375 of file rcc.h.
#define RCC_CSR_RTCSEL_LSE (0x1)
Definition at line 373 of file rcc.h.
#define RCC_CSR_RTCSEL_LSI (0x2)
Definition at line 374 of file rcc.h.
#define RCC_CSR_RTCSEL_MASK (0x3)
Definition at line 371 of file rcc.h.
Referenced by rcc_rtc_select_clock().
#define RCC_CSR_RTCSEL_NONE (0x0)
Definition at line 372 of file rcc.h.
#define RCC_CSR_RTCSEL_SHIFT (16)
Definition at line 370 of file rcc.h.
Referenced by rcc_rtc_select_clock().
#define RCC_CSR_SFTRSTF (1 << 28)
Definition at line 363 of file rcc.h.
#define RCC_CSR_WWDGRSTF (1 << 30)
Definition at line 361 of file rcc.h.
#define RCC_ICSCR MMIO32(RCC_BASE + 0x04)
Definition at line 54 of file rcc.h.
Referenced by rcc_clock_setup_msi().
#define RCC_ICSCR_HSICAL_MASK 0xff
Definition at line 109 of file rcc.h.
#define RCC_ICSCR_HSICAL_SHIFT 0
Definition at line 108 of file rcc.h.
#define RCC_ICSCR_HSITRIM_MASK 0x1f
Definition at line 107 of file rcc.h.
#define RCC_ICSCR_HSITRIM_SHIFT 8
Definition at line 106 of file rcc.h.
#define RCC_ICSCR_MSICAL_MASK 0xff
Definition at line 94 of file rcc.h.
#define RCC_ICSCR_MSICAL_SHIFT 16
Definition at line 93 of file rcc.h.
#define RCC_ICSCR_MSIRANGE_131KHZ 0x1
Definition at line 99 of file rcc.h.
#define RCC_ICSCR_MSIRANGE_1MHZ 0x4
Definition at line 102 of file rcc.h.
#define RCC_ICSCR_MSIRANGE_262KHZ 0x2
Definition at line 100 of file rcc.h.
#define RCC_ICSCR_MSIRANGE_2MHZ 0x5
Definition at line 103 of file rcc.h.
#define RCC_ICSCR_MSIRANGE_4MHZ 0x6
Definition at line 104 of file rcc.h.
#define RCC_ICSCR_MSIRANGE_524KHZ 0x3
Definition at line 101 of file rcc.h.
#define RCC_ICSCR_MSIRANGE_65KHZ 0x0
Definition at line 98 of file rcc.h.
#define RCC_ICSCR_MSIRANGE_MASK 0x7
Definition at line 97 of file rcc.h.
Referenced by rcc_clock_setup_msi().
#define RCC_ICSCR_MSIRANGE_SHIFT 13
Definition at line 96 of file rcc.h.
Referenced by rcc_clock_setup_msi().
#define RCC_ICSCR_MSITRIM_MASK 0xff
Definition at line 92 of file rcc.h.
#define RCC_ICSCR_MSITRIM_SHIFT 24
Definition at line 91 of file rcc.h.
Enumeration Type Documentation
enum clock_config_entry_t
Enumerator:
CLOCK_VRANGE1_HSI_PLL_24MHZ
CLOCK_VRANGE1_HSI_PLL_32MHZ
CLOCK_VRANGE1_HSI_RAW_16MHZ
CLOCK_VRANGE1_HSI_RAW_4MHZ
CLOCK_VRANGE1_MSI_RAW_4MHZ
CLOCK_VRANGE1_MSI_RAW_2MHZ
CLOCK_CONFIG_END
Definition at line 398 of file rcc.h.
enum osc_t
Enumerator:
PLL
HSE
HSI
MSI
LSE
LSI
Definition at line 417 of file rcc.h.
Function Documentation
void rcc_backupdomain_reset (void)
void rcc_clock_setup_hsi (const clock_scale_t * clock)
Definition at line 483 of file rcc.c.
References clock_scale_t::apb1_frequency, clock_scale_t::apb2_frequency, flash_64bit_enable(), clock_scale_t::flash_config, flash_prefetch_enable(), flash_set_ws(), clock_scale_t::hpre, HSI, clock_scale_t::ppre1, clock_scale_t::ppre2, pwr_set_vos_scale(), RCC_APB1ENR, RCC_APB1ENR_PWREN, RCC_CFGR_SW_SYSCLKSEL_HSICLK, rcc_osc_on(), rcc_peripheral_enable_clock(), rcc_ppre1_frequency, rcc_ppre2_frequency, rcc_set_hpre(), rcc_set_ppre1(), rcc_set_ppre2(), rcc_set_sysclk_source(), rcc_wait_for_osc_ready(), and clock_scale_t::voltage_scale.
void rcc_clock_setup_msi (const clock_scale_t * clock)
Definition at line 446 of file rcc.c.
References clock_scale_t::apb1_frequency, clock_scale_t::apb2_frequency, flash_64bit_enable(), clock_scale_t::flash_config, flash_prefetch_enable(), flash_set_ws(), clock_scale_t::hpre, MSI, clock_scale_t::msi_range, clock_scale_t::ppre1, clock_scale_t::ppre2, pwr_set_vos_scale(), RCC_APB1ENR, RCC_APB1ENR_PWREN, RCC_CFGR_SW_SYSCLKSEL_MSICLK, RCC_ICSCR, RCC_ICSCR_MSIRANGE_MASK, RCC_ICSCR_MSIRANGE_SHIFT, rcc_osc_on(), rcc_peripheral_enable_clock(), rcc_ppre1_frequency, rcc_ppre2_frequency, rcc_set_hpre(), rcc_set_ppre1(), rcc_set_ppre2(), rcc_set_sysclk_source(), rcc_wait_for_osc_ready(), and clock_scale_t::voltage_scale.
void rcc_clock_setup_pll (const clock_scale_t * clock)
Definition at line 514 of file rcc.c.
References clock_scale_t::apb1_frequency, clock_scale_t::apb2_frequency, flash_64bit_enable(), clock_scale_t::flash_config, flash_prefetch_enable(), flash_set_ws(), clock_scale_t::hpre, HSI, PLL, clock_scale_t::pll_div, clock_scale_t::pll_mul, clock_scale_t::pll_source, clock_scale_t::ppre1, clock_scale_t::ppre2, pwr_set_vos_scale(), RCC_APB1ENR, RCC_APB1ENR_PWREN, RCC_CFGR_SW_SYSCLKSEL_PLLCLK, rcc_osc_on(), rcc_peripheral_enable_clock(), rcc_ppre1_frequency, rcc_ppre2_frequency, rcc_set_hpre(), rcc_set_pll_configuration(), rcc_set_ppre1(), rcc_set_ppre2(), rcc_set_sysclk_source(), rcc_wait_for_osc_ready(), and clock_scale_t::voltage_scale.
void rcc_css_disable (void)
Definition at line 305 of file rcc.c.
References RCC_CR, and RCC_CR_CSSON.
void rcc_css_enable (void)
Definition at line 300 of file rcc.c.
References RCC_CR, and RCC_CR_CSSON.
void rcc_css_int_clear (void)
Definition at line 197 of file rcc.c.
References RCC_CIR, and RCC_CIR_CSSC.
int rcc_css_int_flag (void)
Definition at line 202 of file rcc.c.
References RCC_CIR, and RCC_CIR_CSSF.
void rcc_osc_bypass_disable (osc_t osc)
Definition at line 328 of file rcc.c.
References HSE, HSI, LSE, LSI, MSI, PLL, RCC_CR, RCC_CR_HSEBYP, RCC_CSR, and RCC_CSR_LSEBYP.
void rcc_osc_bypass_enable (osc_t osc)
Definition at line 310 of file rcc.c.
References HSE, HSI, LSE, LSI, MSI, PLL, RCC_CR, RCC_CR_HSEBYP, RCC_CSR, and RCC_CSR_LSEBYP.
void rcc_osc_off (osc_t osc)
Definition at line 276 of file rcc.c.
References HSE, HSI, LSE, LSI, MSI, PLL, RCC_CR, RCC_CR_HSEON, RCC_CR_HSION, RCC_CR_MSION, RCC_CR_PLLON, RCC_CSR, RCC_CSR_LSEON, and RCC_CSR_LSION.
void rcc_osc_on (osc_t osc)
Definition at line 252 of file rcc.c.
References HSE, HSI, LSE, LSI, MSI, PLL, RCC_CR, RCC_CR_HSEON, RCC_CR_HSION, RCC_CR_MSION, RCC_CR_PLLON, RCC_CSR, RCC_CSR_LSEON, and RCC_CSR_LSION.
Referenced by rcc_clock_setup_hsi(), rcc_clock_setup_msi(), and rcc_clock_setup_pll().
BEGIN_DECLS void rcc_osc_ready_int_clear (osc_t osc)
Definition at line 98 of file rcc.c.
References HSE, HSI, LSE, LSI, MSI, PLL, RCC_CIR, RCC_CIR_HSERDYC, RCC_CIR_HSIRDYC, RCC_CIR_LSERDYC, RCC_CIR_LSIRDYC, RCC_CIR_MSIRDYC, and RCC_CIR_PLLRDYC.
void rcc_osc_ready_int_disable (osc_t osc)
Definition at line 146 of file rcc.c.
References HSE, HSI, LSE, LSI, MSI, PLL, RCC_CIR, RCC_CIR_HSERDYIE, RCC_CIR_HSIRDYIE, RCC_CIR_LSERDYIE, RCC_CIR_LSIRDYIE, RCC_CIR_MSIRDYIE, and RCC_CIR_PLLRDYIE.
void rcc_osc_ready_int_enable (osc_t osc)
Definition at line 122 of file rcc.c.
References HSE, HSI, LSE, LSI, MSI, PLL, RCC_CIR, RCC_CIR_HSERDYIE, RCC_CIR_HSIRDYIE, RCC_CIR_LSERDYIE, RCC_CIR_LSIRDYIE, RCC_CIR_MSIRDYIE, and RCC_CIR_PLLRDYIE.
int rcc_osc_ready_int_flag (osc_t osc)
Definition at line 170 of file rcc.c.
References HSE, HSI, LSE, LSI, MSI, PLL, RCC_CIR, RCC_CIR_HSERDYF, RCC_CIR_HSIRDYF, RCC_CIR_LSERDYF, RCC_CIR_LSIRDYF, RCC_CIR_MSIRDYF, and RCC_CIR_PLLRDYF.
void rcc_peripheral_clear_reset (volatile u32 * reg, u32 clear_reset)
Definition at line 361 of file rcc.c.
Referenced by i2c_reset(), spi_reset(), and timer_reset().
void rcc_peripheral_disable_clock (volatile u32 * reg, u32 en)
Definition at line 351 of file rcc.c.
void rcc_peripheral_enable_clock (volatile u32 * reg, u32 en)
Definition at line 346 of file rcc.c.
Referenced by rcc_clock_setup_hsi(), rcc_clock_setup_msi(), and rcc_clock_setup_pll().
void rcc_peripheral_reset (volatile u32 * reg, u32 reset)
Definition at line 356 of file rcc.c.
Referenced by i2c_reset(), spi_reset(), and timer_reset().
void rcc_rtc_select_clock (u32 clock)
Definition at line 440 of file rcc.c.
References RCC_CSR, RCC_CSR_RTCSEL_MASK, and RCC_CSR_RTCSEL_SHIFT.
void rcc_set_adcpre (u32 adcpre)
void rcc_set_hpre (u32 hpre)
Definition at line 416 of file rcc.c.
References RCC_CFGR.
Referenced by rcc_clock_setup_hsi(), rcc_clock_setup_msi(), and rcc_clock_setup_pll().
void rcc_set_pll_configuration (u32 source, u32 multiplier, u32 divisor)
Definition at line 375 of file rcc.c.
References RCC_CFGR, RCC_CFGR_PLLDIV_MASK, RCC_CFGR_PLLDIV_SHIFT, RCC_CFGR_PLLMUL_MASK, and RCC_CFGR_PLLMUL_SHIFT.
Referenced by rcc_clock_setup_pll().
void rcc_set_pll_source (u32 pllsrc)
Definition at line 389 of file rcc.c.
References RCC_CFGR.
void rcc_set_ppre1 (u32 ppre1)
Definition at line 407 of file rcc.c.
References RCC_CFGR.
Referenced by rcc_clock_setup_hsi(), rcc_clock_setup_msi(), and rcc_clock_setup_pll().
void rcc_set_ppre2 (u32 ppre2)
Definition at line 398 of file rcc.c.
References RCC_CFGR.
Referenced by rcc_clock_setup_hsi(), rcc_clock_setup_msi(), and rcc_clock_setup_pll().
void rcc_set_rtcpre (u32 rtcpre)
Definition at line 425 of file rcc.c.
References RCC_CR.
void rcc_set_sysclk_source (u32 clk)
Definition at line 366 of file rcc.c.
References RCC_CFGR.
Referenced by rcc_clock_setup_hsi(), rcc_clock_setup_msi(), and rcc_clock_setup_pll().
void rcc_set_usbpre (u32 usbpre)
u32 rcc_system_clock_source (void)
Definition at line 434 of file rcc.c.
References RCC_CFGR.
void rcc_wait_for_osc_ready (osc_t osc)
Definition at line 207 of file rcc.c.
References HSE, HSI, LSE, LSI, MSI, PLL, RCC_CR, RCC_CR_HSERDY, RCC_CR_HSIRDY, RCC_CR_MSIRDY, RCC_CR_PLLRDY, RCC_CSR, RCC_CSR_LSERDY, and RCC_CSR_LSIRDY.
Referenced by rcc_clock_setup_hsi(), rcc_clock_setup_msi(), and rcc_clock_setup_pll().
void rcc_wait_for_sysclk_status (osc_t osc)
Definition at line 231 of file rcc.c.
References HSE, HSI, MSI, PLL, RCC_CFGR, RCC_CFGR_SWS_SYSCLKSEL_HSECLK, RCC_CFGR_SWS_SYSCLKSEL_HSICLK, RCC_CFGR_SWS_SYSCLKSEL_MSICLK, and RCC_CFGR_SWS_SYSCLKSEL_PLLCLK.
Variable Documentation
const clock_scale_t clock_config[CLOCK_CONFIG_END]
Definition at line 32 of file rcc.c.
u32 rcc_ppre1_frequency
Definition at line 29 of file rcc.c.
Referenced by rcc_clock_setup_hsi(), rcc_clock_setup_msi(), rcc_clock_setup_pll(), and usart_set_baudrate().
u32 rcc_ppre2_frequency
Definition at line 30 of file rcc.c.
Referenced by rcc_clock_setup_hsi(), rcc_clock_setup_msi(), rcc_clock_setup_pll(), and usart_set_baudrate().