libopencm3: pwr.h File Reference
pwr.h File Reference
#include <libopencm3/stm32/memorymap.h>
#include <libopencm3/stm32/common/pwr_common_all.h>
Macros
#define PWR_CR_LPRUN (1 << 14)
#define PWR_CR_VOS_LSB 11
#define PWR_CR_VOS_RANGE1 (0x1 << PWR_CR_VOS_LSB)
#define PWR_CR_VOS_RANGE2 (0x2 << PWR_CR_VOS_LSB)
#define PWR_CR_VOS_RANGE3 (0x3 << PWR_CR_VOS_LSB)
#define PWR_CR_VOS_MASK (0x3 << PWR_CR_VOS_LSB)
#define PWR_CR_FWU (1 << 10)
#define PWR_CR_ULP (1 << 9)
#define PWR_CR_LPSDSR (1 << 0) /* masks common PWR_CR_LPDS */
#define PWR_CSR_EWUP3 (1 << 10)
#define PWR_CSR_EWUP2 (1 << 9)
#define PWR_CSR_EWUP1 PWR_CSR_EWUP
#define PWR_CSR_REGLPF (1 << 5)
#define PWR_CSR_VOSF (1 << 4)
#define PWR_CSR_VREFINTRDYF (1 << 3)
Enumerations
enum vos_scale_t { RANGE1, RANGE2, RANGE3 }
Functions
void pwr_set_vos_scale (vos_scale_t scale)
Macro Definition Documentation
#define PWR_CR_FWU (1 << 10)
Definition at line 67 of file pwr.h.
#define PWR_CR_LPRUN (1 << 14)
Definition at line 52 of file pwr.h.
#define PWR_CR_LPSDSR (1 << 0) /* masks common PWR_CR_LPDS */
Definition at line 73 of file pwr.h.
#define PWR_CR_ULP (1 << 9)
Definition at line 70 of file pwr.h.
#define PWR_CR_VOS_LSB 11
Definition at line 55 of file pwr.h.
#define PWR_CR_VOS_MASK (0x3 << PWR_CR_VOS_LSB)
Definition at line 64 of file pwr.h.
Referenced by pwr_set_vos_scale().
#define PWR_CSR_EWUP1 PWR_CSR_EWUP
Definition at line 85 of file pwr.h.
#define PWR_CSR_EWUP2 (1 << 9)
Definition at line 82 of file pwr.h.
#define PWR_CSR_EWUP3 (1 << 10)
Definition at line 79 of file pwr.h.
#define PWR_CSR_REGLPF (1 << 5)
Definition at line 88 of file pwr.h.
#define PWR_CSR_VOSF (1 << 4)
Definition at line 91 of file pwr.h.
#define PWR_CSR_VREFINTRDYF (1 << 3)
Definition at line 94 of file pwr.h.
Enumeration Type Documentation
enum vos_scale_t
Enumerator
RANGE1
RANGE2
RANGE3
Definition at line 100 of file pwr.h.
Function Documentation
void pwr_set_vos_scale (vos_scale_t scale)
Definition at line 40 of file pwr.c.
References PWR_CR, PWR_CR_VOS_MASK, PWR_CR_VOS_RANGE1, PWR_CR_VOS_RANGE2, PWR_CR_VOS_RANGE3, RANGE1, RANGE2, and RANGE3.
Referenced by rcc_clock_setup_hsi(), rcc_clock_setup_msi(), and rcc_clock_setup_pll().