libopencm3: pwr.c File Reference
pwr.c File Reference
#include <libopencm3/stm32/pwr.h>
#include <libopencm3/stm32/rcc.h>
Functions
void pwr_set_vos_scale (vos_scale_t scale)
Function Documentation
void pwr_set_vos_scale (vos_scale_t scale)
Definition at line 40 of file pwr.c.
References PWR_CR, PWR_CR_VOS_MASK, PWR_CR_VOS_RANGE1, PWR_CR_VOS_RANGE2, PWR_CR_VOS_RANGE3, RANGE1, RANGE2, and RANGE3.
Referenced by rcc_clock_setup_hsi(), rcc_clock_setup_msi(), and rcc_clock_setup_pll().