libopencm3: rcc_common_all.h File Reference
rcc_common_all.h File Reference
Functions
void rcc_peripheral_enable_clock (volatile uint32_t *reg, uint32_t en)
RCC Enable Peripheral Clocks.
void rcc_peripheral_disable_clock (volatile uint32_t *reg, uint32_t en)
RCC Disable Peripheral Clocks.
void rcc_peripheral_reset (volatile uint32_t *reg, uint32_t reset)
RCC Reset Peripherals.
void rcc_peripheral_clear_reset (volatile uint32_t *reg, uint32_t clear_reset)
RCC Remove Reset on Peripherals.
void rcc_periph_clock_enable (enum rcc_periph_clken clken)
Enable Peripheral Clock in running mode.
void rcc_periph_clock_disable (enum rcc_periph_clken clken)
Disable Peripheral Clock in running mode.
void rcc_periph_reset_pulse (enum rcc_periph_rst rst)
Reset Peripheral, pulsed.
void rcc_periph_reset_hold (enum rcc_periph_rst rst)
Reset Peripheral, hold.
void rcc_periph_reset_release (enum rcc_periph_rst rst)
Reset Peripheral, release.
Function Documentation
void rcc_periph_clock_disable (enum rcc_periph_clken clken)
Disable Peripheral Clock in running mode.
Disable the clock on particular peripheral.
Parameters
[in] periph periph_t Peripheral Name
For available constants, see #periph_t (RCC_UART1 for example)
Definition at line 134 of file rcc_common_all.c.
References _RCC_BIT, and _RCC_REG.
void rcc_periph_clock_enable (enum rcc_periph_clken clken)
Enable Peripheral Clock in running mode.
Enable the clock on particular peripheral.
Parameters
[in] periph periph_t Peripheral Name
For available constants, see #periph_t (RCC_UART1 for example)
Definition at line 120 of file rcc_common_all.c.
References _RCC_BIT, and _RCC_REG.
void rcc_periph_reset_hold (enum rcc_periph_rst rst)
Reset Peripheral, hold.
Reset particular peripheral, and hold in reset state.
Parameters
[in] periph periph_t Peripheral name
For available constants, see #periph_t (RCC_UART1 for example)
Definition at line 165 of file rcc_common_all.c.
References _RCC_BIT, and _RCC_REG.
void rcc_periph_reset_pulse (enum rcc_periph_rst rst)
Reset Peripheral, pulsed.
Reset particular peripheral, and restore to working state.
Parameters
[in] periph periph_t Peripheral name
For available constants, see #periph_t (RCC_UART1 for example)
Definition at line 149 of file rcc_common_all.c.
References _RCC_BIT, and _RCC_REG.
void rcc_periph_reset_release (enum rcc_periph_rst rst)
Reset Peripheral, release.
Restore peripheral from reset state to working state.
Parameters
[in] periph periph_t Peripheral name
For available constants, see #periph_t (RCC_UART1 for example)
Definition at line 180 of file rcc_common_all.c.
References _RCC_BIT, and _RCC_REG.
void rcc_peripheral_clear_reset (volatile uint32_t * reg, uint32_t clear_reset)
RCC Remove Reset on Peripherals.
Remove the reset on particular peripherals. There are three registers involved, each one controlling reset of peripherals associated with the AHB, APB1 and APB2 respectively. Several peripherals could have the reset removed simultaneously only if they are controlled by the same register.
Parameters
[in] *reg Unsigned int32. Pointer to a Reset Register (either RCC_AHBENR, RCC_APB1ENR or RCC_APB2ENR)
[in] clear_reset Unsigned int32. Logical OR of all resets to be removed:
If register is RCC_AHBRSTR, from rcc_ahbrstr_rst
If register is RCC_APB1RSTR, from rcc_apb1rstr_rst
If register is RCC_APB2RSTR, from rcc_apb2rstr_rst
Definition at line 102 of file rcc_common_all.c.
Referenced by i2c_reset(), spi_reset(), and timer_reset().
void rcc_peripheral_disable_clock (volatile uint32_t * reg, uint32_t en)
RCC Disable Peripheral Clocks.
Enable the clock on particular peripherals. There are three registers involved, each one controlling the enabling of clocks associated with the AHB, APB1 and APB2 respectively. Several peripherals could be disabled simultaneously only if they are controlled by the same register.
Parameters
[in] *reg Unsigned int32. Pointer to a Clock Enable Register (either RCC_AHBENR, RCC_APB1ENR or RCC_APB2ENR)
[in] en Unsigned int32. Logical OR of all enables to be used for disabling.
If register is RCC_AHBER, from RCC_AHBENR enable values
If register is RCC_APB1ENR, from RCC_APB1ENR enable values
If register is RCC_APB2ENR, from RCC_APB2ENR enable values
Definition at line 61 of file rcc_common_all.c.
void rcc_peripheral_enable_clock (volatile uint32_t * reg, uint32_t en)
RCC Enable Peripheral Clocks.
Enable the clock on particular peripherals. There are three registers involved, each one controlling the enabling of clocks associated with the AHB, APB1 and APB2 respectively. Several peripherals could be enabled simultaneously only if they are controlled by the same register.
Parameters
[in] *reg Unsigned int32. Pointer to a Clock Enable Register (either RCC_AHBENR, RCC_APB1ENR or RCC_APB2ENR)
[in] en Unsigned int32. Logical OR of all enables to be set
If register is RCC_AHBER, from RCC_AHBENR enable values
If register is RCC_APB1ENR, from RCC_APB1ENR enable values
If register is RCC_APB2ENR, from RCC_APB2ENR enable values
Definition at line 40 of file rcc_common_all.c.
Referenced by rcc_clock_setup_hsi(), rcc_clock_setup_msi(), and rcc_clock_setup_pll().
void rcc_peripheral_reset (volatile uint32_t * reg, uint32_t reset)
RCC Reset Peripherals.
Reset particular peripherals. There are three registers involved, each one controlling reset of peripherals associated with the AHB, APB1 and APB2 respectively. Several peripherals could be reset simultaneously only if they are controlled by the same register.
Parameters
[in] *reg Unsigned int32. Pointer to a Reset Register (either RCC_AHBENR, RCC_APB1ENR or RCC_APB2ENR)
[in] reset Unsigned int32. Logical OR of all resets.
If register is RCC_AHBRSTR, from rcc_ahbrstr_rst
If register is RCC_APB1RSTR, from rcc_apb1rstr_rst
If register is RCC_APB2RSTR, from rcc_apb2rstr_rst
Definition at line 81 of file rcc_common_all.c.
Referenced by i2c_reset(), spi_reset(), and timer_reset().