libopencm3: IWDG
IWDG
STM32F0xx
libopencm3 STM32F0xx Independent Watchdog Timer
Macros
#define LSI_FREQUENCY 32000
#define COUNT_LENGTH 12
#define COUNT_MASK ((1 << COUNT_LENGTH)-1)
Functions
void iwdg_start (void)
IWDG Enable Watchdog Timer.
void iwdg_set_period_ms (uint32_t period)
IWDG Set Period in Milliseconds.
bool iwdg_reload_busy (void)
IWDG Get Reload Register Status.
bool iwdg_prescaler_busy (void)
IWDG Get Prescaler Register Status.
void iwdg_reset (void)
IWDG reset Watchdog Timer.
Detailed Description
libopencm3 STM32F0xx Independent Watchdog Timer
Version
1.0.0
Date
11 July 2013
LGPL License Terms libopencm3 License
Author
© 2012 Ken Sarkies ksark.nosp@m.ies@.nosp@m.inter.nosp@m.node.nosp@m..on.n.nosp@m.et
This library supports the Independent Watchdog Timer System in the STM32F1xx series of ARM Cortex Microcontrollers by ST Microelectronics.
The watchdog timer uses the LSI (low speed internal) clock which is low power and continues to operate during stop and standby modes. Its frequency is nominally 32kHz (40kHz for the STM32F1xx series) but can vary from as low as 17kHz up to 60kHz (refer to datasheet electrical characteristics).
Note that the User Configuration option byte provides a means of automatically enabling the IWDG timer at power on (with counter value 0xFFF). If the relevant bit is not set, the IWDG timer must be enabled by software.
Note
: Tested: CPU STM32F103RET6, Board ET-ARM Stamp STM32
Macro Definition Documentation
#define COUNT_LENGTH 12
Definition at line 42 of file iwdg_common_all.c.
#define COUNT_MASK ((1 << COUNT_LENGTH)-1)
Definition at line 43 of file iwdg_common_all.c.
Referenced by iwdg_set_period_ms().
#define LSI_FREQUENCY 32000
Definition at line 41 of file iwdg_common_all.c.
Function Documentation
bool iwdg_prescaler_busy (void)
IWDG Get Prescaler Register Status.
Returns
boolean: TRUE if the prescaler register is busy and unavailable for loading a new period value.
Definition at line 132 of file iwdg_common_all.c.
References IWDG_SR, and IWDG_SR_PVU.
Referenced by iwdg_set_period_ms().
bool iwdg_reload_busy (void)
IWDG Get Reload Register Status.
Returns
boolean: TRUE if the reload register is busy and unavailable for loading a new count value.
Definition at line 120 of file iwdg_common_all.c.
References IWDG_SR, and IWDG_SR_RVU.
Referenced by iwdg_set_period_ms().
void iwdg_reset (void)
IWDG reset Watchdog Timer.
The watchdog timer is reset. The counter restarts from the value in the reload register.
Definition at line 144 of file iwdg_common_all.c.
References IWDG_KR, and IWDG_KR_RESET.
void iwdg_set_period_ms (uint32_t period)
IWDG Set Period in Milliseconds.
The countdown period is converted into count and prescale values. The maximum period is 32.76 seconds; values above this are truncated. Periods less than 1ms are not supported by this library.
A delay of up to 5 clock cycles of the LSI clock (about 156 microseconds) can occasionally occur if the prescale or preload registers are currently busy loading a previous value.
Parameters
[in] period uint32_t Period in milliseconds (< 32760) from a watchdog reset until a system reset is issued.
Definition at line 73 of file iwdg_common_all.c.
References COUNT_MASK, IWDG_KR, IWDG_KR_UNLOCK, IWDG_PR, IWDG_PR_DIV128, IWDG_PR_DIV16, IWDG_PR_DIV256, IWDG_PR_DIV32, IWDG_PR_DIV4, IWDG_PR_DIV64, IWDG_PR_DIV8, iwdg_prescaler_busy(), iwdg_reload_busy(), and IWDG_RLR.
void iwdg_start (void)
IWDG Enable Watchdog Timer.
The watchdog timer is started. The timeout period defaults to 512 milliseconds unless it has been previously defined.
Definition at line 53 of file iwdg_common_all.c.
References IWDG_KR, and IWDG_KR_START.