libopencm3: RCC
RCC
STM32F0xx
libopencm3 STM32F0xx Reset and Clock Control
Macros
#define _RCC_REG(i) MMIO32(RCC_BASE + ((i) >> 5))
#define _RCC_BIT(i) (1 << ((i) & 0x1f))
Functions
void rcc_osc_ready_int_clear (enum rcc_osc osc)
RCC Clear the Oscillator Ready Interrupt Flag.
void rcc_osc_ready_int_enable (enum rcc_osc osc)
RCC Enable the Oscillator Ready Interrupt.
void rcc_osc_ready_int_disable (enum rcc_osc osc)
RCC Disable the Oscillator Ready Interrupt.
int rcc_osc_ready_int_flag (enum rcc_osc osc)
RCC Read the Oscillator Ready Interrupt Flag.
void rcc_css_int_clear (void)
RCC Clear the Clock Security System Interrupt Flag.
int rcc_css_int_flag (void)
RCC Read the Clock Security System Interrupt Flag.
void rcc_wait_for_osc_ready (enum rcc_osc osc)
RCC Wait for Oscillator Ready.
void rcc_osc_on (enum rcc_osc osc)
RCC Turn on an Oscillator.
void rcc_osc_off (enum rcc_osc osc)
RCC Turn off an Oscillator.
void rcc_css_enable (void)
RCC Enable the Clock Security System.
void rcc_css_disable (void)
RCC Disable the Clock Security System.
void rcc_osc_bypass_enable (enum rcc_osc osc)
RCC Enable Bypass.
void rcc_osc_bypass_disable (enum rcc_osc osc)
RCC Disable Bypass.
void rcc_set_sysclk_source (enum rcc_osc clk)
RCC Set the Source for the System Clock.
void rcc_set_pll_multiplication_factor (uint32_t mul)
RCC Set the PLL Multiplication Factor.
void rcc_set_ppre (uint32_t ppre)
RCC Set the APB Prescale Factor.
void rcc_set_hpre (uint32_t hpre)
RCC Set the AHB Prescale Factor.
void rcc_set_prediv (uint32_t prediv)
void rcc_set_mco (uint32_t mcosrc)
enum rcc_osc rcc_system_clock_source (void)
RCC Get the System Clock Source.
void rcc_clock_setup_in_hsi_out_8mhz (void)
void rcc_clock_setup_in_hsi_out_16mhz (void)
void rcc_clock_setup_in_hsi_out_24mhz (void)
void rcc_clock_setup_in_hsi_out_32mhz (void)
void rcc_clock_setup_in_hsi_out_40mhz (void)
void rcc_clock_setup_in_hsi_out_48mhz (void)
void rcc_periph_clock_enable (enum rcc_periph_clken periph)
void rcc_periph_clock_disable (enum rcc_periph_clken periph)
void rcc_periph_reset_pulse (enum rcc_periph_rst periph)
void rcc_periph_reset_hold (enum rcc_periph_rst periph)
void rcc_periph_reset_release (enum rcc_periph_rst periph)
Variables
uint32_t rcc_core_frequency = 8000000
uint32_t rcc_ppre_frequency = 8000000
Detailed Description
libopencm3 STM32F0xx Reset and Clock Control
Version
1.0.0
Date
29 Jun 2013
This library supports the Reset and Clock Control System in the STM32F0xx series of ARM Cortex Microcontrollers by ST Microelectronics.
LGPL License Terms libopencm3 License
Macro Definition Documentation
#define _RCC_BIT (i) (1 << ((i) & 0x1f))
Definition at line 605 of file rcc.c.
Referenced by rcc_periph_clock_disable(), rcc_periph_clock_enable(), rcc_periph_reset_hold(), rcc_periph_reset_pulse(), and rcc_periph_reset_release().
#define _RCC_REG (i) MMIO32(RCC_BASE + ((i) >> 5))
Definition at line 604 of file rcc.c.
Referenced by rcc_periph_clock_disable(), rcc_periph_clock_enable(), rcc_periph_reset_hold(), rcc_periph_reset_pulse(), and rcc_periph_reset_release().
Function Documentation
void rcc_clock_setup_in_hsi_out_16mhz (void)
Definition at line 482 of file rcc.c.
References FLASH_ACR_LATENCY_000_024MHZ, flash_set_ws(), HSI, PLL, RCC_CFGR, RCC_CFGR_HPRE_NODIV, RCC_CFGR_PLLMUL_MUL4, RCC_CFGR_PLLSRC, RCC_CFGR_PPRE_NODIV, rcc_core_frequency, rcc_osc_on(), rcc_ppre_frequency, rcc_set_hpre(), rcc_set_pll_multiplication_factor(), rcc_set_ppre(), rcc_set_sysclk_source(), and rcc_wait_for_osc_ready().
void rcc_clock_setup_in_hsi_out_24mhz (void)
Definition at line 507 of file rcc.c.
References FLASH_ACR_LATENCY_000_024MHZ, flash_set_ws(), HSI, PLL, RCC_CFGR, RCC_CFGR_HPRE_NODIV, RCC_CFGR_PLLMUL_MUL6, RCC_CFGR_PLLSRC, RCC_CFGR_PPRE_NODIV, rcc_core_frequency, rcc_osc_on(), rcc_ppre_frequency, rcc_set_hpre(), rcc_set_pll_multiplication_factor(), rcc_set_ppre(), rcc_set_sysclk_source(), and rcc_wait_for_osc_ready().
void rcc_clock_setup_in_hsi_out_32mhz (void)
Definition at line 531 of file rcc.c.
References FLASH_ACR_LATENCY_024_048MHZ, flash_set_ws(), HSI, PLL, RCC_CFGR, RCC_CFGR_HPRE_NODIV, RCC_CFGR_PLLMUL_MUL8, RCC_CFGR_PLLSRC, RCC_CFGR_PPRE_NODIV, rcc_core_frequency, rcc_osc_on(), rcc_ppre_frequency, rcc_set_hpre(), rcc_set_pll_multiplication_factor(), rcc_set_ppre(), rcc_set_sysclk_source(), and rcc_wait_for_osc_ready().
void rcc_clock_setup_in_hsi_out_40mhz (void)
Definition at line 555 of file rcc.c.
References FLASH_ACR_LATENCY_024_048MHZ, flash_set_ws(), HSI, PLL, RCC_CFGR, RCC_CFGR_HPRE_NODIV, RCC_CFGR_PLLMUL_MUL10, RCC_CFGR_PLLSRC, RCC_CFGR_PPRE_NODIV, rcc_core_frequency, rcc_osc_on(), rcc_ppre_frequency, rcc_set_hpre(), rcc_set_pll_multiplication_factor(), rcc_set_ppre(), rcc_set_sysclk_source(), and rcc_wait_for_osc_ready().
void rcc_clock_setup_in_hsi_out_48mhz (void)
Definition at line 579 of file rcc.c.
References FLASH_ACR_LATENCY_024_048MHZ, flash_set_ws(), HSI, PLL, RCC_CFGR, RCC_CFGR_HPRE_NODIV, RCC_CFGR_PLLMUL_MUL16, RCC_CFGR_PLLSRC, RCC_CFGR_PPRE_NODIV, rcc_core_frequency, rcc_osc_on(), rcc_ppre_frequency, rcc_set_hpre(), rcc_set_pll_multiplication_factor(), rcc_set_ppre(), rcc_set_sysclk_source(), and rcc_wait_for_osc_ready().
void rcc_clock_setup_in_hsi_out_8mhz (void)
Definition at line 467 of file rcc.c.
References FLASH_ACR_LATENCY_000_024MHZ, flash_set_ws(), HSI, RCC_CFGR_HPRE_NODIV, RCC_CFGR_PPRE_NODIV, rcc_core_frequency, rcc_osc_on(), rcc_ppre_frequency, rcc_set_hpre(), rcc_set_ppre(), rcc_set_sysclk_source(), and rcc_wait_for_osc_ready().
void rcc_css_disable (void)
RCC Disable the Clock Security System.
Definition at line 306 of file rcc.c.
References RCC_CR, and RCC_CR_CSSON.
void rcc_css_enable (void)
RCC Enable the Clock Security System.
Definition at line 297 of file rcc.c.
References RCC_CR, and RCC_CR_CSSON.
void rcc_css_int_clear (void)
RCC Clear the Clock Security System Interrupt Flag.
Definition at line 176 of file rcc.c.
References RCC_CIR, and RCC_CIR_CSSC.
int rcc_css_int_flag (void)
RCC Read the Clock Security System Interrupt Flag.
Returns
int. Boolean value for flag set.
Definition at line 187 of file rcc.c.
References RCC_CIR, and RCC_CIR_CSSF.
void rcc_osc_bypass_disable (enum rcc_osc osc)
RCC Disable Bypass.
Re-enable the internal clock (high speed and low speed clocks only). The internal clock must be disabled (see rcc_osc_off) for this to have effect.
Parameters
[in] osc enum ::osc_t. Oscillator ID. Only HSE and LSE have effect.
Definition at line 351 of file rcc.c.
References HSE, HSI, HSI14, LSE, LSI, PLL, RCC_BDCR, RCC_BDCR_LSEBYP, RCC_CR, and RCC_CR_HSEBYP.
void rcc_osc_bypass_enable (enum rcc_osc osc)
RCC Enable Bypass.
Enable an external clock to bypass the internal clock (high speed and low speed clocks only). The external clock must be enabled (see rcc_osc_on) and the internal clock must be disabled (see rcc_osc_off) for this to have effect.
Parameters
[in] osc enum ::osc_t. Oscillator ID. Only HSE and LSE have effect.
Definition at line 322 of file rcc.c.
References HSE, HSI, HSI14, LSE, LSI, PLL, RCC_BDCR, RCC_BDCR_LSEBYP, RCC_CR, and RCC_CR_HSEBYP.
void rcc_osc_off (enum rcc_osc osc)
RCC Turn off an Oscillator.
Disable an oscillator and power off.
Note
An oscillator cannot be turned off if it is selected as the system clock.
Parameters
[in] osc enum ::osc_t. Oscillator ID
Definition at line 269 of file rcc.c.
References HSE, HSI, HSI14, LSE, LSI, PLL, RCC_BDCR, RCC_BDCR_LSEON, RCC_CR, RCC_CR2, RCC_CR2_HSI14ON, RCC_CR_HSEON, RCC_CR_HSION, RCC_CSR, and RCC_CSR_LSION.
void rcc_osc_on (enum rcc_osc osc)
RCC Turn on an Oscillator.
Enable an oscillator and power on. Each oscillator requires an amount of time to settle to a usable state. Refer to datasheets for time delay information. A status flag is available to indicate when the oscillator becomes ready (see rcc_osc_ready_int_flag and rcc_wait_for_osc_ready).
Parameters
[in] osc enum ::osc_t. Oscillator ID
Definition at line 234 of file rcc.c.
References HSE, HSI, HSI14, LSE, LSI, PLL, RCC_BDCR, RCC_BDCR_LSEON, RCC_CR, RCC_CR2, RCC_CR2_HSI14ON, RCC_CR_HSEON, RCC_CR_HSION, RCC_CSR, and RCC_CSR_LSION.
Referenced by rcc_clock_setup_in_hsi_out_16mhz(), rcc_clock_setup_in_hsi_out_24mhz(), rcc_clock_setup_in_hsi_out_32mhz(), rcc_clock_setup_in_hsi_out_40mhz(), rcc_clock_setup_in_hsi_out_48mhz(), and rcc_clock_setup_in_hsi_out_8mhz().
void rcc_osc_ready_int_clear (enum rcc_osc osc)
RCC Clear the Oscillator Ready Interrupt Flag.
Clear the interrupt flag that was set when a clock oscillator became ready to use.
Parameters
[in] osc enum ::osc_t. Oscillator ID
Definition at line 55 of file rcc.c.
References HSE, HSI, HSI14, LSE, LSI, PLL, RCC_CIR, RCC_CIR_HSERDYC, RCC_CIR_HSI14RDYC, RCC_CIR_HSIRDYC, RCC_CIR_LSERDYC, RCC_CIR_LSIRDYC, and RCC_CIR_PLLRDYC.
void rcc_osc_ready_int_disable (enum rcc_osc osc)
RCC Disable the Oscillator Ready Interrupt.
Parameters
[in] osc enum ::osc_t. Oscillator ID
Definition at line 115 of file rcc.c.
References HSE, HSI, HSI14, LSE, LSI, PLL, RCC_CIR, RCC_CIR_HSERDYC, RCC_CIR_HSI14RDYC, RCC_CIR_HSIRDYC, RCC_CIR_LSERDYC, RCC_CIR_LSIRDYC, and RCC_CIR_PLLRDYC.
void rcc_osc_ready_int_enable (enum rcc_osc osc)
RCC Enable the Oscillator Ready Interrupt.
Parameters
[in] osc enum ::osc_t. Oscillator ID
Definition at line 85 of file rcc.c.
References HSE, HSI, HSI14, LSE, LSI, PLL, RCC_CIR, RCC_CIR_HSERDYIE, RCC_CIR_HSI14RDYIE, RCC_CIR_HSIRDYIE, RCC_CIR_LSERDYIE, RCC_CIR_LSIRDYIE, and RCC_CIR_PLLRDYIE.
int rcc_osc_ready_int_flag (enum rcc_osc osc)
RCC Read the Oscillator Ready Interrupt Flag.
Parameters
[in] osc enum ::osc_t. Oscillator ID
Returns
int. Boolean value for flag set.
Definition at line 146 of file rcc.c.
References cm3_assert_not_reached, HSE, HSI, HSI14, LSE, LSI, PLL, RCC_CIR, RCC_CIR_HSERDYF, RCC_CIR_HSI14RDYF, RCC_CIR_HSIRDYF, RCC_CIR_LSERDYF, RCC_CIR_LSIRDYF, and RCC_CIR_PLLRDYF.
void rcc_periph_clock_disable (enum rcc_periph_clken periph)
Definition at line 612 of file rcc.c.
References _RCC_BIT, and _RCC_REG.
void rcc_periph_clock_enable (enum rcc_periph_clken periph)
Definition at line 607 of file rcc.c.
References _RCC_BIT, and _RCC_REG.
void rcc_periph_reset_hold (enum rcc_periph_rst periph)
Definition at line 623 of file rcc.c.
References _RCC_BIT, and _RCC_REG.
void rcc_periph_reset_pulse (enum rcc_periph_rst periph)
Definition at line 617 of file rcc.c.
References _RCC_BIT, and _RCC_REG.
void rcc_periph_reset_release (enum rcc_periph_rst periph)
Definition at line 628 of file rcc.c.
References _RCC_BIT, and _RCC_REG.
void rcc_set_hpre (uint32_t hpre)
RCC Set the AHB Prescale Factor.
Parameters
[in] hpre Unsigned int32. AHB prescale factor rcc_cfgr_ahbpre
Definition at line 429 of file rcc.c.
References RCC_CFGR, and RCC_CFGR_HPRE.
Referenced by rcc_clock_setup_in_hsi_out_16mhz(), rcc_clock_setup_in_hsi_out_24mhz(), rcc_clock_setup_in_hsi_out_32mhz(), rcc_clock_setup_in_hsi_out_40mhz(), rcc_clock_setup_in_hsi_out_48mhz(), and rcc_clock_setup_in_hsi_out_8mhz().
void rcc_set_mco (uint32_t mcosrc)
Definition at line 441 of file rcc.c.
References RCC_CFGR, and RCC_CFGR_MCO.
void rcc_set_pll_multiplication_factor (uint32_t mul)
RCC Set the PLL Multiplication Factor.
Note
This only has effect when the PLL is disabled.
Parameters
[in] mul Unsigned int32. PLL multiplication factor rcc_cfgr_pmf
Definition at line 404 of file rcc.c.
References RCC_CFGR, and RCC_CFGR_PLLMUL.
Referenced by rcc_clock_setup_in_hsi_out_16mhz(), rcc_clock_setup_in_hsi_out_24mhz(), rcc_clock_setup_in_hsi_out_32mhz(), rcc_clock_setup_in_hsi_out_40mhz(), and rcc_clock_setup_in_hsi_out_48mhz().
void rcc_set_ppre (uint32_t ppre)
RCC Set the APB Prescale Factor.
Note
The APB1 clock frequency must not exceed 36MHz.
Parameters
[in] ppre1 Unsigned int32. APB prescale factor rcc_cfgr_apb1pre
Definition at line 418 of file rcc.c.
References RCC_CFGR, and RCC_CFGR_PPRE.
Referenced by rcc_clock_setup_in_hsi_out_16mhz(), rcc_clock_setup_in_hsi_out_24mhz(), rcc_clock_setup_in_hsi_out_32mhz(), rcc_clock_setup_in_hsi_out_40mhz(), rcc_clock_setup_in_hsi_out_48mhz(), and rcc_clock_setup_in_hsi_out_8mhz().
void rcc_set_prediv (uint32_t prediv)
Definition at line 435 of file rcc.c.
References RCC_CFGR2, and RCC_CFGR2_PREDIV.
void rcc_set_sysclk_source (enum rcc_osc clk)
RCC Set the Source for the System Clock.
Parameters
[in] osc enum ::osc_t. Oscillator ID. Only HSE, LSE and PLL have effect.
Definition at line 376 of file rcc.c.
References HSE, HSI, HSI14, LSE, LSI, PLL, RCC_CFGR, RCC_CFGR_SW, RCC_CFGR_SW_HSE, RCC_CFGR_SW_HSI, and RCC_CFGR_SW_PLL.
Referenced by rcc_clock_setup_in_hsi_out_16mhz(), rcc_clock_setup_in_hsi_out_24mhz(), rcc_clock_setup_in_hsi_out_32mhz(), rcc_clock_setup_in_hsi_out_40mhz(), rcc_clock_setup_in_hsi_out_48mhz(), and rcc_clock_setup_in_hsi_out_8mhz().
enum rcc_osc rcc_system_clock_source (void)
RCC Get the System Clock Source.
Returns
::osc_t System clock source:
Definition at line 452 of file rcc.c.
References cm3_assert_not_reached, HSE, HSI, PLL, RCC_CFGR, RCC_CFGR_SWS, RCC_CFGR_SWS_HSE, RCC_CFGR_SWS_HSI, and RCC_CFGR_SWS_PLL.
void rcc_wait_for_osc_ready (enum rcc_osc osc)
RCC Wait for Oscillator Ready.
Parameters
[in] osc enum ::osc_t. Oscillator ID
Definition at line 198 of file rcc.c.
References HSE, HSI, HSI14, LSE, LSI, PLL, RCC_CIR, RCC_CIR_HSERDYF, RCC_CIR_HSI14RDYF, RCC_CIR_HSIRDYF, RCC_CIR_LSERDYF, RCC_CIR_LSIRDYF, and RCC_CIR_PLLRDYF.
Referenced by rcc_clock_setup_in_hsi_out_16mhz(), rcc_clock_setup_in_hsi_out_24mhz(), rcc_clock_setup_in_hsi_out_32mhz(), rcc_clock_setup_in_hsi_out_40mhz(), rcc_clock_setup_in_hsi_out_48mhz(), and rcc_clock_setup_in_hsi_out_8mhz().
Variable Documentation
uint32_t rcc_core_frequency = 8000000
Definition at line 43 of file rcc.c.
Referenced by rcc_clock_setup_in_hsi_out_16mhz(), rcc_clock_setup_in_hsi_out_24mhz(), rcc_clock_setup_in_hsi_out_32mhz(), rcc_clock_setup_in_hsi_out_40mhz(), rcc_clock_setup_in_hsi_out_48mhz(), and rcc_clock_setup_in_hsi_out_8mhz().
uint32_t rcc_ppre_frequency = 8000000
Definition at line 44 of file rcc.c.
Referenced by rcc_clock_setup_in_hsi_out_16mhz(), rcc_clock_setup_in_hsi_out_24mhz(), rcc_clock_setup_in_hsi_out_32mhz(), rcc_clock_setup_in_hsi_out_40mhz(), rcc_clock_setup_in_hsi_out_48mhz(), rcc_clock_setup_in_hsi_out_8mhz(), and usart_set_baudrate().