libopencm3: usart.c File Reference
usart.c File Reference
#include <libopencm3/stm32/usart.h>
#include <libopencm3/stm32/rcc.h>
Functions
void usart_set_baudrate (uint32_t usart, uint32_t baud)
USART Set Baudrate.
void usart_set_databits (uint32_t usart, uint32_t bits)
USART Set Word Length.
void usart_set_stopbits (uint32_t usart, uint32_t stopbits)
USART Set Stop Bit(s).
void usart_set_parity (uint32_t usart, uint32_t parity)
USART Set Parity.
void usart_set_mode (uint32_t usart, uint32_t mode)
USART Set Rx/Tx Mode.
void usart_set_flow_control (uint32_t usart, uint32_t flowctrl)
USART Set Hardware Flow Control.
void usart_enable (uint32_t usart)
USART Enable.
void usart_disable (uint32_t usart)
USART Disable.
void usart_send (uint32_t usart, uint8_t data)
USART Send a Data Word.
uint8_t usart_recv (uint32_t usart)
USART Read a Received Data Word.
void usart_wait_send_ready (uint32_t usart)
USART Wait for Transmit Data Buffer Empty.
void usart_wait_recv_ready (uint32_t usart)
USART Wait for Received Data Available.
void usart_send_blocking (uint32_t usart, uint8_t data)
USART Send Data Word with Blocking.
uint8_t usart_recv_blocking (uint32_t usart)
USART Read a Received Data Word with Blocking.
void usart_enable_rx_dma (uint32_t usart)
USART Receiver DMA Enable.
void usart_disable_rx_dma (uint32_t usart)
USART Receiver DMA Disable.
void usart_enable_tx_dma (uint32_t usart)
USART Transmitter DMA Enable.
void usart_disable_tx_dma (uint32_t usart)
USART Transmitter DMA Disable.
void usart_enable_rx_interrupt (uint32_t usart)
USART Receiver Interrupt Enable.
void usart_disable_rx_interrupt (uint32_t usart)
USART Receiver Interrupt Disable.
void usart_enable_tx_interrupt (uint32_t usart)
USART Transmitter Interrupt Enable.
void usart_disable_tx_interrupt (uint32_t usart)
USART Transmitter Interrupt Disable.
void usart_enable_error_interrupt (uint32_t usart)
USART Error Interrupt Enable.
void usart_disable_error_interrupt (uint32_t usart)
USART Error Interrupt Disable.
bool usart_get_flag (uint32_t usart, uint32_t flag)
USART Read a Status Flag.
bool usart_get_interrupt_source (uint32_t usart, uint32_t flag)
USART Return Interrupt Source.
Function Documentation
void usart_disable (uint32_t usart)
USART Disable.
At the end of the current frame, the USART is disabled to reduce power.
Parameters
[in] usart unsigned 32 bit. USART block register address base usart_reg_base
Definition at line 158 of file usart.c.
References USART_CR1, and USART_CR1_UE.
void usart_disable_error_interrupt (uint32_t usart)
USART Error Interrupt Disable.
Parameters
[in] usart unsigned 32 bit. USART block register address base usart_reg_base
Definition at line 382 of file usart.c.
References USART_CR3, and USART_CR3_EIE.
void usart_disable_rx_dma (uint32_t usart)
USART Receiver DMA Disable.
Parameters
[in] usart unsigned 32 bit. USART block register address base usart_reg_base
Definition at line 281 of file usart.c.
References USART_CR3, and USART_CR3_DMAR.
void usart_disable_rx_interrupt (uint32_t usart)
USART Receiver Interrupt Disable.
Parameters
[in] usart unsigned 32 bit. USART block register address base usart_reg_base
Definition at line 334 of file usart.c.
References USART_CR1, and USART_CR1_RXNEIE.
void usart_disable_tx_dma (uint32_t usart)
USART Transmitter DMA Disable.
Parameters
[in] usart unsigned 32 bit. USART block register address base usart_reg_base
Definition at line 309 of file usart.c.
References USART_CR3, and USART_CR3_DMAT.
void usart_disable_tx_interrupt (uint32_t usart)
USART Transmitter Interrupt Disable.
Parameters
[in] usart unsigned 32 bit. USART block register address base usart_reg_base
Definition at line 358 of file usart.c.
References USART_CR1, and USART_CR1_TXEIE.
void usart_enable (uint32_t usart)
USART Enable.
Parameters
[in] usart unsigned 32 bit. USART block register address base usart_reg_base
Definition at line 144 of file usart.c.
References USART_CR1, and USART_CR1_UE.
void usart_enable_error_interrupt (uint32_t usart)
USART Error Interrupt Enable.
Parameters
[in] usart unsigned 32 bit. USART block register address base usart_reg_base
Definition at line 370 of file usart.c.
References USART_CR3, and USART_CR3_EIE.
void usart_enable_rx_dma (uint32_t usart)
USART Receiver DMA Enable.
DMA is available on:
USART1 Rx DMA1 channel 3 or 5.
USART2 Rx DMA1 channel 5.
Parameters
[in] usart unsigned 32 bit. USART block register address base usart_reg_base
Definition at line 269 of file usart.c.
References USART_CR3, and USART_CR3_DMAR.
void usart_enable_rx_interrupt (uint32_t usart)
USART Receiver Interrupt Enable.
Parameters
[in] usart unsigned 32 bit. USART block register address base usart_reg_base
Definition at line 321 of file usart.c.
References USART_CR1, and USART_CR1_RXNEIE.
void usart_enable_tx_dma (uint32_t usart)
USART Transmitter DMA Enable.
DMA is available on:
USART1 Tx DMA1 channel 2 or 4.
USART2 Tx DMA1 channel 4.
Parameters
[in] usart unsigned 32 bit. USART block register address base usart_reg_base
Definition at line 297 of file usart.c.
References USART_CR3, and USART_CR3_DMAT.
void usart_enable_tx_interrupt (uint32_t usart)
USART Transmitter Interrupt Enable.
Parameters
[in] usart unsigned 32 bit. USART block register address base usart_reg_base
Definition at line 346 of file usart.c.
References USART_CR1, and USART_CR1_TXEIE.
bool usart_get_flag (uint32_t usart, uint32_t flag)
USART Read a Status Flag.
Parameters
[in] usart unsigned 32 bit. USART block register address base usart_reg_base
[in] flag Unsigned int32. Status register flag usart_sr_flags.
Returns
boolean: flag set.
Definition at line 396 of file usart.c.
References USART_ISR.
bool usart_get_interrupt_source (uint32_t usart, uint32_t flag)
USART Return Interrupt Source.
Returns true if the specified interrupt flag (IDLE, RXNE, TC, TXE or OE) was set and the interrupt was enabled. If the specified flag is not an interrupt flag, the function returns false.
Parameters
[in] usart unsigned 32 bit. USART block register address base usart_reg_base
[in] flag Unsigned int32. Status register flag usart_sr_flags.
Returns
boolean: flag and interrupt enable both set.
Definition at line 414 of file usart.c.
References USART_CR1, USART_CR3, USART_CR3_CTSIE, USART_ISR, USART_ISR_IDLE, USART_ISR_ORE, and USART_ISR_TXE.
uint8_t usart_recv (uint32_t usart)
USART Read a Received Data Word.
If parity is enabled the MSB (bit 7 or 8 depending on the word length) is the parity bit.
Parameters
[in] usart unsigned 32 bit. USART block register address base usart_reg_base
Returns
unsigned 16 bit data word.
Definition at line 187 of file usart.c.
References USART_RDR.
uint8_t usart_recv_blocking (uint32_t usart)
USART Read a Received Data Word with Blocking.
Wait until a data word has been received then return the word.
Parameters
[in] usart unsigned 32 bit. USART block register address base usart_reg_base
Returns
unsigned 16 bit data word.
Definition at line 251 of file usart.c.
References usart_recv(), and usart_wait_recv_ready().
void usart_send (uint32_t usart, uint8_t data)
USART Send a Data Word.
Parameters
[in] usart unsigned 32 bit. USART block register address base usart_reg_base
[in] data unsigned 16 bit.
Definition at line 171 of file usart.c.
References USART_TDR.
Referenced by usart_send_blocking().
void usart_send_blocking (uint32_t usart, uint8_t data)
USART Send Data Word with Blocking.
Blocks until the transmit data buffer becomes empty then writes the next data word for transmission.
Parameters
[in] usart unsigned 32 bit. USART block register address base usart_reg_base
[in] data unsigned 16 bit.
Definition at line 235 of file usart.c.
References usart_send(), and usart_wait_send_ready().
void usart_set_baudrate (uint32_t usart, uint32_t baud)
USART Set Baudrate.
Parameters
[in] usart unsigned 32 bit. USART block register address base usart_reg_base
[in] baud unsigned 32 bit. Baud rate specified in Hz.
Definition at line 42 of file usart.c.
References rcc_ppre_frequency, USART1, and USART_BRR.
void usart_set_databits (uint32_t usart, uint32_t bits)
USART Set Word Length.
The word length is set to 8 or 9 bits. Note that the last bit will be a parity bit if parity is enabled, in which case the data length will be 7 or 8 bits respectively.
Parameters
[in] usart unsigned 32 bit. USART block register address base usart_reg_base
[in] bits unsigned 32 bit. Word length in bits 8 or 9.
Definition at line 67 of file usart.c.
References USART_CR1, and USART_CR1_M.
void usart_set_flow_control (uint32_t usart, uint32_t flowctrl)
USART Set Hardware Flow Control.
The flow control bit can be selected as none, RTS, CTS or RTS+CTS.
Parameters
[in] usart unsigned 32 bit. USART block register address base usart_reg_base
[in] flowcontrol unsigned 32 bit. Flowcontrol usart_cr3_flowcontrol.
Definition at line 132 of file usart.c.
References USART_CR3, and USART_FLOWCONTROL.
void usart_set_mode (uint32_t usart, uint32_t mode)
USART Set Rx/Tx Mode.
The mode can be selected as Rx only, Tx only or Rx+Tx.
Parameters
[in] usart unsigned 32 bit. USART block register address base usart_reg_base
[in] mode unsigned 32 bit. Mode usart_cr1_mode.
Definition at line 116 of file usart.c.
References USART_CR1, and USART_MODE.
void usart_set_parity (uint32_t usart, uint32_t parity)
USART Set Parity.
The parity bit can be selected as none, even or odd.
Parameters
[in] usart unsigned 32 bit. USART block register address base usart_reg_base
[in] parity unsigned 32 bit. Parity usart_cr1_parity.
Definition at line 101 of file usart.c.
References USART_CR1, and USART_PARITY.
void usart_set_stopbits (uint32_t usart, uint32_t stopbits)
USART Set Stop Bit(s).
The stop bits are specified as 0.5, 1, 1.5 or 2.
Parameters
[in] usart unsigned 32 bit. USART block register address base usart_reg_base
[in] stopbits unsigned 32 bit. Stop bits usart_cr2_stopbits.
Definition at line 86 of file usart.c.
References USART_CR2, and USART_CR2_STOP.
void usart_wait_recv_ready (uint32_t usart)
USART Wait for Received Data Available.
Blocks until the receive data buffer holds a valid received data word.
Parameters
[in] usart unsigned 32 bit. USART block register address base usart_reg_base
Definition at line 218 of file usart.c.
References USART_ISR, and USART_ISR_RXNE.
void usart_wait_send_ready (uint32_t usart)
USART Wait for Transmit Data Buffer Empty.
Blocks until the transmit data buffer becomes empty and is ready to accept the next data word.
Parameters
[in] usart unsigned 32 bit. USART block register address base usart_reg_base
Definition at line 203 of file usart.c.
References USART_ISR, and USART_ISR_TXE.