libopencm3: General Purpose I/O Defines
General Purpose I/O Defines
LM4F Defines
Defined Constants and Types for the LM4F General Purpose I/O
Modules
GPIO register base addresses
GPIO pin identifiers
Enumerations
enum gpio_mode { GPIO_MODE_OUTPUT, GPIO_MODE_INPUT, GPIO_MODE_ANALOG }
enum gpio_pullup { GPIO_PUPD_NONE, GPIO_PUPD_PULLUP, GPIO_PUPD_PULLDOWN }
enum gpio_output_type { GPIO_OTYPE_PP, GPIO_OTYPE_OD }
enum gpio_drive_strength { GPIO_DRIVE_2MA, GPIO_DRIVE_4MA, GPIO_DRIVE_8MA, GPIO_DRIVE_8MA_SLEW_CTL }
enum gpio_trigger {
GPIO_TRIG_LVL_LOW, GPIO_TRIG_LVL_HIGH, GPIO_TRIG_EDGE_FALL, GPIO_TRIG_EDGE_RISE,
GPIO_TRIG_EDGE_BOTH
}
Functions
BEGIN_DECLS void gpio_enable_ahb_aperture (void)
Enable access to GPIO registers via the AHB aperture.
void gpio_mode_setup (u32 gpioport, enum gpio_mode mode, enum gpio_pullup pullup, u8 gpios)
Configure a group of pins.
void gpio_set_output_config (u32 gpioport, enum gpio_output_type otype, enum gpio_drive_strength drive, u8 gpios)
Configure output parameters of a group of pins.
void gpio_set_af (u32 gpioport, u8 alt_func_num, u8 gpios)
Multiplex group of pins to the given alternate function.
void gpio_toggle (u32 gpioport, u8 gpios)
Toggle a Group of Pins.
void gpio_unlock_commit (u32 gpioport, u8 gpios)
Unlock the commit control of a special function pin.
void gpio_configure_trigger (u32 gpioport, enum gpio_trigger trigger, u8 gpios)
Configure the interrupt trigger on the given GPIO pins.
void gpio_enable_interrupts (u32 gpioport, u8 gpios)
Enable interrupts on specified GPIO pins.
void gpio_disable_interrupts (u32 gpioport, u8 gpios)
Disable interrupts on specified GPIO pins.
static void gpio_write (u32 gpioport, u8 gpios, u8 data)
Set level of a Group of Pins (atomic)
static void gpio_set (u32 gpioport, u8 gpios)
Set a Group of Pins (atomic)
static void gpio_clear (u32 gpioport, u8 gpios)
Clear a Group of Pins (atomic)
static u8 gpio_port_read (u32 gpioport)
Read level of all pins from a port (atomic)
static void gpio_port_write (u32 gpioport, u8 data)
Set level of of all pins from a port (atomic)
static void gpio_clear_interrupt_flag (u32 gpioport, u8 gpios)
Mark interrupt as serviced.
Detailed Description
Defined Constants and Types for the LM4F General Purpose I/O
Version
1.0.0
Author
© 2011 Gareth McMullin garet.nosp@m.h@bl.nosp@m.acksp.nosp@m.here.nosp@m..co.n.nosp@m.z
© 2013 Alexandru Gagniuc mr.nu.nosp@m.ke.m.nosp@m.e@gma.nosp@m.il.c.nosp@m.om
Date
16 March 2013
LGPL License Terms libopencm3 License
Enumeration Type Documentation
enum gpio_drive_strength
Enumerator:
GPIO_DRIVE_2MA
2mA drive
GPIO_DRIVE_4MA
4mA drive
GPIO_DRIVE_8MA
8mA drive
GPIO_DRIVE_8MA_SLEW_CTL
8mA drive with slew rate control
Definition at line 198 of file gpio.h.
enum gpio_mode
Enumerator:
GPIO_MODE_OUTPUT
Configure pin as output.
GPIO_MODE_INPUT
Configure pin as input.
GPIO_MODE_ANALOG
Configure pin as analog function.
Definition at line 181 of file gpio.h.
enum gpio_output_type
Enumerator:
GPIO_OTYPE_PP
Push-pull configuration.
GPIO_OTYPE_OD
Open drain configuration.
Definition at line 193 of file gpio.h.
enum gpio_pullup
Enumerator:
GPIO_PUPD_NONE
Do not pull the pin high or low.
GPIO_PUPD_PULLUP
Pull the pin high.
GPIO_PUPD_PULLDOWN
Pull the pin low.
Definition at line 187 of file gpio.h.
enum gpio_trigger
Enumerator:
GPIO_TRIG_LVL_LOW
Level trigger, signal low.
GPIO_TRIG_LVL_HIGH
Level trigger, signal high.
GPIO_TRIG_EDGE_FALL
Falling edge trigger.
GPIO_TRIG_EDGE_RISE
Rising edge trigger.
GPIO_TRIG_EDGE_BOTH
Falling and Rising edges trigger.
Definition at line 205 of file gpio.h.
Function Documentation
static void gpio_clear (u32 gpioport, u8 gpios) inline static
Clear a Group of Pins (atomic)
Clear one or more pins of the given GPIO port. This is an atomic operation.
Parameters
[in] gpioport GPIO block register address base GPIO register base addresses
[in] gpios GPIO pin identifiers. Any combination of pins may be specified by OR'ing then together.
Definition at line 296 of file gpio.h.
References gpio_write().
static void gpio_clear_interrupt_flag (u32 gpioport, u8 gpios) inline static
Mark interrupt as serviced.
After an interrupt is services, its flag must be cleared. If the flag is not cleared, then execution will jump back to the start of the ISR after the ISR returns.
Parameters
[in] gpioport GPIO block register address base GPIO register base addresses
[in] gpios GPIO pin identifiers. Any combination of pins may be specified by OR'ing then together.
Definition at line 365 of file gpio.h.
void gpio_configure_trigger (u32 gpioport, enum gpio_trigger trigger, u8 gpios)
Configure the interrupt trigger on the given GPIO pins.
Sets the Pin direction, analog/digital mode, and pull-up configuration of or a set of GPIO pins on a given GPIO port.
Parameters
[in] gpioport GPIO block register address base GPIO register base addresses
[in] trigger Trigger configuration (gpio_trigger)
GPIO_TRIG_LVL_LOW – Trigger on low level
GPIO_TRIG_LVL_HIGH – Trigger on high level
GPIO_TRIG_EDGE_FALL – Trigger on falling edges
GPIO_TRIG_EDGE_RISE – Trigger on rising edges
GPIO_TRIG_EDGE_BOTH – Trigger on all edges
[in] gpios GPIO pin identifiers. Any combination of pins may be specified by OR'ing then together
Definition at line 524 of file gpio.c.
References GPIO_TRIG_EDGE_BOTH, GPIO_TRIG_EDGE_FALL, GPIO_TRIG_EDGE_RISE, GPIO_TRIG_LVL_HIGH, and GPIO_TRIG_LVL_LOW.
void gpio_disable_interrupts (u32 gpioport, u8 gpios)
Disable interrupts on specified GPIO pins.
Disable interrupts on the specified GPIO pins
Note that the NVIC must be enabled and properly configured for the interrupt to be routed to the CPU.
Parameters
[in] gpioport GPIO block register address base GPIO register base addresses
[in] gpios GPIO pin identifiers. Pins whose interrupts to disable. Any combination of pins may be specified by OR'ing them together.
Definition at line 586 of file gpio.c.
BEGIN_DECLS void gpio_enable_ahb_aperture (void)
Enable access to GPIO registers via the AHB aperture.
All GPIO registers are accessed in libopencm3 via the AHB aperture. It provides faster control over the older APB aperture. This aperture must be enabled before calling any other gpio_*() function.
Definition at line 184 of file gpio.c.
void gpio_enable_interrupts (u32 gpioport, u8 gpios)
Enable interrupts on specified GPIO pins.
Enable interrupts on the specified GPIO pins
Note that the NVIC must be enabled and properly configured for the interrupt to be routed to the CPU.
Parameters
[in] gpioport GPIO block register address base GPIO register base addresses
[in] gpios GPIO pin identifiers. Pins whose interrupts to enable. Any combination of pins may be specified by OR'ing them together.
Definition at line 568 of file gpio.c.
void gpio_mode_setup (u32 gpioport, enum gpio_mode mode, enum gpio_pullup pullup, u8 gpios)
Configure a group of pins.
Sets the Pin direction, analog/digital mode, and pull-up configuration of or a set of GPIO pins on a given GPIO port.
Parameters
[in] gpioport GPIO block register address base GPIO register base addresses
[in] mode Pin mode (gpio_mode)
GPIO_MODE_OUTPUT – Configure pin as output
GPIO_MODE_INPUT – Configure pin as input
GPIO_MODE_ANALOG – Configure pin as analog function
[in] pullup Pin pullup/pulldown configuration (gpio_pullup)
GPIO_PUPD_NONE – Do not pull the pin high or low
GPIO_PUPD_PULLUP – Pull the pin high
GPIO_PUPD_PULLDOWN – Pull the pin low
[in] gpios GPIO pin identifiers. Any combination of pins may be specified by OR'ing then together
Definition at line 207 of file gpio.c.
References GPIO_MODE_ANALOG, GPIO_MODE_INPUT, GPIO_MODE_OUTPUT, GPIO_PUPD_NONE, GPIO_PUPD_PULLDOWN, and GPIO_PUPD_PULLUP.
static u8 gpio_port_read (u32 gpioport) inline static
Read level of all pins from a port (atomic)
Read the current value of the given GPIO port. This is an atomic operation.
This is functionally identical to gpio_read (gpioport, GPIO_ALL).
Parameters
[in] gpioport GPIO block register address base GPIO register base addresses
Returns
The level of all the pins on the GPIO port.
Definition at line 312 of file gpio.h.
References gpio_read().
static void gpio_port_write (u32 gpioport, u8 data) inline static
Set level of of all pins from a port (atomic)
Set the level of all pins on the given GPIO port. This is an atomic operation.
This is functionally identical to gpio_write (gpioport, GPIO_ALL, data).
Parameters
[in] gpioport GPIO block register address base GPIO register base addresses
[in] gpios GPIO pin identifiers. Any combination of pins may be specified by OR'ing then together.
[in] data Level to set pin to. Bit 0 of data corresponds to GPIO0, bit 1 to GPIO1. and so on.
Definition at line 330 of file gpio.h.
References gpio_write().
static void gpio_set (u32 gpioport, u8 gpios) inline static
Set a Group of Pins (atomic)
Set one or more pins of the given GPIO port. This is an atomic operation.
Parameters
[in] gpioport GPIO block register address base GPIO register base addresses
[in] gpios GPIO pin identifiers. Any combination of pins may be specified by OR'ing then together.
Definition at line 282 of file gpio.h.
References gpio_write().
void gpio_set_af (u32 gpioport, u8 alt_func_num, u8 gpios)
Multiplex group of pins to the given alternate function.
Mux the pin or group of pins to the given alternate function. Note that a number of pins may be set but only with a single AF number. This is useful when one or more of a peripheral's pins are assigned to the same alternate function.
Because AF0 is not used on the LM4F, passing 0 as the alt_func_num parameter will disable the alternate function of the given pins.
Parameters
[in] gpioport GPIO block register address base GPIO register base addresses
[in] alt_func_num Pin alternate function number or 0 to disable the alternate function multiplexing.
[in] gpios GPIO pin identifiers. Any combination of pins may be specified by OR'ing then together
Definition at line 319 of file gpio.c.
void gpio_set_output_config (u32 gpioport, enum gpio_output_type otype, enum gpio_drive_strength drive, u8 gpios)
Configure output parameters of a group of pins.
Sets the output configuration and drive strength, of or a set of GPIO pins for a set of GPIO pins in output mode.
Parameters
[in] gpioport GPIO block register address base GPIO register base addresses
[in] otype Output driver configuration (gpio_output_type)
GPIO_OTYPE_PP – Configure pin driver as push-pull
GPIO_OTYPE_OD – Configure pin driver as open drain
[in] drive Pin drive strength (gpio_drive_strength)
GPIO_DRIVE_2MA – 2mA drive
GPIO_DRIVE_4MA – 4mA drive
GPIO_DRIVE_8MA – 8mA drive
GPIO_DRIVE_8MA_SLEW_CTL – 8mA drive with slew rate control
[in] gpios GPIO pin identifiers. Any combination of pins may be specified by OR'ing then together
Definition at line 268 of file gpio.c.
References GPIO_DRIVE_2MA, GPIO_DRIVE_4MA, GPIO_DRIVE_8MA, GPIO_DRIVE_8MA_SLEW_CTL, and GPIO_OTYPE_OD.
void gpio_toggle (u32 gpioport, u8 gpios)
Toggle a Group of Pins.
Toggle one or more pins of the given GPIO port.
Parameters
[in] gpioport GPIO block register address base GPIO register base addresses
[in] gpios Pin identifiers. GPIO pin identifiers
Definition at line 438 of file gpio.c.
void gpio_unlock_commit (u32 gpioport, u8 gpios)
Unlock the commit control of a special function pin.
Unlocks the commit control of the given pin or group of pins. If a pin is a JTAG/SWD or NMI, the pin may then be reconfigured as a GPIO pin. If the pin is not locked by default, this has no effect.
Parameters
[in] gpioport GPIO block register address base GPIO register base addresses
[in] gpios GPIO pin identifiers. Any combination of pins may be specified by OR'ing then together.
Definition at line 362 of file gpio.c.
static void gpio_write (u32 gpioport, u8 gpios, u8 data) inline static
Set level of a Group of Pins (atomic)
Sets the level of the given pins. Bit 0 of the data parameter corresponds to GPIO0, bit 1 to GPIO1. and so on. Maskedpins (corresponding bit of gpios parameter set to zero) are returned not affected.
This is an atomic operation.
Parameters
[in] gpioport GPIO block register address base GPIO register base addresses
[in] gpios GPIO pin identifiers. Any combination of pins may be specified by OR'ing then together.
[in] data Level to set pin to. Bit 0 of data corresponds to GPIO0, bit 1 to GPIO1. and so on.
Definition at line 267 of file gpio.h.
Referenced by gpio_clear(), gpio_port_write(), and gpio_set().